Repository mozilla-mobile/fenix, pull requests merged in 2019-10, with the labels that each got.

#5738 No issue: Removes feature flags for delete data
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/res/xml/preferences.xml
Labels: needs:uplift

#5741 No issue: Removes feature flags for delete data (#5738)
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/res/xml/preferences.xml
Labels: do not land

#5759 Fixes #5758 - Increase UI test wait time
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
Labels: eng:automation

#5802 For #5213 - Add helper to set menu color
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/res/menu/bookmarks_add_folder.xml
  app/src/main/res/menu/bookmarks_edit.xml
  app/src/main/res/menu/bookmarks_menu.xml
  app/src/main/res/menu/bookmarks_select_folder.xml
  app/src/main/res/menu/bookmarks_select_multi.xml
  app/src/main/res/menu/bookmarks_select_multi_not_item.xml
  app/src/main/res/menu/history_select_multi.xml
  app/src/main/res/menu/library_menu.xml
Labels: Feature:Bookmarks

#5766 Fix the incognito icon looks out of place/misaligned
  app/src/main/res/layout/fragment_home.xml
Labels: needs:UX-feedback, pr:needs-landing

#5697 For #3563. Use `ListAdapter` for Bookmark folder selection list.
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
Labels: pr:needs-landing

#5698 For #3563. Use `ListAdapter` for App Share list.
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareToAppsView.kt
  app/src/main/java/org/mozilla/fenix/share/listadapters/AppShareAdapter.kt
  app/src/test/java/org/mozilla/fenix/share/listadapters/AppShareAdapterTest.kt
Labels: pr:needs-landing

#5807 Use the new fragment constructor
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/share/AddNewDeviceFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
  app/src/main/res/layout/fragment_library.xml
Labels: eng:health

#5765 Closes #5573: harmonize spacing between radio buttons
  app/src/main/res/layout/preference_widget_radiobutton.xml
Labels: pr:needs-landing

#5851 Fix complete-pr which does not depend on lint tasks
  taskcluster/ci/pr/kind.yml
Labels: pr:needs-landing

#5811 Bug 1586039 - Fix quoted version names
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:needs-landing

#5719 Filter github release events for "publishes"
  .taskcluster.yml
Labels: pr:needs-landing

#5810 Remove @ObsoleteCoroutinesApi from TestCore
  app/src/test/java/org/mozilla/fenix/TestApplication.kt
  app/src/test/java/org/mozilla/fenix/components/TestComponents.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
Labels: eng:health, pr:needs-landing

#4914 Closes #778 - Progressive Web Apps!
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: Feature:PWA

#5849 Closes #5847: Use IO thread when submitting crash report
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterController.kt
  app/src/test/java/org/mozilla/fenix/crashes/CrashReporterControllerTest.kt
Labels: pr:needs-landing

#5538 Add glinter overrides.
  app/metrics.yaml
Labels: pr:needs-landing

#5857 Closes #5852 - Use createAddedTestFragment in tests
  app/src/test/java/org/mozilla/fenix/collections/CreateCollectionFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/components/StoreProviderTest.kt
Labels: pr:needs-landing

#5391 Closes #394 - Trusted Web Activities
  app/src/debug/AndroidManifest.xml
  app/src/fenixNightly/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsService.kt
Labels: Feature:PWA

#5886 For #5094: Adds telemetry for show search shortcuts
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
Labels: needs:data-review

#5973 For #5898: Launch SUMO article properly for default browser
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserSettingsFragment.kt
Labels: needs:uplift

#5999 For #5709: Align ETP Settings Screen implementation with original mocks
  app/src/main/res/layout/preference_widget_radiobutton_with_info.xml
  app/src/main/res/layout/tracking_protection_learn_more_preference.xml
Labels: pr:needs-landing

#6032 For #5990: Revert sessionTokenScope to fix broken QR pairing flow
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
Labels: needs:uplift

#6143 no issue - removed unused feature flags .
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#6138 no issue - fixed alignment of open tabs header for RTL
  app/src/main/res/layout/tab_header.xml
Labels: pr:needs-landing

#6125 Don't show fingerprinters section of the standard tracking policy UI 🤞🏻
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
Labels: pr:needs-landing

#6098 Added OnCheckListener to checkboxes: DeleteBrowsingDataFragment
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
Labels: pr:needs-landing

#6082 For #6063 - ETP blocking info title new strings
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
Labels: pr:needs-landing

#6022 Fixes #5030: Modified Dialog to match the others.
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
Labels: pr:needs-landing

#6020 For #1383: Fix updating description of close button on title change
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
Labels: pr:needs-landing

#6016 for #6008 - fix address bar layout on home fragment for RTL ◀
  app/src/main/res/layout/fragment_home.xml
Labels: pr:needs-landing

#5900 For #3366 - Use one layout for edit/add bookmark 👋🏻
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/res/layout/fragment_add_bookmark_folder.xml
  app/src/main/res/layout/fragment_edit_bookmark.xml
Labels: Feature:Bookmarks

#6141 Refactor asCamelCase to use string builder
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
Labels: eng:health

#6137 Closes mozilla-mobile#2435 Change edit icon to share icon on the book…
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/res/menu/bookmarks_select_multi.xml
Labels: pr:needs-landing

#6234 Closes #6168: Globe icon for exceptions
  app/src/main/res/xml/tracking_protection_preferences.xml
Labels: pr:needs-landing

#6201 Closes mozilla-mobile#4558 Change height of bookmark linearlayout
  app/src/main/res/layout/fragment_bookmark.xml
Labels: pr:needs-landing

#6238 Add explanation to @Ignore in CollectionTest
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: pr:needs-landing

#6140 Use tools:listitem with collection creation
  app/src/main/res/layout/collection_tab_list_row.xml
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/component_collection_creation_name_collection.xml
  app/src/main/res/layout/component_collection_creation_select_collection.xml
Labels: eng:health, pr:needs-landing

#6246 Closes #6237: Change android:text to tools:text .
  app/src/main/res/layout/layout_percentage_seek_bar.xml
Labels: pr:needs-landing

#6253 No issue: Sign in button style should be ThemeIndependentMaterialGrey…
  app/src/main/res/layout/component_sign_in.xml
Labels: pr:needs-landing

#6152 For #5497 -c Align text to viewStart
  app/src/main/res/layout/sign_in_preference.xml
Labels: pr:needs-landing

#6240 Closes #6236: Fix padding lint issues
  app/src/main/res/layout/account_preference.xml
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/fragment_add_new_device.xml
  app/src/main/res/layout/fragment_create_shortcut.xml
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/layout/fragment_tracking_protection_blocking.xml
  app/src/main/res/layout/layout_percentage_seek_bar.xml
  app/src/main/res/layout/layout_url_background.xml
Labels: pr:needs-landing

#5631 Closes #2441. Update LeakCanary to `2.0-beta-3` version
  app/build.gradle
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#5975 For #5737: Adds telemetry for open links in a private tab
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  docs/metrics.md
Labels: needs:data-review

#6261 Replaced beta square icon with round icons
  app/src/fenixBeta/res/mipmap-hdpi/ic_launcher-round.png
  app/src/fenixBeta/res/mipmap-hdpi/ic_launcher_round.png
  app/src/fenixBeta/res/mipmap-mdpi/ic_launcher-round.png
  app/src/fenixBeta/res/mipmap-mdpi/ic_launcher_round.png
  app/src/fenixBeta/res/mipmap-xhdpi/ic_launcher-round.png
  app/src/fenixBeta/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/fenixBeta/res/mipmap-xxhdpi/ic_launcher-round.png
  app/src/fenixBeta/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/fenixBeta/res/mipmap-xxxhdpi/ic_launcher-round.png
  app/src/fenixBeta/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: pr:needs-landing

#6257 Add intent-filter to support nfc tags
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing

#6189 For #6179 - Changed positioning of private mode icons in tab header
  app/src/main/res/layout/tab_header.xml
Labels: pr:needs-landing

#6277 For #6219 - Reset default setting if user opts out of experiments
  app/src/main/java/org/mozilla/fenix/ExperimentsManager.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: needs:uplift

#6188 For #5733 - Private mode notification - wrong home screen
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/session/SessionNotificationService.kt
Labels: pr:needs-landing

#6047 For #5848 Wrong toolbar colour - edit bookmark fragment
  app/src/main/java/org/mozilla/fenix/ext/Toolbar.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
Labels: pr:needs-landing

#6295 For #6294 - When only one tab is being saved to collection, add it to selected tabs
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
Labels: needs:uplift

#6183 Consolidate duplicated code in NavControllerTest.
  app/src/test/java/org/mozilla/fenix/ext/NavControllerTest.kt
Labels: pr:needs-landing

#6210 Fixes #5917: Show snackbar when URL is copied
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing
