Repository mozilla-mobile/fenix, pull requests merged in 2019-07, with the labels that each got.

#3407 Move RecyclerView.Adapter Job setup code to helper class
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/share/AppShareView.kt
  app/src/main/java/org/mozilla/fenix/utils/AdapterWithJob.kt
Labels: 🤒 code health

#3724 For #3174: Adds telemetry for bookmarks
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  docs/metrics.md
Labels: needs data review

#3868 Import strings from android-l10n
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#3923 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#2760 Modify the order of Privacy Policy and About in Settings
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: 🦄 Needs UX Feedback

#3932 Replace deprecated pxToDp
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/ext/View.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
Labels: 🤒 code health

#3951 Update HomeScreenTest and add first run homescreen test
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🤖 automation

#4028 Closes #3996: Remove workarounds for opening custom tab in browser.
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: do not land

#3982 Use putCompoundDrawables helper
  app/src/main/java/org/mozilla/fenix/browser/FenixSnackbarDelegate.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoContentMessageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFirefoxAccountViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingIcon.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionUIView.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
  app/src/main/res/layout/no_content_message.xml
Labels: 🤒 code health

#4054 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3619 Use tools:text to avoid inflating strings twice
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsUIView.kt
  app/src/main/res/layout/account_auth_error_preference.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/layout/component_bookmark.xml
  app/src/main/res/layout/component_exceptions.xml
  app/src/main/res/layout/component_history.xml
  app/src/main/res/layout/component_permissions_blocked_by_android.xml
  app/src/main/res/layout/delete_browsing_data_item.xml
  app/src/main/res/layout/exception_item.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_select_bookmark_folder.xml
  app/src/main/res/layout/fragment_site_permissions_exceptions_item.xml
  app/src/main/res/layout/tab_list_row.xml
Labels: eng:health

#3980 Remove unused sessions resources
  app/src/main/java/org/mozilla/fenix/home/SessionBottomSheetFragment.kt
  app/src/main/res/drawable/ic_session_thumbnail_placeholder_greyscale.xml
  app/src/main/res/drawable/session_list_empty_bg.xml
  app/src/main/res/drawable/session_sheet_background.xml
  app/src/main/res/layout/session_bottom_sheet.xml
  app/src/main/res/layout/session_item.xml
  app/src/main/res/layout/session_list_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature:Collections, eng:health

#3979 Merge some library UIView code for toolbar
  app/src/main/java/org/mozilla/fenix/ext/Int.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageUIView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkUIView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryUIView.kt
Labels: Feature:Library

#3940 For #2362: Adds telemetry for history
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  docs/metrics.md
Labels: needs:data-review

#4055 Use StateListDrawable & resources with TabCollection
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/ext/TabCollection.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/res/drawable/collection_home_list_row_background.xml
  app/src/main/res/drawable/ic_chevron.xml
  app/src/main/res/drawable/rounded_all_corners.xml
  app/src/main/res/drawable/rounded_top_corners.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/org/mozilla/fenix/ext/TabCollectionTest.kt
Labels: Feature:Collections, Feature:HomeScreen

#4101 Closes A-C #3695 - add UI to open current page in external app
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionComponent.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionUIView.kt
  app/src/main/res/drawable/library_icon_app_links_circle_background.xml
  app/src/main/res/layout/layout_quick_action_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🌐 L10N

#4157 For #4124 - Remove browser toolbar editing code
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
Labels: eng:health

#3941 For #2267: Adds telemetry for reader mode
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  docs/metrics.md
Labels: needs:data-review

#3935 For #969: Adds telemetry for collections
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationUIView.kt
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  docs/metrics.md
Labels: needs:data-review

#4110 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  l10n.toml
Labels: import-l10n

#4202 For #4201 fix app crash on renaming a collection
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionFragment.kt
Labels: needs:uplift

#4088 Add taskcluster job for UI test automation
  .gitignore
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  automation/taskcluster/androidTest/flank-arm.yml
  automation/taskcluster/androidTest/flank-x86-tablet.yml
  automation/taskcluster/androidTest/flank-x86.yml
  automation/taskcluster/androidTest/ui-test.sh
  automation/taskcluster/decision_task.py
  automation/taskcluster/helper/get-secret.py
  automation/taskcluster/lib/tasks.py
Labels: eng:automation

#4255 Remove redundant super calls
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMetrics.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/lib/Do.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
Labels: eng:health

#3707 Create shared custom view for library items
  app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/layout/bookmark_row.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/layout/library_site_item.xml
Labels: Feature:Bookmarks, Feature:History, Feature:Library

#4276 Minify logo path
  app/src/main/res/drawable-v26/ic_launcher_foreground.xml
Labels: eng:performance
