Repository mozilla-mobile/fenix, pull requests merged in 2019-02, with the labels that each got.

#340 Add accounts related preferences
  app/src/main/res/drawable/sign_in_preference_background.xml
  app/src/main/res/layout/sign_in_preference.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: in progress, review

#342 I336 browser interaction
  app/src/main/java/org/mozilla/fenix/BackHandler.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: in progress, review

#344 Move architecture/mvi code to separate gradle module.
  app/build.gradle
  architecture/build.gradle
  architecture/proguard-rules.pro
  architecture/src/main/AndroidManifest.xml
  architecture/src/main/java/org/mozilla/fenix/mvi/ActionBusFactory.kt
  architecture/src/main/java/org/mozilla/fenix/mvi/Concepts.kt
  architecture/src/main/java/org/mozilla/fenix/mvi/UIComponent.kt
  architecture/src/main/java/org/mozilla/fenix/mvi/UIView.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  settings.gradle
Labels: in progress, review

#365 No issue: Hook up browser menu items Settings and temporary Share
  app/src/main/java/org/mozilla/fenix/components/toolbar/Toolbar.kt
  app/src/main/res/values/strings.xml
Labels: in progress, review

#367 Fix usage of sentry token in staging
  .taskcluster.yml
  automation/taskcluster/decision_task_nightly.py
Labels: in progress, review

#313 Closes #146 & Closes #147: Integrates find in page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/Toolbar.kt
  app/src/main/res/layout/fragment_browser.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#375 I364 toolbar component in browser
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt
  app/src/main/res/layout/component_search.xml
  app/src/main/res/layout/fragment_browser.xml
Labels: in progress, review

#381 Closes #378 - Creates Library Fragment UI and adds resources
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryListItem.kt
  app/src/main/res/drawable/ic_bookmark_filled.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_history.xml
  app/src/main/res/drawable/ic_screenshots.xml
  app/src/main/res/drawable/ic_session_restore.xml
  app/src/main/res/drawable/library_icon_downloads_circle_background.xml
  app/src/main/res/drawable/library_icon_favorites_circle_background.xml
  app/src/main/res/drawable/library_icon_history_circle_background.xml
  app/src/main/res/drawable/library_icon_logins_circle_background.xml
  app/src/main/res/drawable/library_icon_screenshots_circle_background.xml
  app/src/main/res/drawable/library_icon_sessions_circle_background.xml
  app/src/main/res/drawable/library_separator.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/library_list_item.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#385 Fixes #384 - Prvent fragment from subscribing multiple times
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: in progress, review

#392 Fixes #391: Home button is not visible
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt
Labels: in progress, review

#393 Fixes #389 - Opens the browser when opening from a link
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
Labels: in progress, review

#406 Fix breaking API changes of latest AC snapshot..
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: in progress, review

#411 Closes #370 - Edit Primary Color for Toggle Color
  app/src/main/res/values/colors.xml
Labels: in progress, review

#409 Reduce PNG file size with ImageOptim.
  app/src/main/res/drawable-hdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-mdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xxhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xxxhdpi/ic_logo_wordmark.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: in progress, review

#405 Closes #363 & Closes #364: Adds private browsing theme
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/SearchView.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarMenu.kt
  app/src/main/res/drawable-xxxhdpi/ic_logo_wordmark_white.png
  app/src/main/res/drawable/home_background_gradient.xml
  app/src/main/res/drawable/home_search_background_private.xml
  app/src/main/res/drawable/home_search_background_private_dark.xml
  app/src/main/res/drawable/home_search_background_private_dark_no_border.xml
  app/src/main/res/drawable/ic_home_white.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/private_browsing_button_background.xml
  app/src/main/res/drawable/private_browsing_button_white_background.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/layout/component_awesomebar.xml
  app/src/main/res/layout/component_search.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/layout_url_backround.xml
  app/src/main/res/values-v23/styles.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#413 Closes #358: Adds local history to AwesomeBar
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
Labels: in progress, review

#414 Closes #412: Enforces consistent naming in colors.xml
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt
  app/src/main/res/drawable/home_search_background_dark.xml
  app/src/main/res/drawable/home_search_background_dark_no_border.xml
  app/src/main/res/drawable/home_search_background_light.xml
  app/src/main/res/drawable/home_search_background_private.xml
  app/src/main/res/drawable/home_search_background_private_dark.xml
  app/src/main/res/drawable/home_search_background_private_dark_no_border.xml
  app/src/main/res/drawable/ic_home_white.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/private_browsing_button_white_background.xml
  app/src/main/res/layout/component_awesomebar.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#416 Closes #322: Adds missing string descriptions
  app/src/main/res/values/strings.xml
Labels: in progress, review

#407 Use ViewBoundFeatureWrapper and BackHandler from the base component.
  app/src/main/java/org/mozilla/fenix/BackHandler.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarIntegration.kt
Labels: in progress, review

#415 Fixes #351 Create home screen component for multitasking
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/View.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeLayouts.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsComponent.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsComponent.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt
  app/src/main/res/drawable/ic_add_black_24dp.xml
  app/src/main/res/drawable/ic_close_black_24dp.xml
  app/src/main/res/layout/component_sessions.xml
  app/src/main/res/layout/component_tabs.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/tab_list_header.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: in progress, review

#426 Handle multitasking via toolbar actions
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt
Labels: in progress, review

#428 Fixes #427: Browser toolbar does not auto-hide if ANY accessibility on
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/res/layout/fragment_browser.xml
Labels: in progress, review

#437 Fixes #433: Corrects URL text field color
  app/src/main/res/layout/layout_url_backround.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#441 Closes #440 - Set Find in Page colors from theme attrs
  app/src/main/res/layout/fragment_browser.xml
Labels: in progress, review

#439 Closes #436 - Make Toolbar Menu Item When Exhaustive
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: in progress, review

#446 Fixes #434: Settings visible in private mode
  app/src/main/res/values/styles.xml
Labels: in progress, review

#447 Closes #438: Adds dynamic nav bar color
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#452 Closes #451 - Update to Navigation Beta 2
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#453 Fixes #431: Scroll-down on the home screen messes up everything
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeLayouts.kt
Labels: in progress, review

#454 Enable Proguard plus optimizations for release
  app/build.gradle
  gradle.properties
Labels: in progress, review

#458 Fixes #430 - Hides software keyboard when you background the app
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: in progress, review

#460 Closes #459 - Remove redundant awesome bar in browser fragment
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/fragment_search.xml
Labels: in progress, review

#461 Fixes the library list item layout
  app/src/main/res/layout/library_list_item.xml
Labels: in progress, review

#462 Fixes #390 - Gives Fenix the ability to respond to the assist intent
  app/src/main/AndroidManifest.xml
Labels: in progress, review

#464 Closes #463 - Add attr for home divider color for private mode theming
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#474 Update to Mozilla Android Components 0.43.0-SNAPSHOT.
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#471 Introduce aarch64 flavor and publish nightly build.
  .taskcluster.yml
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#473 Closes #472: Integrate feature-session-bundling component.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#480 Fixes #401: Resolve known leak and install LeakCanary with toggle
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  architecture/src/main/java/org/mozilla/fenix/mvi/ActionBusFactory.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#481 Add initial proguard rules
  app/proguard-rules.pro
Labels: in progress, review

#483 Fix taskcluster Nigthly configuration.
  .taskcluster.yml
Labels: in progress, review

#485 Closes #476: Adds browserToolbarMenuIcon theming
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#486 Adds build date to the about page
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/settings/AboutPage.kt
  app/src/main/res/raw/about.html
  buildSrc/src/main/java/Config.kt
Labels: in progress, review

#491 Fixes #488: LeakCanary crash
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
Labels: in progress, review

#492 Adds support to navigate from HistoryFragment when launched from the Home View
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: in progress, review

#495 Closes #487 - Replace home toolbar icon with tabs icon
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/res/drawable/ic_home_white.xml
  app/src/main/res/drawable/ic_tabs.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#429 Fixes #354: Overflow menu for multitasking in current session
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/res/drawable/ic_add_black_24dp.xml
  app/src/main/res/drawable/ic_archive.xml
  app/src/main/res/drawable/ic_close_black_24dp.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/ic_session_thumbnail_placeholder_blue.xml
  app/src/main/res/layout/current_session_bottom_sheet.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/tab_list_header.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#502 Pass concept-fetch Client implementation to SearchSuggestionProvider.
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
Labels: in progress, review

#503 Issue #444: Adapt version code for aarch64 to follow order: X86 > aarch64 > ARM.
  app/build.gradle
Labels: in progress, review

#512 Fixes #511: Corrects theming for home fragment menu
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: in progress, review

#515 Closes #508 - Use Default Component Text Size for Toolbar
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
Labels: in progress, review

#506 Closes #347: Adds private browsing logic
  app/src/main/java/org/mozilla/fenix/BrowsingModeManager.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsComponent.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsUIView.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsComponent.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/drawable/session_background.xml
  app/src/main/res/drawable/session_border.xml
  app/src/main/res/layout/session_list_empty_private.xml
  app/src/main/res/layout/session_list_header.xml
  app/src/main/res/layout/tab_list_header.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#525 Fixes #523: Multitasking unpressable after Home button and reopen
  architecture/src/main/java/org/mozilla/fenix/mvi/ActionBusFactory.kt
Labels: in progress, review

#522 Default to LeakCanary being off
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  app/src/main/res/xml/preferences.xml
Labels: in progress, review

#516 Sets up CODEOWNERS file
  .github/CODEOWNERS
Labels: in progress, review

#540 Ensures that fenix team is also notified of automation changes
  .github/CODEOWNERS
Labels: in progress, review

#547 Closes #530: Adds private keyboard support
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: in progress, review

#549 Closes #546 - Uses Minimum Touch Target Size for Tab Header Buttons
  app/src/main/res/layout/tab_list_header.xml
Labels: in progress, review

#554 Fixes #545: overflow menu for multitasking mixes regular and private
  app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt
Labels: in progress, review

#555 Fixes #541: Crash on Home Screen
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  architecture/build.gradle
  architecture/src/main/java/org/mozilla/fenix/mvi/ActionBusFactory.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#556 Fixes #551: Cropped Sessions Info Box
  app/src/main/res/layout/session_list_empty.xml
Labels: in progress, review

#558 Fixes #557: Selected tab should appear with selected theme
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsComponent.kt
  app/src/main/res/layout/tab_list_row.xml
Labels: in progress, review

#569 Fixes #568: Crash on custom tabs menu if no other tabs are open
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
Labels: in progress, review

#567 Fixes #545: overflow menu multitasking deletes private and non-private
  app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt
Labels: in progress, review

#572 Fixes #571: Startup IncompatibleClassChangeError crash on Android 6.0
  architecture/build.gradle
  architecture/proguard-rules.pro
Labels: in progress, review

#576 Handle listener state bugs as onViewCreated isn't always called
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: in progress, review

#585 Closes #584: Adds missing string descriptions
  app/src/main/res/values/strings.xml
Labels: in progress, review

#588 Closes #586 - Use Circular Ripple for Tab List Header Icons
  app/src/main/res/drawable/private_browsing_button_white_background.xml
  app/src/main/res/layout/tab_list_header.xml
  app/src/main/res/values-v23/styles.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#592 Fixes #575: Crash "IllegalStateException: Display already acquired"
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
Labels: in progress, review

#593 For #537: Removes unused asset
  app/src/main/res/drawable/rounded_button.xml
Labels: in progress, review

#590 Fixes #589: Add sample unit tests for a component
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/library/history/HistoryComponent.kt
  app/src/test/java/org/mozilla/fenix/ExampleUnitTest.kt
  app/src/test/java/org/mozilla/fenix/TestUtils.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryComponentTest.kt
  architecture/src/main/java/org/mozilla/fenix/mvi/UIComponent.kt
  architecture/src/main/java/org/mozilla/fenix/test/Mockable.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#596 Closes #484 -Library Screen UI remove divider, add selectable background
  app/src/main/res/drawable/library_separator.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/library_list_item.xml
  app/src/main/res/values/dimens.xml
Labels: in progress, review

#594 Fixes #566: Clears search on new tab
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: in progress, review

#598 Fixes #595: Galaxy S7: tap on URL bar doesn't register after task switch
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: in progress, review

#621 Fixes #620: Top toolbar flashes "fragment_browser" when exiting Settings
  app/src/main/res/navigation/nav_graph.xml
Labels: in progress, review

#623 Closes #622: Adds Glide
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#634 No issue: Update Navigation Library to rc 01
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#629 Closes #537: Refactors private sessions
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: in progress, review

#603 Close #420 - Default Browser Preference reacts to default browser status
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserPreference.kt
  app/src/main/res/layout/preference_default_browser.xml
  app/src/main/res/xml/preferences.xml
Labels: in progress, review

#645 Fixes #293: Adds about settings page
  app/src/main/java/org/mozilla/fenix/settings/AboutPage.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/raw/about.html
  app/src/main/res/values/strings.xml
Labels: in progress, review

#657 disable blank searches
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: review

#646 Fixes #423: [Battery Performance] Set up Fenix and Raptor
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/browser/BrowserPerformanceTestActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: blocked, in progress, review

#648 Closes #647 - Private Mode Inherit from Dark Theme
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/drawable/ic_about.xml
  app/src/main/res/drawable/ic_accessibility.xml
  app/src/main/res/drawable/ic_archive.xml
  app/src/main/res/drawable/ic_bookmark_filled.xml
  app/src/main/res/drawable/ic_bookmark_outline.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_data_collection.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_formfill.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_history.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_language.xml
  app/src/main/res/drawable/ic_library.xml
  app/src/main/res/drawable/ic_login.xml
  app/src/main/res/drawable/ic_permission.xml
  app/src/main/res/drawable/ic_qr.xml
  app/src/main/res/drawable/ic_report_issues.xml
  app/src/main/res/drawable/ic_screenshots.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_shortcuts.xml
  app/src/main/res/drawable/sign_in_preference_background.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/library_menu.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#663 Fixes #661: Unflags open to browser after use
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: in progress, review

#666 Closes #655 - Show/Hide toolbar in onResume
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: in progress, review

#638 Closes #292: Adds placeholder advanced settings fragments
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  app/src/main/res/drawable-xxxhdpi/ic_logo_wordmark.png
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/about.html
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/accessibility_preferences.xml
  app/src/main/res/xml/data_choices_preferences.xml
  app/src/main/res/xml/site_permissions_preferences.xml
Labels: in progress, review

#676 Update to Mozilla Android Components 0.45.0-SNAPSHOT and GeckoView Nightly 67.0.20190226093755.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#670 Limit Raptor to debug and special builds
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: in progress, review

#679 Closes #478 - Use new AC attr to tint close button in the search bar
  app/src/main/res/layout/component_search.xml
Labels: in progress, review

#682 Revert "Closes #478 - Use new AC attr to tint close button in the search bar"
  app/src/main/res/layout/component_search.xml
Labels: in progress, review

#681 Revert "Update to Mozilla Android Components 0.45.0-SNAPSHOT and GeckoView Nightly 67.0.20190226093755."
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#694 No issue: Update to Navigation 1.0.0-rc02
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#697 Update to Mozilla Android Components 0.45.0-SNAPSHOT and GeckoView Nightly 67.0.20190227104426.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#692 Fixes #687 - Show the sessions placeholder when the session list is empty
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsUIView.kt
Labels: in progress, review

#688 Fixes #678: Hides sessionsComponent in private mode
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: in progress, review

#693 Fixes #672 - Moves private browsing description out of sessions
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/session_list_empty_private.xml
Labels: in progress, review

#703 Closes #698: Create product flavors for Fennec transition.
  .taskcluster.yml
  app/build.gradle
  config/pre-push-recommended.sh
Labels: in progress, review

#705 Closes #478 - Use new attr to theme clear button in toolbar
  app/src/main/res/layout/component_search.xml
Labels: in progress, review

#707 Fixes #362 - Auto closes session
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: in progress, review

#723 Closes #717 - Cut off session host preview at 64
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsComponent.kt
  app/src/main/res/layout/session_item.xml
Labels: in progress, review

#734 Issue #309: Add proguard rule for FenixMegazord
  app/proguard-rules.pro
Labels: in progress, review

#686 Closes #630: Polishes tab UI
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt
  app/src/main/res/drawable/session_background.xml
  app/src/main/res/drawable/session_border.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#731 Closes #699: Firefox flavors: Re-use sharedUserId.
  app/src/firefoxBeta/AndroidManifest.xml
  app/src/firefoxNightly/AndroidManifest.xml
  app/src/firefoxRelease/AndroidManifest.xml
Labels: in progress, review

#667 Closes #664 & Closes #665: Refactors load to respect private mode
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Utilities.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
Labels: in progress, review

#738 Closes #510: Adds private browsing myths SUMO link
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
Labels: in progress, review

#740 No issue - pulls logic outside of the UIView
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
Labels: in progress, review

#742 No Issue - Use a consistent color for a session item
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
Labels: in progress, review

#744 Fixes #741 - Dont show the current session in the previous session list
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: in progress, review

#746 Fixes #745: Integrate Browser-Icons component for favicons
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt
  app/src/main/res/layout/tab_list_row.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#659 Adding support for Site Permissions.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: in progress, review

#750 Closes #749: Adds coloring to destructive history option
  app/src/main/java/org/mozilla/fenix/library/history/HistoryItemMenu.kt
Labels: in progress, review

#748 Closes #736 & Closes #722: Adds delete session button to private browsing
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsComponent.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/component_tabs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: in progress, review
