Repository mozilla-mobile/fenix, pull requests merged in 2019-11, with the labels that each got.

#6364 Use new WindowFeature API after browser-state migration
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#6405 Temp disable flaky deleteMultipleSelectionTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: eng:automation, pr:work-in-progress

#6376 Use vector compat in TrackingProtectionPanelView.
  app/src/main/res/layout/component_tracking_protection_panel.xml
Labels: do not land

#6443 For #6442 - Temp disable all History UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: eng:automation

#5874 For #5646 - Use new API for ETP Exceptions
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionDomains.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/TrackingProtectionView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/res/layout/exception_item.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractorTest.kt
  docs/metrics.md
Labels: pr:needs-landing

#6367 Removed redundant code in few tests.
  app/src/test/java/org/mozilla/fenix/ext/BookmarkNodeTest.kt
  app/src/test/java/org/mozilla/fenix/ext/FragmentTest.kt
  app/src/test/java/org/mozilla/fenix/ext/LogTest.kt
Labels: pr:needs-landing

#6498 For #5709 Do not animate switch for ETP panel
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
Labels: pr:needs-landing

#6129 Added Vibration Effect On Scanning QR Code
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
Labels: pr:needs-changes

#6331 For #6323 Creating 1st collection from tab shows Name collection screen
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: pr:needs-landing

#6352 For #5586 - Adds Logins Telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/LoginsFragment.kt
  docs/metrics.md
Labels: needs:data-review

#6550 Use consistent verbiage with regard to opened tabs
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
  app/src/main/res/values/strings.xml
Labels: eng:ready

#6463 For #5705 - Adds telemetry for media state
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  docs/metrics.md
Labels: pr:needs-landing

#6603 Fixes #5085 - Use CustomTabWindowFeature
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: Feature:CustomTabs, Feature:PWA

#6554 For #5583 - Adds telemetry for download notification
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/downloads/DownloadNotificationBottomSheetDialog.kt
  docs/metrics.md
Labels: needs:data-review

#6649 For #2271 - Fixes colors on dark theme ▓
  app/src/main/res/drawable/search_pill_background.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#6640 For #6621 - Add Secure Flag to Window in Logins Fragments
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsFragment.kt
Labels: pr:needs-landing

#6675 For #6620 Jump to tab overview if closed tab has no parent tab
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#6592 Fixed History flaky tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: eng:automation

#6705 Closes #5938: Enable encryption of persisted FxA account state on nightly/debug
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
Labels: pr:needs-landing

#6722 Update to Mozilla Android Components 23.0.0-SNAPSHOT
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#6700 Extract TP onboarding popup
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlayTest.kt
Labels: Feature:TrackingProtection, eng:health

#6691 For #6625 Fix back navigation in search mode from browser with keyboard down
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: pr:needs-landing

#6724 For #2294 - History URL is cut with a large font set
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/main/res/layout/history_list_item.xml
Labels: pr:needs-landing

#6684 For #6523 - Remove close button in library
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/LibraryMenuTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibraryRobot.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/res/menu/bookmarks_menu.xml
  app/src/main/res/menu/library_menu.xml
Labels: Feature:Library, pr:needs-landing

#6383 Add ETP settings accessibility labels
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonInfoPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#6659 For #4824 - Fixes onboarding telemetry events from being sent a…
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
Labels: pr:needs-landing

#6532 Clean up tracking protection fragment
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsView.kt
  app/src/main/java/org/mozilla/fenix/exceptions/viewholders/ExceptionsListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsAdapter.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
Labels: eng:health

#6258 Switched to AC string extensions
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryDataSource.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/test/java/org/mozilla/fenix/ext/StringTest.kt
Labels: pr:needs-landing

#6698 Use ShareData with ShareFragment
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareCloseView.kt
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/listadapters/ShareTabsAdapter.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: pr:needs-landing

#6531 Add toolbar helpers
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/LoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountProblemFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataOnQuitFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/share/AddNewDeviceFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
Labels: eng:health

#6608 For #5694 & #6054: Allows users to change toolbar position
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarTopBehavior.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/ToolbarSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/component_bottom_browser_toolbar.xml
  app/src/main/res/layout/component_browser_top_toolbar.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/toolbar_preferences.xml
  docs/metrics.md
Labels: do not land, needs:data-review

#6806 Bug 1587765 - Support UTF-8 characters in commit messages
  .taskcluster.yml
Labels: eng:automation, pr:needs-landing

#6779 Split android-test build job into 2 so it can be signed with 2...
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/ci/ui-test/kind.yml
  taskcluster/fenix_taskgraph/transforms/single_dep.py
Labels: pr:needs-landing

#6601 For #6396 - Added metrics for history/bookmarks account sync
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  docs/metrics.md
Labels: needs:data-review

#6765 Suppress upcoming deprecation
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: eng:health, pr:needs-landing
