Repository mozilla-mobile/fenix, pull requests merged in 2019-06, with the labels that each got.

#3048 Update A-S to 0.30.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🙅 blocked

#3085 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3120 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3128 Redesign Report and Collection icons
  app/src/main/res/drawable/ic_report_issues.xml
  app/src/main/res/drawable/ic_tab_collection.xml
Labels: UX review needed

#3253 Import strings from android-l10n
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#3343 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
Labels: import-l10n

#3469 Import strings from android-l10n
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: import-l10n

#3543 Update A-C to 0.56.5
  buildSrc/src/main/java/Dependencies.kt
Labels: whistler

#3515 For #2726 - Update ConstraintLayout to 2.0.0-beta2
  buildSrc/src/main/java/Dependencies.kt
Labels: whistler

#3542 Disable send tab for non-nightly, non-debug builds
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
Labels: whistler

#3512 For #3508: "Send crash report" checkbox is ignored
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
Labels: whistler

#3540 Fixes #3538 - Fix ic_tabs path
  app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt
  app/src/main/res/drawable/ic_tab_circle_background.xml
  app/src/main/res/drawable/ic_tabs.xml
Labels: whistler

#3541 Fixes #3539 - vectordrawablecompat for gradients
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFirefoxAccountViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/res/drawable/ic_fx_accounts_avatar.xml
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous.xml
  app/src/main/res/drawable/ic_onboarding_firefox_accounts.xml
  app/src/main/res/drawable/ic_onboarding_privacy_notice.xml
  app/src/main/res/drawable/ic_onboarding_private_browsing.xml
  app/src/main/res/layout/onboarding_firefox_account.xml
  app/src/main/res/layout/onboarding_privacy_notice.xml
  app/src/main/res/layout/onboarding_private_browsing.xml
  app/src/main/res/layout/onboarding_theme_picker.xml
  app/src/main/res/layout/onboarding_tracking_protection.xml
  app/src/main/res/layout/sign_in_preference.xml
Labels: whistler

#3545 For #3544 - Set SearchSuggestions preference value from settings
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: whistler

#3632 For #981 - Adds missing events to leanplum docs
  docs/mma.md
Labels: needs data review

#3618 Use @JvmOverloads instead of multiple constructors
  app/src/main/java/org/mozilla/fenix/library/LibraryListItem.kt
  app/src/main/java/org/mozilla/fenix/settings/AccountAuthErrorPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/AccountPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataItem.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineListPreference.kt
Labels: 🤒 code health

#3617 Import variables referred to by path
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
  app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt
  app/src/main/java/org/mozilla/fenix/ext/Resources.kt
  app/src/main/java/org/mozilla/fenix/home/SessionBottomSheetFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkUIView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryUIView.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  app/src/main/java/org/mozilla/fenix/share/AccountDevicesShareView.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
Labels: 🤒 code health

#3646 For #3647: Fix raptor decision task
  automation/taskcluster/lib/tasks.py
Labels: work in progress

#3685 Add lint exception for when statement
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarBottomBehavior.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarTopBehavior.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SwipeToDeleteCallback.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  config/detekt.yml
Labels: 🤒 code health

#3616 Use ImageView rather than rebuilding drawable
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/ext/Drawable.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingIcon.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt
  app/src/main/res/layout/onboarding_firefox_account.xml
  app/src/main/res/layout/onboarding_header.xml
  app/src/main/res/layout/onboarding_privacy_notice.xml
  app/src/main/res/layout/onboarding_private_browsing.xml
  app/src/main/res/layout/onboarding_section_header.xml
  app/src/main/res/layout/onboarding_tracking_protection.xml
  app/src/main/res/layout/private_browsing_description.xml
Labels: 🤒 code health
