Repository mozilla-mobile/fenix, pull requests merged in 2019-09, with the labels that each got.

#5088 For #4474: Adds what's new button to home screen menu
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/whatsnew/WhatsNew.kt
  app/src/main/java/org/mozilla/fenix/whatsnew/WhatsNewStorage.kt
  app/src/main/java/org/mozilla/fenix/whatsnew/WhatsNewVersion.kt
  app/src/main/res/drawable/ic_whats_new.xml
  app/src/main/res/drawable/ic_whats_new_notification.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/whatsnew/WhatsNewStorageTest.kt
  app/src/test/java/org/mozilla/fenix/whatsnew/WhatsNewVersionTest.kt
Labels: pr:needs-review

#5089 No issue: Adds screenshots to the PR checklist
  .github/PULL_REQUEST_TEMPLATE
Labels: pr:needs-review

#5102 Import strings from android-l10n
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#5106 For #4908: Adds metrics for send tab telemetry
  app/metrics.yaml
  docs/metrics.md
Labels: needs:data-review

#5090 For #5021: Adds metric for what's new button
  app/metrics.yaml
  docs/metrics.md
Labels: needs:data-review

#5119 For #5025 - Do not remove custom tab session with config removed
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
Labels: pr:needs-landing

#5127 Remove ThumbnailsFeature.
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Session.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlComponent.kt
Labels: pr:needs-review

#5120 For #5075 - Fix boolean error for private mode notification persistence
  app/src/main/java/org/mozilla/fenix/session/NotificationSessionObserver.kt
Labels: pr:needs-review

#5136 Temporarily disable broken test
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: eng:automation

#5118 For #5033 - Update browsing mode when session selected
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-review

#4442 fixes #4193 - made close button for tabs more accessible.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  app/src/main/res/layout/tab_list_row.xml
Labels: needs:UX-feedback, pr:needs-review

#5161 No issue: Top aligns close button for tab in collection
  app/src/main/res/layout/tab_in_collection.xml
Labels: pr:needs-landing

#5144 For #4763 - Enable GV logging in debug builds
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:needs-landing

#5064 For #4517: Keep Bookmarks fragment when navigating to browser
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-review

#5043 Reduce require calls in BrowserFragment 🧐
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: eng:health, pr:needs-landing

#5145 No issue: Only use iconTint in XML for bookmark menus
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/res/menu/bookmarks_edit.xml
  app/src/main/res/menu/bookmarks_select_multi.xml
  buildSrc/src/main/java/Config.kt
Labels: pr:needs-review

#4973 Code Health #4883: Refactored accessing settings by using Context extensions
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/Search.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheetView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SharedPreferenceUpdater.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/TrackingProtectionSettingView.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#5176 Clean up SupportUtils
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/AuthCustomTabActivity.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/test/java/org/mozilla/fenix/settings/SupportUtilsTest.kt
Labels: eng:health, pr:needs-review

#5196 Use A-C preferences property delegates
  app/src/main/java/org/mozilla/fenix/settings/sharedpreferences/BooleanPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/sharedpreferences/PreferencesHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/settings/sharedpreferences/BooleanPreferenceTest.kt
Labels: pr:needs-landing

#4758 Move bookmark navigation listener to separate file
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkDeselectNavigationListener.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkDeselectNavigationListenerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/DefaultDeleteBrowsingDataControllerTest.kt
Labels: Feature:Bookmarks, pr:needs-landing

#4948 For #419: Create shortcuts for private browsing
  app/src/debug/AndroidManifest.xml
  app/src/debug/res/xml/shortcuts_debug.xml
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher_private-web.png
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/PrivateShortcutCreateManager.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
  app/src/main/res/drawable-v26/ic_launcher_private_background.xml
  app/src/main/res/drawable-v26/ic_launcher_private_foreground.xml
  app/src/main/res/drawable-v26/ic_static_shortcut_private_tab.xml
  app/src/main/res/drawable-v26/ic_static_shortcut_tab.xml
  app/src/main/res/drawable/ic_pbm_notification.xml
  app/src/main/res/drawable/ic_pbm_triangle.xml
  app/src/main/res/drawable/ic_static_shortcut_background.xml
  app/src/main/res/drawable/ic_static_shortcut_private_tab.xml
  app/src/main/res/drawable/ic_static_shortcut_private_tab_foreground.xml
  app/src/main/res/drawable/ic_static_shortcut_tab.xml
  app/src/main/res/drawable/ic_static_shortcut_tab_foreground.xml
  app/src/main/res/drawable/pbm_shortcut_popup_background.xml
  app/src/main/res/drawable/rounded_gray_corners.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_private.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_private_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_private.png
  app/src/main/res/mipmap-hdpi/ic_launcher_private_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_private.png
  app/src/main/res/mipmap-mdpi/ic_launcher_private_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_private.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_private_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_private.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_private_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_private.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_private_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/shortcuts.xml
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
Labels: pr:needs-changes

#5223 No issue: Add AC pinning to releng steps
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: pr:needs-landing

#5216 For #5214 - Bumps expiration dates for telemetry
  app/metrics.yaml
Labels: needs:data-review

#5194 For #4658: Add private browsing mode shortcut telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  docs/metrics.md
Labels: needs:data-review

#5162 Closes #5091: Refactor Sentry BreadCrumbs to use lib-crash BreadCrumbs
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/BreadcrumbsRecorder.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/BreadcrumbRecorderTest.kt
Labels: pr:needs-landing

#5259 Use new feature-downloads API....
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
Labels: do not land

#5309 For #5277: Updates string for delete browsing data
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataFragment.kt
  app/src/main/res/values/strings.xml
Labels: needs:uplift

#5300 Import strings from android-l10n
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#5283 For #5254: Fix transition to private browsing mode after sharing a page
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: needs:uplift

#5324 Fix broken UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:automation

#5322 For #5279 - Don't use runBlocking in delete and quit
  app/src/main/java/org/mozilla/fenix/utils/DeleteAndQuit.kt
Labels: pr:needs-landing

#5327 For #5277: Pass app name to delete browsing data prompt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataFragment.kt
Labels: pr:needs-landing

#5363 Import strings from android-l10n
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-ja/strings.xml
Labels: import-l10n, needs:uplift, pr:needs-landing

#5328 Separates tracker bucket sorting code
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackerBucketsTest.kt
Labels: Feature:TrackingProtection, eng:health

#5333 Use .orEmpty()
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MozillaProductDetector.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
Labels: eng:health, pr:needs-landing

#5317 No issue: Uncomment APK instructions and provide extra detail
  .github/PULL_REQUEST_TEMPLATE
Labels: pr:needs-landing

#5398 For #514: Reverts broken activity alias
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
Labels: needs:uplift

#5395 For #1749 - Update to new ETP Settings Strings
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tracking_protection_preferences.xml
Labels: pr:needs-landing

#5393 For #5371: Updates search engine settings string
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/search_engine_preferences.xml
Labels: pr:needs-landing

#5209 No issue: Pass color resource for what's new menu item by id!!
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:needs-landing

#5415 For #3077 - Replaces connect another device dialog with a scree
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/share/AddNewDeviceFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/res/layout/fragment_add_new_device.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#5044 For #3440 - Reduce HomeFragment require calls
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: eng:health, pr:needs-landing

#5407 No issue: Add Digital Asset Links token for TWAs.
  .gitignore
  app/build.gradle
  automation/taskcluster/lib/tasks.py
Labels: pr:needs-landing

#5337 Use enum to simplify delete on quit code
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataOnQuitFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataOnQuitType.kt
  app/src/main/java/org/mozilla/fenix/utils/DeleteAndQuit.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/utils/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#5441 No issue: cleaned up formatting on Build Variants section of readme
  README.md
Labels: eng:documentation, pr:needs-landing

#4954 Publishes to a public track for the separate nightly app
  taskcluster/fenix_taskgraph/pushapk.py
Labels: pr:needs-landing

#5321 Add tryGetHostFromUrl and update ExceptionDomains
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionDomains.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryDataSource.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/ext/StringTest.kt
Labels: Feature:TrackingProtection, eng:health

#5439 Fixes #5438 - Upgrade UI test devices to prevent slowdowns in test lab
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  automation/taskcluster/lib/tasks.py
Labels: eng:automation

#5440 Reverts #1151: Removes unused Flipper library
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: eng:health

#5394 Use const feature flags
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: eng:health

#5310 Extract and test crash reporter code
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterController.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/res/layout/fragment_crash_reporter.xml
  app/src/test/java/org/mozilla/fenix/crashes/CrashReporterControllerTest.kt
Labels: Feature:CrashReporting, eng:health, pr:needs-landing

#5357 For #5141 Changed "learn more" link to be accessible to Talkback users
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsView.kt
  app/src/main/res/layout/component_exceptions.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#5456 1581556: Initialize Glean on the main thread
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: pr:needs-landing

#5453 For #5448 - Reload custom tab session when TP is toggled
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
Labels: pr:needs-landing

#5455 For #394, #778 - Add hide toolbar feature
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsService.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: Feature:PWA, pr:needs-landing

#5433 For #778 - Rename CustomTabActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  app/src/main/java/org/mozilla/fenix/customtabs/AuthCustomTabActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/test/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivityTest.kt
Labels: Feature:CustomTabs, Feature:PWA, pr:needs-landing

#5329 Move settings classes to packages
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountAuthErrorPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountProblemFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuit.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataItem.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataOnQuitFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataOnQuitType.kt
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_delete_browsing_data.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/search_engine_preferences.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: Feature:Settings, eng:health, pr:needs-landing

#5266 For #5197: Adds telemetry for media controls
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  docs/metrics.md
Labels: pr:needs-landing

#5463 Move UI tests to x86 devices on Firebase
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/FindInPageRobot.kt
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  automation/taskcluster/androidTest/flank-armeabi-v7a.yml
  automation/taskcluster/androidTest/flank-x86-tablet.yml
  automation/taskcluster/androidTest/flank-x86.yml
  automation/taskcluster/androidTest/flank-x86_64.yml
  automation/taskcluster/androidTest/ui-test.sh
  automation/taskcluster/lib/tasks.py
Labels: eng:automation

#5343 Extract current mode from home fragment
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/Mode.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlComponent.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
  app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
Labels: Feature:HomeScreen, eng:health

#5482 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#4752 Move BookmarkNode extensions to helper class
  app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/DesktopFolders.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/DesktopFoldersTest.kt
Labels: Feature:Bookmarks, eng:health

#5504 Extract UriOpened observer from HomeActivity
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/UriOpenedObserver.kt
  app/src/test/java/org/mozilla/fenix/browser/UriOpenedObserverTest.kt
Labels: eng:health

#5335 Cleanup extension functions
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/Search.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/ext/Resources.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheetView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SharedPreferenceUpdater.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/TrackingProtectionSettingView.kt
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: eng:health

#5519 taskgraph: Speed up gradle calls
  app/build.gradle
  taskcluster/fenix_taskgraph/gradle.py
Labels: pr:needs-landing

#5521 Bug 1580778 - Raptor: put ytp exceptions back
  automation/taskcluster/lib/__init__.py
  automation/taskcluster/lib/tasks.py
  taskcluster/ci/raptor/kind.yml
  taskcluster/fenix_taskgraph/transforms/raptor.py
Labels: pr:needs-landing

#5562 Import strings from android-l10n.
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n, needs:uplift

#5158 For 5092 - Show a Snackbar with retry option if sharing to devices fails
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/res/drawable/fenix_snackbar_error_background.xml
  app/src/main/res/layout/fenix_snackbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: do not land

#5493 For #2754 Add tab cards to share sheet
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuRobot.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareCloseView.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/listadapters/ShareTabsAdapter.kt
  app/src/main/res/drawable/bottom_sheet_dialog_fragment_background.xml
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/layout/share_close.xml
  app/src/main/res/layout/share_tab_item.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: do not land

#5625 Closes #5624 - Fix crash on preference change listener
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
Labels: needs:uplift

#5502 Closes #4711 - Extract VoiceSearchActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
  app/src/main/java/org/mozilla/fenix/widget/VoiceSearchActivity.kt
  app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/widget/VoiceSearchActivityTest.kt
Labels: eng:health, feature:SearchWidget, pr:needs-landing

#5520 For #5197: Adds telemetry for media notification
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  docs/metrics.md
Labels: do not land, needs:uplift, pr:needs-landing

#5579 For #1298: Adds adjustCampaignId to core ping
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  docs/metrics.md
Labels: pr:needs-landing

#4755 Move signedIn tracking to BookmarksSharedViewModel
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarksSharedViewModel.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/SignInView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderInteractor.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarksSharedViewModelTest.kt
Labels: Feature:Bookmarks, pr:needs-landing

#5620 Change Firebase device for UI tests
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:automation

#5654 Fixes #5653: Removes crash with null campaign
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Labels: needs:uplift

#5685 For #5679: Hides autoplay behind feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/site_permissions_preferences.xml
  docs/metrics.md
Labels: needs:uplift

#5690 For #5681: Sets OPEN_TO_BROWSER false when using new tab shortcut
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
Labels: needs:uplift

#5639 Import strings from android-l10n 🤚🏻
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n, needs:uplift

#5689 For #5672: Fixes broken send tab link
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
Labels: needs:uplift
