Repository mozilla-mobile/fenix, pull requests merged in 2019-12, with the labels that each got.

#6837 Disabled all flaky History UI Tests.
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: eng:automation

#6475 Added multi-selection tests for bookmarks
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation

#6746 For #6070 Adds telemetry for enabling search suggestions in private
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  docs/metrics.md
Labels: needs:data-review

#6923 Use multi_dep instead of single_dep !!
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/loader/__init__.py
  taskcluster/fenix_taskgraph/loader/multi_dep.py
  taskcluster/fenix_taskgraph/loader/single_dep.py
  taskcluster/fenix_taskgraph/transforms/multi_dep.py
Labels: pr:needs-landing

#6936 Enable nightly startup-test on push-apk !!
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/startup-test/kind.yml
Labels: eng:automation

#6982 Disable flaky testDownloadNotification - API28
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: eng:automation

#6909 For #4664 - Updates search_with string.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#7001 Closes #6873: Support many more Content-Type in our MockResponse in MockWebServer (UI tests)
  app/src/androidTest/java/org/mozilla/fenix/helpers/MockWebServer.kt
Labels: eng:automation

#6894 Fix flaky History UI tests by adding an extra verification step
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: eng:automation

#7025 Bug 1600104 - part 2: Change FennecNightly signing format to have sha1 digest
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/transforms/signing.py
Labels: pr:needs-landing

#7003 For #1607 - Passes "custom" as the search engine identifier for custo…
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/search/SearchController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/PerformedSearchTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchInteractorTest.kt
Labels: needs:uplift

#6921 For #5771 - Don't force landscape mode on fullscreen
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#7012 Extract IntentProcessorType to its own file and add tests
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessorType.kt
  app/src/test/java/org/mozilla/fenix/components/IntentProcessorTypeTest.kt
Labels: eng:health

#7054 Let push-apk not be blocked by the startup tests anymore
  taskcluster/ci/push-apk/kind.yml
Labels: pr:needs-landing

#6617 Fixes #6717 - Re-enable Screenshots tests
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/screenshots/ScreenshotTest.java
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/DefaultHomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/ScreenshotTest.java
Labels: eng:automation

#7010 For #6830 - Fix "Open in" text size for custom tab
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
Labels: Feature:CustomTabs

#6155 Closes #5913: Add new sessionToken scope
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
Labels: pr:needs-landing

#7162 For #7160: Use feature-accounts-push, which replaces feature-sendtab.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  buildSrc/src/main/java/Dependencies.kt
  docs/metrics.md
Labels: pr:needs-landing

#6761 For #5711 - Onboarding colours have contrast issues.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/res/drawable/onboarding_card_background_dark.xml
  app/src/main/res/layout/onboarding_manual_signin.xml
Labels: pr:needs-landing

#7091 For #7048: Network info migration
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/ext/ConnectivityManager.kt
  app/src/main/java/org/mozilla/fenix/share/ShareViewModel.kt
  app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareViewModelTest.kt
Labels: pr:needs-landing

#7249 Use localized strings in the quick settings panel
  app/src/main/res/layout/quicksettings_permissions.xml
Labels: pr:needs-landing

#7107 Split out CustomTabToolbarIntegration
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/ext/NavController.kt
  app/src/test/java/org/mozilla/fenix/crashes/CrashReporterControllerTest.kt
  app/src/test/java/org/mozilla/fenix/ext/FragmentTest.kt
  app/src/test/java/org/mozilla/fenix/ext/NavControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsInteractorTest.kt
Labels: eng:health, pr:needs-landing

#7224 For #7219 - Polish Download Notification Dialog.
  app/src/main/java/org/mozilla/fenix/downloads/DownloadNotificationBottomSheetDialog.kt
  app/src/main/res/layout/download_notification_layout.xml
Labels: pr:needs-landing

#7279 For #7250 - Replace anko.dimen
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
Labels: pr:needs-landing

#6882 For #768 - Add PWA install option to menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/MenuPresenter.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values/strings.xml
Labels: Feature:PWA

#7252 For #7085 - Remove anko px2dip
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt
Labels: eng:health

#6116 Bug 1589684 - Let taskgraph handle params["head_tag"]
  .taskcluster.yml
  taskcluster/fenix_taskgraph/__init__.py
Labels: pr:needs-landing

#6374 Consolidate duplicate mock initialization in intent processor tests.
  app/src/test/java/org/mozilla/fenix/home/intent/OpenBrowserIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
Labels: pr:needs-landing

#7297 For #7253 - Replace anko setters
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkFolderViewHolder.kt
Labels: pr:needs-landing

#7024 Clean up settings fragments
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/OnSharedPreferenceChangeListener.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/ToolbarSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/EditCustomSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
Labels: eng:health, pr:needs-landing

#6999 For #6992, for #6897, for #6889: Disable multitouch in app
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#7286 Closes #7254 - Replace Anko applyConstraintSet
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchLayouts.kt
Labels: pr:needs-landing

#7304 Temp disable flaky UI testDownloadPrompt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: eng:automation

#7311 For #7041 - Respect current mode when opening library items
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: pr:needs-landing

#6161 Added UI tests for the Submenu About settings.
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: eng:automation

#7390 Fix issue #7388 - Temp disable UI test verifyAboutFirefoxPreview
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
Labels: eng:automation, 🐞 bug
