Repository mozilla-mobile/fenix, pull requests merged in 2019-05, with the labels that each got.

#2124 For #1932: Crash on telemetry setting change when unattached
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
Labels: review

#2113 Feature #2088: Async load the default search engine icon at startup
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: review

#2158 Import strings from android-l10n
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: import-l10n, review

#2171 Closes #2156 - Update theme for selected session in BrowserFragment
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: review

#2149 For #1573 - Create Save to Collection Component and Views
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationComponent.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationUIView.kt
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveToCollectionListAdapter.kt
  app/src/main/res/layout/collections_list_item.xml
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1874 Initial view for the Sync Fragment
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TurnOnSyncFragment.kt
  app/src/main/res/drawable/ic_sign_in.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/turn_on_sync_preferences.xml
Labels: review

#1707 Generate the `activation` ping and send it with Glean
  app/build.gradle
  app/metrics.yaml
  app/pings.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/ActivationPing.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/ActivationPingTest.kt
  buildSrc/src/main/java/Dependencies.kt
  docs/activation.md
  docs/telemetry.md
Labels: review

#1893 Updates Fenix taskcluster tasks to support beta release
  .taskcluster.yml
  README.md
  app/build.gradle
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/lib/util.py
  buildSrc/src/main/java/Config.kt
Labels: review

#2338 Import strings from android-l10n
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#2567 Import strings from android-l10n
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ko/strings.xml
Labels: import-l10n

#2679 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#2733 Import strings from android-l10n
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#2702 Fixes #654 - Update refresh/stop toolbar buttons
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/components/toolbar/MenuPresenter.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: Feature:Address bar, Feature:Main menu ⋮

#2695 Use a ListAdapter for SessionControl
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionMessageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoContentMessageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoTabMessageViewHolder.kt
  app/src/main/res/layout/no_content_message.xml
  app/src/main/res/layout/no_tab_message.xml
  app/src/main/res/layout/onboarding_section_header.xml
Labels: Feature:HomeScreen, 🤒 code health

#2882 Fixes #2862 - Fix about_content placeholder
  app/src/main/res/values/static_strings.xml
Labels: 🐞 bug

#2873 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#2934 Update GeckoView Beta to 68.0.20190527103257
  buildSrc/src/main/java/Gecko.kt
Labels: do not land, in progress

#2856 Fixes #445 - Ship Fenix x86_64 builds
  app/build.gradle
  build.gradle
  buildSrc/src/main/java/Gecko.kt
Labels: 🏗️ build, 🤖 automation
