Repository mozilla-mobile/fenix, pull requests merged in 2019-08, with the labels that each got.

#4358 For #969: Adds more telemetry for collections
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/SaveTabGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabViewHolder.kt
  docs/metrics.md
Labels: needs:data-review

#4328 For #2267: Fixes telemetry for reader view
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserInteractor.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserInteractorTest.kt
  docs/metrics.md
Labels: needs:data-review

#4449 For #4412: Only consume state change when UI initialized
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: needs:uplift

#4450 For #4441 - Keeps the ID 0 based for the recyclerview
  app/src/main/java/org/mozilla/fenix/library/history/HistoryDataSource.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryStore.kt
Labels: needs:uplift

#4453 Issue #2379 - Use LibraryPageView in history
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkStore.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryStore.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/res/layout/component_bookmark.xml
Labels: Feature:History

#4464 Closes #4462 - Adjust layout params of select bookmark folder view
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
Labels: needs:uplift

#4466 Issue #2379 - Use LibrarySiteItemView in history
  app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkFolderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkNodeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkSeparatorViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/layout/history_list_item.xml
Labels: Feature:History, Feature:Library

#4296 Closes #1657 - Use Gecko for downloads
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/downloads/DownloadService.kt
Labels: Feature:Download

#4388 Split browser fragment
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: Feature:CustomTabs, eng:health

#4573 For #4572 - Stub out UI tests for tabs
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabsRobot.kt
Labels: eng:automation

#4539 For #969: Adds more telemetry for collections
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/SaveTabGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabHeaderViewHolder.kt
  docs/metrics.md
Labels: needs:data-review

#4568 For #3060: Adds Leanplum attributes for fxa syncing
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  docs/mma.md
Labels: needs:data-review

#4520 For #4507 Enable codecov on PRs
  app/build.gradle
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/upload_coverage_report.sh
  codecov.yml
Labels: do not land

#4603 Consolidate private browsing code
  app/src/main/java/org/mozilla/fenix/BrowsingModeManager.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlComponent.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: eng:health

#4643 Import strings from android-l10n
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#4629 For #4123: Adds telemetry for quick action open in app
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheetController.kt
  buildSrc/src/main/java/Dependencies.kt
  docs/metrics.md
Labels: needs:data-review

#4443 fixes #4434 - made close button for collections more accessible.
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/layout/tab_in_collection.xml
Labels: needs:UX-feedback

#4714 For #4457: Adds telemetry for search widget actions
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  docs/metrics.md
Labels: needs:data-review

#4694 For #4421: Add search widget attribute to Leanplum
  app/src/main/java/org/mozilla/fenix/SearchWidgetProvider.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  docs/mma.md
Labels: needs:data-review

#4626 For #4421: Adds Leanplum events and attributes
  app/metrics.yaml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SignOutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TurnOnSyncFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  docs/metrics.md
  docs/mma.md
Labels: needs:data-review, needs:uplift

#4739 Closes #3860 - Update description text for collections
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
Labels: needs:uplift

#4762 No issue: Fix search widget launch for 1x1, 2x1 icons
  app/src/main/res/layout/search_widget_extra_small_v1.xml
  app/src/main/res/layout/search_widget_extra_small_v2.xml
  app/src/main/res/layout/search_widget_small_no_mic.xml
Labels: needs:uplift

#4368 Extract quick action sheet observer code
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheetSessionObserver.kt
  app/src/test/java/org/mozilla/fenix/quickactionsheet/QuickActionSheetSessionObserverTest.kt
Labels: eng:health

#4821 For #4804: Resolves issue with crash reporter stack
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: needs:uplift

#4816 For #4421: Fixes issues with new glean events
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  docs/metrics.md
Labels: needs:data-review

#4753 For #2706: Refactor Glean to reduce errors
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  docs/metrics.md
  docs/mma.md
Labels: needs:data-review

#4656 Issue #1000 - Remove isCustomTab flag
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/SentryBreadcrumbsRecorder.kt
  app/src/main/java/org/mozilla/fenix/customtabs/AuthCustomTabActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
  app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt
  app/src/test/java/org/mozilla/fenix/customtabs/CustomTabActivityTest.kt
Labels: eng:health

#4819 Color the system bars in custom tabs
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: Feature:CustomTabs

#4731 Clean up create collection view model and fragment
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationComponent.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationUIView.kt
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/CreateCollectionViewModel.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/collections/CreateCollectionViewModelTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: Feature:Collections, eng:health

#4699 Clean up preferences code
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/AccountAuthErrorPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/AccountPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/AccountProblemFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SharedPreferenceUpdater.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TextPercentageSeekBarPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/sharedpreferences/SitePermissionsRulesActionPreference.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_turn_on_sync.xml
  app/src/test/java/org/mozilla/fenix/settings/sharedpreferences/SitePermissionsRulesActionPreferenceTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: eng:health

#4825 Stub out Settings tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSyncTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
Labels: eng:automation

#4857 Move classes out of top-level package
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/browsingmode/BrowsingModeManager.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/home/PrivateBrowsingButtonView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlComponent.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryItemMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/Extensions.kt
  app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/PrivateBrowsingButtonViewTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
Labels: eng:health

#4879 Make `Settings.instance` private
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt
Labels: eng:health

#4884 Extract intent processors from HomeActivity
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/HomeIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/OpenBrowserIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/test/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/OpenBrowserIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
Labels: eng:health

#4896 Import strings from android-l10n
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#4843 Closes #1000 - Custom tab fragment
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserInteractor.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: Feature:CustomTabs

#4968 For #4658: Add private browsing mode telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/intent/NotificationsIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/session/SessionNotificationService.kt
  docs/metrics.md
Labels: needs:data-review

#5022 Add comments to AuthCustomTabActivity
  app/src/main/java/org/mozilla/fenix/customtabs/AuthCustomTabActivity.kt
Labels: eng:health

#5024 Closes #4965 - Fix dex error on UI test job
  architecture/build.gradle
  automation/taskcluster/androidTest/flank-armeabi-v7a.yml
  automation/taskcluster/androidTest/flank-x86_64.yml
  automation/taskcluster/androidTest/ui-test.sh
  automation/taskcluster/lib/tasks.py
Labels: eng:automation

#5008 Closes #5007 - Add PR guidelines to README.
  README.md
Labels: pr:needs-changes
