Repository mozilla-mobile/fenix, pull requests merged in 2019-04, with the labels that each got.

#1272 Fixes #916, fixes #917, fixes #920: Save, share, and delete bookmarks
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkComponent.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkUIView.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionComponent.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionUIView.kt
  app/src/main/res/drawable/favicon_background.xml
  app/src/main/res/drawable/ic_folder_icon.xml
  app/src/main/res/layout/bookmark_row.xml
  app/src/main/res/layout/component_bookmark.xml
  app/src/main/res/layout/component_quick_action_sheet.xml
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/layout_quick_action_sheet.xml
  app/src/main/res/layout/toolbar_selected_bookmarks.xml
  app/src/main/res/menu/bookmarks_add_folder.xml
  app/src/main/res/menu/bookmarks_edit.xml
  app/src/main/res/menu/bookmarks_select_folder.xml
  app/src/main/res/menu/library_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapterTest.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  settings.gradle
Labels: review

#1314 Fix trust level in decision task
  .taskcluster.yml
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
Labels: review

#1316 Don't use glean's not-really-public EventMetricType directly
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: review

#1310 No issue: Hook up share button on session item to action
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
Labels: review

#1326 Remove favicon contentDescription.
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/values/strings.xml
Labels: Accessibility, review

#1324 Gradle: Ignore non-greenfield build variants.
  app/build.gradle
Labels: review

#1317 Add missing indexes and Treeherder jobs
  .taskcluster.yml
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
Labels: review

#1328 No issue: only run lint checks for a single variant
  automation/taskcluster/lib/tasks.py
Labels: review

#1334 Closes #1172: Make RadioButton in RadioButtonPreference non focusable.
  app/src/main/res/layout/preference_widget_radiobutton.xml
Labels: review

#1337 No issue - update to A-C 50
  app/src/main/java/org/mozilla/fenix/components/Utilities.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1338 Remove Quick Actions Sheet contentDescription
  app/src/main/res/layout/layout_quick_action_sheet.xml
  app/src/main/res/values/strings.xml
Labels: Accessibility, review

#1342 Remove custom appservices repository
  build.gradle
Labels: review

#1336 Closes #1329: Raptor performance tests can no longer be executed
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1339 For #208 - Dark/Night Theme
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/BrowsingModeManager.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/home/SearchView.kt
  app/src/main/java/org/mozilla/fenix/home/SessionBottomSheetFragment.kt
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryItemMenu.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable-night-xxxhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable/home_search_background_normal.xml
  app/src/main/res/drawable/ic_customize.xml
  app/src/main/res/drawable/ic_drawer_pull_tab.xml
  app/src/main/res/drawable/ic_private_browsing.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/sign_in_preference_background.xml
  app/src/main/res/layout/bookmark_row.xml
  app/src/main/res/layout/component_awesomebar.xml
  app/src/main/res/layout/component_history.xml
  app/src/main/res/layout/component_tabs.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/fragment_crash_reporter.xml
  app/src/main/res/layout/layout_quick_action_sheet.xml
  app/src/main/res/layout/session_bottom_sheet.xml
  app/src/main/res/layout/session_item.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/bools.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-v23/styles.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values-v28/bools.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/bools.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/theme_preferences.xml
Labels: review

#1345 Fix TC indexes
  automation/taskcluster/lib/tasks.py
Labels: review

#1349 Build against GeckoView 68.0 (browser-engine-gecko-nightly).
  app/build.gradle
  buildSrc/src/main/java/Gecko.kt
Labels: review

#1234 Fixes #1219: Display crash reporter (without reporting) on all builds
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: review

#1269 Closes #1194: Adds shortcut telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: review

#1295 Fixes #1294: Renames nightly apks to follow the form "target.$arch.apk"
  .taskcluster.yml
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
Labels: review

#1359 No issue: Remove conflicting appcompat dependency
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1357 Fixes #496: Adds new content description to tabs icon
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/res/values/strings.xml
Labels: review

#1356 For #945 - Disable leanplum when we stop telemetry
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
Labels: review

#1355 No issue: Update Androidx dependencies from 4-3-2019
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1364 For #1144 - Use System Black Navigation Bar for <API27 + Light Theme
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
  app/src/main/res/values-v23/styles.xml
  app/src/main/res/values-v27/styles.xml
Labels: review

#1367 Fixes #983 - Changes broken link
  docs/telemetry.md
Labels: review

#1352 For #1049 - Add photon gradient drawable for progress bar
  CHANGELOG.md
  app/src/main/res/drawable/progress_gradient.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: review

#1371 For #1333 - Correct vertical alignment of history list item
  app/src/main/res/layout/history_list_item.xml
Labels: review

#1341 Update strings.xml
  app/src/main/res/layout/session_list_empty.xml
  app/src/main/res/values/strings.xml
Labels: review

#1346 Closes #1165: Added Doorhanger to the toolbar
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsManagePhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/permissions_settings_strings.xml
  app/src/main/res/values/styles.xml
Labels: review

#1370 For #1323 - Attempt to pop inclusive out of browser if no current ses…
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1378 Quantize and optimize images to save about 3MB in APK
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt
  app/src/main/res/drawable-hdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-hdpi/sessions_01.png
  app/src/main/res/drawable-hdpi/sessions_02.png
  app/src/main/res/drawable-hdpi/sessions_03.png
  app/src/main/res/drawable-hdpi/sessions_04.png
  app/src/main/res/drawable-hdpi/sessions_05.png
  app/src/main/res/drawable-hdpi/sessions_06.png
  app/src/main/res/drawable-hdpi/sessions_07.png
  app/src/main/res/drawable-hdpi/sessions_08.png
  app/src/main/res/drawable-mdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-mdpi/sessions_01.png
  app/src/main/res/drawable-mdpi/sessions_02.png
  app/src/main/res/drawable-mdpi/sessions_03.png
  app/src/main/res/drawable-mdpi/sessions_04.png
  app/src/main/res/drawable-mdpi/sessions_05.png
  app/src/main/res/drawable-mdpi/sessions_06.png
  app/src/main/res/drawable-mdpi/sessions_07.png
  app/src/main/res/drawable-mdpi/sessions_08.png
  app/src/main/res/drawable-night-xxxhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xhdpi/sessions_01.png
  app/src/main/res/drawable-xhdpi/sessions_02.png
  app/src/main/res/drawable-xhdpi/sessions_03.png
  app/src/main/res/drawable-xhdpi/sessions_04.png
  app/src/main/res/drawable-xhdpi/sessions_05.png
  app/src/main/res/drawable-xhdpi/sessions_06.png
  app/src/main/res/drawable-xhdpi/sessions_07.png
  app/src/main/res/drawable-xhdpi/sessions_08.png
  app/src/main/res/drawable-xxhdpi/ic_logo_wordmark.png
  app/src/main/res/drawable-xxhdpi/sessions_01.png
  app/src/main/res/drawable-xxhdpi/sessions_02.png
  app/src/main/res/drawable-xxhdpi/sessions_03.png
  app/src/main/res/drawable-xxhdpi/sessions_04.png
  app/src/main/res/drawable-xxhdpi/sessions_05.png
  app/src/main/res/drawable-xxhdpi/sessions_06.png
  app/src/main/res/drawable-xxhdpi/sessions_07.png
  app/src/main/res/drawable-xxhdpi/sessions_08.png
  app/src/main/res/drawable-xxxhdpi/ic_logo_wordmark_white.png
  app/src/main/res/drawable-xxxhdpi/sessions_01.png
  app/src/main/res/drawable-xxxhdpi/sessions_02.png
  app/src/main/res/drawable-xxxhdpi/sessions_03.png
  app/src/main/res/drawable-xxxhdpi/sessions_04.png
  app/src/main/res/drawable-xxxhdpi/sessions_05.png
  app/src/main/res/drawable-xxxhdpi/sessions_06.png
  app/src/main/res/drawable-xxxhdpi/sessions_07.png
  app/src/main/res/drawable-xxxhdpi/sessions_08.png
Labels: review

#1380 No issue: Fix build breakage on erroneous lint warnings for WrongCons…
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
Labels: review

#1381 Closes #1377: Fixed Doorhanger not shown when the toolbar padlock is clicked.
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: review

#1390 Closes #1315: Re-introduce FxA interceptor to make auth work
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
Labels: review

#1391 Fix up TC task descriptions
  automation/taskcluster/lib/tasks.py
Labels: review

#1389 Hide tabs list when no session is selected
  app/src/main/java/org/mozilla/fenix/home/tabs/TabsUIView.kt
Labels: Accessibility, review

#1395 History UI limits: visit type & time
  app/src/main/java/org/mozilla/fenix/library/history/HistoryComponent.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryComponentTest.kt
Labels: review

#1396 Prevent RecyclerView from loading everything
  app/src/main/java/org/mozilla/fenix/library/history/HistoryUIView.kt
  app/src/main/res/layout/component_history.xml
Labels: review

#1401 Update GV architectures to nightly
  app/build.gradle
Labels: review

#1394 For #208 - Dark Mode UX edits
  app/src/main/java/org/mozilla/fenix/home/sessions/SessionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutEngineManager.kt
  app/src/main/java/org/mozilla/fenix/utils/ItsNotBrokenSnack.kt
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_session_thumbnail_placeholder_blue.xml
  app/src/main/res/drawable/ic_session_thumbnail_placeholder_greyscale.xml
  app/src/main/res/drawable/search_pill_background_unselected.xml
  app/src/main/res/drawable/search_pill_drawable_button_background.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/session_bottom_sheet.xml
  app/src/main/res/layout/session_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: review

#1405 For #1387 - Downgrade androidx preference version
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1404 For #1144 - Only send SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR flag >O
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
Labels: review

#1403 For #1399 - Only show battery saver theme preference for API <P
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  app/src/main/res/values-v28/bools.xml
  app/src/main/res/values/bools.xml
  app/src/main/res/xml/theme_preferences.xml
Labels: review

#1363 Fixes #1361: Adds new tab when selecting history or bookmark items
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: review

#1362 Closes #1195: Adds telemetry for quick action sheet
  CHANGELOG.md
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionComponent.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionUIView.kt
Labels: review

#1428 Closes #1422 - Do not hide keyboard on pause
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1426 For #1421 - Fix Shortcut ToggleButton states
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutEngineManager.kt
  app/src/main/res/color/toggle_text_color.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/styles.xml
Labels: review

#1435 For #627 - Set Engine Setting for PreferredColorScheme
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: review

#1434 For #1049 - Add New Top Progress Bar Gravity
  app/src/main/res/layout/component_search.xml
Labels: review

#1440 For #469: remove "Your" from "Your library" string
  app/metrics.yaml
  app/src/main/res/values/strings.xml
Labels: review

#1432 For #904 - Add tab counter to tab icon
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/res/drawable/mozac_ui_tabcounter_box.xml
  app/src/main/res/layout/mozac_ui_tabcounter_layout.xml
Labels: review

#1433 For #1002 and #1222: Adds ability to restore crashed tabs
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt
Labels: review

#1450 Closes #1429: Updated site permissions ui for MVP
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/site_permissions_preferences.xml
Labels: review

#1464 For #1456 - Fixes missing delete button
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/DeleteTabsViewHolder.kt
  app/src/main/res/layout/component_session_control.xml
  app/src/main/res/layout/component_sessions.xml
  app/src/main/res/layout/component_tabs.xml
Labels: review

#1457 For #1312, #1236, #1237, #1238, #1239: Creating, Editing, and Deleting
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Int.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkUIView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarksSharedViewModel.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/SignInComponent.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/SignInUIView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/res/layout/bookmark_row.xml
  app/src/main/res/layout/component_bookmark.xml
  app/src/main/res/layout/component_sign_in.xml
  app/src/main/res/layout/fragment_add_bookmark_folder.xml
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_edit_bookmark.xml
  app/src/main/res/layout/fragment_select_bookmark_folder.xml
  app/src/main/res/menu/bookmarks_add_folder.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapterTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1463 Fixes #1157 - Addes Fenix Core to the telemetry notification list
  app/metrics.yaml
Labels: review

#1466 No Issue - Only block a subset of trackers by default
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: review

#1471 No Issue - Bump GeckoView Nightly version.
  buildSrc/src/main/java/Gecko.kt
Labels: review

#1470 Fixes home screen animation
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/drawable/home_header_shadow.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/xml/home_scene.xml
Labels: review

#1475 Bump GeckoView to latest
  buildSrc/src/main/java/Gecko.kt
Labels: review

#1473 For #1406, #1465 - Only pop browser when all sessions have been removed
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1477 For #1445 - Update vector icons
  app/src/main/res/drawable/ic_about.xml
  app/src/main/res/drawable/ic_archive.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_formfill.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_internet.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_login.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_qr.xml
  app/src/main/res/drawable/ic_screenshots.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_shortcuts.xml
  app/src/main/res/drawable/ic_tabs.xml
  app/src/main/res/xml/preferences.xml
Labels: review

#1480 For #860 - Update suggestion highlight light theme
  app/src/main/res/values/colors.xml
Labels: review

#1479 For #897 - Set default theme so private mode doesn't have to recreate
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ThemeManager.kt
Labels: review

#1490 No issue: Fixes master after a-c snapshot changes
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
Labels: review

#1492 For #1488 - add telemetry bool to project automation
  automation/taskcluster/lib/tasks.py
Labels: review

#1497 Fixes #1496: Crash adding bookmark folder
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
Labels: review

#1494 No Issue - Adds a debug metric controller
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
Labels: review

#1505 For #1459 - Try more ways to get title for history item
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: review

#1508 For #1408 - Set Toolbar titles in code (vs in navgraph)
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SitePermissionsFragment.kt
Labels: review

#1509 For #1068 - Adds the ability to quickly copy a URL
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/res/values/strings.xml
Labels: review

#1462 Closes #1420: Moves tab preview to top of page
  app/src/main/java/org/mozilla/fenix/home/ImageViewTopCrop.kt
  app/src/main/res/layout/tab_list_row.xml
Labels: review

#1524 Fixes #1485 - Page crash message now displays correctly in dark theme
  app/src/main/res/layout/fragment_crash_reporter.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: review

#1521 No Issue - Adds some proguard clauses
  app/proguard-rules.pro
Labels: review

#1520 For #689: Adds fade animation to Android <9.0
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1452 Closes #1170: Allow user to add a new site exception to site permissions
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/Storage.kt
  app/src/main/java/org/mozilla/fenix/settings/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
  app/src/main/res/layout/fragment_manage_site_permissions_feature_phone.xml
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/values/permissions_settings_strings.xml
  app/src/main/res/values/styles.xml
Labels: review

#1522 Fixes #1517 - Filter private sessions when updating the tab counter
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: review

#1518 Fixes #1504 - Added missing bottom constraint for bookmark icon image…
  app/src/main/res/layout/bookmark_row.xml
Labels: review

#1527 adds missing class
  app/proguard-rules.pro
Labels: review

#1417 1321: Dep-sign APKs for Raptor on-master-push
  .taskcluster.yml
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/build_variants.py
  automation/taskcluster/lib/chain_of_trust.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/lib/util.py
Labels: review

#1537 Passthrough browser performance test activity
  app/src/main/java/org/mozilla/fenix/browser/BrowserPerformanceTestActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: review

#1538 Try to fix build bustage from #1321.
  automation/taskcluster/lib/tasks.py
Labels: review

#1543 For #1542 - Add ripple to quick action buttons
  app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt
  app/src/main/res/layout/layout_quick_action_sheet.xml
Labels: review

#1544 Fix #1516: fixed scrolling library menu in landscape mode
  app/src/main/res/layout/fragment_library.xml
Labels: review

#1546 Fixes Snackbar interaction with the browser toolbar
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarBottomBehavior.kt
Labels: review

#1548 Closes #1530 - center history text
  app/src/main/res/layout/history_list_item.xml
Labels: review

#1559 Fix #1159 - Hide the QuickActionBar if fullscreen
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: review

#1560 Fixes #1498 - Ignores missing translation lint
  app/lint.xml
Labels: review

#1549 Fixes #1534 - Fixes snackbar not finding the root layout
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
Labels: review

#1563 For #1139: Cold start has Dispatchers.Main 1/5th second delay
  CHANGELOG.md
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1564 Adds a gitattribute file to manage changelog merges
  .gitattributes
Labels: review

#1584 For #176 - Start swipe to close gesture
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SwipeToDeleteCallback.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/SessionViewHolder.kt
  app/src/main/res/drawable/session_background.xml
Labels: review

#1587 For #538 - Reverse tabs in list
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlUIView.kt
Labels: review

#1592 Fix #1531 - Remember HistoryState.Mode to choose the right HistoryAction.Delete
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryDeleteButtonViewHolder.kt
Labels: review

#1550 For #1539: Add bookmark multi-select features
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkComponent.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkUIView.kt
  app/src/main/res/layout/component_sign_in.xml
  app/src/main/res/menu/bookmarks_select_multi.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkComponentTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1604 Remove deprecated success path for Firefox Accounts login
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Services.kt
Labels: review

#1605 No Issue - Remove data team from notifications emails list
  app/metrics.yaml
Labels: review

#1603 For #619 - Keep toolbar expanded while page is loading
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarBottomBehavior.kt
Labels: review

#1569 No issue: Make bookmark deletion undoable
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/ext/CoroutineScope.kt
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/res/values/strings.xml
Labels: review

#1612 For #1084 - Add Setting to enable/disable TP
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable/ic_tracking_protection.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/tracking_protection_preferences.xml
Labels: review

#1606 For #800 - Adds metrics for the default search engine
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: needs data review, review

#1600 For #1599: Crash creating a bookmark for a custom tab
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: review

#1625 No issue: Missing clear button in edit bookmarks UI
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/layout/fragment_add_bookmark_folder.xml
  app/src/main/res/layout/fragment_edit_bookmark.xml
Labels: review

#1611 For #668: Restyles custom tabs
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: review

#1626 No issue: Add Bookmark multi-select edit button
  CHANGELOG.md
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/menu/bookmarks_select_multi.xml
Labels: review

#1638 Fixes #1610: Gives unique identifier to shortcut engine picker suggestions
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProvider.kt
Labels: review

#1640 For #1495 - Reverts editing translated string and creates a new string
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/res/values/strings.xml
Labels: review

#1642 For #1084 - Update TP Policy for the current engineSession
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
Labels: review

#1641 For #724: Fixes white color in dark mode and removes android:tint
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_new.xml
  app/src/main/res/drawable/ic_private_browsing.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/layout/bookmark_row.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  app/src/main/res/layout/session_item.xml
  app/src/main/res/layout/tab_header.xml
  app/src/main/res/values/colors.xml
Labels: review

#1645 Fixes #1430 - Implements UX feedback for the FenixSnackbar
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
Labels: review

#1654 For #1084 - Add tracking protection toggle to quick settings dialog
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsComponent.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
  app/src/main/res/drawable/ic_tracking_protection_disabled.xml
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/values/strings.xml
Labels: review

#1630 For #1616: Parallelize the loading of experiments.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: review

#1651 Fixes #1646: Changes bookmarks toolbar color
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/res/values/colors.xml
Labels: review

#1665 Closes #1655 - Use accent bright for switch in quick settings
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
Labels: review

#1656 Update GeckoView to 68.0.20190414095735 (following AC).
  buildSrc/src/main/java/Gecko.kt
Labels: review

#1670 UI tests for the home screen
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/ExampleInstrumentedTest.kt
  app/src/androidTest/java/org/mozilla/fenix/FirefoxTestApplication.kt
  app/src/androidTest/java/org/mozilla/fenix/FirefoxTestRunner.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1659 Fixes #1632: Hides keyboard on exit, shows on entry
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1663 Closes #1644 - Correct progress bar gravity
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt
Labels: review

#1664 For #1658 - Reload current session (if exists) when theme changes
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
Labels: review

#1666 Fixes #1662: Corrects ripple style for private browsing button
  app/src/main/res/drawable/ic_private_browsing.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/styles.xml
Labels: review

#1705 No issue: Cleans up SearchShortcut changes
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: review

#1677 For #1158 - Add search counts
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: review

#1697 Closes #977: Adds telemetry for custom tabs
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1709 For #1676 - Removes setting for location services
  app/src/main/res/xml/data_choices_preferences.xml
Labels: review

#1711 For #1699 - Remove links to settings sections for beta
  app/src/main/res/xml/preferences.xml
Labels: review

#1713 For #1698 - Removes unimplemented library sections for the beta
  app/src/main/java/org/mozilla/fenix/library/LibraryFragment.kt
  app/src/main/res/layout/fragment_library.xml
Labels: review

#1715 For #1700 - Hides incomplete features in the quick action bar
  app/src/main/res/layout/layout_quick_action_sheet.xml
Labels: review

#1740 For #921: Adds styling to error pages
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/res/raw/high_risk_error_style.css
  app/src/main/res/raw/low_and_medium_risk_error_style.css
  app/src/main/res/raw/low_risk_error_pages.html
  app/src/main/res/raw/medium_and_high_risk_error_pages.html
Labels: review

#1739 For #1297 - Re-adds adjust to build task
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  automation/taskcluster/lib/tasks.py
Labels: review

#1738 Revert "For #689: Adds fade animation to Android <9.0"
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: review

#1708 For #974: Telemetry for Bookmarks
  CHANGELOG.md
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
Labels: review

#1704 Fixes #1691 - Site permissions' pages are not entirely visible
  app/src/main/res/layout/fragment_manage_site_permissions_exceptions_feature_phone.xml
  app/src/main/res/layout/fragment_manage_site_permissions_feature_phone.xml
Labels: review

#1748 For #1264 - Removes data choice options
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/res/xml/data_choices_preferences.xml
Labels: review

#1752 Fix crash loading AdjustLifecycleCallbacks
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Labels: review

#1764 Upgrade A-C to 0.51.0-SNAPSHOT
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Gecko.kt
Labels: review

#1684 #1682 Fixing typos on strings comments [ci skip]
  app/src/main/res/values/strings.xml
Labels: review

#1763 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko/strings.xml
Labels: review

#1778 Fix #1732: Fix crashes opening bookmarks
  app/src/main/java/org/mozilla/fenix/ext/Int.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: review

#1772 Fix blank custom tabs following an NPE.
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
Labels: review

#1777 For #1751 - Add Delete Button to Private Toolbar
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: review

#1779 For #1775 - Remove Language from settings for Beta
  app/src/main/res/xml/preferences.xml
Labels: review

#1781 For #1719: tracking protection label in quick settings almost invisible
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsUIView.kt
Labels: review

#1783 For #1084 - Remove Exceptions from TP setting for Beta
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/res/xml/tracking_protection_preferences.xml
Labels: review

#1782 For #1116 - Fix the language code generation
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
Labels: review

#1786 For #1049 - Round out progress bar
  app/src/main/res/drawable/progress_gradient.xml
Labels: review

#1792 Closes #1790 - Add QuickSettingsChange for TP Toggle Action
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
Labels: review

#1797 No issue: Removes session time out related code
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: review

#1795 For #1375 - Add Bookmarks Suggestion Provider
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarUIView.kt
Labels: review

#1799 For #1682: Bookmark string fix for l10n
  app/src/main/res/values/strings.xml
Labels: review

#1808 For #1701, #1703: Bookmark multi-select icons wrong color after deselect
  app/src/main/java/org/mozilla/fenix/ext/Int.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
Labels: review
