Repository mozilla-mobile/fenix, pull requests merged in 2020-10, with the labels that each got.

#15775 For #14923 - Removes auto size preference toggle
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAccessibilityRobot.kt
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/accessibility_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/ExtensionsTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#15845 No issue - Commit auto-generated glean changes for metrics.md
  docs/metrics.md
Labels: needs:review

#15747 For #14735: Remove debug logs from release build.
  app/proguard-rules.pro
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/FenixLogSink.kt
  app/src/test/java/org/mozilla/fenix/FenixLogSinkTest.kt
Labels: do not land, needs:uplift

#15647 For #12062 - Launch back to browser if we previously had tabs
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt
  app/src/test/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivityTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:approved, pr:needs-landing

#15861 For #15265 - Save cached top sites for metrics ping
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/UriOpenedObserver.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/browser/UriOpenedObserverTest.kt
Labels: pr:approved, pr:waiting-for-authors

#15811 For #15347 - Adds telemetry for tab settings
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  docs/metrics.md
Labels: pr:approved

#15908 For #15907 - Remove the usage of the TabTrayGridItemDecorator
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayGridItemDecorator.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:approved, pr:needs-landing

#15643 For #15596 - Removes upgrade faq link from fennec builds
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
Labels: needs:uplift, pr:approved

#15938 Uplift for 15711 - Custom search providers deleted after upgrade to 81.1.12 Build 2015767043
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
Labels: pr:approved

#15944 Bump A-C to 60.0.5
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#15918 Bug 1671415 - Remove 2019 youtube-playback tests.
  taskcluster/ci/browsertime/kind.yml
  taskcluster/ci/raptor/kind.yml
  taskcluster/fenix_taskgraph/transforms/browsertime.py
  taskcluster/fenix_taskgraph/transforms/raptor.py
Labels: needs:review

#15886 For #10683: Show longer tab titles
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing, ux:approved

#15940 Closes #11286: Add TelemetryMiddleware to remove Session[Manager] observers
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/fenix/browser/TelemetrySessionObserver.kt
  app/src/main/java/org/mozilla/fenix/browser/UriOpenedObserver.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/browser/TelemetrySessionObserverTest.kt
  app/src/test/java/org/mozilla/fenix/browser/UriOpenedObserverTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:approved, pr:needs-ac-bump

#15690 For #15561: add comments to issue template
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: pr:approved, pr:needs-landing

#15909 For #7345 - Update new shield icons, remove lottie
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/res/drawable-v24/shield_dark.xml
  app/src/main/res/drawable-v24/shield_light.xml
  app/src/main/res/drawable/shield_dark.xml
  app/src/main/res/drawable/shield_light.xml
  app/src/main/res/raw-night/shield_json.json
  app/src/main/res/raw/shield_json.json
  app/src/main/res/raw/shield_json_dark.json
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:approved, pr:needs-landing, ux:approved

#15639 For #8947 - Lint check for licenses in Kotlin/Java source files
  mozilla-lint-rules/build.gradle
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/LicenseCommentChecker.kt
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/LicenseDetector.kt
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/LintIssueRegistry.kt
  mozilla-lint-rules/src/test/java/org/mozilla/fenix/lintrules/LicenseDetectorTest.kt
Labels: needs:review

#15988 Issue #15731 - Enable `tg` on release locales.
  l10n-release.toml
Labels: needs:uplift, pr:approved, pr:needs-landing

#15967 For #15937 - Remove topFrecentSite feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/customization_preferences.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:approved, pr:needs-landing

#15975 For #15796 - Use the device locale for the system locale subtitle
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
Labels: pr:approved, pr:needs-landing

#15984 Issue #15731 - Enable `tg` on release locales.
  l10n-release.toml
Labels: pr:approved, pr:needs-landing

#16026 Configure M5 AMO collection for all builds
  app/build.gradle
Labels: pr:approved

#15885 For #14744: Also show Fill link from clipboard with search shortcuts.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: needs:review

#16021 Update Android Components, Kotlin, Gradle plugin
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/exceptions/login/LoginExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/TabCollection.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/res/layout/fragment_add_on_internal_settings.xml
  app/src/main/res/layout/fragment_browser.xml
  buildSrc/src/main/java/AndroidComponents.kt
  buildSrc/src/main/java/Dependencies.kt
  mozilla-lint-rules/build.gradle
Labels: pr:needs-landing

#15253 For #15111 - Update the UI when a collection is renamed
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: needs:review

#15884 For #11631: Move report site issue extension to main menu.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved, pr:needs-ac-bump, pr:waiting-for-authors, ux:approved

#16051 FennecWebAppIntentProcessor: Catch JSONException.
  app/src/main/java/org/mozilla/fenix/customtabs/FennecWebAppIntentProcessor.kt
Labels: pr:needs-landing

#16011 For #11397 - Add lint rule for AppCompatResources instead of ContextCompat
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/readermode/ReaderModeController.kt
  app/src/main/java/org/mozilla/fenix/components/tips/providers/MasterPasswordTipProvider.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  mozilla-lint-rules/build.gradle
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/ContextCompatDetector.kt
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/LintIssueRegistry.kt
  mozilla-lint-rules/src/test/java/org/mozilla/fenix/lintrules/ContextCompatDetectorTest.kt
Labels: needs:review

#16065 #274-android-l10n: Update create account string to avoid partial tran…
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:do-not-land

#15768 For #15080: Handle default search engine when editing or removing
  app/src/main/java/org/mozilla/fenix/components/Search.kt
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/EditCustomSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineListPreference.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProviderTest.kt
Labels: needs:review, pr:needs-landing

#16060 For #16054 - Enable pull to refresh webpage in Nightly and Debug
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: needs:review

#15955 For #14619: Show half a tab top offset when scrolling to selected tab.
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values/dimens.xml
Labels: pr:approved, ux:approved

#16070 For #15910 - Adds back automatic toggle, disables slider when enabled
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAccessibilityRobot.kt
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/AccessibilityFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TextPercentageSeekBarPreference.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/accessibility_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/ExtensionsTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:approved, pr:needs-landing

#16100 For #16084 - match elevation of Tab in Collection to header
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/values/dimens.xml
Labels: pr:approved, pr:needs-landing

#16099 For #12062 - Add feature flag for returning users to browser on cold start if they have open tabs for Nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: pr:approved, pr:waiting-for-authors

#15749 For #15543 - Expand / collapse tabs tray depending on all tabs
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:approved, pr:needs-landing, ux:approved

#15674 For #15508: Show error when trying to save empty or invalid bookmark URL
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
  app/src/main/res/layout/fragment_edit_bookmark.xml
Labels: pr:approved, pr:needs-landing, ux:approved

#16066 For #6313 - Set session ClearColor through Engine DefaultSettings
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:do-not-land, pr:needs-ac-bump

#16180 For #16122 - Add a dark theme color for the top sites pin icon
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: needs:UX-feedback, pr:approved, pr:needs-landing

#16186 For #8169 - Upgrade Mockwebserver
  app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/MockWebServer.kt
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DeepLinkTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeveloperToolsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSyncTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: eng:automation, eng:ui-test

#16181 For #15379: Use proper url when sharing.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:approved, pr:waiting-for-authors

#15880 Closes #15816 - Attempt to handle 'allowInPrivate..' pref with detached context
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: needs:review, pr:needs-changes

#16137 Closes #11285: Replace Session[Manager] observers in BaseBrowserFragment
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: pr:approved

#16227 For #10690: re-enable editBookmarkTest
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test

#16081 For # 15929: Remove the search widget discoverability experiment.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/ExperimentsManager.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/cfr/SearchWidgetCFR.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable-xhdpi/search_widget_illustration.png
  app/src/main/res/layout/search_widget_cfr.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  docs/metrics.md
Labels: needs:review

#16229 For #14637 - Fix sitePermissionsFeature breaking change + AC bump
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#16219 For #16161 - Fixes Saved Login toolbar layout
  app/src/main/res/layout/navigation_toolbar.xml
  app/src/main/res/layout/saved_logins_sort_items_toolbar_child.xml
Labels: pr:approved

#16267 No issue: Make sure we are cleaning up test coroutines
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationTelemetryListenerTest.kt
  app/src/test/java/org/mozilla/fenix/push/WebPushEngineIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsStorageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareViewModelTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/SyncedTabsControllerTest.kt
Labels: pr:approved, pr:needs-landing
