Repository mozilla-mobile/fenix, pull requests merged in 2020-11, with the labels that each got.

#16254 For #14552: Do not display back button when there is no tab history.
  app/src/main/assets/high_risk_error_pages.html
  app/src/main/assets/low_and_medium_risk_error_pages.html
Labels: needs:review

#15939 For #15931: Sort Downloads from newest to oldest
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadFragmentTest.kt
Labels: needs:UX-feedback, pr:approved

#16275 Closes #16268: Allowing multiple task while sharing
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: pr:approved

#16322 Uplift: Disable remote USB debugging for SDK <23.
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: pr:approved

#16310 For #6313 - Remove unneeded delay in BrowserAnimator
  app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt
Labels: pr:approved

#15942 15278 detekt rule runblocking
  .github/CODEOWNERS
  app/src/androidTest/java/org/mozilla/fenix/ui/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/AppStartupTelemetry.kt
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
  app/src/main/java/org/mozilla/fenix/customtabs/FennecWebAppIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/ext/AtomicInteger.kt
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/perf/RunBlockingCounter.kt
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt
  app/src/test/java/org/mozilla/fenix/ext/AtomicIntegerTest.kt
  app/src/test/java/org/mozilla/fenix/perf/RunBlockingCounterTest.kt
  config/detekt.yml
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/CustomRulesetProvider.kt
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/MozillaRunBlockingCheck.kt
Labels: needs:review

#16290 For #4652 - Remove activityViewModels workarounds
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
Labels: pr:approved

#16326 For #12062: Switch to consumeFlow and add tests
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: pr:approved

#16316 For #13446 UI tests: wait for historyList to exist
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: eng:ui-test, intermittent-test

#16314 Closes #16256: Introduce build flag for "Mozilla Online" variant.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/Config.kt
Labels: needs:review

#16350 Uplift #16267 - Make sure we are cleaning up test coroutines
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationTelemetryListenerTest.kt
  app/src/test/java/org/mozilla/fenix/push/WebPushEngineIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsStorageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareViewModelTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/SyncedTabsControllerTest.kt
Labels: needs:review

#16346 For #15847: disables verifyAboutFirefoxPreview UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
Labels: eng:ui-test, intermittent-test

#16311 Closes #12971 - Show collection saved snackbar above...
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
Labels: pr:approved

#16178 For #13172: Reverse tab swipe gestures for navigating between tabs.
  app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
Labels: pr:needs-landing

#16349 Fixes #16348 - Increase Gradle daemon memory size
  gradle.properties
Labels: needs:uplift, pr:approved

#16359 Update to Android-Components 63.0.5.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16320 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#16315 For #6521 - Remove auto sigin onboarding card
  app/src/main/java/org/mozilla/fenix/home/Mode.kt
  app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
Labels: pr:approved

#16329 No issue: Update stable androidx and material versions
  app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:approved, pr:needs-landing

#16371 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#16384 Closes #13242 : Add mozcn safebrowsing
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:approved

#16405 Fix GeckoProvider for beta and release variant.
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:needs-landing

#16372 For issue #15934 fix ConcurrentModificationException on WifiConnectionMonitor
  app/src/main/java/org/mozilla/fenix/wifi/WifiConnectionMonitor.kt
Labels: needs:review

#16419 For #15847: use Espresso's RecyclerView scrollTo action
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: eng:ui-test, intermittent-test

#16418 Update to Android-Components 63.0.6.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16428 For #15764: Update Tabs summary description.
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/strings.xml
Labels: pr:approved

#16452 Update to Android-Components 63.0.7.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16462 For #15960 - Enable Grid View in Nightly only
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:approved

#15887 For #15720 - Remove unused telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/intent/NotificationsIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
Labels: needs:review

#16460 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#16491 Uplift: Update l10n-release.toml to include gl and sat
  l10n-release.toml
Labels: pr:approved

#16236 For #16132 - Revise multiselect mode UI
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/MultiselectSelectionMenu.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayItemMenu.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/res/layout/component_tabstray.xml
  app/src/main/res/layout/tabs_tray_save_to_collections_item.xml
  app/src/main/res/layout/tabstray_multiselect_items.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractorTest.kt
Labels: pr:approved

#16480 Update Android Components version
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
  docs/metrics.md
Labels: pr:needs-landing

#16490 Update l10n-release.toml to include gl and sat
  l10n-release.toml
Labels: pr:approved

#16523 Closes #13217: fixed UI test for main menu items
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncedTabsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#16245 For #11376 - Reverse tabs list order
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: needs:UX-feedback, pr:needs-changes

#16526 Closes #16302: Use larger heap size when running unit tests and fork new process after every 80 test classes.
  app/build.gradle
Labels: needs:review

#16466 For #14920 - Show a Tabs Tray CFR Banner for grid view tip
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractorTest.kt
Labels: pr:approved, pr:needs-landing

#16531 Upift For #14772: Crash in Downloads
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
Labels: needs:review

#16493 For #16132 - Rename normal mode menu item, remove telemetry
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/tabtray/MultiselectSelectionMenu.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayItemMenu.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  docs/metrics.md
Labels: pr:approved

#16532 Update to Android-Components 63.0.8
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review

#16535 For #15761 - [Grid View] Enable the grid view and remove its feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/main/res/xml/tabs_preferences.xml
Labels: needs:review

#16515 Closes #16451 : Change default top sites to Baidu & JD in China build
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/drawable/ic_baidu.png
  app/src/main/res/drawable/ic_jd.png
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: pr:approved, pr:needs-landing

#16548 #16345 Fix lingering share icon replacement
  app/src/main/res/layout/tabstray_multiselect_items.xml
Labels: pr:needs-landing

#16550 Closes #12899: fixed UI test for ETP off
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:ui-test

#16324 For #15725: Set up preferences in onCreatePreferences instead of onResume
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
Labels: pr:needs-landing

#16514 For #16376: assert view hierarchy depth & ConstraintLayout children on start up
  .github/CODEOWNERS
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
Labels: needs:review

#16498 Close #13477: Move BiometricPrompt to a separate feature
  app/src/main/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/biometric/ext/BiometricManager.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/biometric/ext/BiometricManagerKtTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#16618 For #16614 - Ensure a stable order for the items in tabs tray.
  app/src/main/java/org/mozilla/fenix/tabtray/SyncedTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/test/java/org/mozilla/fenix/tabtray/SyncedTabsControllerTest.kt
Labels: pr:approved

#16619 Update Android Components to 67.0.20201117165227
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/test/java/org/mozilla/fenix/push/WebPushEngineIntegrationTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#16616 For #16615: UI smoke test firstRunScreenTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:ui-test

#16635 Update to Android-Components 67.0.2.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#16631 For #15788: Remove nested constraint layout in tabs tray.
  app/src/main/res/layout/component_tabstray.xml
  app/src/main/res/layout/tabstray_multiselect_items.xml
Labels: needs:review

#16628 For #16351 - Make homescreen interactive when search dialog is up
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt
Labels: needs:review

#16639 Update Android Components to 68.0.20201118210655
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review

#16543 Fixes #16542 Nimbus Global Opt Out
  app/build.gradle
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDataCollectionRobot.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/data_choices_preferences.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:approved

#16656 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved

#16674 Bug 1678572 - A github-release shouldn't kick off releases if the bot…
  .taskcluster.yml
Labels: pr:approved

#16641 For #16351 - Add divider lines for search dialog
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/res/layout/fragment_search_dialog.xml
Labels: needs:review

#16715 Update to Android-Components 67.0.4.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16738 For #16615: UI smoke test addPredefinedSearchEngineTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: eng:ui-test

#16753 Update to Android-Components 67.0.5.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16785 Issue #12731: Log and record breadcrumb when onTrimMemory() gets invoked.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: needs:review

#16787 Introduce build flag for disabling optmization.
  app/build.gradle
Labels: needs:review
