Repository mozilla-mobile/fenix, pull requests merged in 2020-06, with the labels that each got.

#11109 Tests and cleanup for tracking protection
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/SwitchWithDescription.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionCategoryItem.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionMode.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionStore.kt
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
Labels: eng:tech-debt

#10420 Fixes #9696: Adds Add-ons menu item to the home menu
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: needs:UX-feedback

#11053 Add tests for some of collection creation
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationBottomBarView.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationStore.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationBottomBarViewTest.kt
Labels: eng:tech-debt

#11147 For #10798: Disable testDownloadPrompt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: disabled-test, intermittent-test

#10481 For #10434: Handle cases when proc/$pid/stat is not accessible.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/perf/StartupFrameworkStartMeasurement.kt
  app/src/main/java/org/mozilla/fenix/perf/Stat.kt
  docs/metrics.md
Labels: needs:data-review

#11160 For #11154: Fix button color on migration UI
  app/src/main/res/layout/activity_migration.xml
Labels: needs:uplift

#11211 For #11118: Add toggle states to metrics ping
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  docs/metrics.md
Labels: needs:data-review

#11337 No issue: Update Flank to v20.06.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#11187 For #11132: Rearranges home menu items
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/drawable/ic_synced_tabs.xml
Labels: eng:ready

#11159 Fixes #8725 - Allow for async execution order
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: intermittent-test

#11164 Add tests for widget
  app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/widget/SearchWidgetProviderTest.kt
  app/src/test/java/org/mozilla/fenix/widget/VoiceSearchActivityTest.kt
Labels: eng:tech-debt

#11391 For #11390 - Removes redundant session observer init for ETP overlay
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: pr:needs-landing

#11528 Add test for SearchStringValidator
  app/src/test/java/org/mozilla/fenix/settings/search/SearchStringValidatorTest.kt
Labels: eng:tech-debt

#11503 For #11498 #11499 - preland new synced tabs strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#10976 [UI Tests] For #116 #173: Verify the nav toolbar buttons
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:automation

#11533 For #11442 - Telemetry for tab counter menu.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  docs/metrics.md
Labels: needs:data-review

#11584 Cleanup tests for toolbar controller
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: eng:tech-debt

#11643 No issue: Disable verifyBasicNavigationToolbarFunctionality
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: disabled-test, eng:ui-test

#11592 For #10909: flaky navigateBookmarksFoldersTest
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test

#11620 Add tests for addon details
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsView.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/Extensions.kt
  app/src/test/java/org/mozilla/fenix/addons/AddonDetailsViewTest.kt
Labels: eng:tech-debt, pr:needs-landing

#11491 For #11456 addon details fragment should use constraint layout, not relative layout
  app/src/main/res/layout/fragment_add_on_details.xml
Labels: pr:needs-landing

#11724 For #11642 & #10642: Disable intermittent tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
Labels: eng:ui-test, intermittent-test

#11748 For #10642: Comment out verifyPageContent calls
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:automation, eng:ui-test, intermittent-test

#11765 No issue: re-enables tests ignoring the verifyPageContent step
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: eng:ui-test

#11768 For #11642: disables crashing UI test privateModeScreenItemsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: eng:ui-test, intermittent-test

#11637 For #11500 - Remove wrong activity title
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt
Labels: pr:needs-landing

#11803 Fixes #11797: defaultDesktopBookmarksFoldersTest intermittent failure
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test, intermittent-test

#11667 No issue: refactor tabs tray to use interactor/controller, add tests
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractorTest.kt
Labels: Skittle, eng:tech-debt

#11824 Add tests for ContextKt
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/test/java/org/mozilla/fenix/ext/ContextTest.kt
Labels: eng:tech-debt

#11826 No Issue - Fixes flash when toggling tab tray
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: Feature:Tabs, Skittle

#11480 Expose reports as artifacts
  taskcluster/ci/lint/kind.yml
  taskcluster/ci/test/kind.yml
Labels: eng:automation

#11647 For #8621 - fix intermittent test failures
  app/src/main/java/org/mozilla/fenix/perf/StartupTimeline.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupHomeActivityLifecycleObserverTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
Labels: intermittent-test

#11924 For #8374 - On external session removed, handle back press
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#11907 For #11903: fix custom tab private gradient
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  app/src/main/res/drawable/toolbar_background_private.xml
Labels: pr:needs-landing

#11925 Add tests for share sheet
  app/src/main/java/org/mozilla/fenix/share/listadapters/ShareTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolder.kt
  app/src/test/java/org/mozilla/fenix/share/ShareCloseViewTest.kt
  app/src/test/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/share/viewholders/AppViewHolderTest.kt
Labels: eng:tech-debt, pr:needs-landing

#11931 For #11430 - Gives enough padding to the tab tray give adequate space…
  app/src/main/res/layout/component_tabstray.xml
Labels: pr:needs-landing

#11932 For #11406 - Scrolls to selected tab when switching modes
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:needs-landing

#11475 Add tests for collection creation controller
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationController.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
Labels: eng:tech-debt

#9959 For #9100 - Private browsing notification fixes
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/session/NotificationSessionObserver.kt
  app/src/main/java/org/mozilla/fenix/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/fenix/session/VisibilityLifecycleCallback.kt
  app/src/test/java/org/mozilla/fenix/session/NotificationSessionObserverTest.kt
Labels: pr:needs-landing

#11904 For #11901: Use safe call for collection item info.
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
Labels: pr:needs-landing

#11887 For #8080: Dismiss menu when swiping away from its anchor.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
Labels: pr:needs-landing

#11926 For #11825: Removing the last pretty animation 😞
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
Labels: pr:needs-landing

#11881 For #11880: Provide default text color for errors in a TextInputLayout
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#11894 For #11562: Align overflow menu button with close buttons.
  app/src/main/res/layout/tab_tray_item.xml
Labels: pr:needs-landing

#11908 For #11860 - Conditionally show add to collection button on Home screen
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/layout/no_collections_message.xml
Labels: pr:needs-landing

#11706 For #11183: Redirect user to homescreen after widget added
  app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
Labels: pr:needs-landing

#11878 Bugfix/#11672, #11727: Delete default tab text and add padding to infinite character
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt
Labels: pr:needs-landing

#11865 For #11613: Expand toolbar onUrlChanged
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#11895 Configure M3 AMO collection for Nightly/Debug
  app/build.gradle
Labels: pr:needs-landing

#11897 No issue: Update Flank to v20.06.2
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#11951 Closes #11947: fix and enable closePrivateTabsNotificationTest
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: eng:ui-test

#11867 #10824: Onboarding telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
  docs/metrics.md
Labels: needs:data-review

#11949 Fixes #11764: delay single-click duration to avoid long-clicks in ThreeDotMenu UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: eng:ui-test, intermittent-test

#11871 For #11866 - Update back press logic for SearchFragment
  app/src/main/java/org/mozilla/fenix/search/SearchController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/search/DefaultSearchControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchInteractorTest.kt
Labels: eng:perf-impact

#12027 For #11943: Fix intermittent coroutine failure
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationController.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
Labels: pr:needs-landing

#12023 Test settings about/advanced
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutItem.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutPageAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/about/viewholders/AboutItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/settings/about/AboutPageAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/about/viewholders/AboutItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: pr:needs-landing

#11940 for #11830 added new metric for collecting startup method from all startup phases
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  docs/metrics.md
Labels: needs:data-review

#12041 For #12002: Show default tab background when thumbnail not available
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#11930 For #11044 - Sets the anchorView of the snackbar to be the new tab fab
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
Labels: pr:needs-landing

#11966 For #11903: Enforce private theme in custom tabs
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  app/src/main/res/drawable/toolbar_background_private.xml
Labels: pr:needs-landing

#12049 For issue #11835 - Update text fonts
  app/src/main/res/layout/account_preference.xml
  app/src/main/res/layout/collections_list_item.xml
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/component_collection_creation_select_collection.xml
  app/src/main/res/layout/fragment_tracking_protection_blocking.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/layout/no_collections_message.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#12055 Configure M3 AMO collection for all builds
  app/build.gradle
Labels: pr:needs-landing

#12094 Fix ignored XML lint issues
  app/src/main/res/drawable/ic_addons_extensions.xml
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_open_in_app.xml
  app/src/main/res/layout/fragment_edit_login.xml
  app/src/main/res/layout/preference_cat_style.xml
  app/src/main/res/layout/search_widget_large.xml
  app/src/main/res/layout/search_widget_medium.xml
Labels: eng:health

#12138 For #12081 - Properly installs searchengines when MLS completes
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
Labels: needs:uplift
