Repository mozilla-mobile/fenix, pull requests merged in 2020-05, with the labels that each got.

#10350 Fix home navigation
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: do not land

#10354 No issue: remove listing directory contents on UI test results
  automation/taskcluster/androidTest/ui-test.sh
Labels: eng:automation

#10407 No Issue Reenable testDownloadPrompt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: do not land

#10446 For #10426: Adds identifier to Glean for 24 hours
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/ActivationPing.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/InstallationPing.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/ActivationPingTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTestRoboelectric.kt
  docs/metrics.md
Labels: needs:data-review

#10478 for #10468: wait for main menu to disappear after creating bookmark
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation, intermittent-test

#10532 For #10426: Removes installation ping GAID
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/InstallationPing.kt
  docs/metrics.md
Labels: do not land

#10566 for #9407: fixed and added collection tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation

#10620 Disable failing tests from #10587 and #10586
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: eng:automation, intermittent-test

#10526 No issue: Update Flank to v20.05.0 (stable)
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#10643 for #10587: Disable all flaky collections tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: eng:automation, intermittent-test

#10649 fixed audioPlaybackSystemNotificationTest flaky test
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
Labels: eng:automation, intermittent-test

#10612 Closes #10611 - Fix exit status of Flank
  automation/taskcluster/androidTest/ui-test.sh
Labels: eng:automation

#10634 for #7032 scroll to dismiss keyboard in search fragment
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: do not land

#10772 No issue: Disable validateBaselinePing UI test
  app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt
Labels: eng:automation

#10819 for #10759: close notification shade if still open
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
Labels: eng:automation

#10842 for #10753: improves the clickAddBookmarkButton method in flaky tests
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation

#10860 For #10859 - Use dark or light mode colors for tab tray in private mode
  app/src/main/res/layout/component_tabstray.xml
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: Feature:Tabs

#10937 For #10936: Adds identifier to Glean InstallationPing
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/InstallationPing.kt
  docs/metrics.md
Labels: needs:data-review

#10945 for #10761: changes the trackingProtection test page
  app/src/androidTest/assets/pages/trackingPage.html
  app/src/androidTest/assets/resources/trackingAPI.js
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
Labels: eng:automation, intermittent-test

#10981 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#10928 Closes #10927: Improve wait on session loaded for UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/SessionLoadedIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:automation

#11057 Add tests for FenixOnboarding
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/test/java/org/mozilla/fenix/onboarding/FenixOnboardingTest.kt
Labels: eng:tech-debt
