Repository mozilla-mobile/fenix, pull requests merged in 2020-02, with the labels that each got.

#8047 For #6834: Adds telemetry for About page items
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  docs/metrics.md
Labels: needs:data-review

#8049 For #7836: Updates the password icons to use and tint the mozac version. 🎲
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/res/drawable/ic_password_hide.xml
  app/src/main/res/drawable/ic_password_reveal.xml
  app/src/main/res/layout/fragment_saved_login_site_info.xml
Labels: Feature:Logins, eng:health

#7968 For #7289: Adds telemetry for selecting dark theme
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/ThemeFragment.kt
  docs/metrics.md
Labels: pr:needs-landing

#8067 Closes #8066: disable failing UI Bookmarks tests
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
Labels: eng:automation

#7958 For #6980: Update ETP onboarding card
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/res/color/primary_state_list_text_color.xml
  app/src/main/res/layout/onboarding_tracking_protection.xml
Labels: pr:needs-landing

#8064 Provide add-on support
  app/build.gradle
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonPermissionsDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/Extensions.kt
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/NotYetSupportedAddonFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/WebExtensionActionPopupFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/drawable/addon_textview_selector.xml
  app/src/main/res/drawable/mozac_ic_extensions_black.xml
  app/src/main/res/drawable/mozac_ic_permissions.xml
  app/src/main/res/layout/activity_addons.xml
  app/src/main/res/layout/fragment_add_on_details.xml
  app/src/main/res/layout/fragment_add_on_internal_settings.xml
  app/src/main/res/layout/fragment_add_on_permissions.xml
  app/src/main/res/layout/fragment_add_ons_management.xml
  app/src/main/res/layout/fragment_installed_add_on_details.xml
  app/src/main/res/layout/fragment_not_yet_supported_addons.xml
  app/src/main/res/layout/overlay_add_on_progress.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  buildSrc/src/main/java/Dependencies.kt
  docs/metrics.md
Labels: needs:data-review

#8000 For #7999 - Change fxa leanplum metrics to false by default
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#7976 For #7862: Correct "Learn more" arrow icon direction in ETP settings for RTL layouts
  app/src/main/res/drawable/ic_arrowhead_right.xml
Labels: pr:needs-landing

#8112 Bump to a-s 0.50.0.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolder.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: do not land

#8092 Clean up toolbar menu class
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
Labels: eng:health

#8134 Use navArgs helper in fragments
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonPermissionsDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/NotYetSupportedAddonFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/WebExtensionActionPopupFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/EditCustomSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
Labels: eng:health

#8130 Add license header to ext tests
  app/src/test/java/org/mozilla/fenix/ext/ActivityTest.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserIconsTest.kt
  app/src/test/java/org/mozilla/fenix/ext/DrawableTest.kt
  app/src/test/java/org/mozilla/fenix/ext/FragmentTest.kt
  app/src/test/java/org/mozilla/fenix/ext/ImageButtonTest.kt
  app/src/test/java/org/mozilla/fenix/ext/LogTest.kt
  app/src/test/java/org/mozilla/fenix/ext/NavControllerTest.kt
  app/src/test/java/org/mozilla/fenix/ext/SharedPreferences.kt
  app/src/test/java/org/mozilla/fenix/ext/StringTest.kt
  app/src/test/java/org/mozilla/fenix/whatsnew/WhatsNewStorageTest.kt
Labels: eng:health

#8093 Fixes #5711 Added tint to onboarding icons
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingIcon.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
  app/src/main/res/layout/onboarding_finish.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#8106 For #5694 - Changes migration list item 'Logins' to 'Passwords'
  app/src/main/java/org/mozilla/fenix/migration/MigrationProgressActivity.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#8170 NOISSUE - Updated misspelled variable name in Custom tab Doorhanger
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionsView.kt
  app/src/main/res/layout/quicksettings_permissions.xml
Labels: Feature:QuickSettings, eng:health

#8138 For #7511 - Override private customtab icon tint
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: Feature:CustomTabs

#8129 Use createBlendModeColorFilterCompat
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/ext/Toolbar.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
Labels: eng:health, pr:needs-landing

#6346 Adding UI tests for the Basic Menu settings. 🎲 !!!!
  app/src/androidTest/java/org/mozilla/fenix/helpers/Matchers.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/assertions/AwesomeBarAssertion.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/matchers/BitmapDrawableMatcher.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAccessibilityRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDefaultBrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuThemeRobot.kt
Labels: eng:automation

#8227 No Issue: Updated About Settings Tests to check if a view is completely displayed.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: eng:automation, 🐞 bug

#8208 For #8172: Add a new "Fenix" Leanplum attribute
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationTelemetryListener.kt
  app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt
  docs/mma.md
Labels: needs:data-review

#8098 For #8126 - Adds default top sites
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/TopSiteStorage.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable/ic_pocket.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  docs/metrics.md
Labels: pr:needs-landing

#8295 For #7896: integrate text selection search from AC
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: implementation review

#8313 For #1741: Passes 'showDescription' boolean to SearchSuggestionProvider
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: do not land

#8377 For #7957: Enable Login management preference for all users
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/res/xml/account_settings_preferences.xml
  app/src/main/res/xml/preferences.xml
Labels: do not land

#8555 🎲 For #8552 - Fixes bug where "installing/uninstalling" was using the o…
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
Labels: needs:uplift

#8601 🧊🎲 For #8535 #8498: Allow for multiple browsingModeListeners dispatch.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/browsingmode/BrowsingModeManager.kt
Labels: needs:uplift

#8661 🎲For #7604 - Correct header colors in navigation bar!
  app/src/main/res/layout/navigation_toolbar.xml
Labels: pr:work-in-progress

#8753 For #8752: fix invalid AutoplayAction crash.
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: Release Blocker, b:crash

#8686 Bug 1614287 - part 3: Let fennec-beta upload APKs on Google Play's al…
  taskcluster/ci/push-apk/kind.yml
  taskcluster/fenix_taskgraph/transforms/push_apk.py
Labels: do not land

#8833 No issue: Disable UI test verifyContextCopyLink for intermittent failure
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: eng:automation, intermittent-test

#8783 Disable Nightly startup test
  taskcluster/ci/startup-test/kind.yml
Labels: eng:automation
