Repository mozilla-mobile/fenix, pull requests merged in 2020-09, with the labels that each got.

#13474 FNX-14654 ⁃ Simplify media state drawables
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
  app/src/main/res/drawable/media_state_background.xml
  app/src/main/res/drawable/media_state_pause.xml
  app/src/main/res/drawable/media_state_play.xml
  app/src/main/res/drawable/pause_with_background.xml
  app/src/main/res/drawable/tab_tray_pause_with_background.xml
  app/src/main/res/drawable/tab_tray_play_with_background.xml
  app/src/main/res/layout/tab_list_row.xml
  app/src/main/res/layout/tab_tray_item.xml
Labels: eng:health

#13268 FNX-14449 ⁃ Gradle configuration avoidance
  app/build.gradle
  build.gradle
Labels: eng:build

#14644 For #14642: Use correct 'Close tabs' summary text for "After one month"
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: needs:uplift

#14689 For #14665: Replace hardcoded label with string resource.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: needs:uplift

#14694 For #14609 - Correct nav from new search experience to browser
  app/src/main/java/org/mozilla/fenix/searchdialog/SearchDialogFragment.kt
Labels: needs:uplift

#14692 For #14679 For #14676 - Dismiss MP Migration tip, init in disabled state
  app/src/main/java/org/mozilla/fenix/components/tips/providers/MasterPasswordTipProvider.kt
  app/src/main/res/layout/fragment_edit_login.xml
  app/src/main/res/values/strings.xml
Labels: needs:uplift

#14704 Enforce IO thread inside of components
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationController.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
  app/src/main/java/org/mozilla/fenix/components/PermissionStorage.kt
  app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
Labels: pr:needs-landing

#14451 For #14376: Reverse items with bottom toolbar
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/TabCounterMenuTest.kt
Labels: pr:needs-landing

#14699 For #14460: Fix PBM notification
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/res/drawable/ic_private_browsing.xml
Labels: needs:UX-feedback, pr:needs-landing

#14308 Extract checkbox selected mask
  app/src/main/java/org/mozilla/fenix/tabtray/FenixTabsAdapter.kt
  app/src/main/res/layout/checkbox_item.xml
  app/src/main/res/layout/tab_tray_item.xml
Labels: eng:health

#14940 For #13829: Disables verifyAddonsCanBeUninstalled UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
Labels: eng:ui-test, intermittent-test

#14927 For #14902 - Disabling bottom toolbar animation now works
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
Labels: pr:needs-landing

#14965 No issue - Updates AC to 58.0.20200910190642 and fixes imports
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/BreadcrumbsRecorder.kt
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/BreadcrumbRecorderTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#14999 For #14283 - Fixes overlapping search suggestions and hint
  app/src/main/java/org/mozilla/fenix/searchdialog/SearchDialogFragment.kt
  app/src/main/res/layout/fragment_search_dialog.xml
  app/src/main/res/layout/search_suggestions_hint.xml
Labels: needs:uplift

#15098 CI run: Integrate Synced Tabs AwesomeBar suggestions
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/search_preferences.xml
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing

#14963 For #14933 - Fixed private browsing icon color in preferences fragment
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: pr:needs-landing

#15155 Closes #13829: Added idling resources to the addon details view
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerAddonDetailedMenuRobot.kt
Labels: eng:ui-test

#13923 For #13922: Add indicator to synced tabs suggestions in awesomebar
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: pr:needs-landing

#14804 For #13300 - Adjust the 'Sharing a Collection' layout to prevent over…
  app/src/main/res/layout/share_close.xml
Labels: pr:needs-landing

#14135 Closes #14131: Move constants to dimens.xml
  app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/ext/SpannableString.kt
  app/src/main/java/org/mozilla/fenix/ext/View.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkTouchHelper.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabtray/CollectionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabsTouchHelper.kt
  app/src/main/java/org/mozilla/fenix/utils/Undo.kt
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/fenix/ext/ViewTest.kt
Labels: eng:health, pr:needs-landing

#15197 For #14982 - Show snackbars with padding with static bottom toolbar
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
Labels: pr:needs-landing

#15201 For #13934 - Make TabHistory work on PWA/Custom Tabs
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryController.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryView.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryControllerTest.kt
Labels: pr:needs-landing

#15298 Closes #14524, #12896, #13830: re-enabled strict ETP tests after code bug fix
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
Labels: eng:ui-test

#15395 For #15349: Fixes SyncedTabs suggestion not clicking (nightly)
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: pr:needs-landing

#15399 No issue: Update Flank to v20.09.3
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#15396 For #15349: Fixes SyncedTabs suggestion not clicking (beta)
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: do not land, needs:uplift

#15315 Use "undo" implementation from Android Components.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Undo.kt
Labels: pr:needs-landing
