Repository mozilla-mobile/fenix, pull requests merged in 2020-07, with the labels that each got.

#12140 Revert "For #9946: Update FennecBeta branding (#10066)" to push to Fi…
  app/src/fennecBeta/res/drawable-hdpi/fenix_search_widget.png
  app/src/fennecBeta/res/drawable/ic_launcher_foreground.xml
  app/src/fennecBeta/res/mipmap-hdpi/ic_launcher.png
  app/src/fennecBeta/res/mipmap-hdpi/ic_launcher_round.png
  app/src/fennecBeta/res/mipmap-mdpi/ic_launcher.png
  app/src/fennecBeta/res/mipmap-mdpi/ic_launcher_round.png
  app/src/fennecBeta/res/mipmap-xhdpi/ic_launcher.png
  app/src/fennecBeta/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/fennecBeta/res/mipmap-xxhdpi/ic_launcher.png
  app/src/fennecBeta/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/fennecBeta/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/fennecBeta/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/fennecBeta/res/values/static_strings.xml
Labels: pr:needs-landing

#12142 Fixes #11642 - Re-enable disabled UI-tests
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
Labels: eng:automation, eng:ui-test, pr:needs-landing

#12176 #12169. Fix pre-push hook instructions.
  config/pre-push-recommended.sh
Labels: pr:needs-landing

#12177 For #12007: Follow ux mock on Settings --> Search screen
  app/src/main/res/layout/checkbox_left_sub_preference.xml
  app/src/main/res/layout/custom_search_engine_radio_button.xml
  app/src/main/res/layout/preference_cat_style.xml
  app/src/main/res/layout/preference_search_add_engine.xml
  app/src/main/res/layout/search_engine_radio_button.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/search_preferences.xml
Labels: pr:needs-landing

#12251 Closes #8714: Re-enable toggleShowVisitedSitesAndBookmarks
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
Labels: eng:automation, eng:ui-test

#12250 No issue: Re-enable Context Menu UI tests
  app/src/androidTest/assets/pages/generic4.html
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
Labels: eng:automation, eng:ui-test

#12314 For #12309: Disable verifyContextSaveImage and verifyContextMixedVariations
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: eng:automation, eng:ui-test, intermittent-test

#12313 For #11764: doubles long-press delay UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
Labels: eng:ui-test, intermittent-test

#12246 Update Android Components version
  app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#12324 For #12086: Follow ux mock on Settings --> Customize screen
  app/src/main/res/layout/preference_cat_style.xml
  app/src/main/res/layout/preference_widget_radiobutton.xml
Labels: pr:needs-landing

#12325 For #12016: Follow ux mock on Settings --> Data Collection
  app/src/main/res/xml/data_choices_preferences.xml
Labels: pr:needs-landing

#12323 For #12007: Fix add search engine items using wrap content for height
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/main/res/layout/custom_search_engine_radio_button.xml
Labels: pr:needs-landing

#12328 For #12263 - Adds end margin to synced tabs header
  app/src/main/res/layout/view_synced_tabs_group.xml
Labels: pr:needs-landing

#12326 For #12078: Follow ux mock on Settings --> Language screen
  app/src/main/res/layout/component_locale_settings.xml
  app/src/main/res/layout/fragment_locale_settings.xml
  app/src/main/res/layout/locale_settings_item.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#12187 Bug 1649400 - part 3: Stop publishing fenixNightly, fennecNightly, and fenixBeta to Google Play
  taskcluster/ci/push-apk/kind.yml
Labels: pr:needs-landing

#11493 Extract radio group logic into helper
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/view/GroupableRadioButton.kt
  app/src/main/java/org/mozilla/fenix/utils/view/ViewHolder.kt
  app/src/test/java/org/mozilla/fenix/utils/view/GroupableRadioButtonTest.kt
Labels: eng:tech-debt

#12343 Update Android Components version
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#12358 Use A-C version of Resources.getSpanned
  app/src/main/java/org/mozilla/fenix/ext/Resources.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
Labels: eng:tech-debt

#12370 Add tests for browser helper classes
  app/src/main/java/org/mozilla/fenix/browser/FenixSnackbarDelegate.kt
  app/src/test/java/org/mozilla/fenix/browser/FenixSnackbarDelegateTest.kt
  app/src/test/java/org/mozilla/fenix/browser/TelemetrySessionObserverTest.kt
  app/src/test/java/org/mozilla/fenix/browser/UriOpenedObserverTest.kt
Labels: eng:tech-debt

#11522 Add tests for onboarding viewholders
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolder.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingSectionHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolderTest.kt
Labels: eng:tech-debt

#12336 [WIP][UI Tests]No Issue: Verify the page main menu items test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/FindInPageRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncedTabsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: do not land, eng:automation, eng:ui-test

#12352 For #11303 - Change copy login origin to open in browser
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/LoginDetailFragment.kt
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_open_in_new.xml
  app/src/main/res/layout/fragment_login_detail.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#12222 Add links in Checks panel for test/lint tasks
  build.gradle
  buildSrc/src/main/java/org/mozilla/fenix/gradle/tasks/GithubDetailsTask.kt
  taskcluster/ci/lint/kind.yml
  taskcluster/ci/test/kind.yml
Labels: eng:automation

#12464 Fix Robolectric tests SDK version
  app/src/test/resources/robolectric.properties
Labels: eng:automation

#12504 For #10911: disables flaky createBookmarkFolderTest
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
Labels: eng:ui-test, intermittent-test

#12521 [uplift] For #12345: catch SecurityException when calling reportFullyDrawn.
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupReportFullyDrawn.kt
Labels: 79ReleaseBlocker, pr:needs-landing

#12258 For #11886 - Re-enable codecov
  automation/taskcluster/.codecov
  automation/taskcluster/upload_coverage_report.sh
  taskcluster/ci/test/kind.yml
Labels: eng:automation

#12524 Test viewholders in home.sessioncontrol
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyBrowsingViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt
Labels: eng:test-debt

#12437 Add tests for search
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProvider.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProviderTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: eng:test-debt

#12552 No issue: Add a couple Tabs Tray UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: Feature:Tabs, eng:automation, eng:ui-test

#12567 Fix nav graph and theme tests
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyBrowsingViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing

#12520 Add helper for underlining text
  app/src/main/java/org/mozilla/fenix/ext/TextView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingIcon.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/tips/ButtonTipViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotectionexceptions/ExceptionsView.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolderTest.kt
Labels: eng:health, eng:test-debt

#12560 Add tests for StartupReportFullyDrawn
  app/src/main/java/org/mozilla/fenix/perf/StartupReportFullyDrawn.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupReportFullyDrawnTest.kt
Labels: eng:test-debt

#12499 Replaces verifyPageContent in UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:ui-test

#12548 For #12544 - Prevent search engines mixup
  app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt
Labels: 79ReleaseBlocker, eng:qa:needed, needs:uplift

#12423 cron-job-ui-screenshots
  .cron.yml
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  automation/taskcluster/androidTest/flank-x86-screenshots-tests.yml
  automation/taskcluster/androidTest/ui-test.sh
  taskcluster/ci/ui-test/kind.yml
  taskcluster/fenix_taskgraph/target_tasks.py
Labels: do not land

#12512 Closes #12493: Remove kapt plugin
  app/build.gradle
Labels: eng:build

#11965 For #11704 Add leanplum attributes for tracking protection
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  docs/mma.md
Labels: pr:needs-landing

#12601 For #12600 - remove AddonInstalled event when the permission dialog is shown
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: pr:needs-landing

#12579 For #12565: Add Locale settings tests & use activity
  app/src/main/java/org/mozilla/fenix/settings/advanced/DefaultLocaleSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleManagerExtension.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/BaseLocaleViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleManagerExtensionTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleSettingsStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleViewHoldersTest.kt
Labels: eng:health, eng:test-debt

#12581 Add tests for sync, wifi, and push
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsViewHolder.kt
  app/src/main/java/org/mozilla/fenix/wifi/SitePermissionsWifiIntegration.kt
  app/src/main/java/org/mozilla/fenix/wifi/WifiConnectionMonitor.kt
  app/src/test/java/org/mozilla/fenix/push/LeanplumNotificationCustomizerTest.kt
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/wifi/SitePermissionsWifiIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/wifi/WifiConnectionMonitorTest.kt
Labels: eng:test-debt

#12507 Ensure logins deletion
  app/src/main/java/org/mozilla/fenix/settings/logins/LoginsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/LoginsListViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsView.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractorTest.kt
Labels: pr:needs-landing

#12612 For #12457: Add MockK matcher for intents
  app/src/test/java/org/mozilla/fenix/addons/AddonDetailsViewTest.kt
  app/src/test/java/org/mozilla/fenix/browser/browsingmode/DefaultBrowsingModeManagerTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/BreadcrumbRecorderTest.kt
  app/src/test/java/org/mozilla/fenix/components/tips/providers/MigrationTipProviderTest.kt
  app/src/test/java/org/mozilla/fenix/ext/MockKMatcherScope.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/DefaultSearchControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetryTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
Labels: eng:test-debt

#11208 For #10173: login duplicates and save
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/LoginDetailView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/LoginsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/LoginsListController.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/interactor/EditLoginInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/interactor/LoginDetailInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/interactor/SavedLoginsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/EditLoginView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginDetailView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginsAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginsListViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/SavedLoginsListView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/color/save_enabled_ic_color.xml
  app/src/main/res/layout/fragment_edit_login.xml
  app/src/main/res/layout/fragment_saved_logins.xml
  app/src/main/res/menu/login_save.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/settings/logins/EditLoginInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginDetailInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginDetailViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsStorageControllerTest.kt
  docs/metrics.md
Labels: 🙅 waiting

#12640 No issue: Update Flank to v20.07.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#12649 Add tests for adapters in collections
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/TabDiffUtil.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/collections/SaveCollectionListAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/collections/TabDiffUtilTest.kt
Labels: eng:test-debt

#12652 Test session control controller
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/about/viewholders/AboutItemViewHolderTest.kt
Labels: eng:test-debt

#12681 Add tests for login exceptions
  app/src/main/java/org/mozilla/fenix/loginexceptions/LoginExceptionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/loginexceptions/LoginExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/loginexceptions/LoginExceptionsView.kt
  app/src/main/java/org/mozilla/fenix/loginexceptions/viewholders/LoginExceptionsHeaderViewHolder.kt
  app/src/test/java/org/mozilla/fenix/loginexceptions/LoginExceptionsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/loginexceptions/LoginExceptionsViewTest.kt
  app/src/test/java/org/mozilla/fenix/loginexceptions/viewholders/LoginExceptionsDeleteButtonViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/loginexceptions/viewholders/LoginExceptionsHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/loginexceptions/viewholders/LoginExceptionsListItemViewHolderTest.kt
Labels: eng:test-debt

#12677 Test migration classes
  app/src/main/java/org/mozilla/fenix/migration/MigrationProgressActivity.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationStatusAdapter.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationTelemetryListener.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationStatusAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationTelemetryListenerTest.kt
Labels: eng:test-debt

#12517 Change enabled lint rules
  app/lint.xml
Labels: eng:automation

#12683 Fix lint issues
  app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
  app/src/main/res/layout/fragment_manage_site_permissions_exceptions_feature_phone.xml
Labels: eng:health

#10930 Closes #10924 - Cleanup SavedLoginsAuthFragment
  app/src/main/java/org/mozilla/fenix/settings/logins/SyncLoginsPreferenceView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SyncLoginsPreferenceViewTest.kt
Labels: eng:health

#12749 For #5499 - Unify CFR drawables and dimens
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt
  app/src/main/res/drawable/ic_cfr_triangle.xml
  app/src/main/res/drawable/ic_pbm_triangle.xml
  app/src/main/res/drawable/ic_triangle.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/layout/search_widget_cfr.xml
  app/src/main/res/layout/tracking_protection_onboarding_popup.xml
  app/src/main/res/values/dimens.xml
Labels: eng:health

#12760 For #12240: Enable btime youtube-playback Fenix tests
  taskcluster/ci/browsertime/kind.yml
  taskcluster/fenix_taskgraph/transforms/browsertime.py
Labels: pr:needs-landing

#12623 [UI Tests]No issue: Verify ETP toolbar shield icon is not displayed if ETP is OFF globally
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
Labels: eng:automation, eng:ui-test

#12225 Bug 1652979 - Stop producing fennecNightly, fenixNightly and fenixBeta
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/Config.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
  taskcluster/ci/browsertime/kind.yml
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/mark-as-shipped/kind.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/raptor/kind.yml
  taskcluster/ci/signing/kind.yml
Labels: pr:work-in-progress

#12685 Add tests for web push integration
  app/src/main/java/org/mozilla/fenix/push/WebPushEngineIntegration.kt
  app/src/test/java/org/mozilla/fenix/push/WebPushEngineIntegrationTest.kt
Labels: eng:test-debt

#12777 Add SearchActionProvider for faster responses that mirro… 4650bcb …r entered text.
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: eng:perf-impact

#12799 For #12797: Use measured height/width for loading a thumbnail
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#12808 For #12801 - Extra debug menu trigger, disable if already triggered
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/SecretDebugMenuTrigger.kt
  app/src/test/java/org/mozilla/fenix/settings/about/SecretDebugMenuTriggerTest.kt
Labels: pr:needs-landing

#12519 For #1048 - Add ability to view tab history by long-pressing the back or forward button.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/OnBackLongPressedListener.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryController.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryView.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolder.kt
  app/src/main/res/layout/component_tabhistory.xml
  app/src/main/res/layout/fragment_tab_history_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryInteractorTest.kt
Labels: eng:perf-impact

#12432 Issue #11333: Set ContentBlocking settings directly on GeckoRuntime
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: do not land

#12747 Create ToolbarPosition enum
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt
  app/src/main/java/org/mozilla/fenix/cfr/SearchWidgetCFR.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarPosition.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolderTest.kt
Labels: eng:health

#12810 Test sync adapter
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsLayout.kt
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsLayoutTest.kt
Labels: eng:test-debt

#12837 Add tests for some classes in home/browser
  app/src/main/java/org/mozilla/fenix/browser/UriOpenedObserver.kt
  app/src/main/java/org/mozilla/fenix/home/tips/ButtonTipViewHolder.kt
  app/src/test/java/org/mozilla/fenix/browser/UriOpenedObserverTest.kt
  app/src/test/java/org/mozilla/fenix/browser/readermode/DefaultReaderModeControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/tips/ButtonTipViewHolderTest.kt
Labels: eng:test-debt

#12869 No issue: Fix recent UI test breakage
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: eng:automation, eng:ui-test

#12891 For #12473: Disbales failing verifyContextCopyLink UiTest
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: eng:ui-test, intermittent-test

#12902 For #12893: Disables failing deleteAllHistoryTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: eng:ui-test, intermittent-test

#12925 For #12804: Set min height for search engine radio button
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/main/res/layout/custom_search_engine_radio_button.xml
  app/src/main/res/layout/search_engine_radio_button.xml
Labels: pr:needs-landing

#12948 For #12947 - Adjust tab selected state on bind
  app/src/main/java/org/mozilla/fenix/tabtray/FenixTabsAdapter.kt
Labels: pr:needs-landing

#12970 For: #12894, #12899, #12968, #11239, disables failing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/DeepLinkTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test, intermittent-test

#9258 Created Addons Settings UI Test
  app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/idlingresource/AddonsInstallingIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/idlingresource/AddonsLoadingIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerAddonDetailedMenuRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation

#12183 For issue #12181 - Convert String to sentence case
  app/src/main/res/values/strings.xml
Labels: pr:needs-changes

#11035 For #6846: Added quick actions for nav bar in home.
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/utils/ToolbarPopupWindowTest.kt
Labels: pr:needs-landing

#12790 For #12565 - Clean up search controller and add tests
  app/src/main/java/org/mozilla/fenix/search/SearchController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/test/java/org/mozilla/fenix/search/DefaultSearchControllerTest.kt
Labels: eng:health, eng:test-debt

#12994 For #12991 - Set height to recommended touch target size for collect …
  app/src/main/res/layout/component_tabstray.xml
Labels: pr:needs-landing

#13020 For #12968: Re-enables Search settings tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
Labels: eng:ui-test

#13026 Closes #13021: Fix verifyAboutFirefoxPreview UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: eng:ui-test, intermittent-test

#13007 Test paged history provider
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: eng:test-debt

#12922 For #12707 - Add vertical scrollbar to search suggestions
  app/src/main/res/layout/fragment_search.xml
Labels: needs:UX-feedback

#12923 For #12704 - Add vertical scrollbar to history screen
  app/src/main/res/layout/component_history.xml
Labels: needs:UX-feedback

#12924 For #12706 - Add vertical scrollbar to bookmarks screen
  app/src/main/res/layout/component_bookmark.xml
Labels: needs:UX-feedback

#12995 Reorganized to highlight the CPG and Bugzilla guidelines
  README.md
Labels: pr:needs-landing

#12984 Closes #12692: Remove www. prefix in tab tray urls
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
Labels: pr:needs-changes

#12329 Switch to groovy in buildSrc
  buildSrc/build.gradle
Labels: eng:automation

#11351 Add tests for Metrics
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/BreadcrumbRecorderTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: eng:tech-debt

#13124 For #11664 — Fixup MissingResourceExceptions being thrown in exotic Locales
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
Labels: R79

#13131 For #11690 - Add areContentsTheSame to top sites and collections in session cont…
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
Labels: pr:needs-landing

#13141 No issue: Adds sameAs function for TopSiteList AdapterItem
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
Labels: pr:needs-landing

#13138 For #11664 — Fixup MissingResourceExceptions being thrown in exotic L…
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
Labels: pr:needs-landing

#13142 For #11664 — Fixup MissingResourceExceptions being thrown in exotic L…
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabtray/SaveToCollectionsButtonAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:needs-landing

#13137 For #6846 - Don't show ToolbarPopupWindow if nothing to show
  app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Labels: pr:needs-landing

#13139 For #12769: Refactored Background Service Test into multiple test cases.
  app/src/test/java/org/mozilla/fenix/components/BackgroundServicesTest.kt
Labels: pr:needs-landing

#13182 For #13135 - Replace about top header with Firefox Daylight
  app/src/main/java/org/mozilla/fenix/Config.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/res/values/static_strings.xml
Labels: needs:uplift
