Repository mozilla-mobile/fenix, pull requests merged in 2020-04, with the labels that each got.

#9556 For #8125 - Send top sites count with metrics ping
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  docs/metrics.md
Labels: needs:data-review

#9466 Closes #9433: Update Flank version in ui-tests Dockerfile
  automation/taskcluster/androidTest/flank-x86.yml
  taskcluster/ci/ui-test/kind.yml
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#8318 For #6174 - Add telemetry for WebExtensions
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  docs/metrics.md
Labels: needs:data-review

#9635 No issue: remove num-flaky-test-attempts from all Flank templates
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  automation/taskcluster/androidTest/flank-armeabi-v7a-start-test.yml
  automation/taskcluster/androidTest/flank-armeabi-v7a.yml
  automation/taskcluster/androidTest/flank-x86-start-test.yml
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:automation

#9639 No issue: re-enable libraryMenuItemsTest and backButtonTest
  app/src/androidTest/java/org/mozilla/fenix/ui/LibraryMenuTest.kt
Labels: eng:automation

#9742 Fix errors in top_sites_count metric.
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: pr:needs-landing

#9745 No issue: Set all Flank templates to one AVD
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  automation/taskcluster/androidTest/flank-armeabi-v7a-start-test.yml
  automation/taskcluster/androidTest/flank-armeabi-v7a.yml
  automation/taskcluster/androidTest/flank-x86-start-test.yml
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:automation

#9606 Fix #9461 - Re-trigger taskcluster jobs on dep download fail
  taskcluster/ci/build/kind.yml
  taskcluster/ci/test/kind.yml
Labels: eng:automation, intermittent-test

#9671 Closes #9495: Dismiss the ShareFragment in onPause()
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
Labels: pr:needs-landing

#9756 For #2818 - Adds Picture-in-Picture feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#9855 Revert #9606 - do not retry build on fail
  taskcluster/ci/build/kind.yml
  taskcluster/ci/test/kind.yml
Labels: eng:automation, intermittent-test

#9767 For #9670: fix intermittent tests and verify system media notification is gone
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: eng:automation

#9840 For #7208 For #7212 - Update parameterized strings
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/PrivateShortcutCreateManager.kt
  app/src/main/java/org/mozilla/fenix/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt
  app/src/main/res/layout/fragment_sign_out.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#9838 For #9692 - Fix "Install" PWA menu item labeling.
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenuTest.kt
Labels: pr:needs-landing

#9658 For #8546 - Use destructive_normal_theme colors for login panel errors
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#10122 No issue: Update Flank in UI-Tests Dockerfile [dummy edit]
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#9835 Add 'useEmail' metrics event
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountProblemFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  docs/metrics.md
Labels: needs:data-review

#10192 [UI Test] no issue: fix private notification text
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
Labels: eng:automation

#9878 Adds new Bookmarks UI tests & closes #7417
  app/src/androidTest/java/org/mozilla/fenix/helpers/RecyclerViewIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsTurnOnSyncRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuBookmarksRobot.kt
Labels: eng:automation

#10136 for #9783: bring app in focus with sendSingleTapToScreen
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:automation

#10089 Fixes #6760 - Show test results in tc task
  automation/taskcluster/androidTest/parse-ui-test.py
  automation/taskcluster/androidTest/ui-test.sh
  taskcluster/docker/base/Dockerfile
Labels: do not land, eng:automation
