Repository mozilla-mobile/fenix, pull requests merged in 2020-03, with the labels that each got.

#8733 Re-enable ETP UI tests and update local asset
  app/src/androidTest/assets/pages/etp.html
  app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation, intermittent-test

#8839 For #2271 - Fix hairline color on dark theme and private mode
  app/src/main/res/values/colors.xml
Labels: needs:UX-feedback, pr:work-in-progress

#8046 Bug 1608153 - Do not trigger a new build on every single action that …
  .taskcluster.yml
Labels: pr:needs-landing

#8875 Login storage refactor.
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsFragment.kt
  app/src/test/java/org/mozilla/fenix/components/BackgroundServicesTest.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
Labels: do not land

#8395 UI tests for Private browsing settings sub-menu
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDefaultBrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation

#8999 Added close private tabs tests
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:automation

#9122 No issue - Fixes shadow on top layout
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: needs:uplift

#9080 Bug 1621252 - Move Fenix Raptor tests to tier 1
  taskcluster/ci/raptor/kind.yml
Labels: pr:needs-landing

#9201 For #9200: Remove star icon from empty state icon in toolbar.
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: pr:needs-landing

#9259 Swap AVD (x86) Nexus 6 (API 25) with a Nexus6P (API 27)
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:automation

#9245 MigrationPushRenewer: Remove ExperimentalCoroutinesApi.
  app/src/migration/java/org/mozilla/fenix/MigrationPushRenewer.kt
Labels: pr:needs-landing

#9263 Closes #9262: Add additional waits to LibraryMenuTest
  app/src/androidTest/java/org/mozilla/fenix/helpers/ext/WaitNotNull.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/LibraryMenuTest.kt
Labels: eng:automation, intermittent-test

#9255 For #8592: Relocate device name in account preferences.
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/res/xml/account_settings_preferences.xml
Labels: pr:needs-landing

#9247 For #8653 - changed menu capitalization
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryListItem.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataItem.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#9292 Closes #9291: Fix shortcutSearchEngineSettingsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: eng:automation

#8306 For #6317 - Applies 3dot menuItem look to quickSettings and tracking
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/quicksettings_website_info.xml
  app/src/main/res/values/styles.xml
Labels: needs:UX-feedback

#9331 For #9256: Attempts to fix installation ping not being sent
  app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/InstallationPing.kt
Labels: do not land

#9378 For issue #9364 Crash when blocking app permissions and returning to the app
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
Labels: needs:uplift

#9417 Pass lazy references to FennecMigrator
  app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt
Labels: do not land

#9470 Closes #9469 - Change UI test failure output
  automation/taskcluster/androidTest/ui-test.sh
Labels: eng:automation, eng:release

#9439 Closes #9189: Fixes "static asset not found" error in AndroidAssetDispatcher dispatcher
  app/src/androidTest/java/org/mozilla/fenix/helpers/MockWebServer.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: eng:automation

#8903 For #8412: Passes error handling function to 'CustomTabWindowFeature'
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:UX-feedback

#9330 Added Media Notifications UITests
  -e
  app/src/androidTest/assets/pages/audioMediaPage.html
  app/src/androidTest/assets/pages/videoMediaPage.html
  app/src/androidTest/assets/resources/audioSample.mp3
  app/src/androidTest/assets/resources/videoSample.webm
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: eng:automation
