Repository mozilla-mobile/fenix, pull requests merged in 2020-08, with the labels that each got.

#13201 Renamed Deps.mozilla_ui_publicsuffixlist to Deps.mozilla_lib_publicsuffixlist
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#13222 For #13220, #13217: Disables failing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test, intermittent-test

#11859 For #10261: PWA Telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/shortcut/PwaOnboardingDialogFragment.kt
  docs/metrics.md
Labels: pr:needs-landing

#13184 For #11280 - Adds FxA Signed Up Leanplum Event
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  docs/mma.md
Labels: needs:data-review, needs:uplift

#13046 For #12906 - Fix swipe-to-delete bookmark folder.
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkTouchHelper.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkTouchHelperTest.kt
Labels: pr:needs-changes

#13263 For #13262: Update gradle
  app/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: eng:build

#13311 For #13218: Fix settingsAddonsItemsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:automation, eng:ui-test

#13344 No issue: Update Flank to v20.08.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#13345 No issue: Remove unused import in SettingsAddonsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
Labels: eng:automation, eng:ui-test

#13367 Changed name_collection_dialog.xml's EditText's input type from "text…
  app/src/main/res/layout/name_collection_dialog.xml
Labels: pr:needs-landing

#13352 Issue #13106 - 80 Beta branch bump AC version to 52.0.2
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#13510 For #13424 - Fix detekt config and warnings.
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt
  app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/FeatureFlagPreference.kt
  config/detekt.yml
Labels: eng:health

#13810 Closes #12778: re-arranged steps to follow current flow in closeTabTest & closePrivateTabTest
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: eng:ui-test

#13475 FNX-14655 ⁃ For #13404: Update Android lint URL
  build.gradle
Labels: eng:build

#13275 FNX-14456 ⁃ For #13251 - Use bottomSheetCallback in multiselect mode
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:needs-landing

#13502 Closes #13219: Fixing long-tap delay for UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: eng:ui-test, intermittent-test

#13947 No issue: Fix missing FeatureFlags imports
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:needs-landing

#13972 For #13938: Implement nav to notification settings for all OS versions.
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: do not land

#13967 for #7584 - make about libraries toolbar theme consistent
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutLibrariesFragment.kt
  app/src/main/res/layout/fragment_about_libraries.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/settings/about/AboutLibrariesFragmentTest.kt
Labels: pr:needs-changes, pr:needs-landing

#14115 Fix breaking AC change to support monochrome icons
  app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#14137 Replace setPadding with updatePadding
  app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/CollectionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/java/org/mozilla/fenix/utils/Undo.kt
Labels: eng:health

#14113 For #8765: Use shared list widget in exceptions
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsAdapter.kt
  app/src/main/java/org/mozilla/fenix/exceptions/viewholders/ExceptionsListItemViewHolder.kt
  app/src/main/res/layout/site_list_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/exceptions/viewholders/ExceptionsListItemViewHolderTest.kt
Labels: style guide

#11821 For 11660: fixing nits for previous #11668
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/TopSiteStorage.kt
  app/src/main/java/org/mozilla/fenix/ext/LiveData.kt
Labels: pr:needs-changes

#14244 Pre-land strings For #14243 For #14239
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#14245 No issue: monitor performance via CODEOWNERS.
  .github/CODEOWNERS
Labels: eng:performance

#14004 Closes #11944: changes the way the system notifications are tested
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: eng:ui-test

#12676 For #12673: Adjust top and left alignment of logo on homescreen
  app/src/main/res/layout/collection_header.xml
  app/src/main/res/layout/fragment_home.xml
Labels: pr:needs-landing

#13481 FNX-14661 ⁃ Delete drawables
  app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt
  app/src/main/java/org/mozilla/fenix/session/PrivateNotificationService.kt
  app/src/main/res/drawable-v26/ic_menu_kebab.xml
  app/src/main/res/drawable/bookmark_two_state.xml
  app/src/main/res/drawable/bookmarks_circle_background_filled.xml
  app/src/main/res/drawable/bookmarks_circle_background_outline.xml
  app/src/main/res/drawable/ic_collections_circle_background.xml
  app/src/main/res/drawable/ic_library.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_menu_tab_tray.xml
  app/src/main/res/drawable/ic_pbm_notification.xml
  app/src/main/res/drawable/ic_tab_circle_background.xml
  app/src/main/res/drawable/ic_whats_new_notification.xml
  app/src/main/res/drawable/library_icon_app_links_circle_background.xml
  app/src/main/res/drawable/library_icon_downloads_circle_background.xml
  app/src/main/res/drawable/library_icon_history_circle_background.xml
  app/src/main/res/drawable/library_icon_screenshots_circle_background.xml
  app/src/main/res/drawable/mozac_ic_permissions.xml
  app/src/main/res/drawable/quick_action_icon_appearance.xml
  app/src/main/res/drawable/quick_action_icon_read.xml
  app/src/main/res/drawable/quick_action_icon_share.xml
  app/src/main/res/layout/component_tabstray.xml
Labels: eng:health

#13909 Add tests for collection creation
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationStore.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationStoreTest.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapterTest.kt
Labels: eng:test-debt

#13884 For #8765: Use shared list widget in tab history
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolderTest.kt
Labels: style guide

#14371 No issue: Add strings for tab management
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#13854 Split toolbar controller into two classes
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserInteractor.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/test/java/org/mozilla/fenix/browser/browsingmode/SimpleBrowsingModeManager.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: eng:health

#13816 Remove un-needed nullables
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/searchdialog/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
Labels: eng:health

#14374 For #14376: Use concept-menu with tab counter menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserInteractor.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterMenuItem.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/TabCounterMenuTest.kt
Labels: Feature:MainMenu

#14370 For #14346: Fix min height on site list item
  app/src/main/res/layout/site_list_item.xml
Labels: style guide
