Repository mozilla-mobile/fenix, pull requests merged in 2020-01, with the labels that each got.

#7301 Closes #7085 - Remove anko version in Dependencies.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: eng:health

#7474 Change type for OnboardingAutomaticSignIn
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
Labels: eng:health

#7537 For #6620 Only close tab on back press if it has a parent tab.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#7548 Closes #7414
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#7486 For #1718: Sets accessibility users to top toolbar by default
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/ToolbarSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/toolbar_preferences.xml
Labels: do not land

#7409 For #7343: Handle sharing to multiple devices
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolder.kt
Labels: pr:needs-landing

#7567 For #6992 Always hide toolbar when showing find in page bar
  app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt
Labels: pr:needs-landing

#7601 Update App Services version to 0.48.1
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#7609 No issue: Fix dynamic theming to accommodate lazily inflated readerview
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/readermode/ReaderModeController.kt
Labels: pr:needs-landing

#7487 Bug 1605454 - Webrender experiment for Fenix
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing

#7598 For #7583 Align text in language title and subtitle to viewStart.
  app/src/main/res/layout/locale_settings_item.xml
Labels: pr:needs-landing

#7595 For #7593 Set AboutFragment title just in onCreate
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-landing

#7618 For #7431: Remove extra share button
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: Feature:CustomTabs

#7631 Closes #7611: Add UI tests for content context menus
  app/src/androidTest/assets/pages/generic4.html
  app/src/androidTest/assets/resources/rabbit.jpg
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:automation

#7413 Bugfix for About Settings test
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: eng:automation, 🐞 bug

#7471 Issue 7445 - Modified Onboarding Card Colors
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous.xml
  app/src/main/res/layout/onboarding_automatic_signin.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#7596 For #7594: Doesn't allow for hint in URL bar on main page in two lines
  app/src/main/res/layout/fragment_home.xml
Labels: do not land, needs:UX-feedback

#7688 Closes #7687: Temp disable UI test verifyContextCopyImageLocation and verifyContextSaveImage and verifyContextOpenImageNewTab
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: pr:needs-landing

#7694 Closes #7693: Temp disable UI test verifyContextMixedVariations
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: pr:needs-landing

#7667 For #5545 For #5542 Closes #6696 Integrate logins API, adds Settings for Autofilling/Saving Logins
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/LoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SaveLoginSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginSiteInfoFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_saved_logins.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/logins_preferences.xml
  app/src/main/res/xml/save_logins_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractorTest.kt
Labels: pr:needs-landing

#7310 For #6556: Adds Telemetry counts for Search Access Points
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  app/src/main/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/search/SearchController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchInteractorTest.kt
  docs/metrics.md
Labels: pr:needs-landing

#7572 For #7417 Wait for deletion to finish and loading of new UI
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
Labels: pr:needs-landing

#7776 For #220 - Puts language picker behind a feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/preferences.xml
Labels: needs:uplift

#7454 🎲 No Issue: Add custom detekt rule to blacklist certain properties
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  config/detekt.yml
  mozilla-detekt-rules/.gitignore
  mozilla-detekt-rules/build.gradle
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/CustomRulesetConsoleReport.kt
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/CustomRulesetProvider.kt
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/MozillaBannedPropertyAccess.kt
  mozilla-detekt-rules/src/main/resources/META-INF/services/io.gitlab.arturbosch.detekt.api.ConsoleReport
  mozilla-detekt-rules/src/main/resources/META-INF/services/io.gitlab.arturbosch.detekt.api.RuleSetProvider
  mozilla-detekt-rules/src/main/resources/config.yml
  mozilla-detekt-rules/src/test/java/org/mozilla/fenix/detektrules/MozillaBannedPropertyAccessTest.kt
  settings.gradle
Labels: eng:performance, pr:needs-landing

#7658 For #4904: Pressing hardware back external link doesn't go back
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#7777 For #6396 For #6553 - Update sync engine checkboxes and send telemetry once
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: pr:needs-landing

#7728 Bug 1608882 - part 1: Move Fennec Nightly to a dedicated hook
  .cron.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/fenix_taskgraph/target_tasks.py
  taskcluster/fenix_taskgraph/transforms/push_apk.py
Labels: pr:work-in-progress

#7683 For #3813 - Create a save button for bookmark editing
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/res/layout/fragment_edit_bookmark.xml
  app/src/main/res/menu/bookmarks_edit.xml
  app/src/main/res/values/strings.xml
  docs/metrics.md
Labels: pr:needs-landing

#7621 for #7421 :removed collection from clear browsing history
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/res/layout/fragment_delete_browsing_data.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-co/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
Labels: pr:needs-landing

#7767 For #5586 - Add telemetry for save logins setting
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SaveLoginSettingFragment.kt
  docs/metrics.md
Labels: needs:data-review

#7873 No issue: Enable about:config in beta builds
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/Config.kt
Labels: pr:needs-landing

#7916 No issue: Update Firefox Logo in Migration UI
  app/src/main/res/drawable/ic_firefox.xml
Labels: pr:needs-landing

#7909 No issue: don't export OssLicense*Activity.
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing

#7317 Connectivity manager tests
  app/src/test/java/org/mozilla/fenix/ext/ConnectivityManagerTest.kt
Labels: pr:needs-landing

#7914 Issue #7890: Make migration screen scrollable !!
  app/src/main/res/layout/activity_migration.xml
Labels: pr:needs-landing

#7891 For #7272: Show info when saved logins list is empty.
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/SavedLoginsView.kt
  app/src/main/res/layout/component_saved_logins.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractorTest.kt
Labels: pr:needs-landing
