Repository mozilla-mobile/fenix, pull requests merged in 2020-12, with the labels that each got.

#16812 For#16591: Split UI smoke tests into smaller tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#16800 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#16818 For #16032: Support installing recommended add-ons from AMO
  app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/Extensions.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
  app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
Labels: pr:needs-landing

#16826 Update to Android-Components 67.0.7.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16764 Issue #16648: Expose Nexus logs
  taskcluster/ci/toolchain/android.yml
Labels: pr:needs-landing

#16682 Nimbus-SDK-119 Get Nimbus server endpoint at build time.
  .gitignore
  README.md
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:approved

#16841 For #16838: deleted SmokeTest.mainMenuOpenInAppTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:intermittent-test, eng:ui-test

#16679 For #16629 - Fix for collection snackbar View button
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: needs:review

#16605 For #8791: Replace fenix tab counter with AC version
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserInteractor.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/FenixTabCounterMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounterToolbarButton.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  app/src/main/res/layout/tab_preview.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/TabCounterMenuTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:do-not-land, pr:needs-ac-bump, pr:work-in-progress

#16814 Create new android-test-beta build
  taskcluster/ci/build/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:approved

#16646 For #15362: Remove swipe to delete for bookmarks
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkTouchHelper.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkTouchHelperTest.kt
Labels: pr:needs-landing

#16851 For #16133: Simplify OpenInAppOnboardingObserver condition
  app/src/main/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserver.kt
  app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
Labels: Feature:OpenInApp, needs:review

#16834 For #16248 - Cleanup error pages of inlined code
  app/src/main/assets/highRiskErrorPages.js
  app/src/main/assets/high_risk_error_pages.html
  app/src/main/assets/lowMediumErrorPages.js
  app/src/main/assets/low_and_medium_risk_error_pages.html
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-ac-bump

#16842 For #16615: Smoke UI test swipeToSwitchTabTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:ui-test

#16864 Update to Android-Components 67.0.8.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16893 Update to Android-Components 67.0.9.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16909 Closes #16896: Integrate new MediaSession API to nightly or debug builds
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/intent/OpenSpecificTabIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/media/MediaSessionService.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/intent/OpenSpecificTabIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayViewHolderTest.kt
Labels: needs:review

#16923 Update to Android-Components 67.0.10.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#16811 For #16775: Fallback to light mode drawable when ui mode is not resolved
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: needs:review

#16950 Call nimbus.updateExperiments on startup
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
Labels: pr:needs-landing

#16954 For #16442 - Check if fragment is still attached before updating site…
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:approved

#16962 Fix #16960 & #16959: updateSavedLoginTest, swipeToSwitchTabTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:intermittent-test, eng:ui-test

#16967 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved

#16926 Add withExperiment extension method to Nimbus
  app/src/main/java/org/mozilla/fenix/ext/Nimbus.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:approved

#16977 Update to Android-Components 67.0.11.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-landing

#16853 For #15636 - Focus a11y collection on snackbar view tap
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: needs:review

#16953 For #16807 - Make sure there's only one instance of search dialog
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
Labels: pr:needs-landing

#15540 For #15403 - Adds a secret debug info screen in settings
  app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/secret_info_settings_preferences.xml
Labels: pr:approved, pr:needs-landing

#16697 For #16675 For #16398 - Fix button styling
  app/src/main/res/layout/download_dialog_layout.xml
  app/src/main/res/layout/fragment_add_new_device.xml
  app/src/main/res/layout/fragment_pwa_onboarding.xml
  app/src/main/res/layout/search_suggestions_hint.xml
  app/src/main/res/values/styles.xml
Labels: pr:approved, pr:needs-landing

#16983 For #16937 - Ensure FIP is removed on navigation
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#16947 For issue #16847 Show the autoplay icon in the toolbar
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
Labels: pr:needs-landing

#14353 For #4333: Open the keyboard when a search engine is selected
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: pr:approved, pr:needs-landing, ux:approved

#16905 No issue: add script to set up start up profiling
  tools/setup-startup-profiling.py
  tools/startup-profiling-configs/org.mozilla.fenix-geckoview-config.yaml
  tools/startup-profiling-configs/org.mozilla.fenix.debug-geckoview-config.yaml
  tools/startup-profiling-configs/org.mozilla.firefox-geckoview-config.yaml
  tools/startup-profiling-configs/org.mozilla.firefox_beta-geckoview-config.yaml
  tools/startup-profiling-configs/template
Labels: needs:review

#16730 For #11578 - Add telemetry for how many times we download something
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt
  docs/metrics.md
Labels: needs:data-review, needs:review

#16728 For #15367 - DownloadsFragment telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialog.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
  docs/metrics.md
Labels: needs:data-review, needs:review

#17027 For #16422: Handle theme for tab history bottom sheet.
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryDialogFragment.kt
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#16833 For #15368 - Adds telemetry for fullscreen, pip
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  docs/metrics.md
Labels: needs:data-review, needs:review

#16942 For #16941 - [Telemetry] Bookmark Counts
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  docs/metrics.md
Labels: needs:data-review, pr:approved

#16985 For #16973 - Use controller handled action instead of toolbar focus
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: needs:review

#17053 Closes #17045: Crash caused by calling consumeFlow on wrong thread
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/test/java/org/mozilla/fenix/onboarding/FenixOnboardingTest.kt
Labels: pr:approved

#17052 For #16615: UI smoke test redirectToAppPermissionsSystemSettingsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt
Labels: eng:ui-test

#16854 For #16068: Update SUMO links.
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/test/java/org/mozilla/fenix/settings/SupportUtilsTest.kt
Labels: needs:review

#16815 For #16483: Rotate edit arrow when toolbar position is set to bottom.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: needs:review

#16837 Bug 1676499 - Update perfherder data schema for visual metrics.
  taskcluster/docker/visual-metrics/performance-artifact-schema.json
Labels: pr:approved

#17038 For #13321 - Do not hide toolbar when opening multiple bookmarks
  app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt
Labels: pr:approved

#16918 Update release checklist to now include steps regarding shipit
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: pr:approved

#17159 Code cleanup in BookmarksRobot and BookmarksTest
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#17179 For #17165 - Use application context to get notification localized st…
  app/src/main/java/org/mozilla/fenix/customtabs/PoweredByNotification.kt
  app/src/main/java/org/mozilla/fenix/session/PrivateNotificationService.kt
Labels: needs:review

#17137 For #15703 and #17133: allow ETP redirect trackers setting to be customized
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt
  app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionStore.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/fragment_tracking_protection_blocking.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/tracking_protection_preferences.xml
  app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
Labels: pr:needs-landing

#17131 For issue #13981 Use DEEP_LINK_SCHEME instead of hard-coded fenix
  app/src/main/java/org/mozilla/fenix/components/Components.kt
Labels: pr:needs-landing

#17207 For #17073: Stop observers after test run
  app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
  app/src/test/java/org/mozilla/fenix/shortcut/PwaOnboardingObserverTest.kt
Labels: pr:needs-landing
