Repository mozilla-mobile/fenix, pull requests merged in 2021-12, with the labels that each got.

#22543 Add distribution_id into first session ping
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/FirstSessionPing.kt
Labels: pr:needs-landing

#22646 No issue: fix URL in ui-test kind.yml
  taskcluster/ci/ui-test/kind.yml
Labels: pr:needs-landing

#22647 Add webrender flag for the extra option.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#22652 Close #20701: Dismiss keyboard when scrolling home screen
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#22648 Android Autofill: Enable keyboard inline autofill suggestions
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/autofill_configuration.xml
Labels: pr:needs-landing

#22665 Disable failing verifyUndoSnackBarTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: pr:needs-landing, eng:ui-test

#22668 Refactor: Move historymetadata classes in separate package
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataServiceTest.kt
Labels: pr:needs-landing

#22650 For #22516 - Fixed alignment of "Show all" buttons on the homescreen
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/layout/recent_tabs_header.xml
  app/src/main/res/layout/recent_visits_header.xml
Labels: Feature:HomeScreen, pr:approved, pr:needs-landing-squashed

#22660 [UI smoke test] For #21002: Add testETPOffGlobally UI smoke test
  app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22678 For #22676 - Replace top_site_title_text with fx_mobile_text_color_primary color token
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22657 No issue: re-enable contributor UI test job
  .github/workflows/build-contributor-pr.yml
Labels: pr:needs-landing

#22693 For #22691 - Created Composables for Primary and Secondary text UI
  app/src/main/java/org/mozilla/fenix/compose/Text.kt
Labels: pr:needs-landing

#22699 For #22698 - Remove unused mozac_browser_menu_item_switch.xml resource
  app/lint-baseline.xml
  app/src/main/res/layout/mozac_browser_menu_item_switch.xml
Labels: pr:needs-landing

#22720 For #22710 - Disable run-ui in build-contributor-pr workflow
  .github/workflows/build-contributor-pr.yml
Labels: pr:needs-landing-squashed

#22554 For #22495 - Disable inactive tabs survey
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#22709 For #22708 - Remove unused syncedTabsSeparator attribute
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#22697 For #22696 - Remove unused tab_header.xml resource
  app/lint-baseline.xml
  app/src/main/res/layout/tab_header.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#22713 For #22712 - Remove unused menuCategoryText attribute
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#22723 For #22701 - Replace whats_new_notification_color with fx_mobile_icon_color_notice color token
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#22726 For #22725 - Regenerate lint-baselint.xml
  app/lint-baseline.xml
Labels: pr:needs-landing, pr:approved

#22724 For #22702 - Replace home_show_all_button_text with fx_mobile_text_color_action color token
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/layout/recent_tabs_header.xml
  app/src/main/res/layout/recent_visits_header.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#22587 [UI Smoke Tests] New undoDeleteBookmarkFolderTest UI test and Improve coverage for deleteNonEmptyBookmarkFolderTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test, pr:needs-landing-squashed

#22730 For #22729 - Tag unused strings for removal
  app/lint-baseline.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22605 For #22445 - Improve the scrolling behavior for Recently visited
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
Labels: pr:needs-landing

#22740 Update version.txt to 97.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#22742 For #22741 - Remove all unused strings marked moz:removedIn <= 94
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuHistoryItemRobot.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21805 Closes #21759: Do not render home fragment when launching to tab
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/StartupFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-landing

#22751 Support tab movement/reordering
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BlankDragShadowBuilder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/DraggableItemAnimator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabDragData.kt
Labels: pr:needs-landing-squashed

#22758 Issue #22757: Check the parent cast to AbstractBrowserTrayList first
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: pr:needs-landing

#22465 RELENG-489 - Beetmover
  taskcluster/ci/beetmover/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/loader/__init__.py
  taskcluster/fenix_taskgraph/manifests/fenix_candidates.yml
  taskcluster/fenix_taskgraph/transforms/beetmover.py
  taskcluster/fenix_taskgraph/transforms/multi_dep.py
  taskcluster/fenix_taskgraph/util/__init__.py
  taskcluster/fenix_taskgraph/util/scriptworker.py
  taskcluster/fenix_taskgraph/worker_types.py
Labels: pr:needs-landing

#22700 For #22694 - Remove primary_text_dark_theme usage
  app/src/main/res/layout/button_tip_item.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/layout/tracking_protection_learn_more_preference.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22735 For #9294: Add option to clear current site data in quick settings dialog
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ClearSiteDataView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentState.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/layout/quicksettings_clear_site_data.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/ClearSiteDataViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractorTest.kt
Labels: pr:needs-landing

#22645 Update recyclerview dependency
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#22748 For #17130: Replace hardcoded strings with string resources.
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
Labels: pr:needs-landing

#22788 For #22784: Prevent crashing when snackbar is triggered after the fragment has been detached.
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: pr:needs-landing

#22780 For #22779 - Remove @color/inset_light_theme redirection
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22774 Fix beetmover destination targets
  taskcluster/fenix_taskgraph/manifests/fenix_candidates.yml
  taskcluster/fenix_taskgraph/transforms/beetmover.py
  taskcluster/fenix_taskgraph/util/scriptworker.py
Labels: pr:needs-landing

#22778 For #22777 - Replace about_link_normal_theme with fx_mobile_text_color_action
  app/src/main/res/layout/fragment_add_on_details.xml
  app/src/main/res/layout/fragment_add_on_permissions.xml
  app/src/main/res/layout/settings_studies.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22673 Closes #22688: Remove inactive_tabs_recently_closed probe
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
Labels: pr:needs-landing

#22801 For #22800 - Remove unused tabs tray attributes
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22810 For #22809 - Use the design tokens for the Scrim Start/End colors
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22811 For #22808 - Add private theme design tokens
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22796 Change beetmover destination paths to match firefox
  taskcluster/fenix_taskgraph/manifests/fenix_candidates.yml
  taskcluster/fenix_taskgraph/util/scriptworker.py
Labels: pr:needs-landing

#22853 For #22851 add wallpapers feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#22833 For #22832 - Added parameters to base Text composables
  app/src/main/java/org/mozilla/fenix/compose/Text.kt
Labels: pr:needs-landing

#22854 For #22842 - Use gradient color tokens for Reader mode gradient
  app/src/main/res/drawable/ic_readermode_selected.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22829 fixes #20833: move home recycler bottom margin into standalone item
  app/src/main/java/org/mozilla/fenix/home/BottomSpacerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#22859 For #22858 - Set all @color/tab_tray_item_media_stroke usages to @color/photonWhite
  app/src/main/res/drawable/media_state_background.xml
  app/src/main/res/drawable/media_state_pause.xml
  app/src/main/res/drawable/media_state_play.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22843 Modify strings for Privacy notice for MozillaOnline builds
  app/src/main/java/org/mozilla/fenix/home/mozonline/PrivacyContentDisplayHelper.kt
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values/mozonline_strings.xml
Labels: pr:needs-landing

#22878 For #22450: Replace quit icon with AC one.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/drawable/ic_exit.xml
Labels: pr:needs-landing

#22887 Closes #22671: Show correct time groups header in history
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryAdapterTest.kt
Labels: pr:needs-landing

#22882 For #22508 - Increase menu height to avoid it become scrollable
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
Labels: pr:needs-landing

#22890 fixes #22889: add bottom spacer to onboarding adapter
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/home/BottomSpacerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/bottom_spacer.xml
Labels: pr:needs-landing

#22893 Add default topsite MeiTuan for MozillaOnline builds
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/drawable/ic_meituan.png
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values/mozonline_strings.xml
Labels: pr:needs-landing, pr:approved

#22860 For #22851 toggle wallpapers when tap on the Firefox log
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/drawable/wallpaper_1.png
  app/src/main/res/drawable/wallpaper_2.png
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#22922 Closes #22736: Do not remove focus from toolbar when scrolling
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing

#22923 update which bot is used
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: pr:needs-landing-squashed

#22787 For #20513: Use UrlMetricType for search engine submission url.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:needs-landing

#22935 For #22931 Only enable wallpapers on normal mode
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: needs:review

#22855 For #22852 - Add a new "Cross-site cookies" permission
  app/src/main/java/org/mozilla/fenix/settings/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionsView.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable/ic_cookies.xml
  app/src/main/res/drawable/ic_cookies_disabled.xml
  app/src/main/res/drawable/ic_cookies_enabled.xml
  app/src/main/res/layout/quicksettings_permissions.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/site_permissions_details_exceptions_preferences.xml
  app/src/main/res/xml/site_permissions_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/AutoplayValueTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentReducerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#22912 For #18160: Show a prompt when trying to leave private browsing with …
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/DownloadState.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: pr:approved

#22917 No bug - Update l10nScreenshotsTests doc
  docs/l10nScreenshotsTests.md
Labels: pr:needs-landing, pr:approved

#22955 Revert "For #22777 - Replace about_link_normal_theme with fx_mobile_text_color_action"
  app/src/main/res/layout/fragment_add_on_details.xml
  app/src/main/res/layout/fragment_add_on_permissions.xml
  app/src/main/res/layout/settings_studies.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: needs:review

#22938 For #22415: Remove element type from content descriptions.
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/layout/recent_tabs_header.xml
  app/src/main/res/layout/recent_visits_header.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#22957 Issue #22561: Fix tab group titles colour when in private mode
  app/src/main/res/layout/tab_group_item.xml
  app/src/main/res/layout/tab_tray_title_header_item.xml
Labels: pr:needs-landing

#22937 For #22851: Optimize wallpaper testing images.
  app/src/main/res/drawable/wallpaper_1.png
  app/src/main/res/drawable/wallpaper_2.png
Labels: pr:needs-landing

#22967 Closes #22754: Customize home button should work on fresh install
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
Labels: pr:needs-landing

#22968 For #22965 - Update design color tokens based on the latest UX changes
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#22961 Closes #20377: Pass distribution_id to Socorro crash report
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
Labels: pr:needs-landing, pr:approved

#22972 For #22971 - Remove @color/above_dark_theme redirection
  app/src/main/res/layout/migration_list_item.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#22984 For #22983 - Remove @color/destructive_button_text_color redirection
  app/src/main/res/layout/fragment_credit_card_editor.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22974 For #22973 - Remove @color/contrast_text_light_theme redirection
  app/src/main/res/layout/onboarding_inactive_tabs_cfr.xml
  app/src/main/res/layout/onboarding_jump_back_in_cfr.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#22985 Closes #10737: wrong search view width on language and saved logins s…
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
Labels: pr:needs-landing, pr:approved
