Repository mozilla-mobile/fenix, pull requests merged in 2021-02, with the labels that each got.

#17127 For #16390 - Include selected session in session suggestions if opened from home fragment
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: needs:UX-review, pr:needs-landing

#17684 Re-enable Nimbus with Off the main thread I/O and non-blocking networking
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: eng:perf-impact, pr:needs-ac-bump

#17638 For #16615: UI Smoke Tests for Tab Crash Reporter
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:ui-test

#17729 For #17641 Fix Intermittent test addPredefinedSearchEngineTest
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: eng:ui-test

#17694 For #12894 Fix Intermittent test goForwardTest
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
Labels: eng:ui-test

#17731 For #16959: verify page url not content in swipeToSwitchTabTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#17728 Issue #1340: Forward Activity results to the fragment
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#17763 Remove SessionManager dependency from CustomTabsIntegration.
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: needs:review

#17750 Add mozcn safebrowsing for release variant
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:approved

#17573 For #17364: Make search suggestion hint scrollable and avoid overlapping other elements.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/res/layout/fragment_search_dialog.xml
  app/src/main/res/layout/search_suggestions_hint.xml
Labels: needs:UX-review, pr:approved

#17465 Update bug numbers to URLs for activation ping
  app/pings.yaml
Labels: pr:approved

#17789 Remove TabsUseCases methods that take a Session object.
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved

#17813 For #17655: Do not pass threshold if showTopFrecentSites is false. (#17657)
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: pr:approved, pr:needs-landing

#17811 For #17304 - Implement top site search engine attribution (#17580)
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:approved, pr:needs-landing

#17787 For #12895 Fix Intermittent test navigateBookmarksFoldersTest
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test

#17793 For #16615: UI smoke test customTrackingProtectionSettingsTest
  app/src/androidTest/assets/pages/trackingPage.html
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
Labels: eng:ui-test

#17829 For #16020 Fix Intermittent tests caused by the Menu Button
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:ui-test

#17849 For #17847: disables editCustomSearchEngineTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#17862 For #17418 - Add event ping telemetry for the Google Top Site click
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  docs/metrics.md
Labels: needs:review

#17842 For #17785 - Use screenshots setting when adding secure flag
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/PrivateBrowsingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
Labels: needs:review

#17839 Closes #13089 - Adds correct animations for account settings
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-landing

#17863 Closes #17174: Remove the New Media Session API Feature Flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/intent/OpenSpecificTabIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/intent/OpenSpecificTabIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayViewHolderTest.kt
Labels: pr:approved

#17873 Closes #17871 - use viewLifecycleOwner for TopSitesFeature owner on H…
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: needs:review

#17874 For #17817 Change the feature prompt references to activity
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: needs:review

#17909 For #17847: Removes editCustomSearchEngineTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: eng:ui-test

#17902 For #14523 Fix Intermittent tests verifyContextOpenLinkNewTab & verifyContextOpenLinkPrivateTab
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: eng:ui-test

#17866 Uplift: For #17418 - Add event ping telemetry for the Google Top Site click (#17862) (Release)
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  docs/metrics.md
Labels: pr:do-not-land

#17867 Uplift: For #17418 - Add event ping telemetry for the Google Top Site click (#17862) (Beta)
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  docs/metrics.md
Labels: pr:do-not-land

#17916 For #17915 - Do not launch system settings on Role Request Intent cancel
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: needs:review

#17913 For #17195 Fix Intermittent UI test verifyTabTrayNotShowingStateHalfExpanded
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: eng:ui-test

#17914 For #17906 - Allow screenshots for private home screenshot test
  app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
Labels: needs:review

#17951 Issue #17174: Remove usage of old media APIs.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationStore.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/media/MediaService.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
Labels: needs:review

#17955 Fix OpenSpecificTabIntentProcessorTest to remove AbstractMediaService
  app/src/test/java/org/mozilla/fenix/home/intent/OpenSpecificTabIntentProcessorTest.kt
Labels: pr:needs-landing

#17954 ToolbarIntegration: Use global public suffix list instance.
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: needs:review

#17948 Add UI tests nightly build
  automation/taskcluster/androidTest/flank-x86-start-test.yml
  taskcluster/ci/build/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/ci/ui-test/kind.yml
Labels: pr:do-not-land

#17637 For #17418 - Added telemetry for Google Default Top Site
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/TrackKeyInfo.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetryTest.kt
  docs/metrics.md
Labels: Feature:Telemetry, needs:review

#17838 For #17771: three-dot menu reorder
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: needs:review

#17726 For #17686 - Use a custom behavior to scroll InfoBanner with the top toolbar
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserver.kt
  app/src/main/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBanner.kt
  app/src/main/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBannerBehavior.kt
  app/src/main/java/org/mozilla/fenix/browser/infobanner/InfoBanner.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
  app/src/test/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBannerBehaviorTest.kt
  app/src/test/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBannerTest.kt
Labels: needs:review

#17980 For #17771: Remove temporary UI test ignores
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: needs:review

#17930 For #17352 - Fixes deleted downloads reappearing
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
Labels: pr:approved, pr:needs-landing

#18010 For #17484, #18003 UI tests: retry closing tab if it fails
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: eng:intermittent-test, eng:ui-test

#17949 Issue #17819: Get leanplum artifacts from leanplum repository.
  build.gradle
  taskcluster/scripts/toolchain/android-gradle-dependencies.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/after.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/nexus.xml
Labels: needs:review

#17489 Don't run tasks for mergify branches on push
  .taskcluster.yml
Labels: pr:approved, pr:waiting-for-authors

#18029 For #16317: resets long press delay at the end of UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
Labels: eng:ui-test

#17087 Reset nimbus telemetry identifiers on data prefs change.
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
Labels: pr:work-in-progress

#18047 For #16317 UI tests: save long tap preference to restore it
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
Labels: eng:ui-test

#18048 Closes #18006: DefaultSessionControlControllerTest: Correctly unmock SearchStateKt class.
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: needs:review

#17843 Workflow to build contributor PRs
  .github/workflows/build-contributor-pr.yml
Labels: pr:do-not-land

#18060 Update Kotlin to 1.4.30 and Coroutines to 1.4.2.
  app/src/test/java/org/mozilla/fenix/downloads/DynamicDownloadDialogBehaviorTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: needs:review

#17864 Issue #12731: Collect telemetry about the content process of tabs getting killed.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt
  docs/metrics.md
Labels: needs:data-review, needs:review

#17830 Close #13892: Remove Synced Tabs appended to tabs tray
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsFragment.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsLayout.kt
  app/src/main/java/org/mozilla/fenix/tabtray/SyncedTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/SyncedTabsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabtray/TabTrayFragmentInteractorTest.kt
Labels: needs:review, pr:do-not-land

#18070 Closes #17522: Add MOZILLA_ONLINE_ADDON_EXCLUSIONS for Mozilla Online builds
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: pr:needs-landing

#18110 Add l10n.toml to list of auto-merge files.
  .mergify.yml
Labels: pr:needs-landing

#17857 For #16044: Suggest search engines based on typed text.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/res/drawable/ic_search_with.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: needs:review

#17809 Target Android 11
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/session/PerformanceActivityLifecycleCallbacks.kt
  app/src/main/java/org/mozilla/fenix/session/VisibilityLifecycleCallback.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareViewModel.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
  app/src/main/java/org/mozilla/fenix/wifi/WifiConnectionMonitor.kt
  app/src/test/java/org/mozilla/fenix/ext/ActivityTest.kt
  buildSrc/src/main/java/Config.kt
Labels: needs:review

#18180 Replace TopSitesUseCases.renameTopSites with TopSitesUseCases.updateTopSites
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing

#18161 Close #17928: Add feature flag for tabs tray refactor
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: needs:review

#18133 Added kmr and tl locales for v87
  l10n-release.toml
Labels: pr:needs-landing
