Repository mozilla-mobile/fenix, pull requests merged in 2021-10, with the labels that each got.

#21609 For #21608: Update strings for home screen dialog features
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/res/layout/fragment_onboarding_home_dialog.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21298 For #21287: Long press menu on homescreen
  app/src/main/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataController.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/interactor/HistoryMetadataInteractor.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/interactor/HistoryMetadataInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
Labels: pr:needs-landing

#21603 For #21551 - Add delete history metadata in the History view
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragment.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/interactor/HistoryMetadataGroupInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
Labels: pr:needs-landing

#21616 No issue: Make sure jump back in group always have more than one tab
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
Labels: needs:review

#21612 For #21611: Add jump back in contextual hint text
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21607 Update language in adjust docs
  docs/adjust.md
Labels: pr:needs-landing

#21614 Close #21610: Update Strings for Tab Settings
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tabs_preferences.xml
Labels: pr:needs-landing

#21598 For #21441, #21477, #21500, #21499 #21476, #21474: retry dismissing the search bar
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21633 Allow opening pocket stories when search dialog is active
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesController.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/DefaultPocketStoriesControllerTest.kt
Labels: pr:needs-landing

#21588 For #21392 - Update new strings descriptions
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21638 For #16437: Remove unnecessary space for tracking protection exceptions
  app/src/main/res/layout/fragment_site_permissions_exceptions.xml
Labels: pr:needs-landing

#21634 For #21632 - Preland strings for the inactive tab survey
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21636 For #21635 - Preland strings for tab auto close message
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing-squashed

#21645 For #21643: Pre-land strings for inactive tabs CFR and section title for non-search group tabs
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TitleHeaderAdapter.kt
  app/src/main/res/layout/tab_tray_title_header_item.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21647 For #21646: Update section titles and customize button name on home
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
  app/src/main/res/layout/customize_home_list_item.xml
  app/src/main/res/layout/history_metadata_header.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/customization_preferences.xml
Labels: pr:needs-landing

#21655 For #21653: pre-land section title for tab preferences
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21650 Issue #21641: Do not add a group of only one tab
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
Labels: pr:needs-landing

#21652 For #21648: match Pocket sections on home to designs
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/compose/SectionHeader.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21656 Make search term grouping tolerant to (parent tab) navigation
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#21669 Issue #21632: Correct inactive tabs survey string
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing-squashed

#21667 For #21611: Add jump back in Contextual Hints
  app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  app/src/main/res/drawable/onboarding_popup_shape.xml
  app/src/main/res/layout/onboarding_jump_back_in_cfr.xml
Labels: pr:needs-landing, needs:review

#21411 For #21618: Integrate Nimbus with MR2 Home Page to enable experimentation
  app/src/debug/res/raw/initial_experiments.json
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/settings/FeatureFlagPreference.kt
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusFeatures.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:needs-landing

#21627 For #21626 - Avoid showing story invalid properties
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing

#21663 Issue #21576: Hide 'Other' title when there are no search groups
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSelectors.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBindingTest.kt
Labels: pr:needs-landing

#21679 For #21644 fix disabled alwaysStartOnHomeTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21672 Issue #21671: Remove Recently Closed from Inactive Tabs
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/res/layout/inactive_recently_closed_item.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21660 For #21658 - Don't pass Client into composable functions
  app/src/main/java/org/mozilla/fenix/compose/Image.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
Labels: pr:needs-landing

#21696 CI for Docs: Add extra context to events.browser_menu_action
  app/metrics.yaml
Labels: pr:needs-landing-squashed

#21698 Move tabs out of search group if direct load occurs
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#21670 Issue #21642: Remove in-progress media tab from homescreen
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
Labels: pr:approved

#21701 For #21694 - Fix the layout in the Recent Searches
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt
Labels: pr:needs-landing, pr:approved

#21661 Issue #21582: Use ThumbnailStorage in recent tabs on home
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing

#21601 For #21599 - Add UTM parameters for Pocket recommendations links
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#21685 For #20814 fix flaky tabMediaControlButtonTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21709 For #21708 - Fixes missing header bottom border
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
Labels: pr:needs-landing

#21581 Close #21573: Constraint image size when using an icon in jump back in or recently bookmarked sections
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/res/drawable-night/ic_all_tabs.xml
  app/src/main/res/drawable/ic_all_tabs.xml
  app/src/main/res/drawable/ic_search_group_thumbnail.xml
  app/src/main/res/drawable/recent_bookmark_background.xml
  app/src/main/res/layout/recent_bookmark_item.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#21724 Update version.txt to 95.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#21359 SearchDialogFragment: Start to split consumeFrom() into independent observers that trigger less often
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
Labels: pr:needs-landing

#21740 No issue: Small layout update for Pocket Stories
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing

#21748 No issue: Update Pocket categories spacing to 16dp.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing
