Repository mozilla-mobile/fenix, pull requests merged in 2021-01, with the labels that each got.

#17134 Closes #9778: Site permission settings item height set to 48dp
  app/src/main/res/values/dimens.xml
Labels: pr:approved, pr:needs-landing, ux:approved

#16968 For #11580 - Tracks text selection context menu usage
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  docs/metrics.md
Labels: pr:approved, pr:do-not-land

#17185 For #15061: Fix error text color in SyncedTabsFragment.
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsFragment.kt
Labels: needs:review

#17293 For #17292 - Remove unused static_strings
  app/src/main/res/values/static_strings.xml
Labels: pr:approved, pr:needs-landing

#16778 16373 Count the # of inflations done on startup
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/perf/PerformanceInflater.kt
  app/src/test/java/org/mozilla/fenix/perf/PerformanceInflaterTest.kt
Labels: pr:needs-changes

#17169 Closes #14009: Fix onboarding 'Sign in to Firefox' ripple effect
  app/src/main/res/drawable/onboarding_padded_background.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#17300 No issue: Update Flank to v21.01.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#17302 Closes #17298: Turn on new MediaSession feature for all builds
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:approved

#17178 For #17177 - Do not show PBM CFR if entering search on home, make sur…
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: needs:review

#17287 For #16966: Remove unnecessary step from SmokeTest.mainMenuAddToHomeScreenTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#17120 Switch to new SessionStorage / session restore API.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt
  buildSrc/src/main/java/AndroidComponents.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: needs:review

#17164 Closes #17118: Fix font spacing when long pressing a URL
  app/src/main/res/layout/browser_toolbar_popup_window.xml
Labels: pr:approved

#17290 For #16790 - Allow top sites to have an empty name when renamed
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
Labels: pr:approved, pr:needs-landing

#17316 For #16759: Prevent crash on showing info banner.
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:needs-landing

#17186 For #15464: Always dismiss search dialog on url committed.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
Labels: pr:approved, pr:needs-landing

#17318 Closes issue #16944 Refactor TrackingProtectionPanelDialogFragment to observe session via store.
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionStore.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionStoreTest.kt
Labels: needs:review

#16741 Fixes #16271 - Fixes ripple being cut-off in Saved logins sort toolbar
  app/src/main/res/layout/saved_logins_sort_items_toolbar_child.xml
Labels: pr:approved, pr:needs-landing

#17350 For #16615: UI Smoke Tests for Recently Closed Tabs
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: eng:ui-test

#17392 For #13522: Also remove history entries from tab history.
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
Labels: needs:review

#17403 For #12732: Match notification accent color with app theme
  app/src/main/java/org/mozilla/fenix/downloads/DownloadService.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: needs:review

#17413 For #16615: UI smoke test editCustomSearchEngineTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: eng:ui-test

#17372 SDK-158 Use disabled/no-op version of Nimbus object to eliminate unnecessary Rust call
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
Labels: pr:approved, pr:needs-ac-bump

#16786 Changes to run tests on beta builds
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
  automation/taskcluster/androidTest/flank-x86-beta.yml
  automation/taskcluster/androidTest/ui-test.sh
  taskcluster/ci/ui-test/kind.yml
Labels: pr:waiting-for-authors

#17126 Update Mergify to also expect ui-test-x86-beta to succeed
  .mergify.yml
Labels: pr:do-not-land

#17335 For #16238 - Back button now dismisses Suggested Logins
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-ac-bump

#17470 For issue #17457: Prevent page refresh when tapping the security icon
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionsView.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionViewTest.kt
Labels: pr:needs-landing

#17483 Migrate some "selected tab" reads from SessionManager to BrowserStore.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/shortcut/CreateShortcutFragment.kt
Labels: needs:review

#17436 For issue: #16846 Add ui for controlling exceptions for auto play
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/res/layout/fragment_manage_site_permissions_exceptions_feature_phone.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/site_permissions_details_exceptions_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragmentTest.kt
Labels: needs:review

#17450 For #17447: add intentional delay in cold start up in debug and nightly.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:do-not-land

#17482 For #16615: Collections UI smoke tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt.ignore
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#17411 For #16615: UI Smoke Tests for Bookmarks
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: eng:ui-test

#17508 SearchDialogController: Pass tab ID instead of Session instance.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogInteractorTest.kt
Labels: needs:review

#17395 Fix breaking API in TabCounterToolbarButton
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-ac-bump

#17510 For #16615: UI Smoke Tests for Tabs Tray
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#17468 Add experimental WebAuthn support for Nightly only
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/WebAuthnFeature.kt
Labels: pr:needs-landing

#17410 For #14011: Remove new line character and spaces from string.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/res/layout/onboarding_privacy_notice.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#16971 For #15181: Remove All Downloads From Settings
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuit.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataOnQuitType.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_delete_browsing_data.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/delete_browsing_data_quit_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
Labels: pr:approved

#17435 For #17377 - Fix for empty awesomeBar on searchFragment open
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: needs:review

#17486 For #17044: Explicitly set a new default engine when default is deleted.
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  app/src/test/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreferenceTest.kt
Labels: pr:needs-landing

#17527 For #16615: UI Smoke Tests for No history in PB and Add to home screen
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:ui-test

#17544 For #17481 - Remove unused long_press_tapped metric
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  docs/metrics.md
Labels: pr:needs-landing

#17546 For #17309, #13447, #14534 UI tests: changed the way page Url is verified
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:ui-test

#17567 Use a smaller request code for WebAuthnFeature
  app/src/main/java/org/mozilla/fenix/browser/WebAuthnFeature.kt
Labels: pr:needs-landing

#17577 For issue: #16394 Fix UI for consider increasing some elements from ETP-Exceptions page
  app/src/main/res/layout/component_exceptions.xml
  app/src/main/res/layout/exception_item.xml
  app/src/main/res/values/dimens.xml
Labels: needs:review

#17561 For #17542 - Removes flash on renaming top site and fixes title not b…
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSitePagerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapterTest.kt
Labels: pr:needs-landing

#17565 For #16615: UI smoke test mainMenuInstallPWATest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#17622 For #16615 & #11191: re-enabled ReaderViewTest and added a UI smoke test
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ReaderViewRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#17564 Refactor ExternalAppBrowserActivity and ExternalAppBrowserFragment to not use Session(Manager).
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: needs:review

#17442 For #16485: Tabs tray grid view telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/test/java/org/mozilla/fenix/tabtray/DefaultTabTrayControllerTest.kt
  docs/metrics.md
Labels: pr:approved

#17628 For #17084: Use in-app browser switching dialog
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: pr:needs-landing

#17583 Bug 1688111 - Sync visual-metrics script with mozilla-central.
  taskcluster/docker/visual-metrics/run-visual-metrics.py
Labels: pr:approved

#17653 Bump version to 86.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#17652 [RELENG-169] support staging release promotion projects
  .taskcluster.yml
  taskcluster/ci/config.yml
  taskcluster/fenix_taskgraph/release_promotion.py
Labels: pr:needs-landing

#17557 Closes #17530: Update has open tabs metrics when tabs are opened or closed
  app/src/main/java/org/mozilla/fenix/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt
Labels: needs:review

#17661 For #9188: wait for page load in Reader mode
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#17664 Closes #17531: Use top sites count fact for top sites telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: needs:review

#17657 For #17655: Do not pass threshold if showTopFrecentSites is false.
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: needs:review

#17679 For #9188: wait for page content to appear in Reader mode tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#17678 Close #15979: Add MOZILLA_OFFICIAL flag for release builds
  app/build.gradle
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: needs:review

#17049 For #16828 - Adds telemetry for open in app banner
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserver.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
  docs/metrics.md
Labels: needs:data-review

#17682 For #17092: Dismiss toolbar menu when configuration change occurs
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: needs:review
