Repository mozilla-mobile/fenix, pull requests merged in 2021-06, with the labels that each got.

#19774 Fixes #19773 - Add a needs:review label to the automatic String Sync PRs
  .github/workflows/sync-strings.yml
Labels: needs:review

#19750 For #19746 - Remove feature flag for the three-dot menu redesign
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/toolbar/DefaultToolbarMenuTest.kt
Labels: pr:approved

#18803 For #15083 - Add multi select in recently closed tabs
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentView.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedItemViewHolder.kt
  app/src/main/res/layout/component_recently_closed.xml
  app/src/test/java/org/mozilla/fenix/library/recentlyclosed/DefaultRecentlyClosedControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentInteractorTest.kt
Labels: pr:needs-landing

#19767 For #18877 - Support updated PromptRequest AC APIs
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-ac-bump

#18880 For #18768: Increased text contrast ratio of TextViews in 'Share tab'
  app/src/main/res/layout/app_share_list_item.xml
  app/src/main/res/layout/share_tab_item.xml
  app/src/main/res/values/styles.xml
Labels: needs:review

#19377 For #19307: Increased contrast ratio of chevron symbol in Collections (For Dark theme)
  app/src/main/res/layout/collection_home_list_row.xml
Labels: needs:UX-review, pr:approved

#19818 For #18647: Fixed and re-enabled customTrackingProtectionSettingsTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: eng:ui-test

#19872 Changes to #17416, #19686, #19770 UI smoke tests to remove flakiness
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Labels: eng:ui-test

#19776 cancel sync-strings on non-beta versions
  .github/workflows/sync-strings.yml
Labels: pr:needs-landing

#19836 For #19495 - Add validation for the name on card
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
Labels: needs:review

#19870 For #19820: Add labels for month and year spinners.
  app/src/main/res/layout/fragment_credit_card_editor.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#19791 For #19789 Start on Home after some amount of time
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tabs_preferences.xml
  app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: needs:review

#19824 For #19738 - Secure mode enabled in private tabs tray
  app/src/main/java/org/mozilla/fenix/tabstray/SecureTabsTrayBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/SecureTabsTrayBindingTest.kt
Labels: needs:review

#19736 Issue #19178: Apply new styling to Synced Tabs list
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsTitleDecoration.kt
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsTrayLayout.kt
  app/src/main/res/layout/component_sync_tabs_tray_layout.xml
  app/src/main/res/layout/sync_tabs_error_row.xml
  app/src/main/res/layout/sync_tabs_list_item.xml
  app/src/main/res/layout/view_synced_tabs_group.xml
  app/src/main/res/layout/view_synced_tabs_no_item.xml
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsTitleDecorationTest.kt
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsViewHolderTest.kt
Labels: needs:UX-review, needs:review

#19127 Closes #10300: Fix Baidu search telemetry
  app/src/main/assets/extensions/ads/manifest.template.json
  app/src/main/assets/extensions/cookies/manifest.template.json
  app/src/main/java/org/mozilla/fenix/search/telemetry/BaseSearchTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetryTest.kt
Labels: pr:approved, pr:needs-landing

#19903 Address typos on start on home strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#19891 For #19815 - Keeps tabTray FAB from obstructing last tab
  app/src/main/res/layout/component_sync_tabs_tray_layout.xml
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/layout/normal_browser_tray_list.xml
  app/src/main/res/layout/private_browser_tray_list.xml
  app/src/main/res/values/dimens.xml
Labels: pr:approved, pr:do-not-land

#19908 For #18986: re-enable changeAccessibiltySettings UI test, not failing…
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: eng:ui-test

#19898 RELENG-586: Add mozillaonline builds & signing
  taskcluster/ci/build/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/transforms/build.py
  taskcluster/fenix_taskgraph/transforms/signing.py
Labels: pr:needs-landing

#19944 For #19916 - Add last viewed tab to home screen
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/interactor/RecentTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/drawable/home_list_row_background.xml
  app/src/main/res/layout/collection_header.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/layout/recent_tabs_header.xml
  app/src/main/res/layout/recent_tabs_list_row.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolderTest.kt
Labels: needs:review

#19965 For #19585: disables failing restoreTabCrashedReporterTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:intermittent-test, eng:ui-test

#19953 For FNX-22339: UI components for recently added bookmarks
  app/src/main/res/color/primary_state_button_text_color.xml
  app/src/main/res/color/primary_state_title_text_color.xml
  app/src/main/res/color/recent_bookmark_item_text_color.xml
  app/src/main/res/layout/component_recent_bookmarks.xml
  app/src/main/res/layout/recent_bookmark_item.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: needs:review

#19936 For #19915: Add telemetry for the toolbar Home screen button.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: needs:data-review

#19911 Suppress deprecation warnings for now-deprecated Glean APIs
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
Labels: needs:review

#19968 For #19938: Remove a11y workaround for tab tray new tab button.
  app/src/main/java/org/mozilla/fenix/tabstray/AccessibleNewTabButtonBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/FloatingActionButtonBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/res/layout/component_tabstray2.xml
  app/src/test/java/org/mozilla/fenix/tabstray/AccessibleNewTabButtonBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/FloatingActionButtonBindingTest.kt
Labels: pr:approved

#20025 Text selection tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: eng:ui-test

#19924 For #19923: renew telemetry probes
  app/metrics.yaml
Labels: pr:needs-landing

#20008 For #20007: Prevent multiselect title being selected by a11y services when not in select mode
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/res/layout/component_tabstray2.xml
Labels: needs:review

#20055 Revert "For #19739 - Moves argument to initial state init"
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
Labels: pr:needs-landing

#20062 Issue #20053: Disabling collection smoke tests temporarily
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: needs:review

#20061 Close #19950: Fix intermittent failure in SearchDialogControllerTest
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: needs:review

#19885 For #19881 add telemetry for start on Home.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing

#20070 For FNX-22819: Update glean notification emails to new email group
  app/metrics.yaml
  app/pings.yaml
Labels: needs:review

#18586 Fixes #18581 Fixed ETP Standard option is truncated
  app/src/main/res/layout/preference_widget_radiobutton_with_info.xml
Labels: needs:review

#20080 For #19910: Define the width/height for sync sign in button on tabs tray
  app/src/main/res/layout/sync_tabs_error_row.xml
Labels: pr:approved

#20082 For #20081: Define the width/height for homescreen empty collections button
  app/src/main/res/layout/no_collections_message.xml
Labels: pr:approved

#20087 For #16330 - Replaces Sentry.capture with submitCaughtException
  app/src/main/java/org/mozilla/fenix/components/tips/providers/MasterPasswordTipProvider.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: pr:needs-landing

#20064 For #19739 - Adds start tabsTray with multiSelect support
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionHandleBinding.kt
Labels: pr:needs-landing

#20074 For FNX-22820: uplift expired telemetry and update glean notification email address
  app/metrics.yaml
  app/pings.yaml
Labels: pr:approved

#20058 Issue #20054: Update recent tab on title or icon changes
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt
Labels: pr:needs-landing

#20073 For #19922 Update the default autoplay setting to be block audio only
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/site_permissions_details_exceptions_preferences.xml
  app/src/main/res/xml/site_permissions_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/PhoneFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#20107 For #19886 - Add right arrowheader to tracking protection navigators
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/values/styles.xml
Labels: needs:review

#20015 Closes #19182: Close Tabs Tray when sharing completes
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: pr:needs-landing

#19491 For #19221, Use ISO-8601 format build date in About Firefox
  buildSrc/src/main/java/Config.kt
Labels: pr:needs-landing

#20049 Add error reporting via sentry to Nimbus caught exceptions
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: pr:needs-landing-squashed

#20126 For #20046 - Show the last accessed tab in Jump back in
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
Labels: pr:needs-landing

#20129 For #19922 Fix the default autoplay setting to be block audio only
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/site_permissions_details_exceptions_preferences.xml
  app/src/main/res/xml/site_permissions_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/PhoneFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: needs:review

#20134 use prod signers for {beta,release}-mozillaonline
  taskcluster/fenix_taskgraph/transforms/signing.py
Labels: pr:needs-landing-squashed

#20142 use prod signers for {beta,release}-mozillaonline (#20134)
  taskcluster/fenix_taskgraph/transforms/signing.py
Labels: pr:needs-landing-squashed

#20110 For #19951 - Use Proton icon for new home button
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: needs:review, pr:needs-ac-bump, pr:needs-landing

#20143 [SDK-279] Adds a way to switch to the "preview" collection in Nimbus
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing

#20169 For #20123: Disable historyMetadataFeature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing
