Repository mozilla-mobile/fenix, pull requests merged in 2021-03, with the labels that each got.

#18115 Fix metric types of engine telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt
  docs/metrics.md
Labels: needs:review

#18259 Update metrics.md
  docs/metrics.md
Labels: pr:needs-landing

#18212 String sync for Fenix v87
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-co/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-gn/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-rm/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-su/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tg/strings.xml
  app/src/main/res/values-tl/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: pr:approved

#18257 metrics.yaml: Update data review link of engine_tab.kill_foreground_age metric.
  app/metrics.yaml
Labels: needs:review

#18216 Closes #18150: select tabs button not displayed
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  app/src/main/java/org/mozilla/fenix/tabtray/SaveToCollectionsButtonAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
Labels: pr:needs-landing

#18256 For #18228: Populate menu options in onResume along with toolbar init.
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
Labels: needs:review

#18229 For #18195: Handle Package visibility changes in Android 11
  app/src/main/AndroidManifest.xml
Labels: needs:review

#18112 For #18040: no network access startup tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/idlingresource/NetworkConnectionIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
Labels: eng:ui-test

#18193 For #18009: Correctly report items in adapter for a11y services.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSiteViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/AccessibilityGridLayoutManager.kt
  app/src/main/res/layout/component_top_sites.xml
Labels: needs:review

#18154 For #18034 - Don't animate the toolbar while the tab is loading
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: pr:needs-ac-bump

#17875 For #17802: Match the design for three-dot menu navigation
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved, pr:needs-landing

#18234 For #17963 - Present Fenix as a browser app to the system
  app/src/main/AndroidManifest.xml
Labels: pr:do-not-land, pr:needs-ac-bump

#18331 For #18325: dismiss GooglePlay ToS dialog after UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
Labels: eng:ui-test

#18326 For #18312: Do not update secure flag on pausing logins fragments.
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
Labels: needs:review

#18172 Closes #18163: Use SyncedTabsFacts for Synced Tab Telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  docs/metrics.md
Labels: needs:review

#18090 Closes #18068: Use AwesomeBarFacts for AwesomeBar Telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  docs/metrics.md
Labels: needs:review

#18174 Closes #18173: Add Telemetry When User Opens a Bookmark
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  docs/metrics.md
Labels: needs:review

#18383 For #18241 - Refactor SyncLoginsPreferenceView to SyncPreferenceView for reusability
  app/src/main/java/org/mozilla/fenix/settings/SyncPreferenceView.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsSyncPreferenceViewTest.kt
Labels: pr:approved

#18372 For #17872, #18032: Remove disabled color for three dot menu icons and add report site issue
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing

#18462 For #18461: add open in app to the main three dot menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing

#18311 For #12528: Provide fallback values for locale display name.
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleViewHoldersTest.kt
Labels: pr:approved

#18457 Integrate Android Autofill support into Nightly and debug builds.
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/autofill/AutofillConfirmActivity.kt
  app/src/main/java/org/mozilla/fenix/autofill/AutofillService.kt
  app/src/main/java/org/mozilla/fenix/autofill/AutofillUnlockActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/nightly/AndroidManifest.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:approved

#18456 Closes #18367 run SupportedAddonsChecker only for users with unsupported extensions
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:approved

#18483 For #14005: fix strict TP tests loading timeout
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#18159 For #18036 - Add TrackKeyInfo to Ad Click Metrics
  app/src/main/assets/extensions/ads/ads.js
  app/src/main/assets/extensions/ads/adsBackground.js
  app/src/main/assets/extensions/ads/manifest.template.json
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/SearchProviderModel.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/TrackKeyInfo.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/ads/AdsTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/TrackKeyInfo.kt
  app/src/test/java/org/mozilla/fenix/search/SearchProviderModelTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/ads/AdsTelemetryTest.kt
Labels: needs:review

#18143 For #18076: Renew telemetry expiring in April.
  app/metrics.yaml
  docs/metrics.md
Labels: needs:data-review, pr:approved

#18071 For #17768: Renew telemetry probes expiring in March.
  app/metrics.yaml
  docs/metrics.md
Labels: needs:data-review, pr:approved

#18486 Add first set of UI tests to Nightly
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  automation/taskcluster/androidTest/flank-x86-start-test.yml
Labels: eng:automation, eng:ui-test

#18498 For #18481: waits for url to be visible in TestHelper.verifyUrl()
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
Labels: eng:ui-test

#18409 For #18408 - Add a lazy getter for AutofillCreditCardsAddressStorage
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: needs:review

#18506 Set version to 87.0.0-rc.1
  version.txt
Labels: pr:needs-landing

#18440 Issue #17822: Create a tabs tray layout and fragment
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayItem.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayViewHolders.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BaseBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/PrivateBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  app/src/main/java/org/mozilla/fenix/tabtray/FenixTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt
  app/src/main/java/org/mozilla/fenix/utils/view/LifecycleViewProvider.kt
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/layout/normal_browser_tray_list.xml
  app/src/main/res/layout/private_browser_tray_list.xml
  app/src/main/res/layout/synced_tabs_tray_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutObserverTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/TabSessionStateKtTest.kt
Labels: pr:approved

#18519 UPLIFT: buildSrc: Use Maven Central instead of JCenter and use artifact cache.
  buildSrc/build.gradle
Labels: pr:needs-landing

#18518 Issue #17819: buildSrc: Use Maven Central instead of JCenter and use artifact cache.
  buildSrc/build.gradle
Labels: pr:needs-landing

#18252 For #17805 - Fix adjustResize deprecation
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AuthCustomTabActivity.kt
  app/src/main/res/values/styles.xml
Labels: needs:review

#18536 Enable new tabs tray only for debug builds
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: needs:review

#18529 For #17644: Always update add-on's telemetry values before sending metric ping
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:approved

#18526 Enable the Nimbus experiments library on all channels
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: needs:review, pr:needs-landing

#18543 No issue: Update Android Components version to 74.0.20210318143143
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review

#18537 Closes #12565: Clean up use of Context within ReviewPromptController.
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/ReviewPromptController.kt
  app/src/test/java/org/mozilla/fenix/components/ReviewPromptControllerTest.kt
Labels: needs:review

#18129 Closes #17956: Add top site telemetry to available search engines
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: needs:review

#18557 Closes #17531: Use shared preference to store top sites count for telemetry
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: needs:review

#18558 For #18426: add probes for long-running areas of start up
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  docs/metrics.md
Labels: pr:approved

#18459 For #17799: Add extensions submenu item.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved

#18410 For #18240 - Add a Credit Card preference screen
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/res/layout/preference_credit_cards_add_credit_card.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/credit_cards_preferences.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/preferences_without_icons.xml
Labels: needs:review

#18179 For #17190: notifications are updated when locale is changed
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/session/PrivateNotificationService.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/DefaultLocaleSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleSettingsControllerTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review, pr:needs-ac-bump

#18605 For #18242 - Wire up "Sync cards across devices" preference with SyncPreferenceView
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-landing

#18541 Issue #18538: Add BrowserTabsAdapter for tabs tray
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayViewHolders.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BaseBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/UseCases.kt
Labels: pr:needs-landing

#18614 set tasks_for to action to use release signing in relpro
  taskcluster/fenix_taskgraph/release_promotion.py
Labels: pr:needs-landing

#18624 Closes #18623: Fix Gradle task name in gradlewbuild.py
  app/src/androidTest/java/org/mozilla/fenix/syncintegration/gradlewbuild.py
Labels: eng:automation

#18550 For #18494: Optimize the order and messages of onboarding cards
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/util/Strings.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingController.kt
  app/src/main/java/org/mozilla/fenix/onboarding/OnboardingInteractor.kt
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous_large.xml
  app/src/main/res/layout/onboarding_manual_signin.xml
  app/src/main/res/layout/onboarding_theme_picker.xml
  app/src/main/res/layout/onboarding_toolbar_position_picker.xml
  app/src/main/res/layout/onboarding_tracking_protection.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tracking_protection_preferences.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
Labels: pr:approved

#18618 For #18260: Add pin to default sites.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt
Labels: needs:review

#18615 Update top sites to add PDD for MozillaOnline builds
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/drawable/ic_pdd.png
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/mozonline_strings.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#18639 For #15372 Improve onboarding strings
  app/src/main/res/values/strings.xml
Labels: pr:approved, pr:needs-landing

#18442 Resolves #18381: Explicitly set android:extractNativeLibs to true in ApplicationManifest.xml
  app/src/main/AndroidManifest.xml
Labels: pr:approved

#18689 For #16830: Increase the Show in private sessions option in Search Preferences Settings
  app/src/main/res/layout/checkbox_left_sub_preference.xml
Labels: pr:approved

#18669 Close #18668: Add stable ID cache for TabAdapter.getItemId
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabAdapterIdStorage.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsAdapter.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabAdapterIdStorageTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabsAdapterTest.kt
Labels: needs:review

#18676 Issue #18521: Focus on page corresponding to selected tab
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: needs:review

#18700 For #18421: Ignore the ContextMenusTest class because of test failures
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: eng:ui-test

#18703 For #18644: fix method to verify system notifications
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: eng:ui-test

#18653 For #17800: Request desktop site from home screen.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:approved

#18387 Closes #18386: Change language display name to traditional/simplified Chinese
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
Labels: pr:approved, pr:needs-landing

#18555 For #17797: Add bookmarks menu item.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/res/drawable/ic_bookmarks_menu.xml
  app/src/main/res/values/strings.xml
Labels: pr:approved, pr:needs-changes

#18722 Disable failing UI Tests
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test

#18699 For #18667 - Migrated exitImmersiveModeIfNeeded to Fenix
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
Labels: needs:review, needs:uplift

#18714 No issue: enable CPU usage in profiler.
  tools/setup-startup-profiling.py
Labels: pr:needs-landing

#18730 For #18729 - Use consistent string naming for generic strings
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing
