Repository mozilla-mobile/fenix, pull requests merged in 2021-08, with the labels that each got.

#20597 Issue #20533: Fix intermittent test failures of DefaultCollectionCreationControllerTest
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
Labels: pr:needs-landing

#20370 Issue #20349 - Categorize unused tabs into an inactive group in the tabs tray
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/PrivateBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenu.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/ConcatAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/AbstractPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/PrivateBrowserPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/inactive_footer_item.xml
  app/src/main/res/layout/inactive_header_item.xml
  app/src/main/res/layout/inactive_tab_list_item.xml
  app/src/main/res/layout/normal_browser_tray_list.xml
  app/src/main/res/layout/private_browser_tray_list.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTrayListTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultBrowserTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/ContextKtTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/TabSessionStateKtTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#17603 For #16396: Fix text contrast ratio on "recently closed tabs"
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
Labels: pr:approved, pr:needs-landing

#20621 No issue: fix glean metrics tests for expired metrics
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInfoBannerBinding.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StorageStatsMetricsTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayInfoBannerBindingTest.kt
Labels: pr:needs-landing-squashed

#20628 Closes #20627: Fix intermittent test failures in HistoryItemMenuTest
  app/src/test/java/org/mozilla/fenix/library/history/HistoryItemMenuTest.kt
Labels: pr:needs-landing

#20624 Fix intermittent test failures in DefaultSessionControlControllerTest.
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: needs:review, pr:needs-landing

#20619 Fix intermittent test failures in DefaultBrowserToolbarControllerTest
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: needs:review, pr:needs-landing

#20622 Fix intermittent test failures in TabsTouchHelperTest
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabsTouchHelperTest.kt
Labels: pr:needs-landing

#20632 Closes #20631: remove @Ignore on StorageStats tests.
  app/src/test/java/org/mozilla/fenix/perf/StorageStatsMetricsTest.kt
Labels: pr:needs-landing

#20397 Add dialog-like theme for AutofillSearchActivity
  app/src/debug/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/autofill/AutofillSearchActivity.kt
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#20595 Closes #20461: remove app_received_intent probe.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
Labels: pr:needs-landing

#20656 Closes #20650: Revert to manually close tab as default setting
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#20658 Fix intermittent test failures in ToolbarViewTest
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing

#20317 For #19970 [Crash] IllegalStateException when navigating to TP panel
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: pr:needs-landing

#20669 For #20601: Use View binding in quick settings.
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionsView.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: needs:review

#20671 Enable Android Autofill in Beta builds.
  app/build.gradle
  app/src/beta/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#20688 For #20310 - Adds Recently Closed button to tabsTray
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/res/layout/inactive_recently_closed_item.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#20711 For #17917 - Add a Kotlin synthetics Lint detector
  app/lint-baseline.xml
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/KotlinSyntheticsDetector.kt
  mozilla-lint-rules/src/main/java/org/mozilla/fenix/lintrules/LintIssueRegistry.kt
  mozilla-lint-rules/src/test/java/org/mozilla/fenix/lintrules/KotlinSyntheticsDetectorTest.kt
Labels: pr:needs-landing

#20687 Issue #20663: Make inactive card collapsible
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecorator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/res/drawable/card_list_row_background.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/layout/inactive_header_item.xml
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecoratorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
Labels: pr:needs-landing

#20713 For #17917: Use View binding in bookmarks screen
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
Labels: pr:needs-landing

#20722 Update Android Components version to 92.0.20210806164329
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProvider.kt
  app/src/test/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProviderTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#19959 Issue #19956: Add telemetry for tab view setting changes
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
Labels: pr:needs-landing

#20681 Closes #20679: revert allowaccessmodification proguard disabling.
  app/build.gradle
  app/proguard-android-optimize-3.5.0-modified.txt
Labels: pr:needs-landing

#20699 Closes #20697: fix intermittent by replace mockked lambda in DownloadControllerTest.
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadControllerTest.kt
Labels: pr:needs-landing

#20724 Closes #20723: Fix credit card management fragment binding
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsManagementView.kt
  app/src/main/res/layout/fragment_saved_cards.xml
Labels: pr:needs-landing

#20725 No issue: correct search_count telemetry after revert
  app/metrics.yaml
Labels: pr:needs-landing

#20719 Issue #20718: Show url if title is missing for inactive tabs
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
Labels: pr:needs-landing

#20728 Close #20726: Fix intermittent failure in AddonsManagementViewTest
  app/src/test/java/org/mozilla/fenix/addons/AddonsManagementViewTest.kt
Labels: pr:needs-landing

#20709 Start on home UI smoke tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuThemeRobot.kt
Labels: pr:needs-landing, eng:ui-test

#20511 For #20425: Re-add tests for class BookmarksUseCaseTest.
  app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt
  app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt
Labels: pr:needs-landing

#20715 For #17917: Use View binding in downloads screen
  app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadView.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/viewholders/DownloadsListItemViewHolder.kt
Labels: pr:needs-landing

#20573 For FNXV2-17067: always show home in background behind search dialog
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/res/layout/collection_header.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
Labels: pr:needs-landing-squashed

#20729 Don't rebase GeckoView or Android-Components version bumps PRs before landing
  .mergify.yml
Labels: pr:needs-landing

#20759 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#20698 No issue: remove unnecessary robolectric annotations.
  app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBannerBehaviorTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTestRoboelectric.kt
  app/src/test/java/org/mozilla/fenix/components/settings/sitepermissions/ExtensionsTest.kt
  app/src/test/java/org/mozilla/fenix/ext/ListTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/biometric/ext/BiometricManagerKtTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/StringTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentReducerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsWifiIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: pr:needs-landing

#20727 CI for #20028
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolderTest.kt
Labels: pr:needs-landing

#20758 Add a default to task-priority to fix issues when forks are named differently
  taskcluster/ci/config.yml
Labels: pr:needs-landing

#20771 Backout mergify changes for bustage
  .mergify.yml
Labels: pr:needs-landing

#20774 Update Android Components version to 92.0.0.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:review

#20775 Set version to 93.0.0
  version.txt
Labels: pr:approved

#20757 For #17917: Use View binding in collections
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
Labels: pr:needs-landing, pr:approved

#20646 For #17917: Use View binding in history screens
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/layout/history_list_item.xml
Labels: pr:needs-landing

#20791 For #20672 crash when attempting to disconnect from Mozilla account
  app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt
Labels: pr:needs-landing

#20798 Disable intermittent tests.
  app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProviderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentReducerTest.kt
Labels: pr:needs-landing

#20765 For #20764 add screen for opting out of experiments
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/CustomViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesAdapterDelegate.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/main/res/layout/settings_studies.xml
  app/src/main/res/layout/studies_section_item.xml
  app/src/main/res/layout/study_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/data_choices_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/studies/DefaultStudiesInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/studies/StudiesAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/studies/StudiesViewTest.kt
Labels: pr:needs-landing

#20790 CI For #20596
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Glean.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt
Labels: pr:needs-landing

#20785 For #20098: Allow PB PiP video screenshots
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: pr:needs-landing

#20807 Update the description for an inactive tabs string
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#20633 No issue: match Collections to other homescreen items
  app/src/main/res/layout/collection_header.xml
Labels: pr:needs-landing-squashed

#20801 No issue: move kotlin-allopen outside appVariants loop.
  app/build.gradle
Labels: pr:needs-landing

#20820 Ship nightlies to Google Play twice a day
  .cron.yml
  taskcluster/fenix_taskgraph/target_tasks.py
Labels: pr:needs-landing

#20835 Use theming in debug screen.
  app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing

#20838 Remove duplicated line in TabsSettingsFragment
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
Labels: pr:needs-landing

#20836 Android Autofill: Use AppCompat theme for UnlockActivity.
  app/src/beta/AndroidManifest.xml
  app/src/debug/AndroidManifest.xml
  app/src/nightly/AndroidManifest.xml
Labels: pr:needs-landing

#20840 For #20764 separate learn more string
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#20732 Update TabSessionState.createdAt for inactive tabs debugging
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
Labels: pr:needs-landing

#20854 Close #20853: Fix intermittent failing test in HomeFragmentStoreTest
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
Labels: pr:needs-landing

#20870 Close #20796: Additional fixes for intermittent failing test
  app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsInteractorTest.kt
Labels: pr:needs-landing

#20874 For #19886 use block color on disabled permissions
  app/src/main/res/drawable/ic_autoplay_disabled.xml
  app/src/main/res/drawable/ic_camera_disabled.xml
  app/src/main/res/drawable/ic_link_disabled.xml
  app/src/main/res/drawable/ic_location_disabled.xml
  app/src/main/res/drawable/ic_microphone_disabled.xml
  app/src/main/res/drawable/ic_notifications_disabled.xml
  app/src/main/res/drawable/ic_storage_disabled.xml
  app/src/main/res/drawable/ic_tracking_protection_disabled.xml
  app/src/main/res/layout/quicksettings_permissions.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#20819 For #17917: Use View binding in Onboarding Tests
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyBrowsingViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingSectionHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolderTest.kt
Labels: pr:needs-landing

#20816 For #17917: Use View binding in Share views
  app/src/main/java/org/mozilla/fenix/share/ShareCloseView.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareToAccountDevicesView.kt
  app/src/main/java/org/mozilla/fenix/share/ShareToAppsView.kt
  app/src/test/java/org/mozilla/fenix/share/ShareCloseViewTest.kt
Labels: pr:needs-landing

#20844 For #20824: use fast service loader for MainDispatcherFactory.
  app/proguard-rules.pro
Labels: pr:needs-landing

#20886 For #17917: Use View binding in tracking protection(2)
  app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsView.kt
  app/src/main/java/org/mozilla/fenix/exceptions/login/LoginExceptionsView.kt
  app/src/main/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionCategoryItem.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionsViewTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsViewTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
Labels: pr:needs-landing

#20899 Issue #20864: Speculative fix for HomeFragmentTest failures
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: pr:needs-landing

#20912 Update Android Components version
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#20885 metrics.yaml: Add data review URL for Android Autofill metrics
  app/metrics.yaml
Labels: pr:needs-landing

#20922 For #20716 - Disables Intermittent failing UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing

#20931 Enable recording of history metadata for all builds
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#20705 Closes #19490 : Add event ping telemetry for the Baidu top site click
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
Labels: pr:needs-landing

#20813 For #17917: Use View binding in Login Exceptions
  app/src/main/java/org/mozilla/fenix/exceptions/login/LoginExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginDetailsBindingDelegate.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginDetailViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListViewHolderTest.kt
Labels: pr:needs-landing

#20883 For #17917 - Migrate `browser` from Kotlin synthetics to View Binding.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  app/src/main/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBanner.kt
  app/src/main/java/org/mozilla/fenix/browser/infobanner/InfoBanner.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
  app/src/test/java/org/mozilla/fenix/browser/infobanner/DynamicInfoBannerTest.kt
Labels: pr:needs-landing

#20882 For #17917 - Migrate `home` from Kotlin synthetics to View Binding.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/res/layout/component_recent_bookmarks.xml
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/tips/ButtonTipViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupReportFullyDrawnTest.kt
Labels: pr:needs-landing

#20904 For #17917: Use View binding in tabs tray
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabGridViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsTrayLayout.kt
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/layout/tab_tray_item.xml
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
Labels: pr:needs-landing

#20933 For #20919 quit the app after removing a study.
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesInteractor.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/studies/DefaultStudiesInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/studies/StudiesAdapterTest.kt
Labels: pr:needs-landing

#20806 Speculative fixes for intermittent test in DeleteAndQuitTest
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt
Labels: pr:needs-landing

#20947 For #20919 quite the app when turning on/off experiments
  app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
Labels: needs:review

#20946 Close #20945: Fix failing test in AccountSettingsInteractorTest
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsInteractorTest.kt
Labels: pr:needs-landing

#20911 CI for #20808
  app/metrics.yaml
  app/pings.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/perf/ApplicationInitTimeContainer.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupFrameworkStartMeasurement.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupTimeline.kt
  app/src/main/java/org/mozilla/fenix/perf/Stat.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupFrameworkStartMeasurementTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupHomeActivityLifecycleObserverTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StatTest.kt
Labels: pr:needs-landing

#20949 For #20919 quite the app when turning on/off experiments
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#20902 Closes #20881 : Use armeabi-v7a version code for MozillaOnline builds
  app/build.gradle
Labels: pr:needs-landing

#20930 For #20927: Replace icons with AC icons.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProvider.kt
  app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt
  app/src/main/res/drawable/ic_add_to_homescreen.xml
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/fragment_edit_login.xml
  app/src/main/res/layout/fragment_installed_add_on_details.xml
  app/src/main/res/layout/fragment_pwa_onboarding.xml
  app/src/test/java/org/mozilla/fenix/search/awesomebar/ShortcutsSuggestionProviderTest.kt
Labels: pr:needs-landing

#20951 For #20892 update connection icons in quick settings
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentState.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/res/drawable/ic_broken_lock.xml
  app/src/main/res/drawable/ic_lock.xml
Labels: pr:needs-landing

#20773 For #17917: Use View binding in add-ons
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsView.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonPermissionDetailsBindingDelegate.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonPermissionsDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/NotYetSupportedAddonFragment.kt
  app/src/main/res/layout/overlay_add_on_progress.xml
  app/src/test/java/org/mozilla/fenix/addons/AddonDetailsViewTest.kt
  app/src/test/java/org/mozilla/fenix/addons/AddonPermissionDetailsBindingDelegateTest.kt
Labels: pr:needs-landing

#20983 Closes 20975: Run metadata cleanup after Megazord.init()
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:needs-landing

#20532 For #20328 - Preland telemetry probes for data review
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
Labels: pr:needs-landing

#20508 For #20507 - Inactive tabs telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabGridViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabListViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/UseCases.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
Labels: pr:needs-landing

#20316 For #19931: Add telemetry probes for recent bookmarks on home screen
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
Labels: pr:needs-landing-squashed

#20980 For #20871 Mark strings for removal
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#20994 For #20919 add confirm dialog when turning on/off experiments
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#20982 No issue: Fix workflow if statement in build-contributor-pr.yml
  .github/workflows/build-contributor-pr.yml
Labels: pr:needs-landing

#20990 No issue: Update Flank to v21.08.1
  taskcluster/docker/ui-tests/Dockerfile
Labels: pr:needs-landing

#21069 Enable Android Autofill support in all build types.
  app/build.gradle
  app/src/beta/AndroidManifest.xml
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/nightly/AndroidManifest.xml
Labels: pr:needs-landing

#21062 For #20702: fix tests flakiness
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21046 For #21002 update and add missing tabs setting validations
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21073 Add tint to settings icon on Tracking protection panel
  app/src/main/res/layout/component_tracking_protection_panel.xml
Labels: pr:needs-landing

#21077 For #21037 - Add a delete history menu item
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/menu/history_menu.xml
Labels: pr:needs-landing, needs:review

#21079 For #21078 - Remove unused creditCardsFeature feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: pr:needs-landing, needs:review
