Repository mozilla-mobile/fenix, pull requests merged in 2021-11, with the labels that each got.

#22193 For #22192 add telemetry for studies
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/settings/studies/StudiesViewTest.kt
Labels: pr:needs-landing

#22241 For #21397: disabled homescreen features to improve collections visibility
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#22176 For #22175: Telemetry for deleting a search term group from recent searches on home
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataControllerTest.kt
Labels: pr:needs-landing, pr:approved

#22253 For #22175: Add data review link
  app/metrics.yaml
Labels: pr:needs-landing

#22104 Close #22103: Add recent bookmarks telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolderTest.kt
Labels: pr:needs-landing

#22173 Close #22172: Add Recent searches telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
Labels: pr:needs-landing

#22244 For #22226 - Open grouped history entries the same as individual ones
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: pr:needs-landing, pr:approved

#22224 For #22138 - Install source metrics probe
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:needs-landing

#22199 For #18421 re-enable verifyContextOpenImageNewTab, verifyContextOpenLinkNewTab & verifyContextOpenLinkPrivateTab UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22225 Improve coverage for cancelCreateBookmarkFolderTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22246 Introduce test rule to work around intermittent mockk failures
  app/src/test/java/org/mozilla/fenix/browser/FenixSnackbarDelegateTest.kt
  app/src/test/java/org/mozilla/fenix/browser/browsingmode/DefaultBrowsingModeManagerTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/viewholders/ExceptionsListItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/helpers/MockkRetryTestRule.kt
  app/src/test/java/org/mozilla/fenix/push/WebPushEngineIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/FenixSnackbarKtTest.kt
Labels: pr:needs-landing

#22058 Issue #22057: Add search term groups telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#22163 For #22155 - Inactive tabs count telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:needs-landing

#22252 No issue: Merge our inactive tab interactor/controllers
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAutoCloseDialogController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAutoCloseDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsAutoCloseDialogInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAutoCloseDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
Labels: pr:needs-landing, pr:approved

#22228 For #21973 - Reduce redirection of colors variables between dark and light theme - Part 4
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#22258 Update version.txt to 96.0.0-beta.1
  version.txt
Labels: pr:needs-landing, pr:approved

#22166 MR2 Telemetry: Recent tabs section probe
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
Labels: Feature:Telemetry, pr:needs-landing-squashed, Feature:RecentTabs

#22268 No issue: Show snackbar when opening non-http URL
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22267 For #22170 record auto-close prompt telemetry events
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: pr:needs-landing

#22255 Improve deleteBookmarkInEditModeTest UI test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22214 Closes #22213: add marker for LayoutInflater.inflate.
  app/src/main/java/org/mozilla/fenix/perf/PerformanceInflater.kt
Labels: pr:needs-landing

#22273 For #21973 - Reduce redirection of colors variables between dark and light theme - Part 6
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22295 For #22281 Fix studies opt out learn more link
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
Labels: pr:needs-landing

#22289 For #22078 Selecting search group in Jump back in switches active tab
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayStoreReducerTest.kt
Labels: pr:needs-landing

#22293 Recent bookmark count telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: Feature:Bookmarks, pr:needs-landing-squashed

#22296 Closes #21659: Add SERPs to history search groups
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#21789 For #21313: Remove expiring/unused metrics for December
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/crashes/CrashReporterController.kt
  app/src/test/java/org/mozilla/fenix/crashes/CrashReporterControllerTest.kt
Labels: pr:needs-landing-squashed

#21316 For #21313: Renew product telemetry expiring in December
  app/metrics.yaml
Labels: pr:needs-landing-squashed

#22216 No issue: change label in perf issue template to `performance`
  .github/ISSUE_TEMPLATE/---performance-issue.md
Labels: pr:needs-landing

#22317 For #22304 & #22256: Disabled failing visitedUrlHistoryTest & editCustomSearchEngineTest tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#22306 No issue: history view search group missing
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:needs-landing

#22300 Close #22299: Add history search term group telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing, pr:approved

#22285 ThreadPenaltyDeathWithIgnoresListener: Ignore violations without Mozilla code in the stack trace.
  app/src/main/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListener.kt
  app/src/test/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListenerTest.kt
  app/src/test/resources/InstrumentationHooksLogcat.txt
Labels: pr:needs-landing

#22325 Fix download dialog displaying long filenames
  app/src/androidTest/assets/pages/download.html
  app/src/androidTest/assets/resources/tAJwqaWjJsXS8AhzSninBMCfIZbHBGgcc001lx5DIdDwIcfEgQ6vE5Gb5VgAled17DFZ2A7ZDOHA0NpQPHXXFHPSD4wzCkRWiaOorNI574zLtv4Hjiz6O6T7onmUTGgUQ2YQoiQFyrCrPv8ZB9KvmtoRFRVIZh8Pg2a1THrm9gpMoLwP44nDNN5o70USUyVXFxPeTerG9OSdpZIwCWGIVM3AZmjFSaiAyZKxJp8G1oZ2md4DBQYy6F1.svg
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/main/res/layout/download_dialog_layout.xml
Labels: eng:qa:needed, pr:needs-landing

#22360 Improve verifyEmptyTabTray Ui test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21937 Make findDuplicate() suspend
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt
Labels: pr:needs-landing

#22339 For #22256 re-enable editCustomSearchEngineTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#22390 No issue: clean up code duplication in PagedHistoryProvider
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:needs-landing

#22386 Close #22223: Move to the selected page when switching modes
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: pr:needs-landing

#22301 MR2 telemetry - Inactive tabs CFR
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInactiveTabsOnboardingBinding.kt
Labels: Feature:Telemetry, pr:needs-landing-squashed, Feature:InactiveTabs

#22333 MR2 Telemetry: Opening screen preference
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: Feature:HomeScreen, Feature:Telemetry, pr:needs-landing-squashed

#22400 No issue: creates new SmokeTest annotation.
  app/src/androidTest/java/org/mozilla/fenix/customannotations/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#22399 For #22388 - Update content description of the delete button
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedItemViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22391 For #22271 Improve URL accessing from the clipboard for Android 12 and above.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
  app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
  app/src/main/res/values-v31/dimens.xml
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/utils/ClipboardHandlerTest.kt
Labels: pr:needs-landing

#22362 Improve homeThreeDotMenuItemsTest UI test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  automation/taskcluster/androidTest/flank-x86.yml
Labels: pr:needs-landing, eng:ui-test

#22368 For #22147 - New search term groups telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragment.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
Labels: pr:needs-landing

#22421 For #22155 - Store inactive tabs count telemetry when user opens tabs tray
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabSorterTest.kt
Labels: pr:needs-landing

#22377 MR2 Telemetry: Homescreen view count
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: Feature:HomeScreen, Feature:Telemetry, needs:review, pr:needs-landing-squashed

#22406 Close #22402: Add top placeholder for home
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeScreenViewModel.kt
  app/src/main/java/org/mozilla/fenix/home/TopPlaceholderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/top_placeholder_item.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#22476 Improve mainMenuAddToHomeScreenTest UI test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#22491 For #21002: add missing steps to selectSearchEnginesShortcutTest, addPredefinedSearchEngineTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22485 Closes #22484 - Track direct loads per tab; fix search term lookup
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#22506 For #22502 - Update "Jump back in" group's subtitle format
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22456 Update Jetpack Compose to 1.0.5 and Activity Compose to 1.4.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, pr:approved

#22530 For issue #5298 the same page appears in the History section multiple times
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:approved

#22538 For issue #22537 crash: BookmarkFragment is attached to a context
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
Labels: pr:needs-landing

#22574 [UI Smoke tests] For #21002: improves the share tabs smoke tests coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22512 Bug 1742138 - Remove non-webrender browsertime tests.
  taskcluster/ci/browsertime/kind.yml
  taskcluster/fenix_taskgraph/transforms/browsertime.py
Labels: pr:needs-landing

#22568 Closes #22499: Emit search group disband action on history group removal
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: pr:needs-landing

#22266 For #22250 - Convert Recent Bookmarks to Jetpack Compose
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksItemAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/component_recent_bookmarks.xml
  app/src/main/res/layout/recent_bookmark_item.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#22583 For #22488 - Fix intermittent test failure with InactiveTabsControllerTest
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
Labels: pr:needs-landing

#22466 Closes #22321: Upgrade protobuf version.
  app/build.gradle
Labels: pr:needs-landing

#22572 For #22502 - Keep the previous string resource until safe to remove
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22545 [UI Smoke Tests] Text search UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#22573 Issue #12731: Disable suspending of engine sessions under memory pressure in Nightly
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#22581 Issue #22580: Track APK size in perfherder
  app/build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/org/mozilla/fenix/gradle/tasks/ApkSizeTask.kt
  taskcluster/ci/build/kind.yml
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:needs-landing, pr:approved

#22294 For #22211 - Use Hero images for Recent Bookmarks
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/interactor/RecentBookmarksInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/components/TestComponents.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
  app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#22603 Closes #22552: Optimize PNGs with ImageOptim
  app/src/beta/res/drawable-hdpi/ic_logo_wordmark_normal.png
  app/src/beta/res/drawable-hdpi/ic_logo_wordmark_private.png
  app/src/beta/res/drawable-mdpi/ic_logo_wordmark_normal.png
  app/src/beta/res/drawable-mdpi/ic_logo_wordmark_private.png
  app/src/beta/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  app/src/beta/res/drawable-xhdpi/ic_logo_wordmark_private.png
  app/src/beta/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  app/src/beta/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  app/src/beta/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  app/src/beta/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  app/src/main/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  app/src/main/res/drawable-xhdpi/ic_logo_wordmark_private.png
  app/src/main/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  app/src/main/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  app/src/main/res/drawable/ic_baidu.png
  app/src/main/res/drawable/ic_jd.png
  app/src/main/res/drawable/ic_pdd.png
  app/src/main/res/drawable/ic_tc.png
  app/src/nightly/res/drawable-hdpi/ic_logo_wordmark_normal.png
  app/src/nightly/res/drawable-hdpi/ic_logo_wordmark_private.png
  app/src/nightly/res/drawable-mdpi/ic_logo_wordmark_normal.png
  app/src/nightly/res/drawable-mdpi/ic_logo_wordmark_private.png
  app/src/nightly/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  app/src/nightly/res/drawable-xhdpi/ic_logo_wordmark_private.png
  app/src/nightly/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  app/src/nightly/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  app/src/nightly/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  app/src/nightly/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  app/src/nightly/res/ic_launcher-web.png
  app/src/nightly/res/mipmap-hdpi/ic_launcher.png
  app/src/nightly/res/mipmap-hdpi/ic_launcher_round.png
  app/src/nightly/res/mipmap-mdpi/ic_launcher_round.png
  app/src/nightly/res/mipmap-xhdpi/ic_launcher.png
  app/src/nightly/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/nightly/res/mipmap-xxhdpi/ic_launcher.png
  app/src/nightly/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/nightly/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/nightly/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/release/res/drawable-hdpi/fenix_search_widget.png
  app/src/release/res/drawable-hdpi/ic_logo_wordmark_normal.png
  app/src/release/res/drawable-hdpi/ic_logo_wordmark_private.png
  app/src/release/res/drawable-mdpi/ic_logo_wordmark_normal.png
  app/src/release/res/drawable-mdpi/ic_logo_wordmark_private.png
  app/src/release/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  app/src/release/res/drawable-xhdpi/ic_logo_wordmark_private.png
  app/src/release/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  app/src/release/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  app/src/release/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  app/src/release/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  app/src/release/res/mipmap-hdpi/ic_launcher.png
  app/src/release/res/mipmap-hdpi/ic_launcher_round.png
  app/src/release/res/mipmap-mdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xhdpi/ic_launcher.png
  app/src/release/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xxhdpi/ic_launcher.png
  app/src/release/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/release/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: pr:needs-landing

#22557 For #22556 - Update to latest taskgraph revision + path changes
  .taskcluster.yml
  taskcluster/ci/build/kind.yml
  taskcluster/ci/lint/kind.yml
  taskcluster/ci/test/kind.yml
  taskcluster/scripts/toolchain/android-gradle-dependencies/before.sh
Labels: pr:needs-landing

#22596 For #22595 - Remove unused OnboardingAutomaticSignInViewHolder
  app/src/main/java/org/mozilla/fenix/home/Mode.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolder.kt
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous.xml
  app/src/main/res/drawable/onboarding_padded_background.xml
  app/src/main/res/layout/onboarding_automatic_signin.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolderTest.kt
Labels: pr:needs-landing

#22621 Closes #22198: Mergify: Replace deprecated "strict mode" merge action
  .mergify.yml
Labels: pr:needs-landing

#22479 Tab group count telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabSorterTest.kt
Labels: Feature:Telemetry, pr:approved, pr:needs-landing-squashed, Feature:SearchTermTabs

#22535 For #22534 - Show history highlights and groups in "Recently visited"
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataFeature.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataGroup.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataController.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/interactor/HistoryMetadataInteractor.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataService.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/RecentlyVisitedItem.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsController.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentVisitMenuItem.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentVisitsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/recent_visits_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/home_preferences.xml
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/HistoryMetadataServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/view/RecentBookmarksViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/view/RecentVisitsHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing-squashed

#22593 For #22592 - Refactor hideOnboardingIfNeeded() calls when the home menu items are tapped
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing
