Repository mozilla-mobile/fenix, pull requests merged in 2021-09, with the labels that each got.

#21086 For #19166: Increases tab_tray_list bottom padding
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#21124 For 20892 Update connection icons in address bar
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentState.kt
  app/src/main/res/drawable/mozac_ic_broken_lock.xml
Labels: pr:needs-landing

#21129 Closes #21128: remove measure_start_up.py.
  tools/measure_start_up.py
Labels: pr:needs-landing

#20909 Issue #18711: Telemetry for credit card autofill
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardsManagementInteractor.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementInteractorTest.kt
Labels: pr:needs-landing, pr:approved

#21173 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:do-not-land

#21142 For #21138: re-enable excessive resource use test.
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
Labels: pr:needs-landing

#21176 Set version to 94.0.0
  version.txt
Labels: pr:needs-landing

#21092 For #20881 print if the build is a MozillaOnline
  app/build.gradle
Labels: pr:needs-landing

#21185 Issue #21184: Update artifacts format
  taskcluster/ci/toolchain/gecko-derived.yml
Labels: pr:needs-landing

#21141 Issue mozilla-mobile#21140 - Updated recent tab logic to show media tab and second-to-last tab, if the media tab was the last active tab.
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
Labels: pr:needs-landing-squashed

#21196 For #20892 update connection panel strings
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentState.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: pr:needs-landing

#21082 For #21095 allow users to configure their home screen.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/customization_preferences.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#20682 Fix TaskCluster badge in README
  README.md
Labels: pr:needs-landing

#21203 For #6968: Use close instead of read to close the response stream.
  app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt
Labels: pr:needs-landing

#21218 Issue mozilla-mobile#20637 - Fixed bug causing the tabs tray to scroll to the wrong tab when opened
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
Labels: pr:needs-landing

#21215 Handle breaking changes from a-s 83.0.0
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/fenix/experiments/NimbusSetupKtTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#21230 For #21133 fix openMainMenuSyncItemTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21238 For #21211 hide the ETP in custom tabs.
  app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: pr:needs-landing

#21235 For #21226 only show the "Customize Home" menu on home screen.
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#20428 For #18629: ETP SmartBlock
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackerBuckets.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractor.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackerBucketsTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
Labels: pr:needs-landing

#21261 Improve coverage for addPrivateBrowsingShortcut UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21282 CI for #21237, attempt 2
  app/lint-baseline.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#21115 For #20654: allow switching between private mode behind search dialog
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
Labels: pr:needs-landing

#21263 Improve coverage for copyBookmarkURLTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21264 New deleteBookmarkInEditModeTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21167 For #21120 - ImageLoader with a solid color placeholder
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
Labels: pr:needs-landing

#21290 For #20936: run perftests with conditioned profiles.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#21271 No issue: add GVE to setup-startup-profiling.py
  tools/setup-startup-profiling.py
Labels: pr:needs-landing

#21321 Sort history metadata on home and allow limiting results
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataFeature.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataGroup.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataFeatureTest.kt
Labels: pr:needs-landing

#21135 Issue #21099 - Update items under "Jump back in" section to the latest designs
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecorator.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/layout/recent_tabs_list_row.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecoratorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#21328 Add default topsite 58 for MozillaOnline builds
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/drawable/ic_tc.png
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values/mozonline_strings.xml
Labels: pr:needs-landing

#21320 Closes #18102: remove intermittent failing App onCreate duration meas…
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: pr:needs-landing

#21341 Closes #21340: Disable auto Google login in Flank config
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:automation

#21323 Update strings comments
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21334 Issue #21291: SearchDialogFragment: Get URL from clipboard once and not for every state update
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: pr:needs-landing

#21361 Issue #21236: Fixes empty tray visibility logic
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/AbstractPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
Labels: pr:needs-landing

#21336 Closes #21335: return self instead of mock in FenixSnackbarKtTest.
  app/src/test/java/org/mozilla/fenix/tabstray/ext/FenixSnackbarKtTest.kt
Labels: pr:needs-landing

#21365 Update tabs tray title header string comment to clarify what it does.
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21297 For #21296: add ProfilerMarkers.addForDispatchTouchEvent.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/perf/ProfilerMarkers.kt
Labels: pr:needs-landing

#21260 Improve coverage for verifyAboutFirefoxPreview UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21369 Close #21366: Fix intermittent test failure in TitleHeaderBindingTest
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBindingTest.kt
Labels: pr:needs-landing

#21389 Closes #21388: Only parse clipboard content when search fragment is attached
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing

#21338 For #21337: rename recently saved section on home
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/customization_preferences.xml
  app/src/test/java/org/mozilla/fenix/browser/browsingmode/DefaultBrowsingModeManagerTest.kt
Labels: pr:needs-landing

#21370 Use UpdateUrlAction to record viewTime observations
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#21395 No issue: remove escape chars on add logins string
  app/src/main/res/layout/fragment_add_login.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21396 Fix QR scan button not showing up when choosing a RTL language
  app/src/main/res/layout/fragment_search_dialog.xml
Labels: needs:review

#21272 For #21126: process performancetest intent for AC too.
  app/src/main/java/org/mozilla/fenix/perf/Performance.kt
Labels: pr:needs-landing

#21401 Exit onboarding tour UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21415 For #21413 - Remove unused OnboardingPrivateBrowsingViewHolder and OnboardingWhatsNewViewHolder
  app/lint-baseline.xml
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
  app/src/main/res/drawable/ic_onboarding_private_browsing.xml
  app/src/main/res/drawable/ic_whats_new_notification.xml
  app/src/main/res/layout/onboarding_private_browsing.xml
  app/src/main/res/layout/onboarding_whats_new.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyBrowsingViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolderTest.kt
Labels: pr:needs-landing

#21444 No issue: re-enabled swipeToSwitchTabTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21440 For #21239 improve telemetry values for Allow users to customize their home screen
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
Labels: pr:needs-landing

#21447 Issue #21117 - Modify layout for items displayed under "Recently Visited" in the HomeScreen to follow latest UX designs
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataGroup.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataController.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/interactor/HistoryMetadataInteractor.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataViewHolder.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentVisitMenuItem.kt
  app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/layout/history_metadata_group.xml
  app/src/main/res/layout/history_metadata_header.xml
  app/src/main/res/layout/history_metadata_list_row.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/historymetadata/controller/HistoryMetadataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataGroupViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#21439 Fix for disabled saveLoginFromPromptTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#21431 Improve bookmarks UI tests coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21400 For #17847: adding back editCustomSearchEngineTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21461 For #21460 - Rename "Delete from history" to "Remove" for recent visit dropdown menu
  app/src/main/java/org/mozilla/fenix/historymetadata/view/HistoryMetadataGroupViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#21482 For #20893: Dedupe urls/site in history groups
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:needs-landing

#21465 Issue #21366: Speculative fix for failing test in TitleHeaderBindingTest
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBindingTest.kt
Labels: pr:needs-landing, needs:review

#21485 Closes #21441: Fix changeAccessibiltySettings
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing

#21487 Fix mapping between history visits and groups to use createdAt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:needs-landing

#21131 For #21087: Updates Recently Saved design
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolder.kt
  app/src/main/res/layout/recent_bookmark_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#21501 Fix disabled shortcutButtonTest UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/ext/WaitNotNull.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21434 For #20762 - Fixes NPE crash
  app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: pr:needs-landing

#21494 For #21493 show onboarding dialog for home sections
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_onboarding_home_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#21455 Close #21451: Add active search term tab groups on home
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/interactor/RecentTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroup.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupAdapter.kt
  app/src/main/res/drawable/ic_all_tabs.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#21517 Fix disabled toggleSearchSuggestions UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/ext/WaitNotNull.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21354 Delete browsing data tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21527 Do not capture search terms when user navigates away via app
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing-squashed

#21277 For #21275 - Sort items by how many times they were actually shown
  app/src/main/java/org/mozilla/fenix/ext/HomeFragmentState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/PocketUpdatesMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
  app/src/test/java/org/mozilla/fenix/ext/HomeFragmentStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/PocketUpdatesMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/DefaultPocketStoriesControllerTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#21342 For #21339: update styles for homescreen to match new specs
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/main/res/layout/collection_header.xml
  app/src/main/res/layout/component_top_sites.xml
  app/src/main/res/layout/component_top_sites_pager.xml
  app/src/main/res/layout/customize_home_list_item.xml
  app/src/main/res/layout/history_metadata_header.xml
  app/src/main/res/layout/no_collections_message.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/layout/recent_tabs_header.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#21557 Fix recent tabs intermittent tests
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing

#21553 Close #21552: Remove Extra Subtitle In Jump Back In Item
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing

#21566 For #21478 fix flaky verifyOpenTopSiteNormalTab UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21554 No issue: Improve rendering of jump back in
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing

#21563 For #21442 fix flaky deleteMultipleSelectionTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21392 For #21391 - Updated composables
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/compose/Image.kt
  app/src/main/java/org/mozilla/fenix/compose/ImagesPlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/SectionHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
  app/src/main/java/org/mozilla/fenix/compose/StaggeredHorizontalGrid.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitle.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/TabTitle.kt
  app/src/main/java/org/mozilla/fenix/ext/HomeFragmentState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesViewHolder.kt
  app/src/main/res/drawable/pocket_vector.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/ext/HomeFragmentStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/DefaultPocketStoriesControllerTest.kt
Labels: pr:needs-landing

#21564 For #21561 - Enable/Disable the feature from the customization menu
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#21575 For #21574: Move the homescreen onboarding card behind a feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#21584 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#20972 For #20762 - Adds grey border to inactive tabs
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/res/layout/inactive_footer_item.xml
  app/src/main/res/layout/inactive_header_item.xml
  app/src/main/res/layout/inactive_recently_closed_item.xml
  app/src/main/res/layout/inactive_tab_list_item.xml
Labels: pr:needs-landing

#21591 For #21540 fix flaky editCustomSearchEngineTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#21594 For #21592 - Don't topup with general stories
  app/src/main/java/org/mozilla/fenix/ext/HomeFragmentState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/pocket/PocketStoriesComposables.kt
  app/src/test/java/org/mozilla/fenix/ext/HomeFragmentStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
Labels: pr:needs-landing

#21524 Inactive tabs changes
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TitleHeaderAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSelectors.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/inactive_header_item.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tabs_preferences.xml
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TitleHeaderBindingTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing-squashed, Feature:InactiveTabs

#21569 Don't manually exclude glean-native
  app/build.gradle
Labels: pr:needs-landing
