Repository mozilla-mobile/fenix, pull requests merged in 2021-05, with the labels that each got.

#19325 Close #19259: Pass CoroutineContext to nav interactor constructor
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: pr:needs-landing

#19284 For #19132 - Fix navigation on disconnect started from tabsTray
  app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt
Labels: pr:needs-changes

#19392 For #19281: Add border radius for top sites favicons.
  app/src/main/res/drawable/top_sites_background.xml
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: needs:UX-review, needs:review

#19267 For #18266: Add credit card entry info validation
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/String.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/StringTest.kt
Labels: pr:approved

#19355 For issue #19290 update to proton icons second batch
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/res/drawable/ic_bookmark_filled.xml
  app/src/main/res/drawable/ic_chevron_down.xml
  app/src/main/res/drawable/ic_chevron_up.xml
  app/src/main/res/drawable/ic_confirm_email.xml
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous_large.xml
  app/src/main/res/drawable/ic_onboarding_privacy_notice.xml
  app/src/main/res/drawable/ic_sign_in.xml
  app/src/main/res/drawable/ic_signed_out.xml
  app/src/main/res/drawable/ic_sync_disconnected.xml
  app/src/main/res/drawable/ic_top_sites.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#19398 Closes #3728: Add secret menu switch for allowing third party root certificates
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: needs:strings, pr:approved

#19417 Fix flaky UI Tests #19306 #19160 #19404 #19373
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: eng:ui-test

#19046 For #18226: Fixed display of tabs for when text size is set to largest
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/layout/tab_tray_item.xml
Labels: pr:approved

#18839 For #8984: Added color for "Share" menu's "Recently Used" in Dark theme
  app/src/main/res/drawable/recent_apps_background.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:approved, pr:needs-landing

#19411 Stop generating `metrics.md` and direct to Glean Dictionary instead
  app/build.gradle
  docs/metrics.md
  docs/telemetry.md
Labels: pr:approved, pr:needs-landing

#19450 For #19357: Remove bookmarks experiment and keep star-with-line icon.
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:approved

#19406 For #19401: Replaced hard-coded Hex color codes from values\colors.xml and values-night\colors.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: needs:UX-review, pr:approved

#19397 Issue #19147: Move set startup metrics off main thread
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/components/BackgroundServicesTest.kt
Labels: needs:review

#19455 For #19258: Replace default Android back button with a custom icon.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/res/drawable/ic_back_button.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#19486 Issue #19176: Exit select mode when removing tab
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegration.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegrationTest.kt
Labels: needs:review

#19471 For #17537: Add preferences for syncing credit cards and addresses
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/account_settings_preferences.xml
Labels: needs:review

#19477 For #18287 - Display a credit card autofill prompt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-ac-bump

#19462 For #19418: Allow multiple lines title for sync cards preference.
  app/src/main/res/xml/credit_cards_preferences.xml
Labels: needs:UX-feedback, pr:approved, pr:do-not-land

#19451 For #19054: Navigate to the Credit card screen when deleting last card.
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
Labels: needs:review

#19586 AutofillConfiguration: Correctly specify autofill confirm activity.
  app/src/main/java/org/mozilla/fenix/components/Components.kt
Labels: needs:review

#19581 For #19570 - Sets theme appropriate color for delete card button
  app/src/main/res/values/colors.xml
Labels: pr:approved, pr:needs-landing

#19602 For #15754: Get playback state using MediaSession in MediaNotificatio…
  app/src/androidTest/assets/pages/audioMediaPage.html
  app/src/androidTest/assets/pages/videoMediaPage.html
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: eng:ui-test

#19624 For #18603: Fix and re-enable startBrowsingButtonTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:ui-test

#19598 For #17538: Perform autofill storage warm-up after visual completeness.
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:approved, pr:needs-ac-bump

#19623 For #19554: Add SyncEngine.CreditCards to sync supportedEngines.
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:approved

#19625 For #19415: fixed private browsing button visibility issue
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: eng:intermittent-test, eng:ui-test

#19420 For #18270 - Adds ellipses+last 4 digits to CC display
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardItemViewHolderTest.kt
Labels: pr:approved, pr:needs-ac-bump

#19643 For #18881 - Add a new button "Add credit card" in the "Saved cards" screen
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardsManagementController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardsManagementInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsManagementView.kt
  app/src/main/res/layout/component_credit_cards.xml
  app/src/main/res/layout/layout_add_credit_card.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementInteractorTest.kt
Labels: pr:approved

#19641 Issue #17819: Update detekt to 1.17.1
  app/src/main/java/org/mozilla/fenix/perf/StartupTimelineStateMachine.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/CustomRulesetConsoleReport.kt
  mozilla-detekt-rules/src/test/java/org/mozilla/fenix/detektrules/perf/MozillaBannedPropertyAccessTest.kt
Labels: pr:needs-landing

#19582 For #19569 - Increases CC expiry date spinners
  app/src/main/res/layout/fragment_credit_card_editor.xml
Labels: needs:UX-feedback, pr:needs-changes

#19666 Update 'Add credit card' text alignment for rtl support
  app/src/main/res/layout/layout_add_credit_card.xml
Labels: pr:approved, pr:needs-landing

#19649 For #18263 - Allow dynamically toggling credit cards autofill
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-ac-bump

#19670 Closes #17819: Remove JCenter from build files.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  taskcluster/fenix_taskgraph/job.py
  taskcluster/scripts/toolchain/android-gradle-dependencies.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/after.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/nexus.xml
Labels: needs:review

#19679 Issue #19647: Navigate to browser from home via Synced Tabs page
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: needs:review

#19671 No issue: Added custom tab UI smoke tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: eng:ui-test

#19505 For #18264: add biometric prompt to credit card settings
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/settings/biometric/BiometricPromptPreferenceFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: needs:review

#19692 For #19492 - Provide the correct CreditCardNumber type to UpdatableCreditCardFields when updating a credit card
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
Labels: pr:needs-landing

#19683 Close #19459: Use Store.waitUntilIdle in intermittent failing test
  app/src/test/java/org/mozilla/fenix/nimbus/NimbusBranchesControllerTest.kt
Labels: needs:review

#19548 For #18711: Telemetry for credit card autofill
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
Labels: needs:ac, pr:do-not-land, 🙅 waiting

#19708 For #19693 - Add new string for the prompt to authenticate to use a stored credit card
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#19589 For #19564: Explicitly update switch state for a11y event announcements.
  app/src/main/java/org/mozilla/fenix/settings/SyncPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SyncPreferenceView.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SyncPreferenceViewTest.kt
Labels: needs:review

#19732 Close #19731: Track metrics before we dismiss the tabs tray
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Labels: pr:needs-landing

#19733 For #18711 - Refactor credit card telemetry under the Metrics ping
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:approved, pr:needs-landing

#19735 For #19734 - Enable Credit cards autofill for Release
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/res/xml/preferences.xml
Labels: pr:approved, pr:needs-landing
