Repository mozilla-mobile/fenix, pull requests merged in 2021-07, with the labels that each got.

#20200 For #20000: Re-try swipe on collection items
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
Labels: eng:ui-test, pr:needs-landing

#20218 For #19558 - Adds proper tint to "Report Site Issue"
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing

#20224 For #20154: Override AC fill colors for icons.
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#20228 For #20219: Fix constraints in sign-in onboarding card.
  app/src/main/res/layout/onboarding_manual_signin.xml
Labels: pr:needs-landing

#20255 For #19886 - Add favicon to website info view
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/res/layout/quicksettings_website_info.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: needs:review

#20256 Move Nimbus strings to static_strings
  app/src/main/res/values/static_strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing

#20264 For #17917: Use View binding in onboarding cards.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingSectionHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingWhatsNewViewHolder.kt
Labels: pr:approved, pr:needs-landing

#20254 Don't send notification for android-test-mozillaonline tasks
  taskcluster/ci/signing/kind.yml
Labels: pr:needs-landing

#20272 Closes #19090: Show snackbar on adding to bookmarks from tabs tray
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/FenixSnackbar.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/FenixSnackbarKtTest.kt
Labels: pr:needs-landing

#20275 Closes #20274: Limit about:config to Nightly and Beta
  app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: pr:needs-landing

#20170 For #20029: Remove animations when recreating activity on locale change.
  app/src/main/java/org/mozilla/fenix/settings/advanced/DefaultLocaleSettingsController.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleSettingsControllerTest.kt
Labels: pr:needs-landing

#20171 No issue: New UI smoke test for the Language menu
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLanguageRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/util/Strings.kt
Labels: eng:ui-test, pr:needs-landing

#20277 Closes #20276: Fall-back to URL parsing for tabs with parents to obtain search terms
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/test/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddlewareTest.kt
Labels: pr:needs-landing

#18613 For #18527: Documentation update: experiments.md
  docs/experiments.md
Labels: pr:approved, pr:needs-landing

#20249 For #17855 - Stops SecureWindowFeature from removing FLAG_SECURE
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#20261 For #20250 - Adds FLAG_SECURE to TabsTray dialog
  app/src/main/java/org/mozilla/fenix/tabstray/SecureTabsTrayBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/SecureTabsTrayBindingTest.kt
Labels: pr:needs-landing

#20281 For #20257 - Sets min no. of grid columns to 2 in TabsTray
  app/src/main/java/org/mozilla/fenix/tabstray/ext/Context.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultBrowserTrayInteractorTest.kt
Labels: pr:needs-landing

#20147 Closes #19846: Show Default Browser Notification if browser is not default
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#20302 Closes #19846: Only add default browser notification work if work is not pending
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
Labels: pr:needs-landing

#20304 Closes #19846: Update default browser notification strings
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#19835 For FNX-22339: Recently saved bookmarks
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksItemAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/interactor/RecentBookmarksInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt
  app/src/main/res/color/primary_state_button_text_color.xml
  app/src/main/res/color/primary_state_title_text_color.xml
  app/src/main/res/color/recent_bookmark_item_text_color.xml
  app/src/main/res/layout/collection_home_list_row.xml
  app/src/main/res/layout/component_recent_bookmarks.xml
  app/src/main/res/layout/recent_bookmark_item.xml
  app/src/main/res/layout/recent_bookmarks_header.xml
  app/src/main/res/layout/recent_tabs_list_row.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarkItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolderTest.kt
Labels: needs:UX-review, needs:ac, needs:review, pr:needs-landing-squashed

#20303 Closes #20285: Remove unused GeckoProvider
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:needs-landing

#20308 Use bug report template with data validation
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---bug-report.yml
Labels: pr:needs-landing

#20116 For #19804: Changed `var isDefaultBrowser` to a function
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/ReviewPromptController.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing

#20344 Close #20267: Filter out network errors from Nimbus
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/fenix/experiments/NimbusSetupKtTest.kt
Labels: pr:needs-landing

#20144 Add connection sub-menu
  app/src/main/java/org/mozilla/fenix/android/FenixDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentState.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebSiteInfoInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/res/layout/connection_details_website_info.xml
  app/src/main/res/layout/fragment_connection_details_dialog.xml
  app/src/main/res/layout/quicksettings_website_info.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultConnectionDetailsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: pr:needs-landing

#20345 Close #20320: Use scope from testDispatcher in RecentBookmarksFeatureTest
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeature.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeatureTest.kt
Labels: pr:needs-landing

#20330 For #10915: fix tests by removing existing session
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: eng:ui-test, pr:needs-landing

#20355 For #19886 - Use the new "Details" text for navigating to ETP details
  app/src/main/res/layout/quicksettings_tracking_protection.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#20339 For #19886 - Remove tracking protection overlay CFR
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable/onboarding_popup_background.xml
  app/src/main/res/layout/tracking_protection_onboarding_popup.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlayTest.kt
Labels: needs:review

#20359 Remove outdated README sections
  README.md
Labels: pr:needs-landing

#20361 Update version.txt to 92.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#20220 For #17808: Remove deprecated systemUiVisibility and flags.
  app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
Labels: pr:needs-landing

#20298 For #20292: Use tint for home button icon.
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#20230 For #20229 - Use the AC common implementation for ads/search telemetry
  app/build.gradle
  app/metrics.yaml
  app/src/main/assets/extensions/ads/ads.js
  app/src/main/assets/extensions/ads/adsBackground.js
  app/src/main/assets/extensions/ads/manifest.template.json
  app/src/main/assets/extensions/cookies/cookies.js
  app/src/main/assets/extensions/cookies/cookiesBackground.js
  app/src/main/assets/extensions/cookies/manifest.template.json
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/BaseSearchTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/ExtensionInfo.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/SearchProviderCookie.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/SearchProviderModel.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/TrackKeyInfo.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/ads/AdsTelemetry.kt
  app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetry.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/search/SearchProviderModelTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/BaseSearchTelemetryTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/ads/AdsTelemetryTest.kt
  app/src/test/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetryTest.kt
  app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: needs:data-review, pr:do-not-land

#20373 Issue #19846: Make sure default browser notification only happens once
  app/src/main/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
Labels: pr:needs-landing

#20153 For #19933 - in progress media tab
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecorator.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/layout/recent_tabs_list_row.xml
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewDecoratorTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:approved

#20347 Issue #19989: Add rounded corners to recently tabs' icon
  app/src/main/res/layout/recent_tabs_list_row.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: pr:approved, pr:needs-landing

#20343 Issue #20307: Clear sharedViewModel selectedFolder when backing out of bookmark fragment
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
Labels: pr:needs-landing

#20381 No issue: adds warning comment to beta & release running tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: eng:ui-test, pr:needs-landing

#20311 Closes #19847: Add telemetry for the default browser notification
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessor.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessorTest.kt
Labels: pr:needs-landing

#20396 Closes #19847: Add telemetry for the default browser notification
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessor.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessorTest.kt
Labels: needs:review

#20403 Issue #20402: Disable LastMediaAccessMiddleware temporarily
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
Labels: pr:needs-landing

#20421 For #20420 - Temporarily disable SearchTest#shortcutButtonTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: pr:needs-landing

#20189 For #15499 - Smoothly updates topSites list on remove
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapterTest.kt
Labels: pr:approved, pr:needs-landing

#20050 Allow branch enrollment and unenrollment in Nimbus secret menu
  app/src/debug/res/raw/initial_experiments.json
  app/src/main/java/org/mozilla/fenix/nimbus/NimbusBranchesStore.kt
  app/src/main/java/org/mozilla/fenix/nimbus/controller/NimbusBranchesController.kt
Labels: pr:needs-landing-squashed, pr:waiting-for-authors

#20456 No issue: Update Flank to v21.07.1
  automation/taskcluster/androidTest/parse-ui-test.py
  taskcluster/docker/ui-tests/Dockerfile
Labels: eng:automation

#20458 Issue #16330: Remove remaining usages of Sentry.capture
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/ext/NavController.kt
  app/src/test/java/org/mozilla/fenix/ext/NavControllerTest.kt
Labels: pr:needs-landing

#20452 For #20420 - Re-enable shortcutButtonTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: pr:needs-landing

#20436 Bug 1721329 - Fix perma fail on browsertime tests.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#20512 For #20449 - Fixes `Show most visited sites` crash on disable
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapter.kt
Labels: pr:needs-landing

#20515 For #20297: close tab to avoid saving the same tab to collection
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: eng:ui-test, pr:needs-landing

#20529 Render debug info screen with Jetpack Compose.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_info_settings_preferences.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#20509 For #20440 - Forces TopSitePager bind if no. of pages changed
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapterTest.kt
Labels: pr:needs-landing

#20527 For #19886 - Add a back navigation to the Global Quick Settings from the Tracking Protection dialog
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractor.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionStore.kt
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/quicksettings_tracking_protection.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultConnectionDetailsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
Labels: needs:review

#20537 Closes #16855: disable jetifier.
  gradle.properties
Labels: pr:needs-landing

#20457 Fixes #11427 - Rename master branch to main
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/workflows/sync-strings.yml
  Jenkinsfile
  README.md
  automation/releasetools/PrintMentionedIssuesAndPrs.kts
  automation/taskcluster/update_android_components.sh
  docs/adjust.md
  docs/architecture-overview.md
  docs/crash-reporting.md
  docs/telemetry.md
  l10n-uplift.py
  l10n.toml
  settings.gradle
  taskcluster/ci/ui-test/kind.yml
Labels: needs:review

#20541 Closes #20540: always swipe twice to openSettings in ThreeDotMenuMain…
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing

#20555 Put the Start On home setting behind a feature flag.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/tabs_preferences.xml
Labels: needs:review

#20557 Close #19785: Let WebAuthnFeature ride the trains
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#20561 Issue #20531: Fix intermittent test failures in DefaultQuickSettingsControllerTest
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
Labels: pr:needs-landing

#20556 Use stable version of Jetpack Compose and related tooling/dependencies.
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#20371 For #17917: Use View binding in lists.
  app/src/main/java/org/mozilla/fenix/exceptions/viewholders/ExceptionsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSitePagerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TopSiteViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/ExperimentDefaultBrowserCardViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSitesPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/tips/ButtonTipViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginsListViewHolder.kt
  app/src/main/java/org/mozilla/fenix/share/listadapters/ShareTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolder.kt
  app/src/main/java/org/mozilla/fenix/share/viewholders/AppViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/AbstractPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
Labels: pr:needs-landing

#20138 For #19955: Add telemetry for home screen recent tabs.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
Labels: pr:needs-landing

#20517 For #20516: Renew product telemetry probes expiring in August
  app/metrics.yaml
Labels: pr:approved, pr:needs-landing-squashed

#20252 For #17917: Use View binding in settings screens.
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutLibrariesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/viewholders/AboutItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsView.kt
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsManagementView.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataItem.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/WebsitePermissionsView.kt
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/EditCustomSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/res/layout/fragment_add_search_engine.xml
  app/src/main/res/layout/layout_add_credit_card.xml
  app/src/test/java/org/mozilla/fenix/settings/about/AboutPageAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/about/viewholders/AboutItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleViewHoldersTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/WebsiteInfoViewTest.kt
Labels: pr:needs-landing

#20547 Add telemetry for Android Autofill feature.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: pr:needs-landing

#20577 Keep history metadata for 14 days
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:needs-landing

#20575 Add more context for the Past Exploration localization comment
  app/src/main/res/values/strings.xml
Labels: needs:review, pr:needs-landing

#20589 Issue #20533: Fix intermittent failures of DefaultSessionControlControllerTest
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing

#20581 Add history metadata feature to the settings menu
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing
