Repository mozilla-mobile/fenix, pull requests merged in 2021-04, with the labels that each got.

#18499 For #17772 - Collapse browser menu to "Add to Home screen"
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved, pr:needs-ac-bump, 🙅 waiting

#18760 No issue - Use photon colors from ui-color
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#18766 [SDK-246] Change Nimbus `channel` input to use the same method as Glean
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: pr:approved, pr:needs-landing

#18779 No issue: Make TabLayoutMediator lifecycle aware
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: E1, pr:needs-landing

#18773 Close #17821: Add TabsTrayStore with actions and reducer
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayStoreTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/Tab.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabAdapterIdStorageTest.kt
Labels: pr:needs-landing

#18609 For #17798: Sync Menu Item
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncedTabsRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values/strings.xml
Labels: pr:work-in-progress

#18820 For #18819 - Hide the Credit Card preference by default
  app/src/main/res/xml/preferences.xml
Labels: needs:review

#17406 Closes #17361: Extend perf.awesomebar.* metrics
  app/metrics.yaml
Labels: pr:waiting-for-authors, 🙅 waiting

#18828 For #18770: Correct addons position in three dot menu based on toolbar position
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: needs:review

#16640 Refactor some parts of the autoplay feature
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/settings/PhoneFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wifi/SitePermissionsWifiIntegration.kt
  app/src/main/java/org/mozilla/fenix/wifi/WifiConnectionMonitor.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsWifiIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
  app/src/test/java/org/mozilla/fenix/wifi/WifiConnectionMonitorTest.kt
Labels: pr:needs-landing

#18842 For #17361: Update metrics documentation.
  docs/metrics.md
Labels: pr:approved, pr:needs-landing

#18827 Closes #18068: Track custom fill link from clipboard clicked
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:approved

#18752 For #18743 - Change the top sites label colour and text size
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/colors.xml
Labels: needs:UX-review, pr:approved

#18847 String sync for Fenix v88
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ast/strings.xml
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-gn/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-hy-rAM/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-kmr/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-rm/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-su/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tg/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  l10n.toml
Labels: pr:approved, pr:needs-landing

#18858 No issue: Enable the tabs tray refactor in nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:approved, pr:needs-landing

#17409 Close #11355: Works with and defaults to China FxA/Sync services
  app/src/main/java/org/mozilla/fenix/components/FxaServer.kt
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountUiView.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values/mozonline_strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/preferences_without_icons.xml
  app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt
Labels: pr:needs-landing

#18840 Added UI smoke tests to run on Beta builds.
  automation/taskcluster/androidTest/flank-x86-beta.yml
Labels: eng:automation, eng:ui-test

#18808 For #18268, #18269 - [Saved cards] Display a list of Saved cards fetched from the credit card storage
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardsManagementController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardsManagementInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsAdapter.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsManagementView.kt
  app/src/main/res/layout/component_credit_cards.xml
  app/src/main/res/layout/credit_card_list_item.xml
  app/src/main/res/layout/fragment_saved_cards.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/credit_cards_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementInteractorTest.kt
Labels: needs:review

#18850 For #18776: PWA install to homescreen is available in main menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved

#18849 For #18837: Settings menu item should be tinted if there is an account issue
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: needs:UX-review, pr:approved

#18883 For #17870: Enable new three-dot menu redesign on nightly builds
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: needs:review

#18832 For #17759: Added min SDK 23 to avoid crashes on android 5.0 and 5.1
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: pr:approved

#18844 For #18608 Add experiment for set default browser MenuItem.
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
Labels: needs:review

#18870 Issue #17819: Pull trove4j from Maven Central instead of JCenter.
  build.gradle
Labels: needs:review

#18868 For #18829: Adjust bookmark item color to UX specs.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: needs:UX-review, pr:approved

#18751 For #18742 - Resize the top site item sizes
  app/src/main/res/values/dimens.xml
Labels: pr:approved, pr:needs-landing

#18906 For #15372: Correct one more instance of the onboarding string
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#18955 Fix screenshots tests: showDefaultHomeScreen, bookmarksManagementTest
  app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
Labels: eng:ui-test

#18957 For #17979 & #17840: fix and re-enable UI tests affected by main menu…
  app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ShareButtonTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: eng:ui-test

#18958 For #18608 only show the experiment for set default browser MenuItem when Nightly, Beta, Release are not the default browser
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:approved

#18962 For #18960: Remove nav in homescreen three dot menu
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: needs:review

#18932 Close #18862: Add multi-select banner to tabs tray
  app/src/main/java/org/mozilla/fenix/components/AbstractBinding.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt
  app/src/main/java/org/mozilla/fenix/tabstray/MenuIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BaseBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionHandleBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenu.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/BrowserMenu.kt
  app/src/test/java/org/mozilla/fenix/components/AbstractBindingTest.kt
  app/src/test/java/org/mozilla/fenix/components/TestComponents.kt
  app/src/test/java/org/mozilla/fenix/components/TestCore.kt
  app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/MenuIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegrationTest.kt
Labels: pr:needs-landing

#18963 Closes #18899: Update content description string for synced tabs icon
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/values/strings.xml
Labels: pr:approved

#18886 Closes #18522: Re-add call to action in tabs tray
  app/src/main/java/org/mozilla/fenix/browser/infobanner/InfoBanner.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInfoBannerBinding.kt
  app/src/main/res/layout/component_tabstray2.xml
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayInfoBannerTest.kt
Labels: needs:review

#18974 Close #18973: Fix references to info banner
  app/src/main/res/layout/component_tabstray2.xml
Labels: pr:needs-landing

#18965 Workflow to sync strings
  .github/workflows/sync-strings.yml
Labels: eng:automation, needs:review

#18970 Related to #18822: Add ignores for intermittent toolbar tests
  app/src/test/java/org/mozilla/fenix/toolbar/DefaultToolbarMenuTest.kt
Labels: needs:review

#18872 For #18375: Add experiment for set default browser New Tab card.
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/ExperimentDefaultBrowserCardViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/experiment_default_browser.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentStoreTest.kt
Labels: needs:review

#18996 Fixes #18995 - Upgrade the sync-strings action to v1.0.1
  .github/workflows/sync-strings.yml
Labels: pr:approved, pr:needs-landing

#19017 For #18986 & #19016: disabled failing tests changeThemeSetting & chan…
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
Labels: eng:intermittent-test, eng:ui-test

#18884 For #18272 - [Edit card] Display a saved card information in a Edit card screen
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorState.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardsManagementController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardEditorInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardsManagementInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorStateTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementInteractorTest.kt
Labels: needs:review

#19012 Close #19011: Always have a click listener in TabTrayViewHolder
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayViewHolderTest.kt
Labels: needs:review

#18818 For #18815: Expand app bar on onboarding dismissal and browsing start.
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: needs:review

#18987 For #18856: Add metrics for opening settings screen from home menu.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  docs/metrics.md
Labels: needs:review

#18895 For #18853: Add metrics for default browser new tab experiment.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  docs/metrics.md
Labels: pr:needs-landing

#18956 For #18376: Add experiment for set default browser settings card.
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/layout/default_browser_experiment_preference.xml
  app/src/main/res/xml/preferences_default_browser_experiment.xml
  app/src/main/res/xml/preferences_without_icons_default_browser_experiment.xml
Labels: needs:review

#19025 For #18854: Add metrics for home screen being displayed.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  docs/metrics.md
Labels: needs:data-review

#19034 Closes #19003: Add account setting to tabstray synced tab menu
  app/src/main/java/org/mozilla/fenix/tabstray/MenuIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMenu.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabLayout.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/tabstray/MenuIntegrationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: pr:needs-landing

#18982 Telemetry for #18855, #18851 and #18857
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  docs/metrics.md
Labels: needs:review

#19032 For #18274 - [Edit card] Update a saved credit card information
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardsManagementController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardEditorInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorInteractorTest.kt
Labels: pr:needs-landing

#19058 Issue #18819: Hide Credit Card pref by default (for settings w/o icons)
  app/src/main/res/xml/preferences_without_icons.xml
Labels: pr:approved, pr:needs-landing

#19035 For #18867: remove "signed in as" string in three-dot menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: needs:review

#19031 Issue #19030: Allow homescreen to be scrollable with extra content
  app/src/main/res/layout/fragment_home.xml
Labels: needs:review

#19042 Close #19024: Fix intermittent test failure in NavigationInteractor
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: needs:review

#19083 Update A-C to 75.0.20210416190104
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#19082 Closes #18946: Add undo toast for tabstray
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutObserverTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayStoreTest.kt
Labels: pr:needs-landing

#19086 Close #19064: Focus on tab page with the BrowsingModeManager
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: needs:review

#19097 Update A-C to 75.0.20210417143049
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#18649 For #18496: Set activity theme in onCreate before call to super.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: needs:review

#18998 No issue: test one shard per UI test on FTL
  automation/taskcluster/androidTest/flank-x86.yml
  taskcluster/ci/ui-test/kind.yml
Labels: eng:automation, pr:do-not-land

#19008 For #18745: Add elevation to Top Sites Tiles
  app/src/main/res/drawable/top_sites_background.xml
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:approved, pr:needs-landing

#18891 For #18830 - remove card nickname from credit card editor
  app/src/main/res/layout/fragment_credit_card_editor.xml
Labels: needs:review

#19134 For #18240: Adjust preference screen to fit UX specs.
  app/src/main/res/layout/preference_credit_cards_add_credit_card.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/credit_cards_preferences.xml
Labels: pr:needs-changes

#19037 For #19005: new tab three-dot menu sync sign in
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:approved

#19145 No issue: Suppress deprecation for LoginStorageDelegate
  app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt
  app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt
Labels: pr:approved, pr:needs-landing

#19148 Run the sync-strings workflow daily at 2am
  .github/workflows/sync-strings.yml
Labels: pr:approved

#19149 Update the sync-strings workflow
  .github/workflows/sync-strings.yml
Labels: pr:approved

#19159 For #18608: Also add default browser item in new menu.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing

#18901 No issue: add Android Emulator action for contributor PRs
  .github/workflows/build-contributor-pr.yml
Labels: eng:ui-test

#19165 update_android_components.sh: Watch different component.
  automation/taskcluster/update_android_components.sh
Labels: needs:review

#19118 For #19114: check state of sync account when navigating from sync sign in menu item
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/test/java/org/mozilla/fenix/components/accounts/FenixAccountManagerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:approved

#19060 For #19059: Remove strings marked as deprecated that are no longer being used
  app/src/main/res/values/strings.xml
Labels: pr:approved, pr:do-not-land

#19130 For #18267: Updates preferences visibility depending on creditCardsStore
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
  app/src/main/res/xml/credit_cards_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragmentTest.kt
Labels: pr:approved

#19161 Remove browser-search references.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/search/SearchMigration.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  buildSrc/src/main/java/AndroidComponents.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-ac-bump

#19188 For #19180: Fix tab counter not entirely visible on RTL layout.
  app/src/main/res/layout/tabs_tray_tab_counter2.xml
Labels: pr:needs-landing

#19167 No issue - Replace local photon colors with ui-colors
  app/src/main/res/layout/layout_percentage_seek_bar.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: needs:review

#19133 For #19125: Move top site pin net to title.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolder.kt
  app/src/main/res/drawable/ic_new_pin.xml
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt
Labels: pr:approved

#19187 For #19065: Add extension functions to be used with credit cards.
  app/src/main/java/org/mozilla/fenix/settings/creditcards/String.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/StringTest.kt
Labels: pr:approved

#19186 Issue #19040: Remove Leanplum (Nightly)
  .gitignore
  README.md
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/push/FirebasePushService.kt
  app/src/main/java/org/mozilla/fenix/push/LeanplumNotificationCustomizer.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_info_settings_preferences.xml
  app/src/test/java/org/mozilla/fenix/components/BackgroundServicesTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/push/LeanplumNotificationCustomizerTest.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  docs/mma.md
  docs/telemetry.md
  taskcluster/fenix_taskgraph/transforms/build.py
  taskcluster/scripts/toolchain/android-gradle-dependencies.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/after.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/nexus.xml
Labels: pr:approved

#19243 Properly quote descriptions in ad metric definitions
  app/metrics.yaml
Labels: pr:approved, pr:needs-landing

#19215 For #19213: Adjust synced tabs to properly show in RTL.
  app/src/main/java/org/mozilla/fenix/sync/SyncedTabsViewHolder.kt
  app/src/main/res/layout/view_synced_tabs_group.xml
  app/src/test/java/org/mozilla/fenix/sync/SyncedTabsViewHolderTest.kt
Labels: pr:approved

#19044 For issue #18132 update to proton icons first batch
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/res/drawable-v24/shield_dark.xml
  app/src/main/res/drawable-v24/shield_light.xml
  app/src/main/res/drawable/ic_addons_extensions.xml
  app/src/main/res/drawable/ic_alert.xml
  app/src/main/res/drawable/ic_arrowhead_right.xml
  app/src/main/res/drawable/ic_bookmark_list.xml
  app/src/main/res/drawable/ic_bookmark_outline.xml
  app/src/main/res/drawable/ic_bookmarks_menu.xml
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_desktop.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_fab_sync.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_link_enabled.xml
  app/src/main/res/drawable/ic_new.xml
  app/src/main/res/drawable/ic_onboarding_tracking_protection.xml
  app/src/main/res/drawable/ic_private_browsing.xml
  app/src/main/res/drawable/ic_qr.xml
  app/src/main/res/drawable/ic_readermode.xml
  app/src/main/res/drawable/ic_readermode_selected.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_synced_tabs.xml
  app/src/main/res/drawable/ic_tabs.xml
  app/src/main/res/drawable/ic_tracking_protection.xml
  app/src/main/res/drawable/ic_tracking_protection_anim_disable.xml
  app/src/main/res/drawable/ic_tracking_protection_anim_enable.xml
  app/src/main/res/drawable/ic_tracking_protection_disabled.xml
  app/src/main/res/drawable/ic_tracking_protection_enabled.xml
  app/src/main/res/drawable/ic_whats_new.xml
  app/src/main/res/drawable/mozac_ic_extensions_black.xml
  app/src/main/res/drawable/private_browsing_button.xml
  app/src/main/res/drawable/shield_dark.xml
  app/src/main/res/drawable/shield_light.xml
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/component_collection_creation_name_collection.xml
  app/src/main/res/layout/download_dialog_layout.xml
  app/src/main/res/layout/quicksettings_tracking_protection.xml
  app/src/main/res/layout/share_close.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values/strings.xml
Labels: needs:UX-review

#19269 Follow up on PR #19243: Update metrics documentation.
  docs/metrics.md
Labels: pr:approved, pr:needs-landing

#19262 For #19113 - Change topSite corner radius to 8dp
  app/src/main/res/drawable/top_sites_background.xml
Labels: pr:approved, pr:needs-landing

#19286 Issue #10941: Align Nightly version with Gecko/A-C version.
  app/build.gradle
  buildSrc/src/main/java/Config.kt
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: needs:review

#19111 For #18807: Turn on feature flag for three-dot menu redesign for beta.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:approved, pr:do-not-land

#19312 No issue: uplift three dot menu redesign for beta.
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/test/java/org/mozilla/fenix/components/accounts/FenixAccountManagerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:approved, pr:needs-ac-bump

#19313 Unit tests: Bump max heap size to 3072m.
  app/build.gradle
Labels: needs:review
