Repository mozilla-mobile/fenix, pull requests merged in 2022-10, with the labels that each got.

#27229 For #24544 - Have Talkback use "expand" and "collapse" actions for collections
  app/src/main/java/org/mozilla/fenix/home/collections/Collection.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#27218 For #27129 - Fix accessibility for default wallpaper thumbnail
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing

#27251 No issue: adds new onboarding smoke tests
  app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingFeaturesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27275 For #27253: Add content description to close button.
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#27257 For #3709: Add save to PDF UI.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/share/SaveToPDFInteractor.kt
  app/src/main/java/org/mozilla/fenix/share/SaveToPDFItem.kt
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareInteractor.kt
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareInteractorTest.kt
Labels: pr:approved

#26931 For #26930: Upgrade kotlin to 1.7.10 and compose compiler to 1.3.0.
  app/build.gradle
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27277 For #27128 - Fix accessibility for wallpaper settings "Learn more" heading
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27313 No issue: Disable ETP permanent UI test failures
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
Labels: eng:ui-test

#27291 Close #24498: Add test for history search telemetry
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryInteractor.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryInteractorTest.kt
Labels: pr:needs-landing, pr:approved

#27268 Close #27147: Add telemetry for bookmark search
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchController.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchControllerTest.kt
Labels: pr:needs-landing

#27326 For #27307 - Use the correct warning button text and icon color for DestructiveButton
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#27321 Close #27320: Include testing regex to Google Maven allowlist
  build.gradle
Labels: pr:needs-landing

#27284 Close #26948: Enable custom extension collections in Beta.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: pr:needs-landing

#27332 For #27095 - Download light/dark wallpaper card colors
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperMetadataFetcher.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/wallpaper/ExtensionsTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperDownloaderTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperMetadataFetcherTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#27358 For #27289: standardize coroutine usage in WallpaperFileManager
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
Labels: pr:needs-landing

#27304 Update gradle testing dependencies
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27359 For #27330 - Cache selected wallpaper card colors
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#27368 For #27366 - Revert "For #26644 - Apply the new theme earlier to the private browsing button
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing

#27382 For #27381 - Unregister FXA observer to prevent memory leaks
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: pr:needs-landing

#27389 For #27388 - Add optional background colors to SelectableChip
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
Labels: pr:needs-landing

#27114 For #27101: set dialog to be dismissed when touched outside
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
Labels: pr:needs-landing

#27380 No issue: Adds TCP & jump back in contextual hints UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingFeaturesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27395 Pin relbot Github Action to the 1.0.0 tag
  .github/workflows/update-ac.yml
Labels: pr:needs-landing, pr:approved

#27362 Update Kotlin to 1.7.20
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27397 For #27396 - Add optional text colors to SelectableChip
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
Labels: pr:needs-landing, pr:approved

#27399 For #27117 - update copy in the menu from sign in to sync and save
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27403 Update Google Play Review dependency to 2.0.0
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27363 Update Adjust to latest release
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27437 Update version.txt to 108.0b1.
  version.txt
Labels: pr:needs-landing

#27411 Update protobuf to 3.21.7
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, pr:approved

#27434 For #27405 - Clean up references to "Sing in to Sync" phrase
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/SyncPreferenceView.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SyncPreferenceViewTest.kt
Labels: pr:needs-landing, pr:approved

#27448 Update jna to version 5.12.1
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27440 For #27439: Remove all unused strings marked moz:removedIn <= 105
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27460 For #27456 - Migrate Context.isDark() into a top-level extension
  app/src/main/java/org/mozilla/fenix/ext/Context.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
Labels: pr:needs-landing

#27452 No issue: Fix for None key-pair in Flank client-details
  automation/taskcluster/androidTest/ui-test.sh
Labels: pr:needs-landing

#27446 For #25029 and #26087 re-enable useAppWhileTabIsCrashedTest and privateBrowsingUseAppWhileTabIsCrashedTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27451 Bug 1791998 - Disable TCP popup when running performance tests.
  app/src/main/java/org/mozilla/fenix/perf/Performance.kt
Labels: pr:needs-landing-squashed

#27372 Truncate urls to prevent slowing down of UI
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedDeviceTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#27375 No issue: add script to generate filled telemetry renewal request
  tools/.gitignore
  tools/data_renewal_generate.py
  tools/data_renewal_request.py
Labels: pr:needs-landing, pr:approved

#27410 For #9323 - Use android:background to set small search widget microphone icon
  app/src/main/res/drawable/ic_microphone_widget.xml
  app/src/main/res/drawable/ic_microphone_widget_padded.xml
  app/src/main/res/layout/search_widget_large.xml
  app/src/main/res/layout/search_widget_medium.xml
  app/src/main/res/layout/search_widget_small.xml
Labels: pr:needs-landing

#27445 For #27135 - Correctly report top sites for a11y services
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#27062 For #26577 - resetFocus only when camera permission is denied
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing

#27528 No issue: Update data renewal request script
  tools/data_renewal_request.py
Labels: pr:needs-landing

#27542 For #27541: Update AndroidX Annotation to latest version.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/ext/SpannableString.kt
  app/src/main/java/org/mozilla/fenix/ext/View.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenuBuilder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsController.kt
  app/src/main/java/org/mozilla/fenix/perf/ProfilerMarkerFactProcessor.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupActivityLog.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupPathProvider.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupTypeTelemetry.kt
  app/src/main/java/org/mozilla/fenix/perf/StorageStatsMetrics.kt
  app/src/main/java/org/mozilla/fenix/perf/StrictModeManager.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/PrivateBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
  buildSrc/src/main/java/Dependencies.kt
  mozilla-detekt-rules/src/main/java/org/mozilla/fenix/detektrules/perf/MozillaUseLazyMonitored.kt
Labels: pr:needs-landing, pr:approved

#27028 For #26520 - Color homepage cards via wallpaper card colors
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitePagerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperState.kt
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupReportFullyDrawnTest.kt
Labels: pr:needs-landing, pr:approved

#27534 For #27458: Add AD_ID Permission
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing

#27563 For #27455 - Rename all reference names to AppStore as appStore
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingFeature.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/DefaultTopSitesView.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitePagerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/components/appstate/AppActionTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/MessagingFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/settings/HomeSettingsFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing, pr:approved

#27444 Combine Google package name regex into a single one #27336
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27532 Update Sentry to 6.6.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27543 Close #24613: Remove history improvement feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeature.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeatureTest.kt
Labels: pr:needs-landing, pr:approved

#27545 For #27269: Use parentFile method over substring extraction
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
Labels: pr:needs-landing

#27587 For #27584 - Replace Button in RecentSyncedTab with SecondaryButton
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
Labels: pr:needs-landing

#27517 For #27524 Set as default browser toggle get set to true after user elect Fenix as default browser
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: pr:needs-landing

#27564 For #27522: New search settings UI tests coverage
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: pr:needs-landing, needs:review

#27573 Bug 1780639 - let Save as PDF ride the trains.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#27574 No issue: Update Google Cloud SDK Version to 407.0.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: pr:needs-landing

#27521 For #27522 new delete one/all search engines UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27544 For #27459 - Add divider composable
  app/src/main/java/org/mozilla/fenix/compose/Divider.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:approved
