Repository mozilla-mobile/fenix, pull requests merged in 2022-08, with the labels that each got.

#26266 For #25926 disable failing testDownloadPrompt UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: pr:needs-landing, eng:ui-test

#26243 For #25837 - Invalidate cached nimbusValidation values when changing locale settings
  app/src/main/java/org/mozilla/fenix/settings/advanced/DefaultLocaleSettingsController.kt
Labels: pr:needs-landing

#26249 Fixes: #26052 remove WallpaperManager::updateWallpaper
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing, pr:approved

#26284 For #26283: Use message buttonLabel in MessageCard.
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
Labels: pr:needs-landing, pr:approved

#26282 For #26286 new undoDeleteHistoryItemTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26299 For #26239 - Avoid displaying multiple download items for the same file
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadFragmentTest.kt
Labels: pr:needs-landing

#26152 Bug 1780858 - Run a51 browsertime tests on Fenix branch
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing-squashed

#26173 For #26172 - New CFR popup composable
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupContent.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayout.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupShape.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/compose/cfr/CFRPopupFullScreenLayoutTest.kt
Labels: pr:needs-landing

#26304 For #26227 - Remove search term tab groups from Jump Back In
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/ext/AppState.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/ext/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/interactor/RecentTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt
  app/src/main/res/drawable/ic_all_tabs.xml
  app/src/main/res/drawable/ic_search_group_thumbnail.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/ext/AppStateTest.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/ext/RecentTabsTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayStoreReducerTest.kt
Labels: pr:needs-landing

#26317 For #25926 disable failing mainMenuOpenInAppTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#26314 For #26286 new verifyRemoveTopSiteFromMainMenu UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26223 For #26144 new App-like experience in PWAs UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26326 For #26302 - Change header text height to wrap_content for autofill add/edit screens
  app/src/main/res/layout/fragment_add_login.xml
  app/src/main/res/layout/fragment_address_editor.xml
  app/src/main/res/layout/fragment_credit_card_editor.xml
  app/src/main/res/layout/fragment_edit_login.xml
Labels: pr:needs-landing, pr:approved

#26165 Bug 1756153 - Move startup perf measurements to a background thread
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/perf/StartupTypeTelemetry.kt
Labels: pr:needs-landing

#26364 Fix #26362: Use app:lineHeight to support API Level <= 27
  app/lint-baseline.xml
  app/src/main/res/layout/custom_search_engine.xml
  app/src/main/res/layout/fragment_onboarding_home_dialog.xml
  app/src/main/res/layout/settings_https_only.xml
Labels: pr:needs-landing-squashed

#26291 For #26289 - Remove tab groups metrics and setting
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/tabs_preferences.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabSorterTest.kt
Labels: pr:needs-landing, pr:approved

#26379 Fixes #26377: re-open already opened recent synced tabs
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
Labels: pr:needs-landing

#26228 Close #26041: Re-set TrackingProtectionPolicy after Nimbus SDK is initialized
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#26376 For #22558 - Fix private theme bug in Tabs Tray
  app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeAbstractTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing

#26356 Add "manage account and devices" button to home menu
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenuBuilder.kt
  app/src/main/res/values-zh-rCN/mozonline_strings.xml
  app/src/main/res/values/mozonline_strings.xml
Labels: pr:needs-landing, pr:approved

#26417 Close #26198: Add debounce to account manager syncs
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#26324 Fixes #26245: refactor the WallpaperManager as several WallpaperUseCases
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/ext/Bitmap.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupTypeTelemetryTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#26395 add workflow to update nimbus experiments
  .github/workflows/update-nimbus-experiments.yml
Labels: pr:needs-landing

#26393 update isFirstRun to be manually set and set experiments locally on first run
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved, Feature:Experiments, Nimbus, pr:needs-landing-squashed

#26281 For #26115 - Change homescreen Show all button color according to wallpaper
  app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
Labels: pr:needs-landing, pr:approved, Needs-UX

#26436 For #25602: Lowercase search engine id when recording telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTestRobolectric.kt
Labels: pr:needs-landing

#26328 For #26144 new cancel delete all history UI test and other refactoring work
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26434 Issue ##26361: randomize shortcut titles to avoid data overlapping
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#26309 For #26308 - Add feature flag for MR onboarding
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#26415 For #26412 - Remove try catch for NimbusFeatureException from FxNimbus value() getter
  app/src/main/java/org/mozilla/fenix/components/settings/FeatureFlagPreference.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved

#26477 No issue - Use the onboarding description in nimbus.fml.yaml
  nimbus.fml.yaml
Labels: pr:approved

#26447 Closes #26446: add wallpaper oboarding Nimbus flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#26442 Close #26150: Do not show sync tabs in home when sync open tabs setting is disabled
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#26429 For #26037: Open shared FireFox tab in Firefox browser of the device that recceived the tab
  app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt
Labels: pr:needs-landing

#26422 For #26421 - Extract synced tabs into it's own viewholder
  app/src/main/java/org/mozilla/fenix/ext/AppState.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#26416 For #26414 - Have the Pocket spocs feature as part of the homescreen sections experiments
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#26483 Revert "Closes #25942: use HistoryFragment to show synced history"
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/syncedhistory/SyncedHistoryFragment.kt
  app/src/main/res/layout/fragment_synced_history.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
Labels: pr:needs-landing

#26479 For #26423: simplify wallpaper types to single data class
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#26496 Close #26495: Move Huawei checks to ManufacturerCodes
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/utils/ManufacturerCodes.kt
Labels: pr:needs-landing

#26336 For #26335: Enable sponsored shortcuts by default
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:approved

#26512 For #26335: Allow for more inflations in performance tests
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
Labels: pr:needs-landing

#26493 No issue: Remove code to generate tab group size metrics
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
Labels: pr:needs-landing

#26452 For #26144 new verifySponsoredShortcutsListTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26499 For #26423: add wallpaper metadata fetcher
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperMetadataFetcher.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperMetadataFetcherTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#26524 For #26074 fix failing settingsTest screen shot UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: pr:needs-landing, eng:ui-test, pr:approved

#26518 For #26517 - Create wallpaper v2 feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#26531 Set the gradle memory limit to 12GB.
  gradle.properties
Labels: pr:needs-landing

#26503 Closes #26502: add isLocal parameter for history openItem telemetry event
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryDataSource.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
Labels: pr:needs-landing, pr:approved

#26529 For #26528 - Add a nimbus feature flag for MR Home Onboarding Dialog
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#26535 Revert "Closes #25967: add classes to support multiple viewHolders"
  app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryViewItem.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/EmptyViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/RecentlyClosedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/SignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TimeGroupSeparatorViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TimeGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TopSeparatorViewHolder.kt
  app/src/main/res/layout/history_list_empty.xml
  app/src/main/res/layout/history_list_group.xml
  app/src/main/res/layout/history_list_header.xml
  app/src/main/res/layout/history_list_history.xml
  app/src/main/res/layout/history_list_sign_in.xml
  app/src/main/res/layout/history_list_time_group_separator.xml
  app/src/main/res/layout/history_list_top_separator.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryGroupViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryViewHolderTest.kt
Labels: pr:needs-landing

#26506 Issue #26127, #26092: Ads RetryTestRule to TopSitesTest class, other small refactors
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
Labels: pr:needs-landing, eng:ui-test, pr:approved

#26544 For #26380 - Wait in tests until telemetry is recorded.
  app/src/main/java/org/mozilla/fenix/perf/StartupTypeTelemetry.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupTypeTelemetryTest.kt
Labels: pr:needs-landing

#26546 For #26545 - Update the indicator and the close button of the CFR composable
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupContent.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupShape.kt
Labels: pr:needs-landing, pr:approved

#26552 update_android_components: don't create an empty PR if we couldn't push
  automation/taskcluster/update_android_components.sh
Labels: pr:needs-landing

#26550 For #26549 - Add Nimbus feature flag for first run onboarding page updates and Jump back in CFR
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#26558 Closes #26530: add top spacing to header in history list
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/layout/component_history.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/layout/recently_closed_nav_item.xml
Labels: pr:needs-landing

#26437 For #26399 - Use a list of tabs for recent synced tabs success state
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing, pr:approved

#26553 Let relbot update A-C on trunk
  .cron.yml
  .mergify.yml
  automation/taskcluster/update_android_components.sh
  taskcluster/ci/bump/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/docker-image/kind.yml
  taskcluster/docker/bump/Dockerfile
  taskcluster/docker/bump/mozilla_key.asc
  taskcluster/docker/bump/owner_trust.db
  taskcluster/fenix_taskgraph/target_tasks.py
Labels: pr:needs-landing

#26580 For #26579 - Remove all unused strings marked moz:removedIn <= 103
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#26586 Update version.txt to 106.0b1
  version.txt
Labels: pr:needs-landing

#26561 add about block to nimbus.fml.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#26588 For #26587 - Fix broken previews using Fenix Image composable
  app/src/main/java/org/mozilla/fenix/compose/Image.kt
  app/src/main/java/org/mozilla/fenix/compose/ImagesPlaceholder.kt
Labels: pr:needs-landing

#26494 Close #26072: Don't show sync menu item until account manager is available
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:needs-landing, pr:approved

#26486 For #26398 - Filter recent synced tabs using the homescreen blocklist
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistHandler.kt
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistMiddleware.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistMiddlewareTest.kt
Labels: pr:needs-landing, pr:approved

#26570 Use parallel execution for Gradle
  gradle.properties
Labels: pr:needs-landing, pr:approved

#26598 No issue: increase flaky tests attempts on Nightly tests
  automation/taskcluster/androidTest/flank-x86-start-test.yml
Labels: pr:needs-landing, eng:ui-test

#26595 For #26401: Remove unused wallpaper metrics.
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#26616 Closes #26615 Add nimbus configuration feature flags for MR 2022
  .experimenter.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing

#26509 For #26400 - Add long-press option to remove tab pickup from homescreen
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/ext/AppState.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistHandler.kt
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/interactor/RecentSyncedTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
Labels: pr:needs-landing, pr:approved

#26613 For #26605 - Clean up RecentTabViewHolder
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
Labels: pr:needs-landing, pr:approved

#26585 CFR composable - UI touchups2
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayout.kt
Labels: pr:needs-landing, pr:approved

#26630 For #26556 - Add skr and tok native/English display names
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
Labels: pr:needs-landing

#26610 For #26604 - Add missing preview to RecentTabs
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing, pr:approved

#26632 For #26620 - Replace the onboarding nimbus feature with MR2022 nimbus feature
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#26634 Set the Gradle max heap size to 7g
  gradle.properties
Labels: pr:needs-landing, pr:approved

#26548 For #26169 - MR Home Onboarding Dialog for upgrading users
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/fragment_onboarding_home_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, pr:approved

#26648 For #26646 - Use unescaped typographic apostrophes instead of escaped quotes
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26612 For #26608 - Update recent bookmarks homepage title
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksHeaderViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#26657 For #26656 - Use the correct string for onboarding_home_welcome_description
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing-squashed

#26203 For #26190 - Update jump back in cfr logic and message
  app/src/main/java/org/mozilla/fenix/onboarding/JumpBackInCFRDialog.kt
  app/src/main/res/layout/onboarding_jump_back_in_cfr.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#26623 chore: Bump taskgraph to v3.0.0
  .taskcluster.yml
  taskcluster/fenix_taskgraph/transforms/browsertime.py
  taskcluster/fenix_taskgraph/transforms/release_deps.py
  taskcluster/requirements.txt
Labels: pr:needs-landing

#26649 Close #21702: Update host name check in add login
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
Labels: pr:needs-landing

#26653 Close #26666: Use correct content scale when displaying recent tab thumbnail and icon
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing, pr:approved

#26670 For #26227: Clean up double exclamation operator in BrowserState
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
Labels: pr:needs-landing

#26669 For #26668 - Use the correct string for onboarding_home_sync_title
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26652 rename usage of action repo
  .github/workflows/update-nimbus-experiments.yml
Labels: pr:needs-landing, pr:approved

#26507 For #26489 - Add synced tab pickup onboarding message
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/SyncCFRPresenter.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26689 No issue: disable TCP CFR in screenshots tests
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
Labels: pr:needs-landing, eng:ui-test

#26694 For #26693 - Use a new ID for onboarding_home_sync_title
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26647 For #26555 - Faster wallpapers
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/WallpapersObserver.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/home/WallpapersObserverTest.kt
Labels: pr:needs-landing, pr:approved

#26665 Close #25919: Move UpdateFirstFrameDrawn to RecyclerView.onLayoutCompleted
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#26697 For #26696 - Enable showSynCFR for Nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#26596 For #26551 - Add telemetry for MR Onboarding welcome and sync dialogs.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
Labels: pr:needs-landing, pr:approved

#26702 update bot name
  taskcluster/ci/version-bump/kind.yml
Labels: pr:needs-landing

#26707 For #26093: Use `ic_menu` instead of `ic_close`
  app/src/main/res/layout/library_site_item.xml
Labels: pr:needs-landing

#26701 For #26700 - URI counts will now additionally be sent in baseline
  app/metrics.yaml
Labels: pr:needs-landing

#26692 No issue: Add is Test Lab helper
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
Labels: pr:needs-landing, eng:ui-test

#26451 For #26450: Remove the star icon from Pocket sponsored stories
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/res/drawable/pocket_star_stroke.xml
Labels: pr:needs-landing

#26611 For #26607 - Update back plating for recent Bookmarks
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
Labels: pr:needs-landing, pr:approved

#26562 Download thumbnails
  app/src/main/java/org/mozilla/fenix/components/UseCases.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperMetadataFetcher.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperDownloaderTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing, pr:approved

#26718 For #26717 - Only show the MR onboarding dialog for existing users
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
  app/src/test/java/org/mozilla/fenix/onboarding/FenixOnboardingTest.kt
Labels: pr:needs-landing
