Repository mozilla-mobile/fenix, pull requests merged in 2022-09, with the labels that each got.

#26755 For #26754 - Avoid showing CFR if the MR onboarding is being displayed
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
Labels: pr:needs-landing, pr:approved

#26757 For #26756 - Don't show Jump Back In CFR if the synced tab CFR is shown
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/JumpBackInCFRDialog.kt
  app/src/main/java/org/mozilla/fenix/onboarding/SyncCFRPresenter.kt
Labels: pr:needs-landing

#26748 For #26609 - Update favicon dark mode background color for recent bookmarks and recent tabs
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing, pr:approved

#26761 Bug 1788643 - Add a nightly cron task for performance tests.
  .cron.yml
  taskcluster/ci/browsertime/kind.yml
  taskcluster/fenix_taskgraph/target_tasks.py
Labels: pr:needs-landing-squashed

#26753 For #26739 - Display MR onboarding dialog to existing users as soon as the app is opened
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/WallpapersObserverTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing, pr:approved

#26769 For #26738 - Update MR onboarding with the latest illustrations
  app/lint-baseline.xml
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
  app/src/main/res/drawable/ic_onboarding_sync.xml
  app/src/main/res/drawable/ic_onboarding_welcome.xml
  app/src/main/res/drawable/ic_scan.xml
  app/src/main/res/layout/fragment_turn_on_sync.xml
Labels: pr:needs-landing

#26775 For #26774 - Attempt to show the Synced Tab CFR before the Jump Back In CFR
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
Labels: pr:needs-landing

#26770 For #26759 - Crash fix for UnsupportedOperationException
  app/src/main/java/org/mozilla/fenix/ext/Uri.kt
  app/src/test/java/org/mozilla/fenix/ext/UriTest.kt
Labels: pr:needs-landing

#26202 For #26191 - Add telemetry for jump back in onboarding message
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/onboarding/JumpBackInCFRDialog.kt
Labels: pr:needs-landing, pr:approved

#26780 For #26776 - Don't dim the window when the Jump back in CFR is shown
  app/src/main/java/org/mozilla/fenix/onboarding/JumpBackInCFRDialog.kt
Labels: pr:needs-landing

#26667 Added secret debug menu preference to override the push server URL ( #24170)
  app/src/main/java/org/mozilla/fenix/components/Push.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SyncDebugFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountUiView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/sync_debug_preferences.xml
Labels: pr:needs-landing

#26727 For #26286 new home screen UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26836 For #26830 - Allow the Pocket stories to scroll to the edges of the screen
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
Labels: pr:needs-landing

#26614 For #26606 - Add backplating to Top Sites
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#26848 For #26797 - Add optional parameter to customize the background color of ListItemTabLarge
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#26847 For #26796 - Fix PocketStoriesComposablesPreview
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#26746 For #26731 - First run onboarding updates
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/util/Strings.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/main/res/layout/onboarding_finish.xml
  app/src/main/res/layout/onboarding_header.xml
  app/src/main/res/layout/onboarding_manual_signin.xml
  app/src/main/res/layout/onboarding_privacy_notice.xml
  app/src/main/res/layout/onboarding_toolbar_position_picker.xml
  app/src/main/res/layout/onboarding_tracking_protection.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#26871 Closes #26870: remove layer behind wallpaper thumbnails
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing

#26875 For #26869 - Enable TCP by default starting with v. 106
  nimbus.fml.yaml
Labels: pr:needs-landing

#26838 Bug 1788643 - Enable nightly-test cron on fenix.
  .cron.yml
Labels: pr:needs-landing-squashed

#26863 For #26502: Add time group and private extras in history telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: pr:needs-landing, pr:approved

#26887 remove qa experiment
  app/src/main/res/raw/initial_experiments.json
Labels: pr:needs-landing

#26889 Bug 1781051 - simplify setting ownerEmail in .taskcluster.yml
  .taskcluster.yml
Labels: pr:needs-landing

#26907 Update hash to be ignored for ktlint update
  .git-blame-ignore-revs
Labels: pr:needs-landing

#26764 For #26286 new site security quick settings UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SiteSecurityRobot.kt
Labels: pr:needs-landing, eng:ui-test

#26939 For #26932 disabled failing verifyCustomizeHomepageTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: pr:needs-landing, eng:ui-test

#26941 Close #24913: Update metrics.yaml owners
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#26947 Closes #26865: Make the Nimbus MR Onboarding features true by default.
  nimbus.fml.yaml
Labels: pr:approved

#26906 fixes #26905: update nimbus experiments github action control flow and versions
  .github/workflows/update-nimbus-experiments.yml
Labels: pr:needs-landing

#26940 For #26910: Enable TCP for all modes
  app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomEtpCookiesOptionsDropDownListPreference.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragment.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
  app/src/test/java/org/mozilla/fenix/settings/CustomEtpCookiesOptionsDropDownListPreferenceTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionBlockingFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
Labels: pr:needs-landing

#26944 Closes #26750: add Wallpapers Onboarding dialog
  app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/HomeCFRPresenter.kt
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperOnboarding.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#26671 Thumbnails to wallpapers UI
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/home/WallpapersObserver.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#26950 For #26743: Update the URL text styling in ClickableSubstringLink used by PoweredByPocketHeader
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketRecommendationsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing

#26949 For #26511: apply wallpapers immediately and observe updates
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/WallpapersObserver.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/home/WallpapersObserverTest.kt
Labels: pr:needs-landing

#26789 For #26690 - Dismiss search dialog when opening recent synced tab dropdown menu
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/interactor/RecentSyncedTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
Labels: pr:needs-landing, pr:approved

#26909 For #26908 - Update wallpapers settings page design
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperOnboarding.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/wallpaper/ExtensionsTest.kt
Labels: pr:needs-landing, pr:approved

#26893 Closes #26215: add telemetry events for wallpaper onboarding dialog
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#26982 For #26980: enable task continuity in all channels
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#26988 For #26987 - Update MR Onboarding strings for existing users
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#26993 Disable copyTextTest and selectAllAndCopyTextTest in SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#26974 Closes #26973: adjust wallpaper onboarding ui
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperOnboarding.kt
  app/src/main/res/values/styles.xml
Labels: pr:approved, pr:needs-landing-squashed

#26972 Closes #26971: fix wallpaper onboarding display condition
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing, pr:approved

#26639 For #26286 new sponsored shortcut UI tests and other refactoring work
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27003 For #27002 use featureSettingsHelper instead of app settings
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#26975 For #26784 refactor use of idling resources in UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#26990 Closes #26945: adds telemetry for learn more link on wallpaper settings
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: pr:needs-landing, pr:approved

#27022 Closes #27021: add wallpaper onboarding downloading error snackbar
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
Labels: pr:needs-landing

#26992 For #27024 - Use textAccent for the "Learn more" link in the wallpaper settings
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing, pr:approved

#26996 Closes #26995: add sorting of wallpapers on wallpapers onboarding tool
  app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt
  app/src/test/java/org/mozilla/fenix/settings/wallpaper/ExtensionsTest.kt
Labels: pr:needs-landing

#27013 For #27029 - Use placeholder inplace of app name
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/res/values/static_strings.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27019 For #27020 - Correct padding for wallpaper thumbnails
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing

#27034 Closes #26999: fix disapprearing wallpapers after going back to home screen
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing

#27017 No issue: Adjust shard count in legacy/nightly/beta UI test jobs
  automation/taskcluster/androidTest/flank-arm-beta.yml
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  automation/taskcluster/androidTest/flank-arm-start-test.yml
  taskcluster/ci/ui-test/kind.yml
Labels: pr:needs-landing

#27059 Update version.txt to 107.0b1
  version.txt
Labels: pr:needs-landing

#27044 Update protobuf to latest release.
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27010 For #26286 new homepage settings UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27058 For #24978 re-enable UI tests with frequent ANR
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#27018 Closes #26997: convert v1 wallpapers into collection group
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/test/java/org/mozilla/fenix/settings/wallpaper/ExtensionsTest.kt
Labels: pr:needs-landing, pr:approved

#27068 For #26582 - Renew telemetry expiring in 107
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialog.kt
Labels: pr:needs-landing

#26967 Closes #26966: enable wallpapers V2
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#27014 For #27004: Make the top site frame layout focusable.
  app/src/main/res/layout/top_site_item.xml
Labels: pr:needs-landing

#27074 For #27005 fix flaky updateSavedLoginTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#26969 For #26854 - Fix bug causing the Top Sites sponsored text to show scrollbars
  app/src/main/res/layout/top_site_item.xml
Labels: pr:needs-landing, pr:approved

#27079 For #27055: check whether applied wallpaper name is blank
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperTest.kt
Labels: pr:needs-landing

#27082 Closes #27081: enable wallpaper onboarding flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#27088 For #27008 fix flaky addAndRemoveMostViewedTopSiteTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
Labels: pr:needs-landing, eng:ui-test

#27030 For #27026 - Use the wallpaper adapted text color for the Collections placeholder
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#27112 For #27055: handle legacy wallpaper naming case
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperTest.kt
Labels: pr:needs-landing

#27073 Bug 1789398 - ensure task["metadata"]["owner"] is not empty on github…
  .taskcluster.yml
Labels: pr:needs-landing

#27102 For #25345 re-enable customTrackingProtectionSettingsTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#27104 For #26936 and #26818 fix saveLoginFromPromptTest and neverSaveLoginFromPromptTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27148 For #27111: disable TCP in beta and release
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#27174 Issue #26711: re-enabled verifyPageMainMenuItemsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#27105 For #26644 - Apply the new theme earlier to the private browsing button
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing

#27185 For #26759 - Crash fix for UnsupportedOperationException (backport #26770)
  app/src/main/java/org/mozilla/fenix/ext/Uri.kt
  app/src/test/java/org/mozilla/fenix/ext/UriTest.kt
Labels: pr:needs-landing, pr:approved

#27189 For #27111 - Allow TCP in all releases. Control it from Nimbus.
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#27113 Added missing locales
  l10n-release.toml
Labels: pr:needs-landing

#27137 For #26424 - Handle special legacy wallpaper cases
  app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperMigration.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/LegacyWallpaperMigrationTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#27146 For #27127: do not display wallpaper onboarding in private browsing mode
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing, pr:approved

#27206 For #26087 re-enable UI tests affected by tabs tray migration to compose
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27205 No issue: remove sdk suppression tests tags for API28
  .cron.yml
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: pr:needs-landing, eng:ui-test

#27210 Closes #27209: fix WallpapersSettings crash
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: pr:needs-landing
