Repository mozilla-mobile/fenix, pull requests merged in 2022-07, with the labels that each got.

#25645 For #25551 fix disabled openLinkInAppTest UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: pr:needs-landing, eng:ui-test

#25855 For #24528 - Remove isPrivate conditional in getTheme in favor of inComposePreview
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
  app/src/main/java/org/mozilla/fenix/compose/StaggeredHorizontalGrid.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  app/src/main/java/org/mozilla/fenix/compose/button/TextButton.kt
  app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/MediaImage.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  app/src/main/java/org/mozilla/fenix/home/collections/CollectionItem.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketRecommendationsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressList.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/theme/FenixTypography.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing, pr:approved

#25871 Closes #25825 :Disable marketing telemetry until privacy pop window approved in MozillaOnline builds
  app/src/main/java/org/mozilla/fenix/home/mozonline/PrivacyContentDisplayHelper.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#25838 No issue: Tag problematic UI tests to run on API 28 only
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25882 Fix and re-enable `findInPageTest` UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/FindInPageRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25737 For #25736: Add experiment for Total cookie protection.
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#25890 No issue: Add new cron target task for legacy API UI tests
  .cron.yml
  automation/taskcluster/androidTest/flank-x86-legacy-api-tests.yml
  automation/taskcluster/androidTest/ui-test.sh
  taskcluster/ci/ui-test/kind.yml
  taskcluster/fenix_taskgraph/target_tasks.py
Labels: pr:needs-landing

#25928 For #25852: Fixes visibility issue of private tabs notification in UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25934 For #25933 - Ensure sponsored tiles are enable if enrolled in active experiment
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/settings/FeatureFlagPreference.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#25936 For #25935 - Catch NimbusFeatureException from calling FxNimbus value getter
  app/src/main/java/org/mozilla/fenix/components/settings/FeatureFlagPreference.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#25916 Change style to persistent for default browser
  .experimenter.yaml
  app/lint-baseline.xml
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/drawable/rounded_button_background.xml
  app/src/main/res/layout/default_browser_experiment_preference.xml
  app/src/main/res/xml/preferences_default_browser_experiment.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#25939 For #25938: Address MessageCard text not adapting to the dark theme
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
Labels: pr:needs-landing, pr:approved

#25833 For #25829 - String updates for Sync
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsTurnOnSyncRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: pr:needs-landing, pr:approved

#25983 Close #25982: Fix check between current and new when adding a bookmark
  app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt
  app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt
Labels: pr:needs-landing

#25927 For #25796 fix flaky allowNotificationsPermissionPromptTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25995 For #25992 #25832 and #25710 fix flaky PWA UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Labels: pr:needs-landing, eng:ui-test

#26012 For #25994: Make installToHomescreen item a collapsing menu limit.
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing

#26011 For #24457 re-enable selectAndSearchTextTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: pr:needs-landing, eng:ui-test

#26007 For #25999 - Add GitHub actions to tag milestones, link issues and reopen issues for QA
  .github/PULL_REQUEST_TEMPLATE
  .github/workflows/issue-linker.yml
  .github/workflows/milestone.yml
  .github/workflows/qa-needed.yml
  .github/workflows/reopen-for-qa-needed.yml
Labels: pr:needs-landing

#26045 No issue: remove unused inactive tab auto close dialog controller
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAutoCloseDialogController.kt
Labels: pr:needs-landing

#26046 Bug 1779797 - Let mergify automatically approve l10n bumps on release…
  .github/workflows/sync-strings.yml
  .mergify.yml
Labels: pr:needs-landing

#26000 Closes #25952: update close icon
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/download_dialog_layout.xml
  app/src/main/res/layout/no_collections_message.xml
  app/src/main/res/layout/onboarding_inactive_tabs_cfr.xml
  app/src/main/res/layout/onboarding_jump_back_in_cfr.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
Labels: pr:needs-landing, pr:approved

#26028 Fixes #25955: refactor RecentSyncedTabsFeature to use SyncStore
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#25966 Closes #25967: add classes to support multiple viewholders on history screen
  app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryViewItem.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/EmptyViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/RecentlyClosedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/SignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/SyncedHistoryViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TimeGroupSeparatorViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TimeGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/TopSeparatorViewHolder.kt
  app/src/main/res/layout/history_list_empty.xml
  app/src/main/res/layout/history_list_group.xml
  app/src/main/res/layout/history_list_header.xml
  app/src/main/res/layout/history_list_history.xml
  app/src/main/res/layout/history_list_sign_in.xml
  app/src/main/res/layout/history_list_time_group_separator.xml
  app/src/main/res/layout/history_list_top_separator.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryGroupViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#25920 For #25894 - Add firefox suggest header for lib suggestions
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarWrapper.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:needs-ac-bump

#26003 For #21898 - Remove search term tab groups from the Tabs Tray
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalTabsBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/OtherHeaderBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupListAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TitleHeaderAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/ConcatAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSelectors.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt
  app/src/main/res/layout/tab_group_item.xml
  app/src/main/res/layout/tab_tray_title_header_item.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/OtherHeaderBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabGroupBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabSorterTest.kt
Labels: pr:needs-landing, pr:approved

#26096 Issue #25972, #25971: reduce test failures with more retries on legacy-api-tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  automation/taskcluster/androidTest/flank-x86-legacy-api-tests.yml
Labels: pr:needs-landing, eng:ui-test

#26098 Issue #26097: use mock location in UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: pr:needs-landing, eng:ui-test

#26114 For #26113 ⁃ Enable address autofill in all channels
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved

#25965 Closes #25954: add new delete time range dialog for History and HistoryGroup screens
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/RemoveTimeFrame.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragment.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/interactor/HistoryMetadataGroupInteractor.kt
  app/src/main/res/layout/delete_history_time_range_dialog.xml
  app/src/main/res/menu/history_menu.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/RemoveTimeFrameTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
Labels: pr:needs-landing

#26123 For #26121 - Renew telemetry expiring in 105
  app/metrics.yaml
Labels: pr:needs-landing

#26118 Bug 1777255 - part 3: Bump fenix-beta-version Github Action to suppor…
  .github/workflows/sync-strings.yml
Labels: pr:needs-landing

#26135 For #26134 - Add parameter description for @string/delete_all_history_group_prompt_message
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26141 No issue - commit experimenter.yaml
  .experimenter.yaml
Labels: pr:needs-landing

#26147 For #26146 - Use the correct moz:removedIn version in @string/delete_browsing_data_prompt_message
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26148 Bug 1780740 - A-C bumps should auto-merge if CI is green on release branches
  .mergify.yml
Labels: pr:needs-landing

#26170 For #26167 - Check the QA Needed checkbox by default
  .github/PULL_REQUEST_TEMPLATE
Labels: pr:needs-landing

#26175 Closes #26174: fix delete time range prompt text punctuation
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26177 Update version.txt to 105.0b1
  version.txt
Labels: pr:needs-landing

#26183 For #26182 - Remove all unused strings marked moz:removedIn <= 102
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#26139 For #26026 - Refactor the FenixTabCounterMenu creation from HomeFragment to TabCounterBuilder
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/TabCounterBuilder.kt
  app/src/test/java/org/mozilla/fenix/home/TabCounterBuilderTest.kt
Labels: pr:needs-landing, pr:approved

#26171 Issue #25970: wait for homescreen to exist before scrolling
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25996 For #25891 - Move GridViewHolder to compose
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/main/java/org/mozilla/fenix/compose/HorizontalFadingEdgeBox.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/GridTabThumbnail.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeGridViewHolder.kt
Labels: pr:needs-landing

#26184 For #26180 - Renew telemetry expiring in 106
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#26153 Issue #26101: add telementry for deleting time frames
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
Labels: pr:needs-landing, pr:approved

#26204 For #26197: Cancel history list update on fragment destroyed.
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: pr:needs-landing

#26210 For #26061: Make sure favicons are cropped correctly
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/res/layout/library_site_item.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#25943 Closes #25942: use HistoryFragment to show synced history
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/syncedhistory/SyncedHistoryFragment.kt
  app/src/main/res/layout/fragment_synced_history.xml
  app/src/main/res/layout/history_list_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
Labels: pr:needs-landing

#26222 For #26221 - Use ic_globe instead of favicon for composed tab list item
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/GridTabThumbnail.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
Labels: pr:needs-landing, pr:approved

#26051 Fixes #26029: Add wallpaper state to AppStore
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperState.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing
