Repository mozilla-mobile/fenix, pull requests merged in 2022-04, with the labels that each got.

#24167 For #24099 - Remove Event.wrapper for Collections telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationController.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing

#24516 For #24512 - Remove Event.wrapper for RecentlyClosedTabs metrics
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt
  app/src/test/java/org/mozilla/fenix/library/recentlyclosed/DefaultRecentlyClosedControllerTest.kt
Labels: pr:needs-landing

#24326 Don't crash when receiving a bad uri via send tab
  app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt
Labels: pr:needs-landing-squashed

#24559 For #24556 - Handle preference change for the Contile preference
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
Labels: pr:needs-landing

#24577 Fix and re-enable home screen UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#24588 Update Android Components version to 100.0.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#24594 For #24593 - Initialize Glean on all builds. Avoid Fennec check.
  app/src/main/java/org/mozilla/fenix/Config.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing

#24602 For #24461 - Increase touch target for scan, search engine & voice search button
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/IncreasedTapAreaActionDecorator.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/IncreasedTapAreaActionDecoratorTest.kt
Labels: pr:needs-landing

#24583 Change `.experimenter.json` to `.experimenter.yaml`
  .experimenter.yaml
  app/build.gradle
Labels: pr:needs-landing

#24608 For #24607 - Remove all unused strings marked moz:removedIn <= 98
  app/src/main/res/values/mozonline_strings.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24612 Issue #24611: Enable history improvement feature
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#24579 For #24576 - Record delete collection metric
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing

#24614 For #24581 - Fix row spacing between Top Sites
  app/src/main/res/layout/component_top_sites_pager.xml
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/dimens.xml
Labels: pr:needs-landing

#24622 For #24621: Update HTTP only mode strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24587 Issue #24298: Refactor Scan button from the search toolbar into the display toolbar
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#24619 For #24616 - Update all the strings that references "top site" to "shortcut"
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/res/layout/top_sites_rename_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#24595 For #24508 re-enable private browsing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#24646 For #24645 - Update dark theme Action Secondary to LightGrey30
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#24650 For #24649 - Fix spelling of shortcuts in @string/snackbar_added_to_shortcuts
  .experimenter.yaml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#24651 For #24648 - Add a Modifier extension method to draw a dashed border
  app/src/main/java/org/mozilla/fenix/compose/ext/Modifier.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing

#24654 For #24653 - Fix Text Action Secondary color in FirefoxTheme
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing, pr:approved

#24396 for #24177: sync tabs when home is shown
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/interactor/RecentSyncedTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutMediatorTest.kt
Labels: pr:needs-landing

#24604 For #24603 - Remove Event.wrapper for MediaNotification telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#24592 For #24591 - Remove Event.wrapper for ReaderMode telemetry
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#24641 For #24640 - Remove Event.wrapper for VoiceSearch telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing

#24601 For #24599 - Remove Event.wrapper for Tab telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolderTest.kt
Labels: pr:needs-landing

#24639 For #24638 - Remove Event.wrapper for Logins telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/PasswordRevealHelper.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/LoginsListController.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsSettingFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListControllerTest.kt
Labels: pr:needs-landing

#24671 for #24549: add telemetry for recent synced tab
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
Labels: pr:needs-landing

#24714 For #24708 - Remove Event.wrapper for DarkThemeSelected telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
Labels: pr:needs-landing

#24681 For #24596 - Only restore Pocket categories selections once
  app/src/main/java/org/mozilla/fenix/home/PocketUpdatesMiddleware.kt
Labels: pr:needs-landing

#24664 For #24205: Remove wrapper from set default browser toolbar menu.
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing

#24723 For #24709 - Remove Event.wrapper for Wallpapers telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: pr:needs-landing

#24704 For #24701 - Remove Event.wrapper for Pocket related telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/pocket/DefaultPocketStoriesControllerTest.kt
Labels: pr:needs-landing, needs:review

#24719 for #24718: add two remote firefox wallpapers
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing

#24730 For #24381 re-enable firstRunScreenTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#24705 For #24495 fix and re-enable settingsPrivacyItemsTest UI test.
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: pr:needs-landing-squashed

#24732 For #24297 - Add a search engine menu that shows the search engine and search settings
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelector.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenu.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/res/drawable/ic_chevron_down_6.xml
  app/src/main/res/layout/search_selector.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing

#24734 Issue #24733: Setup search for Unified Search experimentation
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#24628 Enable the messaging framework in nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/CustomAttributeProvider.kt
  app/src/main/res/layout/nimbus_message_card.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#24712 For #24206: Remove wrapper from context menu metrics.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: pr:needs-landing, pr:approved

#24728 For #24706 - Remove Event.wrapper for Autofill related telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing, pr:approved

#24748 For #24747 - Remove unused store property in SessionControlAdapter and SessionControlView
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing

#24767 Update to JNA 5.8.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#24756 For #24711: Remove wrapper from recent tabs metrics.
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
Labels: pr:needs-landing, pr:approved

#24755 For #24707 - Remove Event.wrapper for CreditCards telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/interactor/CreditCardsManagementInteractor.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardsManagementInteractorTest.kt
Labels: pr:needs-landing, pr:approved

#24762 For #24710 - Remove Event.wrapper for RecentBookmarks telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
Labels: pr:needs-landing, pr:approved

#24764 For #24759 - Remove Event.wrapper for text selection context menu metrics
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing, pr:approved

#24788 For #24761: Remove wrapper from autoplay settings metrics.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
  detekt-baseline.xml
Labels: pr:needs-landing, pr:approved

#24792 For #24786 - Remove Event.wrapper for SearchTerms telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
Labels: pr:needs-landing, pr:approved

#24810 For #24809 - Remove Event.wrapper for RecentSearches telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsController.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsControllerTest.kt
Labels: pr:needs-landing

#24812 For #24789: Remove wrapper from PWA metrics.
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing

#24808 For #24790 - Remove Event.wrapper for home screen related telemetry
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing

#24818 For #24206: Fix extra key values for context menu metrics.
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: pr:needs-landing

#24804 For #20811 - Fix synced tabs error button width
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing

#24839 For #24838 - Remove Event.wrapper for Tabs telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
Labels: pr:needs-landing

#24727 For #22640 re-enable verifyUndoSnackBarTest UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: pr:needs-landing, eng:ui-test

#24784 For #24760 - Remove Event.wrapper for suggestions telemetry
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#24846 For #24845 - Add Address preference category to Autofill settings
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/autofill_preferences.xml
Labels: pr:needs-landing, pr:approved

#24848 For #24847 - Refactor CreditCardsFragmentStore to AutofillFragmentStore
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardsManagementView.kt
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementViewTest.kt
Labels: pr:needs-landing

#24776 Issue #24733: Create nimbus feature for Unified Search experimentation
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#24813 For #24811 - Remove Event.wrapper for Messaging telemetry
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/DefaultMessageController.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
Labels: pr:needs-landing

#24844 For #24208 - Remove forEach from LoginDialogFacts test
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#24865 For #24759 - Remove forEach from ContextualMenu telemetry test
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#24860 For #24856 - Toggle the "Manage addresses" and "Add address" preference label depending on whether there are saved addresses
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementFragment.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsManagementViewTest.kt
Labels: pr:needs-landing, pr:approved

#24530 For #24338 - Make a reusable list item Composable
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
Labels: pr:needs-landing, pr:approved

#24875 For #23813 - Clear error message for nameOnCardLayout when valid name is submitted
  app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorViewTest.kt
Labels: pr:needs-landing, pr:approved

#24882 For #23817 disable failing toggleSearchSuggestionsTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: pr:needs-landing, eng:ui-test

#24886 For #23136 re-enable selectSearchEnginesShortcutTest UI test.
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#24890 No issue: Update experimenter.yaml
  .experimenter.yaml
Labels: pr:needs-landing

#24893 bug 1764109 - retry ui-tests on exit code 20.
  taskcluster/ci/ui-test/kind.yml
Labels: pr:needs-landing

#24898 For #24897 - Move clickable handling to the parent in ExpandableListHeader
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
Labels: pr:needs-landing

#24864 For #24603 - Remove forEach from MediaNotification telemetry test
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#24877 For #20872: Prevent crash when updating pending bookmarks to be deleted without a selected folder.
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
Labels: pr:needs-landing, pr:approved

#24907 For #24906: Add SURVEY style to nimbus messages FML.
  nimbus.fml.yaml
Labels: pr:needs-landing

#24398 For #23665 - Make the undo snackbar for the library screens work globally
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Undo.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: pr:needs-landing-squashed

#24894 for #24665: Show recent synced placeholders early
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#24909 For #24908 - Reverse the chevrons direction in ExpandableListHeader
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
Labels: pr:needs-landing

#21286 For #19955: Update the telemetry description for opening in progress media tabs from home
  app/metrics.yaml
Labels: pr:needs-landing

#24863 For #24849 - Add an address editor screen
  app/src/main/java/org/mozilla/fenix/settings/address/AddressEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/address/controller/AddressEditorController.kt
  app/src/main/java/org/mozilla/fenix/settings/address/interactor/AddressEditorInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/res/layout/fragment_address_editor.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/address/AddressEditorViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/address/controller/DefaultAddressEditorControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/address/interactor/DefaultAddressEditorInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragmentTest.kt
Labels: pr:needs-landing

#24912 For #24524 - Refactor FaviconListItem into SyncedTabs
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing, pr:approved

#24928 For #24850 - Display an address list for managing existing addresses
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
  app/src/main/java/org/mozilla/fenix/settings/address/AddressManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/address/controller/AddressManagementController.kt
  app/src/main/java/org/mozilla/fenix/settings/address/interactor/AddressManagementInteractor.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressList.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/address/controller/DefaultAddressManagementControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/address/interactor/DefaultAddressManagementInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragmentTest.kt
Labels: pr:needs-landing, pr:approved

#24953 Issue #24739: Set QR code button to autohide
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#24950 For #24949: Remove malformed message when evaluating it.
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: pr:needs-landing

#24517 History group undo
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/history/PendingDeletionHistory.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragment.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupItemViewHolderTest.kt
Labels: pr:needs-landing

#24962 For #24935: Dismiss keyboard on add address fragment stop.
  app/src/main/java/org/mozilla/fenix/settings/address/AddressEditorFragment.kt
Labels: pr:needs-landing, pr:approved

#24972 Closes #24741: add top padding for download and bookmark fragment
  app/src/main/res/layout/component_bookmark.xml
  app/src/main/res/layout/component_downloads.xml
Labels: pr:needs-landing, pr:approved

#24979 No issue: Additional UI test disabling on API30
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: eng:ui-test

#24986 Revert #24894: settings should not be used to cache previous auth state
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#25000 Disable failing deleteNonEmptyBookmarkFolderTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#25007 For #24707: Remove unused metrics parameter.
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
Labels: pr:needs-landing, pr:approved

#25012 For #24849: Fix saving phone and email values to an address.
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
Labels: pr:needs-landing

#24982 No issue: Renew/Remove metrics set to expire in v102
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing, pr:approved

#25004 For #25003: Pop back stack on main thread.
  app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt
Labels: pr:needs-landing

#25024 Set default browser banner location to homescreen-banner
  nimbus.fml.yaml
Labels: pr:needs-landing

#24868 For #22304 re-enable visitedUrlHistoryTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: pr:needs-landing, eng:ui-test

#25035 Disable redirectToAppPermissionsSystemSettingsTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#25033 For #25032 - Update detekt-baseline file after event.wrapper removal
  detekt-baseline.xml
Labels: pr:needs-landing, pr:approved

#25018 For #25017: Remove promotional wallpapers
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing
