Repository mozilla-mobile/fenix, pull requests merged in 2022-12, with the labels that each got.

#28003 For #26286 dismiss onboarding with page load UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: pr:needs-landing, eng:ui-test

#28050 Update protobuf to version 3.21.10
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#28037 For #27540: Added screen size configuration change handling
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: pr:needs-landing, pr:approved

#28070 No issue: disables openPocketStoryItemTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: pr:needs-landing

#27884 No issue: RTL nav bar UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#28043 For #28042 - Increase lifetime of customize_home.contile to application
  app/metrics.yaml
Labels: pr:needs-landing

#22149 For #8545 - Change home screen recyclerView height to wrap_content
  app/src/main/res/layout/fragment_home.xml
Labels: pr:needs-landing, pr:approved

#28056 For mozilla-mobile#17904 - Increases tap area on the add shortcut button
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: pr:needs-landing, pr:approved

#28012 For #28010 - Update documentation for browser_search_with_ads and browser_search_ad_clicks
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#18869 For #7924: Added an undo snackbar when a pinned site is removed
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
Labels: pr:needs-landing, pr:approved

#28096 Close #27949: Add Nimbus exposure event for re-engagement notification
  app/src/main/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: pr:needs-landing, pr:approved

#28063 Bug 1799996 - Speculative fix checks CFRPopup.anchor is attached to window
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt
Labels: pr:needs-landing, pr:approved

#28099 For #28098 - Disable openPocketDiscoverMoreTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: pr:needs-landing

#28100 Bug 1804107 - Fixed configuration change crash when BrowserFragment UI not initialized
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: pr:needs-landing, pr:approved

#28087 For #15348: Voice search option appears for all search engines
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#28134 For #28133 - Fix Pocket story category color mismatch
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#28088 No issue: refactor verifyLinkFromClipboardNotDisplayedTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28089 For #28069 fix disabled openPocketStoryItemTest UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: pr:needs-landing, eng:ui-test, pr:approved

#28146 For #26286 improve verifySearchEnginesWithRTLLocale UI test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: pr:needs-landing, eng:ui-test

#28054 For #26286 improve firstRunScreenTest UI test coverage
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/util/Strings.kt
Labels: pr:needs-landing, eng:ui-test

#28144 Bug 1804690 - Allow emulator to access network of the host machine
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing

#28171 Update version.txt to 110.0b1
  version.txt
Labels: pr:needs-landing

#28138 Close #28137: Disable run-build tasks on Pull Requests
  .github/workflows/build-contributor-pr.yml
Labels: pr:needs-landing, pr:approved

#28175 For #28174 - Remove all unused strings marked moz:removedIn <= 107
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28168 No issue: Update Cookie banner handling strings
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
Labels: pr:needs-landing

#28162 For #28161- Refactor mozilla-detekt-rules in detekt.yml to the bottom of the file
  config/detekt.yml
Labels: pr:needs-landing, pr:approved

#27262 For #26957 - Exit search dialog when interacting with home fragment
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentLayout.kt
  app/src/main/java/org/mozilla/fenix/home/collections/Collection.kt
  app/src/main/java/org/mozilla/fenix/home/collections/CollectionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/interactor/RecentBookmarksInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/interactor/RecentSyncedTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/interactor/RecentTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsController.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/pocket/DefaultPocketStoriesControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/controller/RecentVisitsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  ktlint-baseline.xml
Labels: pr:approved, pr:needs-landing-squashed

#28180 For #26087 fix disabled tabMediaControlButtonTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28183 For #28165 fix showDefaultHomeScreen screenshot UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28186 No issue: Update add-ons collection.
  app/build.gradle
Labels: pr:needs-landing

#28167 For #26286 new verifyUndoRemoveTopSite UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28189 Bug 1797577 - Clear site data when turning off cookie banner handling.
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerDetailsController.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/DefaultCookieBannerDetailsControllerTest.kt
Labels: pr:needs-landing, needs:review

#28148 Ci for 26733
  app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsStore.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleSettingsStoreTest.kt
Labels: pr:needs-landing

#28196 Issue #27312: Fallback measure for ETP UI tests and re-enabling them
  app/src/androidTest/assets/pages/trackingPage.html
  app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#28206 Closes #28205: fix ripple position over unified search icon
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelector.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
Labels: pr:needs-landing

#28185 For #26087 re-enable UI tests disabled due to tabs tray migration to compose
  app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28095 For #28090: Show QR scanner for general or custom search engine
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#28015 For #28013 - Display correct hint for topic specific search engine
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing, pr:approved

#28024 Bug 1800700 - Add default search suggest header
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28243 Bug 1800611 - Bump relbot to 5.0.2
  .github/workflows/fenix-update-ac.yml
Labels: pr:needs-landing-squashed

#28231 Bug 1804383 - Save as PDF text is missing in Private Mode
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
Labels: pr:needs-landing, pr:approved

#28220 For #28182 fix for verifySearchEnginesWithRTLLocale UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28241 Update MOZILLA_ONLINE_ADDON_EXCLUSIONS
  app/build.gradle
Labels: pr:needs-landing, pr:approved

#28254 Bug 1796319 - Select existing addon settings tab if already opened
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
Labels: pr:needs-landing

#28289 For #28273 - Configure search with the selected search engine before user searching
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogFragmentTest.kt
Labels: pr:needs-landing

#28300 For #28298: Disable deletion of last element in search engines list
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
Labels: pr:needs-landing

#28320 No issue: Fix add-on name check in UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28248 For #28182 fix disabled verifySearchEnginesWithRTLLocale and toggleSearchEnginesShortcutListTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28350 Bug #1807716: Fix for launch crash on Huawei and other devices
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing
