Repository mozilla-mobile/fenix, pull requests merged in 2022-01, with the labels that each got.

#23041 For #23040 - Add hand curated parameters files to `taskgraph/test/params`
  taskcluster/test/params/fork-cron-nightly.yml
  taskcluster/test/params/fork-push.yml
  taskcluster/test/params/fork-release-beta.yml
  taskcluster/test/params/fork-release-production.yml
  taskcluster/test/params/main-repo-cron-nightly.yml
  taskcluster/test/params/main-repo-pull-request.yml
  taskcluster/test/params/main-repo-push.yml
  taskcluster/test/params/main-repo-release-beta.yml
  taskcluster/test/params/main-repo-release-production.yml
Labels: pr:needs-landing

#23042 For #23017 - Ignore ExtraTranslation in our lint-baseline
  app/lint-baseline.xml
  app/lint.xml
Labels: pr:needs-landing

#22886 For #22879: Filter default engines when sending telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/ext/SearchEngine.kt
  app/src/test/java/org/mozilla/fenix/ext/SearchEngineTest.kt
Labels: pr:needs-landing

#22868 No issue: Try out RetryTestRule in SmokeTest UI test class
  app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing-squashed

#23001 For #22995: Address crash when switching languages.
  app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/AddonPermissionsDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/about/AboutLibrariesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
Labels: pr:needs-landing

#22979 For #22978 - Replace @color/foundation_normal_theme with @color/fx_mobile_layer_color_1
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/BrowserMenu.kt
  app/src/main/res/drawable/home_bottom_bar_background.xml
  app/src/main/res/drawable/home_bottom_bar_background_top.xml
  app/src/main/res/layout/button_tip_item.xml
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/values-night-v23/styles.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#22941 For #22851: Adjust theme based on the selected wallpaper.
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing

#23067 Bug 1748687 - remove stale --enable-webrender flag.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#23072 For #23071 - Replace @color/tab_tray_selected_mask_normal_theme with @color/fx_mobile_layer_color_accent_nonopaque
  app/src/main/res/layout/checkbox_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23077 For #23076 - Clean up unneeded FeatureFlags
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: pr:needs-landing

#22976 For #22975 - Replace aboutLink attribute with Text Link color token
  app/src/main/res/layout/fragment_add_on_details.xml
  app/src/main/res/layout/fragment_add_on_permissions.xml
  app/src/main/res/layout/settings_studies.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23080 For #22577: Update work manager version to 2.7.1
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#23050 For #19567 - Change saved logins fragments to SecureFragment
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
Labels: pr:needs-landing, pr:approved

#23093 No issue: Add shared docs/team links to parse-ui-test.py
  automation/taskcluster/androidTest/parse-ui-test.py
Labels: pr:needs-landing

#23103 For #22675 - Replace collection color icon variables with the icon design color tokens
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23109 For #23104: Don't adjust the theme for the default wallpaper.
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing

#22871 For #22869: Renew metrics expiring in January
  app/metrics.yaml
Labels: pr:needs-landing

#23141 For #23142 - Fix license formatting in tests
  app/src/androidTest/java/org/mozilla/fenix/customannotations/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/RecyclerViewIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/ViewVisibilityIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/idlingresource/AddonsInstallingIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/idlingresource/AddonsLoadingIdlingResource.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/matchers/BitmapDrawableMatcher.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/matchers/RecyclerViewItemMatcher.kt
  app/src/androidTest/java/org/mozilla/fenix/perf/SampleBenchmark.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/AccountSettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerAddonDetailedMenuRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  app/src/test/java/org/mozilla/fenix/FenixLogSinkTest.kt
  app/src/test/java/org/mozilla/fenix/components/InflationAwareFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricsUtilsTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/login/LoginExceptionsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/ext/MockKMatcherScope.kt
  app/src/test/java/org/mozilla/fenix/helpers/MockkRetryTestRule.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/library/downloads/DownloadInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/AccountSettingsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/DefaultSyncControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/account/DefaultSyncInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/advanced/LocaleManagerExtensionTest.kt
  app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsStorageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SyncPreferenceViewTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/sync/ext/ErrorTypeKtTest.kt
  app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/PrivateTabsBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/ext/LongKtTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelViewTest.kt
  app/src/test/java/org/mozilla/fenix/whatsnew/WhatsNewTest.kt
  app/src/test/java/org/mozilla/fenix/whatsnew/WhatsNewVersionTest.kt
Labels: pr:needs-landing, pr:approved

#23155 Update version.txt to 98.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#23157 For #23156 - Remove all unused strings marked moz:removedIn <= 95
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23082 For #22559: Update leak canary version to 2.8.1
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#23162 Closes #23150: remove 'threads' feature setup-startup-profiling.py.
  tools/setup-startup-profiling.py
Labels: pr:needs-landing

#22670 Closes #22550: Refactor search term tab grouping logic to rely on middleware
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAutoCloseDialogController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalTabsBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/OtherHeaderBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/PrivateTabsBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroup.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSelectors.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  app/src/test/java/org/mozilla/fenix/ext/BrowserStateTest.kt
  app/src/test/java/org/mozilla/fenix/home/RecentTabsListFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/InactiveTabsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/NormalTabsBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/OtherHeaderBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/PrivateTabsBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabGroupBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/TabSorterTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#22952 For #22383: Propagate ViewTreeLifecycleOwner to composable view holders
  app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt
Labels: pr:needs-landing, pr:approved

#23153 For #21744: Replace InputMethodManager's deprecated toggleSoftInput.
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
Labels: pr:needs-landing, pr:approved

#23180 For #16152 - Add a dark theme for the tabs tray grid view
  app/src/main/res/drawable/tab_tray_grid_item_selected_border.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23179 For #23144 Address regression in COLD start
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing

#23068 For #22851: Add logo animation for wallpapers.
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#23186 Revert "For #22851: Add logo animation for wallpapers."
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#23145 closes #22831: add wallpaper settings screen
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/home_preferences.xml
Labels: pr:needs-landing-squashed

#23105 For #8108 - Add BrowserToolbar option to remove url from TopSites
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/toolbar/DefaultToolbarMenuTest.kt
Labels: pr:needs-landing, pr:approved

#23206 For #23205 - Replace #66FBFBFE with its photon color @color/photonLightGrey05A40
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23210 For #23209 - Replace @color/above_normal_theme with @color/fx_mobile_layer_color_2
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23208 For #23207 - Update the tabs tray FAB color to @color/fx_mobile_layer_color_accent
  app/src/main/res/layout/component_tabstray_fab.xml
Labels: pr:needs-landing

#23192 For #23191 - Replace @color/preference_section_header_normal_theme with @color/fx_mobile_text_color_accent
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23188 For #23187 - Replace @color/notification_accent_color_normal_theme with @color/fx_mobile_text_color_accent
  app/src/main/java/org/mozilla/fenix/downloads/DownloadService.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23204 For #23203 - Replace @color/snackbar_normal_theme with @color/fx_mobile_action_color_primary
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#23196 closes #23220: show snackbar on wallpaper selection
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23241 For #23240 - Replace @color/contrast_text_private_theme with @color/fx_mobile_private_text_color_primary
  app/src/main/res/layout/search_suggestions_hint.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23246 For #23245 - Replace @color/[above|inset]_private_theme with @color/fx_mobile_private_layer_color_1
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23252 For #23251 - Consolidate select credit card and login prompt header styles
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23254 For #23253 - Use photon color variables for @color/scrim[Start|End]_private_theme
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23258 For #23247 - Replace @color/destructive_private_theme with @color/fx_mobile_private_text_color_warning_dark
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23259 For #23248 - Replace @color/menu_item_button_normal_theme with @color/fx_mobile_text_color_accent
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23175 For #21002: improve Manage Downloads smoke tests coverage
  app/src/androidTest/assets/pages/download.html
  app/src/androidTest/assets/resources/tAJwqaWjJsXS8AhzSninBMCfIZbHBGgcc001lx5DIdDwIcfEgQ6vE5Gb5VgAled17DFZ2A7ZDOHA0NpQPHXXFHPSD4wzCkRWiaOorNI574zLtv4Hjiz6O6T7onmUTGgUQ2YQoiQFyrCrPv8ZB9Kvmt.svg
  app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23216 For #23138 - Close recently visited menu on orientation change
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
Labels: pr:needs-landing, pr:approved

#23262 For #23255 - Replace @color/disabled_private_theme with @color/fx_mobile_private_text_color_disabled
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#23271 For #22727 - Add Contile to Top Sites
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/ext/TopSite.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSitesAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapterTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, pr:approved

#23257 Close #23250: Remove duplicate sites within a time period in history
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryDataSource.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryItemTimeGroup.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryDataSourceTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryItemTimeGroupTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupItemViewHolderTest.kt
Labels: pr:needs-landing

#23275 For #23266 - Update the tabs tray multi-select background color to @color/fx_mobile_layer_color_accent
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionHandleBinding.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23274 Close #22956: Define "tags" for metrics in the app repository
  app/metrics.yaml
  app/tags.yaml
  tools/update-glean-tags.py
Labels: pr:needs-landing, pr:approved

#23300 For #23272 - AddLoginFragment use showKeyboard from Components
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
Labels: pr:needs-landing

#23284 For #23283 - Replace @color/accent_on_dark_background_normal_theme with @color/fx_mobile_text_color_accent
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23294 For #23293 - Add @color/fx_mobile_icon_color_primary_inactive and @color/fx_mobile_icon_color_active
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23278 For #23159 - Created setting to turn off the Contile feature
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/checkbox_left_sub_preference.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/home_preferences.xml
Labels: pr:needs-landing

#23273 No issue: Create an asset readme for UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/docs/assets.md
Labels: eng:documentation, pr:needs-landing

#23286 For #23285 - Replace @color/tab_tray_item_url_normal_theme with @color/fx_mobile_text_color_secondary
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23282 For #23281 - Update top sites pager dot to use design system tokens
  app/src/main/res/color/pager_dot.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23288 For #23287 - Replace @color/tab_tray_item_divider_normal_theme with @color/fx_mobile_border_color_default
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23305 For #23304 - Add a setting for enabling Contile
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing

#23290 For #23289 - Update the checkbox background color to @color/fx_mobile_layer_color_accent
  app/src/main/res/layout/checkbox_item.xml
Labels: pr:needs-landing

#23239 Set a minimum number of sites a search group should contain.
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeature.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentvisits/RecentVisitsFeatureTest.kt
Labels: pr:needs-landing

#23299 [UI smoke test] For #21002: Ads app permissions UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23324 For #23323 - Remove addOnPrivateBrowsingInteriorIconBackground attribute
  app/src/main/res/drawable/ic_add_on_private_browsing_label.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23320 For #23319 - Replace mozac_widget_favicon_background_color to @color/fx_mobile_layer_color_2
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23328 [UI smoke test] For #21002: Ads new audio-video permissions test
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23335 No issue: Update PWA package name in mainMenuInstallPWATest
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing

#23334 No issue: Remove showHistorySearchGroups feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: pr:needs-landing

#23331 [UI smoke test] For #21002: Ads UI test for 'Open website' button from Saved logins
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23213 Remove remnants of github-release support
  .taskcluster.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/fenix_taskgraph/parameters.py
  taskcluster/fenix_taskgraph/target_tasks.py
  taskcluster/fenix_taskgraph/transforms/signing.py
Labels: pr:needs-landing

#23166 [UI smoke test] Saved logins in pwa UI smoke test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23343 For #23342 - Replace color values with their photon color equivalent
  app/src/beta/res/values/colors.xml
  app/src/main/res/values/colors.xml
  app/src/release/res/values/colors.xml
Labels: pr:needs-landing

#23352 For #23351 - Refactor collection_icon_colors array into arrays.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23356 For #23355 - Tint mozac_ic_check to white in checkbox_item.xml
  app/src/main/res/layout/checkbox_item.xml
Labels: pr:needs-landing

#23098 For #22851: Load wallpapers dynamically from the assets directory.
  app/src/main/assets/wallpapers/wallpaper_1.png
  app/src/main/assets/wallpapers/wallpaper_2.png
  app/src/main/assets/wallpapers/wallpapers.json
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperStorage.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersAssetsStorage.kt
Labels: pr:needs-landing

#23359 For #22576 - Indicate mutability flag for PendingIntent
  app/lint-baseline.xml
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt
  app/src/main/java/org/mozilla/fenix/components/PrivateShortcutCreateManager.kt
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/utils/IntentUtils.kt
  app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/components/PrivateShortcutCreateManagerTest.kt
Labels: pr:needs-landing-squashed

#23405 fixes #23404: add switch to wallpaper settings to disable tap-to-change
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23410 For #23409 - Specify fetchProvidedTopSites parameter for TopSitesConfig
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#23416 [UI smoke test] Remove hard-coded package string from openAppFromExternalLink
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
Labels: pr:needs-landing, eng:ui-test

#23311 For #22851 Add logo animation for wallpapers
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#23419 [UI smoke test] For #21002: Ads UI test for browsing error pages
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23447 For #23432 - Use the imageUrl as the favicon for a provided top site
  app/src/main/java/org/mozilla/fenix/ext/Client.kt
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountUiView.kt
Labels: pr:needs-landing

#23451 For #23448 - Update the address bar color to use @color/fx_mobile_layer_color_3
  app/src/main/res/drawable/home_search_background.xml
  app/src/main/res/drawable/search_url_background.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23400 First use of Nimbus FML plugin
  .experimenter.json
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/SecurePrefsTelemetry.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/experiments/Experiments.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusFeatures.kt
  app/src/main/java/org/mozilla/fenix/ext/Nimbus.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
  build.gradle
  nimbus.fml.yaml
Labels: needs:review, pr:needs-landing-squashed

#23423 [UI smoke test] External links pwa UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23354 No issue: Update references and doc in parse-ui-test.py
  automation/taskcluster/androidTest/parse-ui-test.py
Labels: pr:needs-landing-squashed

#23453 For #22870: Renew/remove metrics set to expire in February
  app/metrics.yaml
Labels: pr:needs-landing-squashed

#23348 docker: remove tzdata interactive dialog workaround
  taskcluster/docker/base/Dockerfile
Labels: pr:needs-landing

#23497 For #23440,#23441, and #23442 remove adapting themes after switching wallpapers
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:needs-landing

#23427 For #23424 - Add context menu for contile top sites
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemMenu.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
Labels: pr:needs-landing
