Repository mozilla-mobile/fenix, pull requests merged in 2022-02, with the labels that each got.

#23506 For #23426:Changed expiring perf probes to never expire
  app/metrics.yaml
Labels: pr:needs-landing

#23494 For #23433 - Align the provided top sites to the design spec
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/res/layout/top_site_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23523 No issue: quick fix for externalLinkPWATest
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23505 closes #23504: download focus wallpapers at runtime
  .gitignore
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersAssetsStorage.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:needs-landing-squashed

#23525 Issue #12731: Disable TrimMemoryMiddleware on all channels
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:needs-landing

#23499 For #23498 add content description for wallpapers
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#23528 closes #23514: add firefox wallpapers
  app/src/main/assets/wallpapers/wallpaper_1.png
  app/src/main/assets/wallpapers/wallpaper_2.png
  app/src/main/assets/wallpapers/wallpapers.json
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperStorage.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersAssetsStorage.kt
  app/src/main/res/drawable-hdpi/amethyst.png
  app/src/main/res/drawable-hdpi/cerulean.png
  app/src/main/res/drawable-hdpi/sunrise.jpg
  app/src/main/res/drawable-land-hdpi/amethyst.png
  app/src/main/res/drawable-land-hdpi/cerulean.png
  app/src/main/res/drawable-land-hdpi/sunrise.jpg
  app/src/main/res/drawable-land-xhdpi/amethyst.png
  app/src/main/res/drawable-land-xhdpi/cerulean.png
  app/src/main/res/drawable-land-xhdpi/sunrise.jpg
  app/src/main/res/drawable-land-xxhdpi/amethyst.png
  app/src/main/res/drawable-land-xxhdpi/cerulean.png
  app/src/main/res/drawable-land-xxhdpi/sunrise.jpg
  app/src/main/res/drawable-port-xhdpi/amethyst.png
  app/src/main/res/drawable-port-xhdpi/cerulean.png
  app/src/main/res/drawable-port-xhdpi/sunrise.jpg
  app/src/main/res/drawable-port-xxhdpi/amethyst.png
  app/src/main/res/drawable-port-xxhdpi/cerulean.png
  app/src/main/res/drawable-port-xxhdpi/sunrise.jpg
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing, pr:approved

#23169 For #13336: Open bookmarks in current tab
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: pr:needs-landing-squashed

#22588 For #21009 - New Recently closed tabs telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
  app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/test/java/org/mozilla/fenix/library/recentlyclosed/DefaultRecentlyClosedControllerTest.kt
Labels: pr:needs-landing

#23555 For #23554 - Remove Top Sites border
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23560 For #23558 - Update menu copy for What's new and Customize homepage
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23562 For #23498 improve logo content description comments for wallpapers
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23564 For #23563: Address time out crash when downloading wallpaper
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
Labels: pr:needs-landing

#23567 closes #23565: expire remote wallpapers but let users keep selected
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing

#23576 For #23575 - Use design system colors for the Pocket filter and Customize homepage buttons
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt
Labels: pr:needs-landing

#23579 For #23574: Remove stale partial bitmaps created while downloading wallpapers
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
Labels: pr:needs-landing

#23572 CI For #16395 - Improve contrast ratio on Site Permissions subtext
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManagePhoneFeatureFragment.kt
Labels: pr:needs-landing

#23573 Close #10046: Add history search
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarWrapper.kt
  app/src/main/java/org/mozilla/fenix/library/history/toolbar/ToolbarView.kt
  app/src/main/res/layout/fragment_history_search_dialog.xml
  app/src/main/res/menu/history_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistorySearchControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistorySearchDialogInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistorySearchFragmentStoreTest.kt
Labels: pr:needs-landing

#23549 [UI smoke test ]Multiple logins selections UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23578 For #23577: Make description text on the wallpapers settings page align with the start of the switch
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing

#23610 No issue: Update debug app name to Fenix
  app/src/main/res/values/static_strings.xml
Labels: pr:needs-landing, pr:approved

#23487 For #23596 - Add deeplink for wallpaper settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/GlobalDirections.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessorType.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/intent/ExternalDeepLinkIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  app/src/test/java/org/mozilla/fenix/components/IntentProcessorTypeTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/intent/ExternalDeepLinkIntentProcessorTest.kt
Labels: pr:approved

#23621 fixes #23619: use well-defined name for fetching remote wallpaper assets
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing

#23627 Close #23626: Do not exit edit mode in history search toolbar
  app/src/main/java/org/mozilla/fenix/library/history/toolbar/ToolbarView.kt
Labels: pr:needs-landing

#23625 closes #23540: scale wallpaper and translate to bottom of image
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/main/res/layout/fragment_home.xml
Labels: pr:needs-landing

#23634 [UI smoke test] Most viewed top sites UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23556 Fixes #23492: Perf regression of calling isFirefoxDefault from main thread
  .experimenter.json
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing-squashed

#23538 docker: run get-secret.py with python3
  taskcluster/docker/base/Dockerfile
  taskcluster/docker/visual-metrics/Dockerfile
  taskcluster/scripts/get-secret.py
Labels: pr:needs-landing

#23640 Update version.txt to 99.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#23639 Update Android Components version to 98.0.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#23541 For #23526 - Add telemetry for Contile interactions
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing, pr:approved

#23435 For #14954 - Use TabSessionState.id to check if tab is selected
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayStore.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
Labels: pr:needs-landing

#23552 For #14321 - Dismiss search dialog buttons on edit cancel
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
Labels: pr:needs-landing

#23650 [UI smoke test] New browser functionalities in custom tabs UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23642 Remove stale strings for version 96
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#22067 For #21854 - Split the big ComposeView in 3 smaller ones
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketRecommendationsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesController.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
Labels: pr:needs-landing, pr:approved

#23658 No issue: Update history search string
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23656 For #23431 - Display the order of Contile Top Sites correctly
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/ext/TopSite.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/DefaultTopSitesView.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/ext/TopSiteTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#23655 Enable the wallpaper feature
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
Labels: pr:approved

#23680 For #23679 Update the wallpaper settings switch text
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23661 fixes #23644: reload wallpapers on orientation change
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing

#23689 [UI smoke test] For #21002: Adds UI test for Addons in private mode
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23678 For #20634 remove some lint issues from baseline
  app/lint-baseline.xml
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/components/FxaServer.kt
  app/src/main/java/org/mozilla/fenix/components/tips/providers/MasterPasswordTipProvider.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/OnWifiChanged.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/preference_default_browser.xml
  app/src/test/java/org/mozilla/fenix/perf/PerformanceInflaterTest.kt
Labels: pr:needs-landing

#23690 [UI Smoke test] Custom tabs external links and save login UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing, eng:ui-test

#23712 For #23711 - Replace @color/primary_text_normal_theme with @color/fx_mobile_text_color_primary
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMenu.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenu.kt
  app/src/main/res/layout/sync_tabs_error_row.xml
  app/src/main/res/layout/sync_tabs_list_item.xml
  app/src/main/res/layout/tab_group_item.xml
  app/src/main/res/layout/tab_tray_grid_item.xml
  app/src/main/res/layout/tab_tray_item.xml
  app/src/main/res/layout/tab_tray_title_header_item.xml
  app/src/main/res/layout/view_synced_tabs_group.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23714 For #23713 - Replace @color/secondary_text_normal_theme with @color/fx_mobile_text_color_secondary
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionHandleBinding.kt
  app/src/main/res/layout/component_tabhistory.xml
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#23733 For #23731 - Use the disk cache for the Contile top sites
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#23737 For #23341 - Replace @color/disabled_normal_theme with @color/fx_mobile_text_color_disabled
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#23729 closes #23727: Add a fenix.git tag of the current hash to Sentry reports
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
Labels: pr:needs-landing

#23695 Close #23694: Add telemetry for history search
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistorySearchControllerTest.kt
Labels: pr:needs-landing, pr:approved

#23756 Close #23657: Add voice search for history search
  app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#23773 No issue: Update history search string ID
  app/src/main/java/org/mozilla/fenix/library/history/toolbar/ToolbarView.kt
  app/src/main/res/menu/history_menu.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#23767 For #23456 ⁃ Use lifecycleScope in TopSiteItemViewHolder
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitePagerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/perf/StartupReportFullyDrawnTest.kt
Labels: pr:needs-landing

#23038 For #18768 - Update colors for close share layout
  app/src/main/res/drawable/recent_apps_background.xml
  app/src/main/res/layout/account_share_list_item.xml
  app/src/main/res/layout/app_share_list_item.xml
  app/src/main/res/layout/share_close.xml
  app/src/main/res/layout/share_tab_item.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23770 For #23769 - Replace @color/destructive_normal_theme with @color/fx_mobile_text_color_warning
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/res/layout/fragment_credit_card_editor.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23786 No issue: Renew/remove metrics set to expire in April 2022
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: needs:review

#23783 No issue: Renew/remove metrics set to expire in March 2022
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing

#23730 Update Fenix release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: pr:needs-landing-squashed

#23787 For #23752: Address switch is off the screen in the Wallpaper settings.
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Labels: pr:needs-landing, pr:approved

#23784 Create SECURITY.md
  SECURITY.md
Labels: pr:needs-landing, pr:approved

#23788 For #19942 - Add support for sticky headers on the synced tabs list
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedDeviceTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsListItem.kt
  app/src/test/java/org/mozilla/fenix/sync/ext/SyncedDeviceTabsTest.kt
Labels: pr:needs-landing, pr:approved

#23802 No issue: Renew/remove metrics set to expire in April 2022
  app/metrics.yaml
Labels: pr:needs-landing

#23810 For #23808 - Add secret setting for enabling Task Continuity feature
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedDeviceTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/test/java/org/mozilla/fenix/sync/ext/SyncedDeviceTabsTest.kt
Labels: pr:needs-landing, pr:approved

#23877 For #23871 - Update compose to 1.1.0 and kotlin to 1.6.10
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#23887 For #23886 - Use @color/fx_mobile_icon_color_active for tabIndicatorColor
  app/src/main/res/layout/component_tabstray2.xml
Labels: pr:needs-landing

#23851 For #23850 - Replace @color/neutral_text with @color/fx_mobile_[icon|text]_color_oncolor
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/component_collection_creation_name_collection.xml
  app/src/main/res/layout/component_collection_creation_select_collection.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23883 For #23882 - Use textAccent attribute for Smartblock Learn More link
  app/src/main/res/layout/component_tracking_protection_panel.xml
Labels: pr:needs-landing

#23840 For #23839 - Replace @color/contrast_text_normal_theme with @color/fx_mobile_[text|icon]_color_oncolor
  app/src/main/res/layout/component_tabstray2.xml
  app/src/main/res/layout/tabstray_multiselect_items.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23070 for #23069: add blocklist middleware for home
  app/src/main/java/org/mozilla/fenix/ext/HomeFragmentState.kt
  app/src/main/java/org/mozilla/fenix/ext/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistHandler.kt
  app/src/main/java/org/mozilla/fenix/home/blocklist/BlocklistMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/interactor/RecentBookmarksInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksMenuItem.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/interactor/RecentTabInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabMenuItem.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/ext/RecentTabsTest.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistHandlerTest.kt
  app/src/test/java/org/mozilla/fenix/home/blocklist/BlocklistMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
Labels: pr:needs-landing

#23906 For #23829 - Update private theme design token based on the latest UX changes
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23903 For #23902 - Update the top sites pinned icon color to @color/fx_mobile_icon_color_primary
  app/src/main/res/drawable/ic_new_pin.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23897 Revert "For #13336: Open bookmarks in current tab"
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: pr:needs-landing

#23901 For #23900 - Update search widget colours to use design tokens
  app/src/main/res/drawable/ic_microphone_widget.xml
  app/src/main/res/drawable/rounded_search_widget_background.xml
  app/src/main/res/layout/search_widget_large.xml
  app/src/main/res/layout/search_widget_medium.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23926 For #23925 - Update tab counter and reader mode colors to use the design system
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing, pr:approved

#23939 Revert "For #14321 - Dismiss search dialog buttons on edit cancel"
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
Labels: pr:needs-landing

#23913 closes #23912: remove sentry reporting from WallpaperDownloader
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
Labels: pr:needs-landing

#23942 Update Android Components version to 99.0.20220223143136.
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#23920 For #23919 - Replace tabRing attribute with accent
  app/src/main/res/drawable/session_border.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23918 For #23888 - Replace @color/white_color with @color/fx_mobile_[icon|text]_color_oncolor
  app/src/main/java/org/mozilla/fenix/ext/TabCollection.kt
  app/src/main/java/org/mozilla/fenix/library/LibraryPageView.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationProgressActivity.kt
  app/src/main/res/layout/activity_migration.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/menu/bookmarks_select_multi.xml
  app/src/main/res/menu/bookmarks_select_multi_not_item.xml
  app/src/main/res/menu/history_select_multi.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/org/mozilla/fenix/ext/TabCollectionTest.kt
Labels: pr:needs-landing

#23917 For #23907 - Replace tabTrayItemMediaBackground attribute with accent
  app/src/main/res/drawable/media_state_background.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23916 For #23905 - Update onboarding icons to use Icon Active color
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingIcon.kt
  app/src/main/res/drawable/ic_onboarding_avatar_anonymous_large.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23922 For #23921 - Remove unused attributes in attrs.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23805 Close #23804: Use version instead of date for telemetry/metrics expiration
  app/build.gradle
  app/metrics.yaml
  buildSrc/src/main/java/Config.kt
Labels: pr:needs-landing

#23781 For #23738 - Integrate the Contile top sites updater
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:needs-landing

#23948 For #23947 - Inline @color/toolbar_menu_transparent
  app/src/main/res/layout/survey_inactive_tabs_disable.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23950 For #23949 - Use @color/fx_mobile_private_layer_color_4 for the toolbar gradient in the private theme
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23946 Close #13336: Open bookmark in current tab if browsing mode is not private or previous fragment is not home
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
Labels: pr:needs-landing, pr:approved

#23952 For #23951 - Replace @color/toolbar_divider_color_private_theme with @color/fx_mobile_private_border_color_divider
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23974 No issue: remove 'mozilla-mobile/releng' as CODEOWNER of /automation …
  .github/CODEOWNERS
Labels: pr:needs-landing

#23976 For #23975 - Replace tooltip gradient with Layer Gradient Start, End design tokens
  app/src/main/res/drawable/cfr_background_gradient.xml
  app/src/main/res/drawable/onboarding_popup_shape.xml
  app/src/main/res/layout/onboarding_inactive_tabs_cfr.xml
  app/src/main/res/layout/onboarding_jump_back_in_cfr.xml
  app/src/main/res/layout/pbm_shortcut_popup.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#23908 Close #23894: Simplify distinct history algorithm
  app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
Labels: pr:needs-landing

#23909 For #23821 - Add telemtry for RecentlyVisted Homepage
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
Labels: pr:needs-landing

#23982 fixes #23981: open download function and override for test
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/test/java/org/mozilla/fenix/helpers/FenixRobolectricTestApplication.kt
Labels: pr:needs-landing

#24023 For #24022 - Use Border Primary color for Inactive Tabs border
  app/src/main/res/layout/inactive_footer_item.xml
  app/src/main/res/layout/inactive_header_item.xml
  app/src/main/res/layout/inactive_tab_list_item.xml
  app/src/main/res/layout/inactive_tabs_auto_close.xml
Labels: needs:review

#24018 For #24017 - Replace @color/foundation_private_theme with @color/fx_mobile_private_layer_color_1
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#24025 Disable rememberAllowAudioVideoPermissionChoiceTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: pr:needs-landing, eng:ui-test

#24007 For #24006 - Return a null change payload if the new top sites list is larger than the old
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapterTest.kt
Labels: pr:needs-landing

#23994 For #23991 - Fix synced tabs error text mapping
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt
Labels: pr:needs-landing, pr:approved

#23899 For #23238 - Refactor synced tabs sections to be collapsible
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved
