Repository mozilla-mobile/fenix, pull requests merged in 2022-11, with the labels that each got.

#27624 For #26934 fix showDefaultHomeScreen screenshot test
  app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27493 For #27450 Fix Crash from Navigation action/destination org.mozilla.firefox:id/action_savedLoginsAuthFragment_to_loginsListFragment
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
Labels: pr:needs-landing, pr:approved

#27623 For #25811 - Add header to unified search engine menu
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenu.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenuTest.kt
Labels: pr:needs-landing, pr:approved

#27637 For #10344 - Enable tab reordering in beta/release
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: pr:needs-landing

#27628 For #27627 - Check the TCP CFR status lazily
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved

#27600 For #27579 - Fix broken previews for MessageCard
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
Labels: pr:needs-landing, pr:approved

#27556 For #27331 - Add migration for Turning Red wallpaper card colors
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperMigration.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#27577 Close #27023: Add capability to override telemetry URL
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/ext/Configuration.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/test/java/org/mozilla/fenix/ext/ConfigurationKtTest.kt
Labels: pr:needs-landing

#27525 Bug 1796482 - Report save to PDF errors.
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#27625 For #25813 - Use specific hint for history, bookmarks and tab unified search
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#27645 Issue #27522: Search groups tests refactoring
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27639 For #27522 new search codes UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: pr:needs-landing, eng:ui-test

#27665 Closes #27652: Fix A-C auto publish docs in README
  README.md
Labels: pr:needs-landing

#27666 For #27635 - New telemetry for Save to PDF failures
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
Labels: pr:needs-landing

#27531 Update Adjust to version 4.33.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27651 For #27578 - Add optional color parameters to MessageCard
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
Labels: pr:needs-landing

#27597 For #25814 - Hide "Show search engines" toggle from search settings when unified search is enabled
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: pr:needs-landing

#27675 Bug 1795105: Remove usages of ContentState.thumbnail
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: pr:needs-landing, pr:approved

#27596 For #27472 - Added telemetry data points for the Google Play Store review prompts
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/ReviewPromptController.kt
  app/src/test/java/org/mozilla/fenix/components/ReviewPromptControllerTest.kt
Labels: pr:needs-landing

#27687 For #27220 disable failing manageDownloadsInDownloadsMenuTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: pr:needs-landing, eng:ui-test

#27689 Close #7227: Re-enable storage maintenance call.
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
Labels: pr:needs-landing

#27672 For #27671 - Search metrics will now be sent in baseline ping
  app/metrics.yaml
Labels: pr:needs-landing-squashed

#27692 For #27691 - Replace 'Pocket' word in all strings with placeholder
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/res/values/static_strings.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27677 For #27468 - Backplate homepage MessageCard
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
Labels: pr:needs-landing, pr:approved

#27678 For #27469 - Update no collections button colors when a wallpaper is selected
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
Labels: pr:needs-landing, pr:approved

#27682 For #27252 - Update a11y services label for private browsing myths button
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27703 For #27667 - Update the commit sha in .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: pr:needs-landing

#27684 For #26710 fix flaky deleteCookiesTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#27705 Bug 1793823 - Disable perf tests running on P2.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#27505 For #27511: Remove duplicate padding update code
  app/src/main/java/org/mozilla/fenix/utils/Undo.kt
Labels: pr:needs-landing

#27706 For #27392 fix flaky verifyAboutFirefoxPreview UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27748 Close #27023: Add capability to override telemetry URL using local properties
  README.md
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/ext/Configuration.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
Labels: pr:needs-landing

#27760 Issue #27759: Add link to storageMaintenance flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#27755 For #27522: Re-enabled and added search group UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27771 CI For #27715: Allow FirefoxColors.copy to override some values
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  detekt-baseline.xml
Labels: pr:needs-landing

#27770 CI For #27734: Make tab tray overflow menu background layer2
  app/src/main/java/org/mozilla/fenix/tabstray/ext/BrowserMenu.kt
Labels: pr:needs-landing

#27756 For #27714 fix disabled sponsored shortcut UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#27668 No issue: Make the Startup profiling hints clearer.
  tools/setup-startup-profiling.py
Labels: pr:needs-landing, pr:approved

#27550 For #27549 - Collect shim data about the Pocket sponsored stories.
  app/metrics.yaml
  app/pings.yaml
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesController.kt
  app/src/test/java/org/mozilla/fenix/home/pocket/DefaultPocketStoriesControllerTest.kt
Labels: pr:needs-landing

#27800 For #27799: Upgrade AndroidX Test Dependencies
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27423 No issue: Remove deprecated gradle property
  gradle.properties
Labels: pr:needs-landing

#27809 Update leakcanary to version 2.10
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27830 Update version.txt to 109.0b1
  version.txt
Labels: pr:needs-landing

#27647 Closes #25809: tapping on search engine triggers engine selection
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelector.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorInteractor.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenu.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/search_selector.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing, pr:approved

#27554 For #26475 - Remove unnecessary features flags
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingFeature.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/home_preferences.xml
  app/src/main/res/xml/tabs_preferences.xml
Labels: pr:needs-landing, pr:approved

#27797 Close #27795: Add metrics ping to see if user allows notifications
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
Labels: pr:needs-landing

#27833 Remove all unused strings marked moz:removedIn <= 106
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#27670 For #27538: Avoid extra processing of large text from clipboard
  app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
Labels: pr:needs-landing, pr:approved

#27561 Bug 1796146 - Add UI for the Cookie Banner preferences
  .experimenter.yaml
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/cookie_banner_preferences.xml
  app/src/main/res/xml/preferences.xml
  nimbus.fml.yaml
Labels: pr:needs-landing, needs:review

#27776 Bug 1799910 - Migrate fenix from AWS to GCP
  .taskcluster.yml
  taskcluster/ci/config.yml
Labels: eng:automation

#27850 Close #26475: Remove more feature flags
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/home_preferences.xml
Labels: pr:needs-landing

#27838 Close #27836 : Add distribution_id in baseline ping
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#27841 For #27220: replaces manually deleting a file with deleting storage programmatically
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: pr:needs-landing, eng:ui-test

#27843 For #26826 - Add test tags allowing to differentiate Pocket stories
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#27842 For #27801 - Updated new search string
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenu.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenuTest.kt
Labels: pr:needs-landing, pr:approved

#27869 For #27865: Re-enable UI media notification tests.
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing

#27370 For #27346 - Disable swiping to switch tabs when fullscreen
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/browser/SwipeGestureLayout.kt
Labels: pr:needs-landing, pr:approved

#27878 For #27704: Disable search group tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: pr:needs-landing, eng:ui-test

#27853 For #27852 - Set BrowsingMode to Normal when selecting a wallpaper
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: pr:needs-landing, pr:approved

#27650 For #26320: Reorganize Nimbus Startup
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/fenix/helpers/FenixRobolectricTestApplication.kt
Labels: pr:needs-landing

#27920 For #27885 - Change default browser notification delay to 72 hours
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
Labels: pr:needs-landing

#27264 For #27228 - Resume qr scanning if camera permission is changed
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing

#27930 Bug 1796146 - Update l10n descriptions for Cookie Banner protection
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#27927 Close #26320: Make Nimbus first-startup comments clear in FenixApplication
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing

#27889 Closes #27854: Remove unnecessary Theme.getTheme() calls from FirefoxTheme usages
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
  app/src/main/java/org/mozilla/fenix/compose/StaggeredHorizontalGrid.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  app/src/main/java/org/mozilla/fenix/compose/button/TextButton.kt
  app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/MediaImage.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  app/src/main/java/org/mozilla/fenix/home/collections/CollectionItem.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketRecommendationsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressList.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/theme/FenixTypography.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperOnboarding.kt
Labels: pr:needs-landing, pr:approved

#27937 Closes #27290 - Refactor DefaultLoadBitmapUseCase to receive orientation and files directory as argument
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
Labels: pr:needs-landing

#27939 Closes #27288: Remove glean test rule and Android test runner from WallpaperUseCasesTest
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: pr:needs-landing

#27953 Use blank string instead of empty string for version name fallback in release variants.
  buildSrc/src/main/java/Config.kt
Labels: pr:needs-landing

#27956 Disable cookie banner handling by default.
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/cookie_banner_preferences.xml
  nimbus.fml.yaml
Labels: needs:review

#27952 For #27950: add first week days of use growth data
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsStorage.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/components/metrics/DefaultMetricsStorageTest.kt
Labels: pr:needs-landing

#27903 Update Sentry to version 6.8.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#27943 No issue: Adding new start on homepage setting UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
Labels: pr:needs-landing, eng:ui-test

#27551 For #27536: Update Jetpack Compose to latest version.
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, pr:approved

#27967 For #27966 disable verifySponsoredShortcutsSponsorsAndPrivacyOptionTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
Labels: pr:needs-landing, eng:ui-test

#27951 Use NimbusBuilder from AppServices/AndroidComponents
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: pr:needs-landing

#27958 For #26633: Add post notifications permission.
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing, pr:approved

#27921 For #27896 - Match share sheet header style with the rest
  app/src/main/res/layout/share_to_account_devices.xml
Labels: pr:needs-landing, pr:approved

#27480 For #26708 - Add search widget preview for nightly
  app/src/nightly/res/drawable-hdpi/fenix_search_widget.png
Labels: pr:needs-landing, pr:approved, ux:replied

#27977 Update Taskgraph to version 3.7.0
  taskcluster/requirements.txt
Labels: pr:needs-landing

#28022 Close #28021: Add ability to opt in to receiving push notifications on Android 13+ devices
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing
