Repository mozilla-mobile/fenix, pull requests merged in 2022-03, with the labels that each got.

#24028 Revert "For #23871 - Update compose to 1.1.0 and kotlin to 1.6.10"
  app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataMiddleware.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SearchTermTabGroupMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#23859 For #21743: Use InetAddresses isNumericAddress to validate Ipv4 and Ipv6 for SDK>=29.
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/test/java/org/mozilla/fenix/ext/StringTest.kt
Labels: performance, pr:needs-landing, eng:perf-impact, pr:approved

#23985 For #23936 - Show dialog on credit card delete
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/creditcards/controller/CreditCardEditorController.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/creditcards/DefaultCreditCardEditorControllerTest.kt
Labels: pr:needs-landing, pr:approved

#24041 For #22189: Replace placeholder with app name.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
Labels: pr:needs-landing, pr:approved

#24043 For #24042- Remove inactive tabs survey
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/survey_inactive_tabs_disable.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#24049 Add remote wallpapers
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/Wallpaper.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperFileManagerTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing

#24046 For #23388 - Update scrim to match design system
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/drawable/scrim_background.xml
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/component_collection_creation_name_collection.xml
  app/src/main/res/layout/component_collection_creation_select_collection.xml
  app/src/main/res/layout/fragment_create_collection.xml
  app/src/main/res/layout/fragment_create_shortcut.xml
  app/src/main/res/layout/fragment_onboarding_home_dialog.xml
  app/src/main/res/layout/fragment_pwa_onboarding.xml
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#24052 For #24051 - Remove showStartOnHomeSettings feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/home_preferences.xml
Labels: pr:needs-landing

#23992 No issue: Add telemetry data renewal helper
  tools/data_renewal_generate.py
Labels: pr:needs-landing

#24068 For #24066 - Use secondary text color for the No Collections description
  app/src/main/res/layout/no_collections_message.xml
Labels: pr:needs-landing

#24070 For #24069 - Use the correct design tokens for Powered by Pocket text
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing

#23964 For #23399: Add tabs tray multi-select telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
Labels: pr:needs-landing

#23945 For #23893 - Add telemetry for Contile services
  app/metrics.yaml
  app/pings.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesAdapter.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
Labels: pr:needs-landing

#24081 For #24080 - Use layer accent non opaque for the tabs tray and history selected background color
  app/src/main/java/org/mozilla/fenix/tabhistory/TabHistoryViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabViewHolder.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#23996 For #23990 - Allow for Nimbus experimentation for Contile top sites
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#24150 Update Android Components version to 99.0.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#24153 Update version.txt to 100.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#24157 For #24156 - Remove all unused strings marked moz:removedIn <= 97
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24192 Update minidump-stackwalk artifact name
  taskcluster/ci/toolchain/gecko-derived.yml
Labels: pr:needs-landing

#24027 For #23415 - Add support for GeckoView Screen Orientation APIs
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#24176 For #23219 - Add favicons to synced tabs list
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing, pr:approved

#24218 For #24130 - Change Shortcuts setting to toggle the display of Top Sites
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/home_preferences.xml
  app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: pr:needs-landing

#24180 For #23697: Avoid NPEs while pasting URLs from the clipboard
  app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Labels: pr:needs-landing

#24173 Close #14313: Always add copy to clipboard action in share actions
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  app/src/main/java/org/mozilla/fenix/share/ShareViewModel.kt
  app/src/main/res/drawable/ic_share_clipboard.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/share/ShareViewModelTest.kt
Labels: pr:needs-landing

#24239 No issue - Add license to ic_share_clipboard.xml
  app/src/main/res/drawable/ic_share_clipboard.xml
Labels: pr:needs-landing

#24060 For #23719 - Replace preference framework strings with string resources
  app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsExceptionsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24200 Fixes #24188 - Use app_name for InactiveTabAutoClose message
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
Labels: pr:needs-landing, pr:approved

#24250 For #24249 - Use Border Primary for Dividers
  app/src/main/res/layout/add_new_collection_dialog.xml
  app/src/main/res/layout/component_tracking_protection_panel.xml
  app/src/main/res/layout/fragment_history_search_dialog.xml
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
  app/src/main/res/layout/fragment_search_dialog.xml
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/layout/library_separator.xml
  app/src/main/res/layout/onboarding_theme_picker.xml
  app/src/main/res/layout/preference_widget_radiobutton_with_info.xml
Labels: pr:needs-landing

#24243 For #24242 - Update EditText background tint to use Border Primary
  app/src/main/res/layout/fragment_create_shortcut.xml
  app/src/main/res/layout/name_collection_dialog.xml
  app/src/main/res/layout/top_sites_rename_dialog.xml
Labels: pr:needs-landing

#24268 no issue: update layer3 dark pallete color to match token
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing

#24247 For #24246 - Refactor Tab from HomeFragmentStore
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationController.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationInteractor.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationStore.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/collections/SaveCollectionListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/Tab.kt
  app/src/main/java/org/mozilla/fenix/collections/TabDiffUtil.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragmentStore.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationBottomBarViewTest.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationStoreTest.kt
  app/src/test/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/collections/DefaultCollectionCreationControllerTest.kt
  app/src/test/java/org/mozilla/fenix/collections/TabDiffUtilTest.kt
Labels: pr:needs-landing, pr:approved

#24230 For #24219 - Refactor Favicon to fix previews
  app/src/main/java/org/mozilla/fenix/compose/ComposeUtils.kt
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
Labels: pr:needs-landing, pr:approved

#24270 For #24264 - Enable Contile feature for Nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#24272 closes #24194: switch to IO dispatcher when cleaning wallpapers
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperFileManager.kt
Labels: pr:needs-landing, pr:approved

#24261 For #24187 - Avoid creating multiple inactive CFR dialogs
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInactiveTabsOnboardingBinding.kt
Labels: pr:needs-landing, pr:approved

#24283 For #23716: Disables mediaSystemNotificationInPrivateModeTest
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
Labels: pr:needs-landing, eng:intermittent-test, eng:ui-test

#24221 for #24177: add ui wireframe for synced recent tab
  app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24104 Close #12717: Add bookmark search
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchController.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchDialogInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/awesomebar/AwesomeBarInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/awesomebar/AwesomeBarWrapper.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/toolbar/ToolbarView.kt
  app/src/main/res/layout/fragment_bookmark_search_dialog.xml
  app/src/main/res/menu/bookmarks_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchDialogInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkSearchFragmentStoreTest.kt
Labels: pr:needs-landing, pr:approved

#24288 For #24286 - Create new test for synced tabs error mapping
  app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedTabsViewErrorType.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt
  app/src/test/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsViewErrorTypeTest.kt
Labels: pr:needs-landing, pr:approved

#24290 closes #24289: wrap filesDir access in runBlockingIncrement
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
Labels: pr:needs-landing, pr:approved

#24310 CI for #24296
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing

#24322 no issue: update accessibility comment for device icon
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24323 closes #24306: add nav argument to open tabs tray to an initial page
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: pr:needs-landing

#24317 Closes #24305: Remove false wallpaper NPE Sentry report
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
Labels: pr:needs-landing

#24360 For #24342 - Actually log when Pocket stories are shown
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
Labels: pr:needs-landing

#24232 RELENG-805 - Pull taskgraph from pypi
  .taskcluster.yml
  taskcluster/fenix_taskgraph/__init__.py
  taskcluster/fenix_taskgraph/gradle.py
  taskcluster/fenix_taskgraph/job.py
  taskcluster/fenix_taskgraph/loader/__init__.py
  taskcluster/fenix_taskgraph/loader/multi_dep.py
  taskcluster/fenix_taskgraph/parameters.py
  taskcluster/fenix_taskgraph/release_promotion.py
  taskcluster/fenix_taskgraph/routes.py
  taskcluster/fenix_taskgraph/target_tasks.py
  taskcluster/fenix_taskgraph/transforms/beetmover.py
  taskcluster/fenix_taskgraph/transforms/browsertime.py
  taskcluster/fenix_taskgraph/transforms/build.py
  taskcluster/fenix_taskgraph/transforms/github_release.py
  taskcluster/fenix_taskgraph/transforms/mark_as_shipped.py
  taskcluster/fenix_taskgraph/transforms/multi_dep.py
  taskcluster/fenix_taskgraph/transforms/notify.py
  taskcluster/fenix_taskgraph/transforms/push_apk.py
  taskcluster/fenix_taskgraph/transforms/secrets.py
  taskcluster/fenix_taskgraph/transforms/signing.py
  taskcluster/fenix_taskgraph/transforms/test.py
  taskcluster/fenix_taskgraph/transforms/version_bump.py
  taskcluster/fenix_taskgraph/transforms/visual_metrics.py
  taskcluster/fenix_taskgraph/util/scriptworker.py
  taskcluster/fenix_taskgraph/worker_types.py
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: pr:needs-landing

#24370 Bug 1760699 - Fix proxy on run-task jobs
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing

#24368 closes #24366: reset strict mode after locale read
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#24335 For #24334 - Add FeatureFlag for Unified Search feature
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing

#24388 For #24377: Disables verifyRenameTopSite UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
Labels: pr:needs-landing, eng:ui-test

#24392 Bug 1760699 - Revert proxy settings on browsertime task
  taskcluster/ci/browsertime/kind.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: pr:needs-landing

#24390 No issue: Update .experimenter.json
  .experimenter.json
Labels: pr:needs-landing

#24424 Closes #24407: Allow query parameters in AMO installation URLs
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
Labels: pr:needs-landing

#24343 For #24337 - Make a reusable section header for lists in Compose
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
Labels: pr:needs-landing

#24417 Close #24414: Enable Clear Site Data
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#24463 For #24394 - Replace custom synced tabs header with new generic header
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing, pr:approved

#23955 For #23503: Respect studies and telemetry prefs when manually opting in to studies
  app/src/main/java/org/mozilla/fenix/nimbus/NimbusBranchesFragment.kt
  app/src/main/java/org/mozilla/fenix/nimbus/controller/NimbusBranchesController.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/nimbus/NimbusBranchesControllerTest.kt
Labels: pr:needs-landing-squashed

#24225 For #24220 and #24223: Connect Gleanplum messages with the new tab ui card
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/DefaultMessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/KeyPairMessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/Message.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingFeature.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingState.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingReducer.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/ExperimentDefaultBrowserCardViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/nimbus_message_card.xml
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/MessagingFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingReducerTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#23651 Issue #22489: Remove "Fennec to Fenix" migration code
  app/build.gradle
  app/lint-baseline.xml
  app/sampledata/migration_items
  app/src/beta/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessorType.kt
  app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationProgressActivity.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationStatusAdapter.kt
  app/src/main/java/org/mozilla/fenix/migration/MigrationTelemetryListener.kt
  app/src/main/res/anim/placeholder_animation.xml
  app/src/main/res/drawable/button_background_grey.xml
  app/src/main/res/drawable/migration_button_background.xml
  app/src/main/res/layout/activity_migration.xml
  app/src/main/res/layout/migration_list_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/migration/AndroidManifest.xml
  app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt
  app/src/migration/java/org/mozilla/fenix/MigrationDecisionActivity.kt
  app/src/migration/java/org/mozilla/fenix/MigrationPushRenewer.kt
  app/src/migration/java/org/mozilla/fenix/MigrationService.kt
  app/src/release/AndroidManifest.xml
  app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationStatusAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/migration/MigrationTelemetryListenerTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing, needs:review

#24479 For #20418 and #24436 disable failing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
Labels: pr:needs-landing, eng:ui-test

#24426 For #24224: Send telemetry events related to messaging framework
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/DefaultMessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/MessagingFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: pr:needs-landing

#24443 closes #24442: refactor recent tabs to use common composables
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: pr:needs-landing, pr:approved

#24487 For #24486: change perf telemetry expiration email.
  app/metrics.yaml
Labels: pr:needs-landing

#24466 For #24391 - Add a customizable child Composable to the list header
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
Labels: pr:needs-landing

#23112 For #23046 - Align detekt config between Fenix and Android Components
  .experimenter.json
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/FenixLogSink.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationBottomBarView.kt
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  app/src/main/java/org/mozilla/fenix/components/AccountAbnormalities.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialogBehavior.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/shortcut/NewTabShortcutIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/fenix/components/AccountAbnormalitiesTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  config/detekt.yml
  detekt-baseline.xml
Labels: pr:needs-landing

#24328 For #24203 - Remove Event.wrapper for Onboarding telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingThemePickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingToolbarPositionPickerViewHolderTest.kt
Labels: pr:needs-landing

#24400 For #24212 - Remove Event.wrapper for Preferences metrics
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/studies/StudiesView.kt
  app/src/test/java/org/mozilla/fenix/settings/studies/StudiesViewTest.kt
Labels: pr:needs-landing

#24496 For #24381 disable failing firstRunScreenTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#24330 For #24204 - Remove Event.wrapper for Search_shortcuts telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: pr:needs-landing

#24409 No issue: Renew/remove metrics set to expire in v101
  app/metrics.yaml
Labels: pr:needs-landing

#24202 For #23337 - Customize the https-only mode error page
  app/src/main/assets/lowMediumErrorPages.js
  app/src/main/assets/low_and_medium_risk_error_pages.html
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#24491 For #24490 - Remove index selectors in UI tests.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing

#24473 For #24222: Persist user interactions with nimbus messages
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/KeyPairMessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/Message.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/OnDiskMessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/OnDiskMessageMetadataStorageTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Labels: pr:needs-landing

#24364 For #24207 - Remove Event.wrapper for ToolbarSettings telemetry
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
Labels: pr:needs-landing

#24451 For #24450 - Remove Event.wrapper for ErrorPage metrics
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
  app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
Labels: pr:needs-landing

#24527 For #24519 - Add Private theme to FirefoxTheme
  app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/SelectableChip.kt
  app/src/main/java/org/mozilla/fenix/compose/StaggeredHorizontalGrid.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitle.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/TabTitle.kt
  app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
  app/src/main/java/org/mozilla/fenix/compose/list/HomeSectionHeader.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketRecommendationsHeaderViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: pr:needs-landing

#24535 Disable failing deleteCollectionTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#24521 For #24331 - Support for opening new tabs when requested by service workers
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#24484 For #23971 - Migrate CollectionHeaderViewHolder to Compose
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt
  app/src/main/res/layout/collection_header.xml
  app/src/main/res/layout/fragment_home.xml
Labels: pr:needs-landing, pr:approved

#24547 CI For #22308 - Changed constraint of tab tray overflow
  app/src/main/res/layout/component_tabstray2.xml
Labels: pr:needs-landing
