Repository mozilla-mobile/fenix, pull requests merged in 2022-06, with the labels that each got.

#25466 For #25394 disable failing blockUnwantedSoftwarePageTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
Labels: pr:needs-landing, eng:ui-test

#25320 For #24304: update StartupExcessiveResourceUseTest documentation
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
Labels: pr:needs-landing, pr:approved

#25473 For #25472 - Set `context_id` to have "application" lifetime.
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#25499 For #15754: Replace UI tests video asset for video with sound
  app/src/androidTest/assets/pages/videoMediaPage.html
  app/src/androidTest/assets/resources/clip.mp4
  app/src/androidTest/assets/resources/videoSample.webm
  app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
Labels: pr:needs-landing, eng:ui-test

#25496 For #25394 and #25380 re-enable BrowsingErrorPages UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
Labels: pr:needs-landing, eng:ui-test

#25503 For #20848 - Hide Download List delete icon in multiselect mode
  app/src/main/java/org/mozilla/fenix/library/downloads/DownloadAdapter.kt
  app/src/main/java/org/mozilla/fenix/library/downloads/viewholders/DownloadsListItemViewHolder.kt
Labels: pr:needs-landing

#25519 Revert "For #24455 - Migrate NoCollectionsMessageViewHolder to Compose"
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/compose/CollectionsPlaceholder.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
  app/src/main/res/drawable/empty_session_control_background.xml
  app/src/main/res/layout/no_collections_message.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolderTest.kt
Labels: pr:needs-landing

#25513 For #25393 fix flaky verifyAboutFirefoxPreview UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
Labels: pr:needs-landing, eng:ui-test

#25458 For #25125 fix flaky downloadMultipleFileTypesTest UI test
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25540 Run the CI tasks for https://github.com/mozilla-mobile/fenix/pull/25457
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: pr:needs-landing

#25494 For #21102: Build with SDK for Android 12 / API 31
  app/src/main/AndroidManifest.xml
  app/src/nightly/AndroidManifest.xml
  buildSrc/src/main/java/Config.kt
Labels: pr:needs-landing-squashed

#25544 Issue #24522: Add telemetry for unified search
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing, pr:approved

#25517 For #24744 - Observe and update selector icon while the View is attached
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing

#25571 for #25545: turn off task continuity in nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#25382 For #25381 - Add a setting allowing to toggle Pocket sponsored stories
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/home_preferences.xml
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/settings/HomeSettingsFragmentTest.kt
Labels: pr:needs-landing

#25605 For #25490 - Remove PrimaryText and SecondaryText
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/Text.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing, pr:approved

#25587 For #25586 - Update HTTPs-only setting sumo link
  app/src/main/java/org/mozilla/fenix/settings/HttpsOnlyFragment.kt
Labels: pr:needs-landing

#25604 Upgrade gradle to 7.3.
  buildSrc/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: pr:needs-landing

#25616 No issue - Update .experimenter.yaml
  .experimenter.yaml
Labels: pr:needs-landing

#25227 For #24969 - Display address autofill prompt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing, pr:approved

#25512 For #24092 and #25077 fix flaky emailLinkPWATest and telephoneLinkPWATest UI tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25447 For #25446: Ensure for every message shown we have recordExposure
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/DefaultMessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: pr:needs-landing

#25488 Adding support for app-services error reporting
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#25633 For #25586 - Allow for localized sumo links for the https-only mode
  app/src/main/java/org/mozilla/fenix/settings/HttpsOnlyFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
Labels: pr:needs-landing

#25634 stop triggering multiple nightlies off the same revision
  .taskcluster.yml
  taskcluster/fenix_taskgraph/target_tasks.py
  taskcluster/requirements.in
Labels: pr:needs-landing

#25323 For #25183 - Update the Sentry base URL
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
Labels: pr:needs-landing, pr:approved

#25632 For #25511 fix failing shortcutButtonTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25694 For #25551 and #25355 disable failing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: pr:needs-landing, eng:ui-test

#25531 For #23966 - Migrate MessageCardViewHolder to Compose
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
  app/src/main/res/layout/nimbus_message_card.xml
Labels: pr:needs-landing, pr:approved

#25650 Issue #24740: Use unified search bar in history search
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
Labels: pr:needs-landing, pr:approved

#25695 For #25435: Hide accept button just for HSTS error page.
  app/src/main/assets/lowMediumErrorPages.js
Labels: pr:needs-landing

#25717 For #25708 - Change Credit Card preference label to Autofill when address autofill is enabled
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: pr:needs-landing

#25743 For #25726 and #25345 disable failing UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#25731 For #25726 fix failing testStrictVisitSheetDetails UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25732 For #25721 - Remove 'Daylight' from the 'About Firefox' screen
  app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  app/src/main/res/values/static_strings.xml
Labels: pr:needs-landing, pr:approved

#25216 For #24857: Add metrics for addresses autofill.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/settings/address/AddressManagementFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  app/src/test/java/org/mozilla/fenix/settings/address/AddressEditorViewTest.kt
Labels: pr:needs-landing, pr:approved

#25554 No issue: Create --unit-test.md issue template
  .github/ISSUE_TEMPLATE/--unit-test.md
Labels: pr:needs-landing

#22672 For #21894: Move Tabs Tray to compose: Individual tab viewholders: ListViewHolder.
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/MediaImage.kt
  app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupListAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabGroupViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeAbstractTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeListViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#25784 Update Pontoon broken link
  README.md
Labels: needs:review

#25738 Fixes #25545: wait to draw Pocket until after first frame
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt
  app/src/main/res/layout/top_placeholder_item.xml
Labels: pr:needs-landing

#25786 For #24967 - Enable address autofill for Nightly and Debug
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing

#25705 No issue: Add number_of_app_launches custom attribute to nimbus messages
  app/src/main/java/org/mozilla/fenix/gleanplumb/CustomAttributeProvider.kt
  nimbus.fml.yaml
Labels: needs:review

#25817 For #25815: Fix interactor calls for address management.
  app/src/main/java/org/mozilla/fenix/settings/address/AddressManagementFragment.kt
Labels: pr:needs-landing

#25772 For #25061: Update debug maxSdkVersion for screenshots
  app/src/debug/AndroidManifest.xml
Labels: pr:needs-landing, pr:approved

#25730 For #23237 minor refactoring work for privateTabsTrayWithOpenedTabTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#25823 Issue #25805: Always anchored unified search menu to the toolbar icon
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing, pr:approved

#25841 Submit commits to Glean probe-scraper
  .github/workflows/glean-probe-scraper.yml
Labels: pr:needs-landing
