Repository mozilla-mobile/fenix, pull requests merged in 2022-05, with the labels that each got.

#24957 For #24514 - Remove Fact.toEvent from MetricController
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing, pr:approved

#25045 For #25044 - Remove the broken code for focusing the newly created collection
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: pr:needs-landing, pr:approved

#25069 Set version to 101.0.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved

#25030 For #21292: Remove unused MetricController parameters.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/main/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessor.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayMiddleware.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/SpeechProcessingIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/intent/StartSearchIntentProcessorTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
  app/src/test/java/org/mozilla/fenix/home/topsites/TopSiteItemViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/history/HistorySearchControllerTest.kt
  app/src/test/java/org/mozilla/fenix/library/recentlyclosed/DefaultRecentlyClosedControllerTest.kt
  app/src/test/java/org/mozilla/fenix/nimbus/NimbusBranchesControllerTest.kt
  app/src/test/java/org/mozilla/fenix/onboarding/FenixOnboardingTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectTabUseCaseWrapperTest.kt
  app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/wallpapers/WallpaperManagerTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing, pr:approved

#25082 Disable failing openExternalLinksInPrivateTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#24903 For #20973 fix and re-enable `shortcutButtonTest` UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25071 For #25070 - Remove all unused strings marked moz:removedIn <= 99
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#25087 For #23856: Remove deprecated layout_constraintWidth_default
  app/src/main/res/layout/component_collection_creation.xml
  app/src/main/res/layout/fragment_add_on_details.xml
Labels: pr:needs-landing

#24987 for #24665: show recent synced tab faster
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#25100 Disable failing download UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: pr:needs-landing, eng:ui-test

#25010 For #24971 - Split full name from Address editor into first, middle and last name
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  app/src/main/res/layout/fragment_address_editor.xml
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#25112 For #25111 - Remove contileFeature feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/home_preferences.xml
  app/src/main/res/xml/secret_settings_preferences.xml
Labels: pr:needs-landing, pr:approved

#25116 For #25115 - Remove showWallpapers feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/xml/home_preferences.xml
Labels: pr:needs-landing, pr:approved

#25118 For #25117 - Move HomeSectionHeader into its proper package
  app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
Labels: pr:needs-landing, pr:approved

#25094 For #25015 - Add a compose version of PrimaryButton
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
Labels: pr:needs-landing

#25138 For #25135 - Replace Button in SyncedTabs with PrimaryButton
  app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Labels: pr:needs-landing

#25151 For #25142 increase the EXPECTED_RECYCLER_VIEW_CONSTRAINT_LAYOUT_CHILDREN to count for the messaging framework message.
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
Labels: pr:needs-landing

#25143 For #24993 and #25085 fix flaky testStrictVisitProtectionSheet and testStrictVisitSheetDetails UI tests.
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25114 For #25113 - Remove showClearSiteData feature flag
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ClearSiteDataView.kt
Labels: pr:needs-landing

#25174 Issue #24738: hide the QR code button when switching to none default search engine
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: pr:needs-landing, pr:approved

#24904 Application services 93.0.1
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing-squashed

#25171 For #24998 fix flaky deleteDeleteBrowsingHistoryDataTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25133 For #25132 - Catch intermittent RuntimeException in early getInstrumentation() call
  app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
Labels: pr:needs-landing, eng:ui-test

#25039 for #24931: create address label and description based on available data
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
  app/src/main/java/org/mozilla/fenix/settings/address/ext/Address.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressList.kt
  app/src/test/java/org/mozilla/fenix/settings/address/ext/AddressTest.kt
Labels: pr:needs-landing, pr:approved

#24624 For #24455 - Migrate NoCollectionsMessageViewHolder to Compose
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/main/java/org/mozilla/fenix/compose/CollectionsPlaceholder.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolder.kt
  app/src/main/res/drawable/empty_session_control_background.xml
  app/src/main/res/layout/no_collections_message.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/NoCollectionsMessageViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#25191 For #25187: Dismiss the default browser card after clicking.
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
Labels: pr:approved

#25204 Disable failing useAddonsInPrivateModeTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
Labels: pr:needs-landing, eng:ui-test

#25180 For #25179 - Display a save or update credit card prompt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#25201 For #25200 - Add on-failure notify for unit test to Slack
  taskcluster/ci/test/kind.yml
Labels: pr:needs-landing

#25228 For #24666: Ensure trackingProtectionLayout not clipped by clearSiteDataDivier
  app/src/main/res/layout/fragment_quick_settings_dialog_sheet.xml
Labels: pr:needs-landing

#25089 Change FxNimbus initialization sequence
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: pr:approved, pr:needs-landing-squashed

#25234 Revert "Change FxNimbus initialization sequence (#25089)"
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: pr:needs-landing

#25147 For #25145: Unify behavior for opening systems setting for updating the default browser preference
  app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
Labels: pr:needs-landing

#25229 Run CI for 25222
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
Labels: pr:needs-landing

#25230 For #20754: Fix scrolling issues and re-enable verifyAboutFirefoxPreview
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25250 For #25176 - Refactor TabTitle and TabSubtitle
  app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitle.kt
  app/src/main/java/org/mozilla/fenix/compose/TabSubtitleWithInterdot.kt
  app/src/main/java/org/mozilla/fenix/compose/TabTitle.kt
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: pr:needs-landing, pr:approved

#25242 No issue: Add extension function to TabSessionState for shortening urls safely.
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
Labels: pr:needs-landing, pr:approved

#25252 No issue: remove performance codeowners.
  .github/CODEOWNERS
Labels: pr:needs-landing

#25243 For #25209: Avoid trying to download wallpapers without a server URL.
  app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt
Labels: pr:needs-landing, pr:approved

#25270 for #25167: ignore tests failing due to coroutines
  app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt
Labels: pr:needs-landing

#25276 Disable failing selectTabOnLongTapTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#25277 Disable failing verifyContextMixedVariations UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: pr:needs-landing, eng:ui-test

#25287 For #25264 - Refactor toShortUrl extension function from TabSession State to String
  app/src/main/java/org/mozilla/fenix/ext/String.kt
  app/src/main/java/org/mozilla/fenix/home/collections/CollectionItem.kt
  app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
Labels: pr:needs-landing

#25267 Issue #24299: Add history to the search engine menu
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarView.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/res/drawable/ic_history_search.xml
  app/src/main/res/layout/search_selector.xml
  app/src/main/res/values/static_strings.xml
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing

#25101 For #24936 - Replace ListItemIcon with IconButton and Icon
  app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
Labels: pr:needs-landing

#25173 Fix externalLinkPWATest UI test on Firebase
  app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25123 For #25119 - Add Secondary, Tertiary and Destructive Button composable components
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt
  app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: pr:needs-landing

#25236 Fixes #24917: add country dropdown to address editor
  app/src/main/java/org/mozilla/fenix/settings/address/AddressEditorFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  app/src/main/res/layout/fragment_address_editor.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/address/AddressEditorViewTest.kt
Labels: pr:needs-landing, pr:approved

#25016 For #24991 - Refactor the HomeMenu creation from HomeFragment to HomeMenuBuilder
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenuBuilder.kt
  app/src/test/java/org/mozilla/fenix/home/HomeMenuBuilderTest.kt
Labels: pr:needs-landing, pr:approved

#25300 No issue: Update Sentry dependency version to 5.7.3
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#25316 For #23700 - HistoryFragment: Exit edit mode when multi-selection is opened in tabs or shared.
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: pr:needs-landing

#25303 Close #25288: Disable autocomplete for unified history search
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing, pr:approved

#25317 Close #25170: Fix flaky search fragment store tests
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: pr:needs-landing

#25315 Run CI for #22437
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
Labels: pr:needs-landing

#25207 For #24968: Add preference for enabling/disabling addresses autofill.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/autofill_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragmentTest.kt
Labels: pr:needs-landing, pr:approved

#23177 For #23173 - CheckChanged use a single variable instead of two for checked status
  app/src/main/java/org/mozilla/fenix/collections/CollectionCreationTabListAdapter.kt
  app/src/main/java/org/mozilla/fenix/collections/TabDiffUtil.kt
  app/src/test/java/org/mozilla/fenix/collections/TabDiffUtilTest.kt
Labels: pr:needs-landing

#25343 Disable failing audioPlaybackSystemNotificationTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#25090 For #23966 - Migrate MessageCardViewHolder to Compose
  app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  app/src/main/java/org/mozilla/fenix/compose/CollectionsPlaceholder.kt
  app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
  app/src/main/res/layout/nimbus_message_card.xml
Labels: pr:needs-landing, pr:approved

#25298 For #23600 fix flaky saveLoginsInPWATest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25346 For #23481 fix disabled `openLinkInAppTest` UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: pr:needs-landing, eng:ui-test

#25205 For #25002 #25184 and #23417 fix testDownloadCompleteNotification testDownloadPrompt and testCloseDownloadPrompt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
Labels: pr:needs-landing, eng:ui-test

#25375 For #25374: Skip action validation for control messages
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: pr:needs-landing

#25312 For #25311 - Set tokens used when communicating with Pocket
  .gitignore
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  taskcluster/fenix_taskgraph/transforms/build.py
Labels: pr:needs-landing

#25372 Issue #24299: Sort unified search selector menu items based on user settings
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/main/res/drawable/ic_history_search.xml
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing, pr:approved

#25389 Issue #24299: Do not show history search engine in the search settings
  app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
Labels: pr:needs-landing, pr:approved

#25398 For #25212: Add tabs prioritization
  app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: pr:needs-landing

#25410 For #24040: App should not crash when the search widget is clicked while PIP mode is active
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#25353 For #25352 - Add a new FML feature to gate Pocket sponsored stories
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  nimbus.fml.yaml
Labels: pr:needs-landing

#25411 For #25397 - Telemetry for credit card save and update
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/test/java/org/mozilla/fenix/components/metrics/MetricControllerTest.kt
Labels: pr:needs-landing-squashed

#25408 For #24300 - Add Tabs to the search engine menu
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/main/res/drawable/ic_tabs_search.xml
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: pr:needs-landing

#25420 fixes #25386: turn task continuity on by default for nightly
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved

#25376 fixes #24918: add subregion dropdown to address editor
  app/src/main/java/org/mozilla/fenix/settings/address/AddressUtils.kt
  app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  app/src/main/res/layout/fragment_address_editor.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/address/AddressEditorViewTest.kt
Labels: pr:needs-landing, pr:approved

#25415 For #25380: Disable blockHarmfulPageTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
Labels: pr:needs-landing, eng:ui-test

#25405 No issue: Renew/Remove metrics set to expire in v104
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
Labels: pr:needs-landing

#25442 Set version to 102.0.0.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#25445 For #25444 - Remove all unused strings marked moz:removedIn <= 100
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#25443 Update version.txt to 103.0.0-beta.1
  version.txt
Labels: pr:needs-landing

#25450 Close #25449: Use "Enter search terms" as hint when using application search engines
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing

#25440 For #25437: Fix label values for labeled counters.
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/controller/RecentSyncedTabController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/controller/DefaultRecentSyncedTabControllerTest.kt
Labels: pr:needs-landing

#25479 No issue: Cleanup default toolbar menu
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: pr:needs-landing, pr:approved
