Repository mozilla-mobile/fenix, pull requests merged in 2023-02, with the labels that each got.

#28719 For #25588, hide password in android 13 clipboard preview
  app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/interactor/LoginDetailInteractor.kt
  app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
  app/src/test/java/org/mozilla/fenix/settings/logins/SavedLoginsStorageControllerTest.kt
Labels: pr:needs-landing-squashed

#28723 Update to Android-Components 111.0.20230131190137.
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:needs-landing

#28722 Bug 1812075 - Disable useAppWhileTabIsCrashedTest for recent failure
  app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
Labels: pr:needs-landing

#28730 Bug 1814283 - re-enable app link related UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28655 For 1811851: Update message notification worker to handle when a user clicks or dismisses a Notification.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/main/java/org/mozilla/fenix/utils/NotificationBase.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Labels: pr:needs-landing-squashed

#28737 Bug 1814415 - Remove dependency of the TCP CFR from the re-engagement dialog
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing

#28712 Bug 1814171 - Fixed typos in Working with-Strings.md
  docs/Working-with-Strings.md
Labels: pr:needs-landing

#28641 Bug 1812204 - Add usage growth data event
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsStorage.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/components/metrics/DefaultMetricsStorageTest.kt
Labels: pr:needs-landing

#28738 Bug 1814224 - Remove select tab use case wrapper
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapper.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectTabUseCaseWrapperTest.kt
Labels: pr:needs-landing, pr:approved

#28676 Bug 1812616 - Enable clear button on the Password and Host fields
  app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
Labels: pr:needs-landing

#28742 Bug 1812574 - fix flaky toolbarTapDoesntDismissOnboardingTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
Labels: pr:needs-landing, eng:ui-test

#28748 Bug 1814223 - Remove `RemoveTabUseCaseWrapper`
  app/src/main/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapper.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/RemoveTabUseCaseWrapperTest.kt
  detekt-baseline.xml
Labels: pr:needs-landing, pr:approved

#28344 Bug 1814232 - Consume upstream CFRPopupFullscreenLayout
  app/build.gradle
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupContent.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayout.kt
  app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupShape.kt
  app/src/main/java/org/mozilla/fenix/onboarding/HomeCFRPresenter.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  app/src/test/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayoutTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#28756 Bug 1807283 - Fix flakiness in verifyJumpBackInSectionTest
  app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28752 Bug 1814241 - Create interactor/controller for the Tabs Tray FAB
  app/src/main/java/org/mozilla/fenix/tabstray/FloatingActionButtonBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsTrayFabController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/TabsTrayFabInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/FloatingActionButtonBindingTest.kt
Labels: pr:needs-landing, pr:approved

#28746 Bug 1814425 - Don't show a suggestions header for topic specific search engines
  app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: pr:needs-landing, pr:approved

#28630 Bug 1808358 - Create common OnboardingPage composable
  app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
Labels: pr:needs-landing

#28761 Bug 1813085 - If a message notification is being displayed, do not create another notification with the same message.
  app/src/main/java/org/mozilla/fenix/gleanplumb/Message.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/OnDiskMessageMetadataStorage.kt
  app/src/main/java/org/mozilla/fenix/utils/BootUtils.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/OnDiskMessageMetadataStorageTest.kt
  app/src/test/java/org/mozilla/fenix/utils/BootUtilsTest.kt
Labels: pr:needs-landing

#28774 Bug 1814410: Unified search migrate to general search engine after search engine list loads
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing, pr:approved

#28782 Bug 1813694: Update strings for history group section
  app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing, pr:approved

#28783 Bug 1811795 - Surface granular media permissions.
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing

#28790 Bug 1815551 - Update Sentry to version 6.13.1
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#28691 For 1811532 - Add secret setting allowing to overwrite the site parameter for Pocket sponsored stories
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SponsoredStoriesSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/secret_settings_preferences.xml
  app/src/main/res/xml/sponsored_stories_settings.xml
Labels: pr:needs-landing

#28745 Bug 1811537 - Add secret setting allowing to overwrite the `country` and `city` parameters for Pocket sponsored stories
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/settings/SponsoredStoriesSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/sponsored_stories_settings.xml
Labels: pr:needs-landing

#28796 Bug 1815160 - Add sponsored story id to home_recs_spoc_shown and home_recs_spoc_clicked
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesController.kt
  app/src/test/java/org/mozilla/fenix/home/pocket/DefaultPocketStoriesControllerTest.kt
Labels: pr:needs-landing, pr:approved

#28792 Bug 1815306 - Truncate tabs tray title to mitigate scroll performance
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: pr:needs-landing

#28794 Bug 1807270 - re-enable navigateBackInCollectionFlowTest and undoDeleteCollectionTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#28806 Bug 1815885 - Ensure the synced tabs CFR is shown
  app/src/main/java/org/mozilla/fenix/onboarding/HomeCFRPresenter.kt
Labels: pr:needs-landing

#28648 Bug 1815548 – Add offset parameter to menu2
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorMenu.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
Labels: pr:needs-landing, pr:approved

#28788 Don't pass CrashReporter to RustLog
  app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: pr:needs-landing

#28717 Bug 1814208 - Enable speedometer3 in the fenix branch.
  taskcluster/ci/browsertime/kind.yml
Labels: pr:needs-landing-squashed

#28810 Bug 1813421 - Convert Nimbus Experiments to Compose
  app/src/main/java/org/mozilla/fenix/nimbus/NimbusExperimentsFragment.kt
  app/src/main/java/org/mozilla/fenix/nimbus/view/NimbusExperiments.kt
  app/src/main/java/org/mozilla/fenix/nimbus/view/NimbusExperimentsView.kt
Labels: pr:needs-landing

#28118 Bug 1815623 - Add telemetry for sharing to an app from the share sheet
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  app/src/main/java/org/mozilla/fenix/share/ShareToAppsSafeExtras.kt
  app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: pr:needs-landing, pr:approved

#28807 Bug 1815901 - Further document experimentation for cookie banner handling
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#28815 Bug 1815424 - Show Dialog should not be called multiple times.
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: pr:needs-landing

#28784 Bug 1815433 - Update defaults in messaging.fml.yaml configuration prior to release
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
  messaging.fml.yaml
Labels: pr:needs-landing

#28800 Bug 1814506 - Add unit tests to cover multi selection of tabs
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: pr:needs-landing, pr:approved
