Repository mozilla-mobile/fenix, pull requests merged in 2023-01, with the labels that each got.

#28338 Bug 1807933 - Enable places storage maintenance feature for the Beta variant
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing

#28101 For #3722: Invoke search on long press home button
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/home/intent/AssistIntentProcessor.kt
  app/src/test/java/org/mozilla/fenix/home/intent/AssistIntentProcessorTest.kt
Labels: pr:needs-landing

#28285 Bug 1796146 - Add learn more link to cookie banner handling settings page
  app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersSwitchPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  app/src/main/res/layout/preference_switch_learn_more.xml
  app/src/main/res/xml/cookie_banner_preferences.xml
Labels: pr:needs-landing, pr:approved

#28130 For #25812 - Set the cursor at the end for search terms when switching to toolbar editMode
  app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: pr:needs-landing, pr:approved

#28274 Bug 1807270 - re-enable collections UI tests disabled by the tabs tray migration to compose
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28286 Bug 1797593 - Pre-land text for cookie banner handling dialog
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28277 For #27035 - Add padding around onboarding buttons and content
  app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt
Labels: pr:needs-landing

#23892 For #23841: Credit cards: Hide keyboard when selecting month or year
  app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
Labels: pr:needs-landing

#28382 Bug 1808338 - Update Sentry to version 6.11.0
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#28394 Bug 1797593 - Update text descriptions for cookie banner handling dialog
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28395 Switch to AC implementation for checking device manufacturer.
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/perf/StrictModeManager.kt
  app/src/main/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListener.kt
  app/src/main/java/org/mozilla/fenix/utils/ManufacturerCodes.kt
  app/src/test/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListenerTest.kt
  app/src/test/java/org/mozilla/fenix/utils/ManufacturerCodesTest.kt
Labels: pr:needs-landing, pr:approved

#28299 Bug 1807302 - New sponsored shortcuts UI tests and other refactoring work
  app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28391 No issue - Use android resource for positive/negative dialog buttons
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SiteSecurityRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28367 Bug 1807727 - Dismiss SearchDialogFragment on editing cancelled
  app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: pr:needs-landing

#28412 Bug 1807288 - Disable intermittent validateBaselinePing UI test
  app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt
Labels: pr:needs-landing, eng:ui-test

#28381 For EXP-2992: Add notification config with polling interval to messaging feature
  .experimenter.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing-squashed

#28416 Closes 28414: NotificationManagerCompat extension to safely check if notifications are enabled
  app/src/main/java/org/mozilla/fenix/ext/NotificationManagerCompat.kt
  app/src/main/java/org/mozilla/fenix/onboarding/MarketingNotificationHelper.kt
Labels: pr:needs-landing, pr:approved

#28400 For #28261 - Rename solo `xInteractor` parameters in the Tabs Tray to `interactor`
  app/src/main/java/org/mozilla/fenix/tabstray/FloatingActionButtonBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/test/java/org/mozilla/fenix/tabstray/FloatingActionButtonBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
Labels: pr:needs-landing, pr:approved

#28401 Bug 1801022 - Update AndroidX testing libraries to the latest releases
  buildSrc/src/main/java/Dependencies.kt
Labels: pr:needs-landing

#28418 Closes 28417: Add nimbus flags for pre permission prompt
  .experimenter.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#28424 For #28262 - Refactor InactiveTabsAutoCloseDialogInteractor into InactiveTabsInteractor
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
Labels: pr:needs-landing

#28405 Bug 1797593 - Add re-engagement dialog for cookie banners.
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
  app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersSwitchPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerDetailsController.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialog.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogCompose.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractor.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/layout/preference_switch_learn_more.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultConnectionDetailsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/DefaultCookieBannerDetailsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#28411 Bug 1807302 - New set desktop site before page load UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28429 For #28428: update growth data with new events
  app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricsStorage.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/test/java/org/mozilla/fenix/components/metrics/DefaultMetricsStorageTest.kt
  app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: pr:needs-landing

#28435 Bug 1808665 - Record toolbar_menu_visible event
  app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: pr:needs-landing, pr:approved

#28438 Bug 1808689 - Update description for browser_menu_action extra items
  app/metrics.yaml
Labels: pr:needs-landing

#27895 For #25810 - Unified search should give hint to user that there are more menu items available by scrolling
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
  app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: pr:approved, pr:needs-landing-squashed

#28470 Close #28469: Add notification permission prompt onboarding strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28410 For #26280: Add monochromatic themed app icon
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: pr:needs-landing, pr:approved

#28458 Bug 1807125 - Make Studies title and description accessible
  app/src/main/res/layout/settings_studies.xml
Labels: pr:needs-landing, pr:approved

#28484 Revert "Closes #28417: Add nimbus flags for pre permission prompt"
  .experimenter.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing, pr:approved

#28442 For #28263 - Rename inactive tabs interactor functions
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
Labels: pr:needs-landing

#28340 Closes #7861: position text based on layout direction, not on text directionality
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#28482 Close #28469: Update notification permission prompt onboarding strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28443 For #28264 - Refactor synced tabs handling out of `NavigationInteractor`
  app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SyncedTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/SyncedTabsInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: pr:needs-landing

#28490 Revert "Revert "Closes #28417: Add nimbus flags for pre permission prompt""
  .experimenter.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing

#28491 Close #28469: Use placeholders in notification permission prompt onboarding strings
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28487 Bug 1809507 - Use base domain on the cookie banner handling panel.
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerPanelDialogFragment.kt
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
Labels: pr:needs-landing

#28502 For #28190: renew telemetry expiring in 111
  app/metrics.yaml
Labels: pr:needs-landing, pr:approved

#28439 Bug 1808282 - Fix flaky toggleSearchBookmarksAndHistoryTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28485 Bug 1809507 - Update cookie banner to reject_all setting
  app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialog.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/cookie_banner_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
Labels: pr:needs-landing, pr:approved

#28517 For #28516 - Update `InactiveTabsController` function names
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
Labels: pr:needs-landing

#28499 Bug 1808880 and 1809645 - Fix flaky useAppWhileTabIsCrashedTest and privateBrowsingUseAppWhileTabIsCrashedTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28529 Bug 1810115 - Add telemetry for notification pre permission prompt
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
Labels: pr:needs-landing, pr:approved

#28195 Bug 1807279 - create new cookie banner reduction UI smoke tests
  app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuCookieBannerReductionRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28548 Bug 1810528 - New PDFs open and save UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
Labels: pr:needs-landing

#28467 Bug 1810204 - Schedule legacy Android API Cron for test coverage
  .cron.yml
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  automation/taskcluster/androidTest/parse-ui-test.py
  taskcluster/ci/ui-test/kind.yml
Labels: pr:needs-landing, eng:ui-test

#28518 Closes EXP-2986 - Add adjust params to custom attributes for messaging display triggers
  app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/CustomAttributeProvider.kt
  nimbus.fml.yaml
Labels: pr:needs-landing-squashed

#28556 Bug 1809156 - Improve accessibility in CookieBannerReEngagementDialog
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogCompose.kt
Labels: pr:needs-landing

#28501 Bug 1809660: Fix for unwanted Homepage preferences animation when Pocket feature is enabled/disabled
  app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/xml/home_preferences.xml
  app/src/test/java/org/mozilla/fenix/settings/HomeSettingsFragmentTest.kt
Labels: pr:approved, pr:needs-landing-squashed

#28423 EXP 2991: Add surface to messaging fml
  app/src/main/java/org/mozilla/fenix/components/Components.kt
  app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/Message.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingFeature.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingState.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingReducer.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/MessagingFeatureTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingReducerTest.kt
  messaging.fml.yaml
  nimbus.fml.yaml
Labels: pr:needs-landing-squashed

#28514 Update depepndency configuration
  app/build.gradle
Labels: pr:needs-landing

#28568 Revert "Closes #7861: position text based on layout direction, not text directionality
  app/src/main/res/values/styles.xml
Labels: pr:needs-landing

#28563 Bug 1810792 - Enable Pocket sponsored stories
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#28207 For #27338 - Update summary text for preferences from settings screen
  app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: pr:needs-landing

#28587 Switch to the typed API for Glean events
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
Labels: pr:needs-landing

#28574 Bug 1807278 - Re-enable UI tests affected by settings screen changes
  app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsBasicsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28561 Bug 1810735 - Part 2: New logins related UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordOptionsToSaveRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordRobot.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: pr:needs-landing, eng:ui-test

#28590 Closes #28589 - Restrict coroutine calls from messagemiddleware an…
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Labels: pr:needs-landing

#28598 Close #28597: Enable notification pre permission prompt feature in Beta
  app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: pr:needs-landing, pr:approved

#28444 Bug28280 - Add telemetry for form data failures
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: pr:needs-landing

#28343 Closes #28342: change the ui direction after a locale change
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: pr:needs-landing

#28409 Closes #25486: fix sign in button
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserMenuSignIn.kt
  app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/menu/BrowserMenuSignInTest.kt
Labels: pr:needs-landing

#28580 Bug 1811045 - Expand device and scheduling for legacy Android testing cron
  .cron.yml
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: pr:needs-landing

#28504 Bug 1807594 - Respect users setting when switching back to search suggestions
  app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
Labels: pr:needs-landing

#28466 For #26855 - Direct users to Bugzilla for issue tracking
  .github/ISSUE_TEMPLATE/---bug-report.yml
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/---performance-issue.md
  .github/ISSUE_TEMPLATE/---webcontent-issue-report.md
  .github/ISSUE_TEMPLATE/--spike.md
  .github/ISSUE_TEMPLATE/--telemetry-request.md
  .github/ISSUE_TEMPLATE/--ui-test.md
  .github/ISSUE_TEMPLATE/--unit-test.md
  .github/ISSUE_TEMPLATE/--user-story.md
  .github/ISSUE_TEMPLATE/config.yml
  docs/release-checklist.md
Labels: pr:needs-landing, pr:approved

#28611 Bug 1809937 - Change form data telemetry from Sharing to Performance
  app/metrics.yaml
Labels: pr:needs-landing

#28605 Bug 1809444: Add Worker to generate Notifications using Nimbus messaging
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/DefaultMessageController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingController.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorker.kt
  app/src/main/java/org/mozilla/fenix/utils/NotificationBase.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/DefaultMessageControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingControllerTest.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
  messaging.fml.yaml
Labels: pr:needs-landing-squashed

#28520 update nimbus-experiments job action versions
  .github/workflows/fenix-update-nimbus-experiments.yml
Labels: pr:needs-landing

#28607 Bug 1811504 - Update strings for cookie banner handling
  app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
Labels: pr:needs-landing

#28566 Bug 1810818: Configures order of new user onboarding panels using a nimbus feature
  .experimenter.yaml
  app/src/main/java/org/mozilla/fenix/home/Mode.kt
  app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt
  app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
  nimbus.fml.yaml
Labels: pr:needs-landing

#28351 Close #19919: Migrate away from startActivityForResult
  app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  app/src/main/java/org/mozilla/fenix/ext/Fragment.kt
  app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/biometric/BiometricPromptPreferenceFragment.kt
  app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  app/src/main/java/org/mozilla/fenix/widget/VoiceSearchActivity.kt
  app/src/test/java/org/mozilla/fenix/widget/VoiceSearchActivityTest.kt
Labels: pr:needs-landing, pr:approved

#28632 Bug 1811504 - Update string comments for cookie banner handling
  app/src/main/res/values/strings.xml
Labels: pr:needs-landing

#28636 Bug 1812087 - Migrate Fenix wiki pages into the docs folder
  docs/"Secret-settings"-debug-menu-instructions.md
  docs/Acronym-dictionary.md
  docs/Addressing-a-performance-regression.md
  docs/Architecture-Decisions.md
  docs/Crash-Monitoring.md
  docs/Creating-a-release-branch.md
  docs/Data-Practices.md
  docs/Development-Test-Plan.md
  docs/Fennec-Migration.md
  docs/Firefox-for-Android-Team-Processes.md
  docs/Guide-to-merging-contributor-PRs.md
  docs/Home.md
  docs/Implementing-Telemetry.md
  docs/Implementing-a-Nimbus-Experiment.md
  docs/List-of-fenix-threads.md
  docs/Logging-Crash-Information.md
  docs/Metric-Feature-Tags.md
  docs/Telemetry:-implementation,-reviews,-renewals.md
  docs/Test-telemetry-pings.md
  docs/Working-with-Strings.md
Labels: pr:needs-landing

#28584 For #28266 - Merge `BrowserTrayInteractor` into `TabsTrayInteractor`
  app/src/main/java/org/mozilla/fenix/tabstray/FloatingActionButtonBinding.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayDialog.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeGridViewHolder.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeListViewHolder.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/FloatingActionButtonBindingTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayDialogTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolderTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapterTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/viewholders/AbstractBrowserPageViewHolderTest.kt
Labels: pr:needs-landing, pr:approved

#28644 Bug 1812279 - disable mainMenuOpenInAppTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: pr:needs-landing, eng:ui-test

#28512 Bug 1806798 - Better handle longer filenames in download finished dialog. #527
  app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialog.kt
  app/src/main/res/layout/download_dialog_layout.xml
Labels: pr:needs-landing, pr:approved

#28627 EXP-2996 Add triggers for notifications
  app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingTriggerTest.kt
  messaging.fml.yaml
Labels: pr:needs-landing-squashed

#28642 Bug 1812255 - Reduce UI tests max timeouts
  automation/taskcluster/androidTest/flank-arm-beta.yml
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  automation/taskcluster/androidTest/flank-arm-screenshots-tests.yml
  automation/taskcluster/androidTest/flank-arm-start-test.yml
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  automation/taskcluster/androidTest/flank-x86.yml
Labels: pr:needs-landing, eng:ui-test

#28639 Bug 1812178 - Use debounce in tabs, history and bookmarks syncs
  app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkController.kt
  app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: pr:needs-landing

#28645 Bug 1810314 - Update cookie banner snackbar duration.
  app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialog.kt
Labels: pr:needs-landing

#28671 Bug 1812997 - disable swipeLeftToRemoveTabFromCollectionTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#28674 Bugs 1813047 and 1813048 - disable swipeRightToRemoveTabFromCollectionTest and renameCollectionTest UI tests
  app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: pr:needs-landing, eng:ui-test

#28663 No issue: Update flank-arm-legacy-api-tests.yml
  automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: pr:needs-landing

#28678 Bug 1812627 - Add FirefoxTheme to ProfilerDialogueCard
  app/src/main/java/org/mozilla/fenix/perf/ProfilerReusableComposable.kt
Labels: pr:needs-landing

#28672 Bug 1802619: Disable delete browsing button when deletion in progress
  app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
Labels: pr:needs-landing

#28692 Bug 1807293 - remove SDK suppression on audioVideoPermissionChoiceOnEachRequestTest
  app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: pr:needs-landing, eng:ui-test

#28666 Bug 1810745 - Re-enable UI test for cookie banner handling.
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, needs:review

#28673 Bug 1813018 - Adding GV channel compliance to UI test execution
  app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: pr:needs-landing, eng:ui-test

#28689 Bug 1812298 - Rename doc files to avoid special characters
  docs/Secret-settings-debug-menu-instructions.md
  docs/Telemetry-implementation,-reviews,-renewals.md
Labels: pr:needs-landing, needs:review

#28664 For #28510 - Keep experimental messages in the correct order
  app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Labels: pr:needs-landing, pr:approved

#28637 Run CI for #28500
  app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
Labels: pr:needs-landing

#28652 Bug 1807298 - re-enable deleteAllSearchEnginesTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: pr:needs-landing, eng:ui-test

#28696 Bug 1813628 - Adjust shard count for debug UI tests
  automation/taskcluster/androidTest/flank-arm64-v8a.yml
  taskcluster/ci/ui-test/kind.yml
Labels: pr:needs-landing, eng:ui-test

#28708 Bug 1814008 - remove cookie banner dialog disabling directly in test class
  app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
Labels: pr:needs-landing, eng:ui-test

#28703 For #25608 - Adds `foregroundServiceType` to MediaSessionService
  app/src/main/AndroidManifest.xml
Labels: pr:needs-landing, pr:approved

#28694 Bug 1807272 - fix flaky dismissOnboardingWithPageLoadTest UI test
  app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
Labels: pr:needs-landing, eng:ui-test

#28709 Bug 1812188 - Renew/remove telemetry probes expiring in 112.
  app/metrics.yaml
  app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: pr:needs-landing

#28697 Bug 1813596 - Resolve CheckForFormDataException RuntimeException and …
  app/src/main/java/org/mozilla/fenix/components/Core.kt
  app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: pr:needs-landing

#28701 No Bug - Remove deprecated appContext from Nimbus feature .value() call
  app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: pr:needs-landing, pr:approved

#28522 For #28265 - Refactor InactiveTabs interactor/controller into TabsTray
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsAdapter.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsController.kt
  app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsControllerTest.kt
  app/src/test/java/org/mozilla/fenix/tabstray/browser/DefaultInactiveTabsInteractorTest.kt
Labels: pr:needs-landing, pr:approved
